### PR TITLE
Corrects the comment handling in vitess

### LINKED ISSUE #7580: Incorrect Comment handling in vitess
#### Overview of the Issue

Vitess treats everything after `--` as a comment while MySQL treats everything after `-- ` as a comment. (Notice the space). This means that the query `SET @S = --4` is valid on MySQL but Vitess throws a parsing error.

#### Reproduction Steps

The issue can be reproduced by adding a test case to the parser tests.

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description
Vitess treats everything after `-- ` as a comment just like MySQL. This means that the query `SET @S = 1--4` is valid on both MySQL and Vitess. Refer to https://dev.mysql.com/doc/refman/8.0/en/ansi-diff-comments.html for MySQL documentation regarding the same

## Related Issue(s)

-  Fixes #7580 

## Checklist
- [ ] Should this PR be backported? No
- [X] Tests were added or are not required Yes
- [X] Documentation was added or is not required Documentation not required.

## Impacted Areas in Vitess
Components that this PR will affect:

- [X]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [ ]  Build/CI
- [ ]  VTAdmin

### CODE REVIEW

File: go/vt/sqlparser/token.go [hunk 1]
```diff
@@ -64,15 +61,6 @@ func NewStringTokenizer(sql string) *Tokenizer {
...
 
-// NewTokenizer creates a new Tokenizer reading a sql
-// string from the io.Reader.
-func NewTokenizer(r io.Reader) *Tokenizer {
-	return &Tokenizer{
-		InStream: r,
-		buf:      make([]byte, defaultBufSize),
-	}
-}
-
```
Comment (harshit-gangal) [inline go/vt/sqlparser/token.go:75]: :100:

**Review by harshit-gangal — APPROVED** [review]
