### PR TITLE
healthcheck: update healthy tablets correctly when a stream returns an error or times out

### LINKED ISSUE #7177: GetHealthyTabletStats is not updated when healthcheck times out
This is similar to #7123 

When healthcheck times out, the tablet should no longer be considered healthy for serving purposes. Today, the code does not update the healthy list when a timeout occurs.

Reported by @xhh1989

### LINKED ISSUE #7472: VTGate HealthCheckUpdate failing to update vttablet serving status
#### Overview of the Issue

Despite receiving SIGKILL, VTTablet still marked as SERVING by VTGate.

#### Reproduction Steps

1) Run ```./101_initial_cluster.sh```
2) Kill rdonly vttablet 
```
kill -9 `pgrep vttablet | tail -n 1`
```

From the vtgate logs, `HealthCheckUpdate` does appear to update the rdonly's serving status to false:
```
==> vtgate.INFO <==
I0209 00:38:32.330542   10475 tablet_health_check.go:111] HealthCheckUpdate(Serving State): tablet: zone1-102 (localhost) serving true => false for commerce/0 (RDONLY) reason: vttablet: rpc error: code = Unavailable desc = transport is closing
```

However, vtgate still shows the rdonly vttablet as SERVING:
```
mysql --host 127.0.0.1 --port 15306 -e "show vitess_tablets"

+-------+----------+-------+------------+---------+------------------+-----------+----------------------+
| Cell  | Keyspace | Shard | TabletType | State   | Alias            | Hostname  | MasterTermStartTime  |
+-------+----------+-------+------------+---------+------------------+-----------+----------------------+
| zone1 | commerce | 0     | MASTER     | SERVING | zone1-0000000100 | localhost | 2021-02-09T08:37:04Z |
| zone1 | commerce | 0     | REPLICA    | SERVING | zone1-0000000101 | localhost |                      |
| zone1 | commerce | 0     | RDONLY     | SERVING | zone1-0000000102 | localhost |                      |
+-------+----------+-------+------------+---------+------------------+-----------+----------------------+
```

And will still route queries to it:
```
mysql --host 127.0.0.1 --port 15306 @rdonly -e "show tables"
ERROR 1105 (HY000) at line 1: vtgate: http://localhost:15001/: target: commerce.0.rdonly, used tablet: zone1-102 (localhost): vttablet: Connection Closed
```

Once VTGate is restarted, rdonly tablet is properly marked as NOT_SERVING:
```
mysql --host 127.0.0.1 --port 15306 -e "show vitess_tablets"
+-------+----------+-------+------------+-------------+------------------+-----------+----------------------+
| Cell  | Keyspace | Shard | TabletType | State       | Alias            | Hostname  | MasterTermStartTime  |
+-------+----------+-------+------------+-------------+------------------+-----------+----------------------+
| zone1 | commerce | 0     | MASTER     | SERVING     | zone1-0000000100 | localhost | 2021-02-09T08:37:04Z |
| zone1 | commerce | 0     | REPLICA    | SERVING     | zone1-0000000101 | localhost |                      |
| zone1 | commerce | 0     | RDONLY     | NOT_SERVING | zone1-0000000102 | localhost |                      |
+-------+----------+-------+------------+-------------+------------------+-----------+----------------------+
```

#### Binary version
```sh
Version: 10.0.0-SNAPSHOT (Git revision 676911a branch 'master') built on Mon Feb  8 22:37:54 PST 2021 by gary@planetscale using go1.15.6 linux/amd64
```

#### Log Fragments

### PR DESCRIPTION
**Pull request by deepthi**
## Description
There are error conditions from a tablet health check that require the healthy tablet list to be updated.
* Tablet host/port is taken over by a different tablet (Fixed in #7176)
* Healthcheck stream returns an error (this can be for any reason including tablet being down) #7472 
* Healthcheck times out #7177 
* These conditions need to be handled for all tablet types (primary/non-primary)

## Related Issue(s)
Fixes #7472 
Fixes #7177 

## Checklist
- [x] Should this PR be backported?
- [x] Tests were added or are not required
- [ ] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:
- [x]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [ ]  Build/CI
- [ ]  VTAdmin

## Testing
Unit tests were added for each case. For #7472 I also followed the provided testing procedure to reproduce the problem and confirmed that the fix works.
```
mysql> show vitess_tablets;
+-------+----------+-------+------------+---------+------------------+------------------+----------------------+
| Cell  | Keyspace | Shard | TabletType | State   | Alias            | Hostname         | MasterTermStartTime  |
+-------+----------+-------+------------+---------+------------------+------------------+----------------------+
| zone1 | commerce | 0     | MASTER     | SERVING | zone1-0000000100 | localhost        | 2021-03-10T01:24:33Z |
| zone1 | commerce | 0     | REPLICA    | SERVING | zone1-0000000101 | localhost        |                      |
| zone1 | commerce | 0     | RDONLY     | SERVING | zone1-0000000102 | localhost        |                      |
+-------+----------+-------+------------+---------+------------------+------------------+----------------------+
3 rows in set (0.00 sec)
----
kill rdonly vttablet
----
mysql> show vitess_tablets;
+-------+----------+-------+------------+-------------+------------------+------------------+----------------------+
| Cell  | Keyspace | Shard | TabletType | State       | Alias            | Hostname         | MasterTermStartTime  |
+-------+----------+-------+------------+-------------+------------------+------------------+----------------------+
| zone1 | commerce | 0     | MASTER     | SERVING     | zone1-0000000100 | localhost        | 2021-03-10T01:24:33Z |
| zone1 | commerce | 0     | REPLICA    | SERVING     | zone1-0000000101 | localhost        |                      |
| zone1 | commerce | 0     | RDONLY     | NOT_SERVING | zone1-0000000102 | localhost        |                      |
+-------+----------+-------+------------+-------------+------------------+------------------+----------------------+
3 rows in set (0.00 sec)

mysql> use @rdonly;
Database changed
mysql> select * from product;
ERROR 1105 (HY000): target: commerce.0.rdonly: no healthy tablet available for 'keyspace:"commerce" shard:"0" tablet_type:RDONLY '
```

### CODE REVIEW

File: go/vt/discovery/healthcheck.go [hunk 1]
```diff
@@ -404,17 +404,17 @@ func (hc *HealthCheckImpl) deleteTablet(tablet *topodata.Tablet) {
 	}
 }
 
-func (hc *HealthCheckImpl) updateHealth(th *TabletHealth, shr *query.StreamHealthResponse, currentTarget *query.Target, trivialNonMasterUpdate bool, isMasterUpdate bool, isMasterChange bool) {
+func (hc *HealthCheckImpl) updateHealth(th *TabletHealth, currentTarget *query.Target, trivialUpdate bool, isPrimaryUp bool) {
```
Comment (sougou) [inline go/vt/discovery/healthcheck.go:407]: Rename this to `isPrimaryUpdate`? Otherwise, I was reading it as "is primary up".

File: go/vt/discovery/healthcheck.go [hunk 2]
```diff
@@ -427,44 +427,48 @@ func (hc *HealthCheckImpl) updateHealth(th *TabletHealth, shr *query.StreamHealt
...
-			// We already have one up server, see if we
-			// need to replace it.
-			if shr.TabletExternallyReparentedTimestamp < hc.healthy[targetKey][0].MasterTermStartTime {
-				log.Warningf("not marking healthy master %s as Up for %s because its MasterTermStartTime is smaller than the highest known timestamp from previous MASTERs %s: %d < %d ",
-					topoproto.TabletAliasString(shr.TabletAlias),
-					topoproto.KeyspaceShardString(shr.Target.Keyspace, shr.Target.Shard),
-					topoproto.TabletAliasString(hc.healthy[targetKey][0].Tablet.Alias),
-					shr.TabletExternallyReparentedTimestamp,
-					hc.healthy[targetKey][0].MasterTermStartTime)
+	if th.Target.TabletType == topodata.TabletType_MASTER {
```
Comment (sougou) [inline go/vt/discovery/healthcheck.go:430]: I would presume that `isPrimaryUp` would be true only if the tablet type was MASTER. Is there a case where this is not the case?

File: go/vt/discovery/healthcheck.go [hunk 3]
```diff
@@ -427,44 +427,48 @@ func (hc *HealthCheckImpl) updateHealth(th *TabletHealth, shr *query.StreamHealt
...
+						topoproto.KeyspaceShardString(th.Target.Keyspace, th.Target.Shard),
+						topoproto.TabletAliasString(hc.healthy[targetKey][0].Tablet.Alias),
+						th.MasterTermStartTime,
+						hc.healthy[targetKey][0].MasterTermStartTime)
+				} else {
+					// Just replace it.
+					hc.healthy[targetKey][0] = th
+				}
 			}
+		} else {
```
Comment (sougou) [inline go/vt/discovery/healthcheck.go:449]: If this section was the reason you added the MASTER check, it may read better if you explicitly checked for it here. Something like `th.Target.TabletType == topodata.TabletType_MASTER && !isPrimaryUp`. But I'm not sure if that means the same thing.

File: go/vt/discovery/healthcheck.go (hunk 1 above)
Comment (deepthi) [reply go/vt/discovery/healthcheck.go:407]: It is supposed to be "is primary up". The old parameters (isMasterChange and isMasterUpdate) were actually unnecessary because all the information they pass in is available within the scope of this func. However, we do need to know whether the primary should be marked unhealthy (if there is an error/timeout on the healthcheck connection), so I introduced this parameter.

File: go/vt/discovery/healthcheck.go (hunk 2 above)
Comment (deepthi) [reply go/vt/discovery/healthcheck.go:430]: That is a good point. I suppose this is more of a consistency check - to make sure that a caller doesn't pass in `isPrimaryUp` true for a non-master tablet type.

File: go/vt/discovery/healthcheck.go (hunk 3 above)
Comment (deepthi) [reply go/vt/discovery/healthcheck.go:449]: The MASTER check was already there but in the form of a boolean (isMasterUpdate).
I can break this into two separate if blocks instead of an `if .. if .. else` if that is easier to read/understand. What you are suggesting will be equivalent to how it is written today.

Comment (sougou) [reply go/vt/discovery/healthcheck.go:449]: The concern was the deep nesting which made it non-obvious. A cascading if (or switch) may read better. Try it. If it doesn't improve it, we can keep this as is.

**Review by sougou — APPROVED** [review]
Approving, in case no further improvements are possible.

File: go/vt/discovery/healthcheck.go (hunk 3 above)
Comment (deepthi) [reply go/vt/discovery/healthcheck.go]: Ok, I think the switch made it better.

File: go/vt/discovery/healthcheck.go [hunk 4]
```diff
@@ -427,44 +427,52 @@ func (hc *HealthCheckImpl) updateHealth(th *TabletHealth, shr *query.StreamHealt
...
+					th.MasterTermStartTime,
 					hc.healthy[targetKey][0].MasterTermStartTime)
 			} else {
 				// Just replace it.
 				hc.healthy[targetKey][0] = th
 			}
 		}
+	case isPrimary && !isPrimaryUp:
+		// No healthy master tablet
+		hc.healthy[targetKey] = []*TabletHealth{}
```
Comment (narcsfz) [inline go/vt/discovery/healthcheck.go:452]: @deepthi / @sougou I think this might not behave correctly in case of an unplanned failover with an external reparent, please let me know if my thinking is correct here https://github.com/vitessio/vitess/issues/7906 

Thanks!

Comment (deepthi) [reply go/vt/discovery/healthcheck.go:452]: that makes sense. This should be fixed.
