### PR TITLE
Nullable Timestamp Column Fix

### LINKED ISSUE #7739: Incorrect Nullable value in timestamp column
#### Overview of the Issue

Consider the following SQL statement
```sql
CREATE TABLE foo(
    id int primary key,
    a  varchar(255) null,
    b  varchar(255) null default 'foo',
    c  timestamp    null default current_timestamp()
);
```
Running this on vitess creates the table but the column `c` is not nullable. This is verified by running the following SQL statement
```sql
SELECT column_name              column_name,
       data_type                data_type,
       column_type              full_data_type,
       column_default           column_default,
       is_nullable              is_nullable
FROM information_schema.columns
WHERE table_name = 'foo'
ORDER BY ordinal_position;
```

Vitess results show that the column is not nullable but running the same queries on MySQL results in a nullable column

#### Reproduction Steps

Steps to reproduce this issue, example:

1. Run the vttestserver image and run the above queries to see the issue.

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description
Running a query like 
```sql
create table foo (
    id int primary key,
    a varchar(255) null,
    b varchar(255) null default 'foo',
    c timestamp null default current_timestamp()
)
```
on vitess got rewritten to 
```sql
create table foo (
    id int primary key,
    a varchar(255),
    b varchar(255) default 'foo',
    c timestamp default current_timestamp()
)
```

but this is incorrect because by default timestamp column is not nullable. This PR fixes this issue.

## Related Issue(s)

- Fixes #7739 

## Checklist
- [ ] Should this PR be backported?
- [x] Tests were added or are not required
- [ ] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:

- [x]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [ ]  Build/CI
- [ ]  VTAdmin

### CODE REVIEW

File: go/vt/sqlparser/ast.go [hunk 1]
```diff
@@ -1365,6 +1365,7 @@ type ColumnType struct {
 // ColumnTypeOptions are generic field options for a column type
 type ColumnTypeOptions struct {
 	NotNull       bool
+	Null          bool
```
Comment (harshit-gangal) [inline go/vt/sqlparser/ast.go:1368]: do we need both of them?

**Review by harshit-gangal — APPROVED** [review]

File: go/vt/sqlparser/ast.go (hunk 1 above)
Comment (GuptaManan100) [reply go/vt/sqlparser/ast.go:1368]: Yes we need both of them to distinguish 3 cases - 
1. When Not Null is specified
2. When Null is specified
3. When nothing is specified

cases 1 and 2 are straightforward. The complexity arises from the fact that we do not know whether the column will be nullable or not if nothing is specified. We can have a function that returns the default behavior of the data type of the column but otherwise we would require both the variables.

File: go/vt/sqlparser/ast.go [hunk 2]
```diff
@@ -1364,7 +1364,15 @@ type ColumnType struct {
 
 // ColumnTypeOptions are generic field options for a column type
 type ColumnTypeOptions struct {
+	/* We need both Null and NotNull to distinguish 3 cases -
```
Comment (systay) [inline go/vt/sqlparser/ast.go:1367]: I think we should us a `*bool` instead of two bools.

File: go/vt/sqlparser/parse_test.go [hunk 3]
```diff
@@ -1156,6 +1156,9 @@ var (
 	}, {
 		input:  "CREATE TABLE aipk (id INT AUTO_INCREMENT PRIMARY KEY)",
 		output: "create table aipk (\n\tid INT auto_increment primary key\n)",
+	}, {
+		input:  "create table foo (f timestamp null not null , g timestamp not null null)",
```
Comment (systay) [inline go/vt/sqlparser/parse_test.go:1160]: this I don't understand. what does it mean to say both null and not null about the column? why are we picking one of them here instead of failing?

File: go/vt/sqlparser/ast.go (hunk 2 above)
Comment (systay) [reply go/vt/sqlparser/ast.go:1367]: Look at `Select.cache` for another example of the same logic

Comment (GuptaManan100) [reply go/vt/sqlparser/ast.go]: done

File: go/vt/sqlparser/parse_test.go (hunk 3 above)
Comment (GuptaManan100) [reply go/vt/sqlparser/parse_test.go:1163]: added a comment for it

**Review by systay — APPROVED** [review]
