### PR TITLE
fix version issue when using --mysql-shell-speedup-restore=true

### LINKED ISSUE #18309: Bug Report: MySQL Shell backup engine fails to restore with --mysql-shell-speedup-restore=true
### Overview of the Issue

It seems when we enable the flag above, we need to check server capabilities to make sure we can run `ALTER INSTANCE DISABLE INNODB REDO_LOG`, but the validation fails because the version string is not being parsed properly before.

The expected version should be `major.minor.patch` but we are getting something like `Ver 8.#.## Percona Server (GPL), Release '##', Revision '######'` which breaks the validation.

### Reproduction Steps

try to take a mysqlshell backup and the restore it in a tablet that is using `--mysql-shell-speedup-restore=true` 

### Binary Version

```sh
vttablet version Version: 23.0.0-SNAPSHOT (Git revision cec7812fc597817dead7c92987db3bc918e10605 branch 'master') built on Thu May 29 09:10:46 PDT 2025 by #### using go1.24.3 linux/amd64
```

### Operating System and Environment details

```sh
N/A
```

### Log Fragments

```sh
I0529 05:30:24.188580   32687 backup.go:433] Restore: RestorePath: [full:2025-05-29.120513.us_east_1d-0171548866]
I0529 05:30:24.188616   32687 mysqlshellbackupengine.go:248] Calling ExecuteRestore for vt_###### (DeleteBeforeRestore: false)
I0529 05:30:24.189058   32687 restore.go:283] Restore: got a restore manifest: <nil>, err=MySQLShellPreCheckError: MySQL version doesn't support disabling the redo log (must be >=8.0.21)
failed restore precheck, waitForBackupInterval=0s
```

### PR DESCRIPTION
**Pull request by rvrangel**
## Description

This change will make sure that we are correctly parsing the MySQL version beforing passing it to `ServerVersionCapableOf()`, otherwise we will get the wrong capabilities as in #18309.

## Related Issue(s)

Fixes #18309

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on CI?
-   [ ] Documentation was added or is not required

### CODE REVIEW

File: go/vt/mysqlctl/mysqlshellbackupengine_test.go [hunk 1]
```diff
@@ -159,25 +159,60 @@ func TestMySQLShellBackupRestorePreCheckDisableRedolog(t *testing.T) {
...
 		Mysqld: fakeMysqld,
 	}
 
-	// this should work as it is supported since 8.0.21
-	_, err := engine.restorePreCheck(context.Background(), params)
-	require.NoError(t, err, params)
+	for _, tt := range tests {
+		t.Run(tt.version, func(t *testing.T) {
+
+			// it should error out if we change to an older version
```
Comment (deepthi) [inline go/vt/mysqlctl/mysqlshellbackupengine_test.go]: nit: the test structure has changed, so this comment is no longer accurate.

**Review by deepthi — APPROVED** [review]

**Review by dbussink — APPROVED** [review]
