### PR TITLE
fix issue with aggregation inside of derived tables

### LINKED ISSUE #16367: unknown column with aggregation inside derived table
For the query:

```sql
select u.id, u.name, t.num_segments from (select id, count(*) as num_segments from user group by 1 order by 2 desc limit 20) t join unsharded u on u.id = t.id
```

We produce the following plan:

```json
{
  "OperatorType": "Join",
  "Variant": "Join",
  "JoinColumnIndexes": "R:0,R:1,L:0",
  "JoinVars": {
    "t_id": 1
  },
  "TableName": "`user`_unsharded",
  "Inputs": [
    {
      "OperatorType": "Limit",
      "Count": "20",
      "Inputs": [
        {
          "OperatorType": "Route",
          "Variant": "Scatter",
          "Keyspace": {
            "Name": "user",
            "Sharded": true
          },
          "FieldQuery": "select t.num_segments, t.id, count(*) from `user` where 1 != 1 group by id",
          "OrderBy": "2 DESC",
          "Query": "select t.num_segments, t.id, count(*) from `user` group by id order by count(*) desc limit 20",
          "Table": "`user`"
        }
      ]
    },
    {
      "OperatorType": "Route",
      "Variant": "Unsharded",
      "Keyspace": {
        "Name": "main",
        "Sharded": false
      },
      "FieldQuery": "select u.id, u.`name` from unsharded as u where 1 != 1",
      "Query": "select u.id, u.`name` from unsharded as u where u.id = :t_id",
      "Table": "unsharded"
    }
  ]
}
```

The issue is with this line:

```sql
select t.num_segments, t.id, count(*) from `user` group by id order by count(*) desc limit 20
```

The derived table `t` doesn't exist, so this query errors out with:

```
target: xyz.-24.replica: vttablet: rpc error: code = NotFound desc = Unknown column 't.num_segments' in 'field list' (errno 1054)
```

### PR DESCRIPTION
**Pull request by systay**
## Description
For queries doing aggregation inside derived tables, the planner sometimes struggled with which columns are available.

This PR makes sure to handle these queries well.

## Related Issue(s)
Fixes #16367

## Checklist
-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vtgate/planbuilder/operators/horizon_expanding.go [hunk 1]
```diff
@@ -167,6 +170,24 @@ func expandOrderBy(ctx *plancontext.PlanningContext, op Operator, qp *QueryProje
 	}
 }
 
+// exposeOrderingColumn will expose the ordering column to the outer query
+func exposeOrderingColumn(ctx *plancontext.PlanningContext, qp *QueryProjection, orderBy OrderBy, derived string) OrderBy {
```
Comment (GrahamCampbell) [inline go/vt/vtgate/planbuilder/operators/horizon_expanding.go:174]: What if the ordering is an expression that uses multiple columns, or is that explicitly unsupported?

Comment (systay) [reply go/vt/vtgate/planbuilder/operators/horizon_expanding.go:174]: The expression on the inside can be made up of however complex expression, but on the outside it's still a single column. Example:

```sql
select *
from (
	select a+b+c from tbl order by a+b+c
) as t
```

Does that answer your question?

Comment (GrahamCampbell) [reply go/vt/vtgate/planbuilder/operators/horizon_expanding.go:174]: yeh, thanks. 👍

File: go/vt/vtgate/planbuilder/operators/horizon_expanding.go [hunk 2]
```diff
@@ -167,6 +170,24 @@ func expandOrderBy(ctx *plancontext.PlanningContext, op Operator, qp *QueryProje
...
+	for _, se := range qp.SelectExprs {
+		aliasedExpr, err := se.GetAliasedExpr()
+		if err == nil {
+			// if we get an error, we'll just use the whatever was in the AST
```
Comment (frouioui) [inline go/vt/vtgate/planbuilder/operators/horizon_expanding.go:178]: What error are you referring to?

**Review by frouioui — APPROVED** [review]
We should add a test to the vitess-tester aggregation folder. Otherwise, looks good to me.

File: go/vt/vtgate/planbuilder/operators/horizon_expanding.go (hunk 2 above)
Comment (systay) [reply go/vt/vtgate/planbuilder/operators/horizon_expanding.go]: removed that code
