### PR TITLE
bugfix: use the proper interface for comment directives

### LINKED ISSUE #14090: Bug Report: vtexplain does not work when using a scatter query in conjunction with vtgate's `--no_scatter=true` flag
### Overview of the Issue

Vtgate is running with the `--no_scatter=true` flag. Here's what happens when I try to run vtexplain on a scatter query:
```
MYSQL_PWD=<redacted> mysql -u <redacted> -h <redacted> -P 15306 --comments -e 'explain format=vtexplain select /*vt+ ALLOW_SCATTER */ * from etsy_shard.dap_test2 where (shard_id=1 and id=1) OR (shard_id=2 and id=2) OR (shard_id=3 and id=3) OR (shard_id=4 and id=4)'
ERROR 1105 (HY000) at line 1: plan includes scatter, which is disallowed using the `no_scatter` command line argument
```

I expected vtexplain to work because I included the `/*vt+ ALLOW_SCATTER */ ` comment directive

Vschema:
```
% vtctl_etsy GetVSchema etsy_shard
{
  "sharded": true,
  "vindexes": {
    "etsy_shard_hash": {
      "type": "hash",
      "params": {},
      "owner": ""
    },
...
    "dap_test2": {
      "type": "",
      "column_vindexes": [
        {
          "column": "shard_id",
          "name": "etsy_shard_hash",
          "columns": []
        }
      ],
      "auto_increment": null,
      "columns": [],
      "pinned": "",
      "column_list_authoritative": false
    },
...
```

### Reproduction Steps

.

### Binary Version

```sh
Version: 15.0.2
```

### Operating System and Environment details

```sh
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

Linux 3.10.0-1160.21.1.el7.x86_64
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by systay**
## Description
The bug report #14090 exposed an issue where we where not reading comment directives correctly for most statement types. This PR makes sure we read the directives correctly in a lot more situations.

## Related Issue(s)
Fixes #14090

## Checklist
-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/sqlparser/comments.go [hunk 1]
```diff
@@ -322,86 +322,44 @@ func (d *CommentDirectives) GetString(key string, defaultVal string) (string, bo
...
-		comments = stmt.Comments
-	case *Insert:
-		comments = stmt.Comments
-	case *Update:
-		comments = stmt.Comments
-	case *Delete:
-		comments = stmt.Comments
-	}
-	return comments != nil && comments.Directives().IsSet(DirectiveSkipQueryPlanCache)
+	return checkDirective(stmt, DirectiveSkipQueryPlanCache)
```
Comment (systay) [inline go/vt/sqlparser/comments.go:330]: @harshit-gangal this is changing the behaviour for DMLs in the query cache. Are we intentionally skipping the cache?

Comment (harshit-gangal) [reply go/vt/sqlparser/comments.go:330]: why do you think DMLs are handled differently here?

Comment (harshit-gangal) [reply go/vt/sqlparser/comments.go:330]: May be I am missing something.

Comment (systay) [reply go/vt/sqlparser/comments.go]: talked it over. I was confused and wrote DML when I meant DDL

File: go/vt/vtgate/executor_ddl_test.go [hunk 2]
```diff
@@ -57,6 +55,8 @@ func TestDDLFlags(t *testing.T) {
 	}
 	for _, testcase := range testcases {
 		t.Run(fmt.Sprintf("%s-%v-%v", testcase.sql, testcase.enableDirectDDL, testcase.enableOnlineDDL), func(t *testing.T) {
+			executor, _, _, _, ctx := createExecutorEnv(t)
+			session := NewSafeSession(&vtgatepb.Session{TargetString: KsTestUnsharded})
 			enableDirectDDL = testcase.enableDirectDDL
 			enableOnlineDDL = testcase.enableOnlineDDL
```
Comment (harshit-gangal) [inline go/vt/vtgate/executor_ddl_test.go:61]: this change is not required anymore, correct?

File: go/vt/vtgate/executor_test.go [hunk 3]
```diff
@@ -1383,6 +1381,7 @@ func TestExecutorDDLFk(t *testing.T) {
 	for _, stmt := range stmts {
 		for _, fkMode := range []string{"allow", "disallow"} {
 			t.Run(stmt+fkMode, func(t *testing.T) {
+				executor, _, _, sbc, ctx := createExecutorEnv(t)
```
Comment (harshit-gangal) [inline go/vt/vtgate/executor_test.go:1384]: same comment as before

File: go/test/endtoend/vtgate/queries/no_scatter/queries_test.go [hunk 4]
```diff
@@ -0,0 +1,62 @@
...
+	deleteAll()
+
+	return vtConn, func() {
+		deleteAll()
+		vtConn.Close()
+		cluster.PanicHandler(t)
+	}
+}
+
+func TestFailsWhenForcedToScatter(t *testing.T) {
```
Comment (harshit-gangal) [inline go/test/endtoend/vtgate/queries/no_scatter/queries_test.go:50]: to run this as part of CI, I think it should be added in `test/config.json`

**Review by harshit-gangal — APPROVED** [review]
few comments, rest looks good.

**Comment by harshit-gangal** [comment]
I do not think we should backport this to old releases as `vexplain` statement is not a production-related bug.

File: go/vt/vtgate/executor_ddl_test.go (hunk 2 above)
Comment (systay) [reply go/vt/vtgate/executor_ddl_test.go:61]: not really, but I still like it. cleaner to not re-use between tests

**Comment by systay** [comment]
> I do not think we should backport this to old releases as `vexplain` statement is not a production-related bug.

I don't have strong opinions on the subject. @deepthi?

File: go/vt/vtgate/executor_ddl_test.go (hunk 2 above)
Comment (harshit-gangal) [reply go/vt/vtgate/executor_ddl_test.go:61]: `executor` is expected to be reused. This also helped in realising the caching issue with other statements.

**Comment by deepthi** [comment]
> > I do not think we should backport this to old releases as `vexplain` statement is not a production-related bug.
> 
> I don't have strong opinions on the subject. @deepthi?

That's fine. We should amend the release notes for v15+ and list this as a known issue instead.

**Review by frouioui — APPROVED** [review]
