### PR TITLE
Fix type coercion in cascading non-literal updates

### LINKED ISSUE #14523: Bug Report: Vitess managed foreign key cascades incorrect value
### Overview of the Issue

Consider the following schema - 
```SQL
create table fk_t15
(
    id bigint,
    col varchar(10),
    primary key (id),
    index(col)
) Engine = InnoDB;

create table fk_t16
(
    id bigint,
    col varchar(10),
    primary key (id),
    index(col),
    foreign key (col) references fk_t15(col) on delete cascade on update cascade
) Engine = InnoDB;
```

Configure the keyspace such that Vitess is managing the foreign keys. 
Insert the following data into the two tables - 
```sql
insert into fk_t15 (id, col) values (1, '-5')
insert into fk_t16 (id, col) values (1, '-5')
```
Now if you run the query - `update fk_t15 set col = col * (col - (col))`,
you'll see that the foreign key constraints are broken.

In the end, the data in the tables looks like - 
```sql
select * from fk_t15;
+----+------+
| id | col  |
+----+------+
|  1 | -0   |
+----+------+

select * from fk_t16;
+----+------+
| id | col  |
+----+------+
|  1 |  0   |
+----+------+
```

### Reproduction Steps

Given in the description

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
all
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description

This PR fixes the issue described in https://github.com/vitessio/vitess/issues/14523.

I looked at the plan and followed along with what Vitess should have done. The first thing we do is run a SELECT query and that works as intended -
```sql
mysql [localhost:8032] {msandbox} (foreign_key_rfc) > select col, col <=> col * (col - col), col * (col - col) from fk_t15 for update;
+------+---------------------------+-------------------+
| col  | col <=> col * (col - col) | col * (col - col) |
+------+---------------------------+-------------------+
| -0   |                         1 |                -0 |
| -5   |                         0 |                -0 |
| 0    |                         1 |                 0 |
| 5    |                         0 |                 0 |
+------+---------------------------+-------------------+
4 rows in set (0.00 sec)
```

This gives us the correct value of `-0` as we expect it to. However, the value is a float-type value.
Next, we end up executing the query - 
```sql
update /*+ SET_VAR(foreign_key_checks=OFF) */ fk_t16 set col = -0 where col in (('-5')) 
```
This query is intended to cascade the update on the child. Notice that we are setting col to `-0` and not `'-0'` because the value we received from the select was a float-type value.

This query is where the problem is. When we run this query on MySQL, col is actually set to `0` and not `-0`. 

The proposed fix is to first typecast the value we receive from the SELECT query into the type of the column, and then send it down to MySQL.

Post the changes, the query looks like 
```sql
update /*+ SET_VAR(foreign_key_checks=OFF) */ fk_t16 set col = '-0' where col in (('-5')) 
```
and this resolves the issue.

## Related Issue(s)

- Fixes #14523 

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vtgate/engine/fk_cascade.go [hunk 1]
```diff
@@ -185,7 +188,19 @@ func (fkc *FkCascade) executeNonLiteralExprFkChild(ctx context.Context, vcursor
...
+			// the column being updated is a varchar column, then if we don't coerce the value of -0 to
+			// varchar, MySQL ends up setting it to '0' instead of '-0'.
+			finalVal := row[info.UpdateExprCol]
+			var err error
+			if !finalVal.IsNull() {
+				finalVal, err = evalengine.CoerceTo(finalVal, selectionRes.Fields[info.ExprCol].Type)
+			}
+			if err != nil {
+				return err
+			}
```
Comment (harshit-gangal) [inline go/vt/vtgate/engine/fk_cascade.go:202]: nit: error check can happen inside the `if` condition.

**Review by harshit-gangal — APPROVED** [review]

File: go/vt/vtgate/engine/fk_cascade.go (hunk 1 above)
Comment (GuptaManan100) [reply go/vt/vtgate/engine/fk_cascade.go]: Fixed

**Review by frouioui — APPROVED** [review]

**Review by systay — APPROVED** [review]
