### PR TITLE
bugfix: INSERT IGNORE not inserting rows

### LINKED ISSUE #17979: Bug Report: Incorrect Row Insertion Due to Null Handling in Vindex Columns
### Overview of the Issue

Currently, the lookup vindex does not behave as expected when inserting rows with `INSERT IGNORE` where one or more vindex columns have NULL values. In such cases:
* The lookup table with non-null values are updated, but the main table is not inserted correctly.
* This results in an inconsistent state where the row should be inserted, but it is skipped due to a mismatch during verification.

### Reproduction Steps

Simple case:
Have a lookup vindex with ignore_nulls configured.

execute: `insert ignore tbl1 (shard_key, vdx_key) values (1, null)`

The row will not be inserted into `tbl1` even if the [1, NULL] does not exists in the table.

### Binary Version

```sh
`main` - would be in all supported versions.
```

### Operating System and Environment details

```sh
NA
```

### Log Fragments

```sh

```

### PR DESCRIPTION
**Pull request by systay**
## Description
vtgate was failing to insert to the base table when one of the vindexes reported it had ignored a row.

## Related Issue(s)
Fixes #17979

## Checklist
-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by frouioui — APPROVED** [review]

File: go/test/endtoend/vtgate/queries/dml/insert_test.go [hunk 1]
```diff
@@ -516,3 +518,28 @@ func TestInsertJson(t *testing.T) {
 	utils.AssertMatches(t, mcmp.VtConn, `select * from uks.j_utbl order by id`,
 		`[[INT64(1) JSON("{}")] [INT64(2) JSON("{\"a\": 1, \"b\": 2}")] [INT64(3) JSON("{\"k\": \"a\"}")] [INT64(4) JSON("{\"date\": 1629849600, \"keywordSourceId\": 930701976723823, \"keywordSourceVersionId\": 210825230433}")]]`)
 }
+
```
Comment (harshit-gangal) [inline go/test/endtoend/vtgate/queries/dml/insert_test.go:521]: nit: test description

**Review by harshit-gangal — APPROVED** [review]
