### PR TITLE
Fix Incorrect Optimization with LIMIT and GROUP BY

### LINKED ISSUE #16262: Wrong results from query with GROUP BY and LIMIT
For the query: 

```sql
select val2, count(*) 
from aggr_test 
group by val2 
order by count(*), val2 
limit 10
```

We were getting bad results:

```
Query (select val2, count(*) from aggr_test group by val2 order by count(*), val2 limit 10) results mismatched.
        Vitess Results:
        [INT64(8) INT64(15)]
        [INT64(2) INT64(18)]
        [INT64(4) INT64(18)]
        [INT64(9) INT64(18)]
        [INT64(3) INT64(20)]
        [INT64(5) INT64(20)]
        [INT64(0) INT64(22)]
        [INT64(1) INT64(23)]
        [INT64(6) INT64(24)]
        [INT64(7) INT64(29)]
        Vitess RowsAffected: 0
        MySQL Results:
        [INT64(42) INT64(13)]
        [INT64(14) INT64(14)]
        [INT64(25) INT64(14)]
        [INT64(49) INT64(14)]
        [INT64(8) INT64(15)]
        [INT64(23) INT64(15)]
        [INT64(26) INT64(15)]
        [INT64(46) INT64(15)]
        [INT64(10) INT64(16)]
        [INT64(35) INT64(17)]
        MySQL RowsAffected: 0
```

### PR DESCRIPTION
**Pull request by systay**
## Description
This PR addresses an issue where incorrectly optimized query planning with `LIMIT` led to inaccurate results when `GROUP BY` was used on the vtgate side.

### Details:
* Issue: When planning a query with `LIMIT`, our initial approach tried to reduce the number of rows sent over the wire. However, this optimization caused incorrect results in situations where GROUP BY was applied on the vtgate side. By pushing the `LIMIT` to the MySQL query, vtgate did not receive all the rows necessary for proper grouping and inspection.
* Fix: Adjust the logic to ensure `LIMIT` is not pushed down to MySQL queries in scenarios where vtgate needs to perform `GROUP BY`. This guarantees that all relevant rows are available for accurate grouping and aggregation.

## Related Issue(s)
Fixes #16262

## Checklist
-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by GuptaManan100 — APPROVED** [review]
LGTM!

File: go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go [hunk 1]
```diff
@@ -18,6 +18,7 @@ package aggregation
 
 import (
 	"fmt"
+	"math/rand"
```
Comment (dbussink) [inline go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go:21]: We should use rand/v2 in general everywhere. I moved everything to that not too long ago already.

Comment (dbussink) [reply go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go]: https://github.com/vitessio/vitess/pull/16264 to actually lint for this :smile:.

File: go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go [hunk 2]
```diff
@@ -69,6 +70,18 @@ func start(t *testing.T) (utils.MySQLCompare, func()) {
...
+	utils.SkipIfBinaryIsBelowVersion(t, 21, "vtgate")
+	mcmp, closer := start(t)
+	defer closer()
+
+	for i := range 1000 {
+		r := rand.IntN(10)
+		mcmp.Exec(fmt.Sprintf("insert into aggr_test(id, val1, val2) values(%d, 'a', %d)", i, r))
+	}
+	mcmp.Exec("select val2, count(*) from aggr_test group by val2 order by count(*), val2 limit 10")
+}
```
Comment (frouioui) [inline go/test/endtoend/vtgate/queries/aggregation/aggregation_test.go:83]: This test passes with or without the fix proposed by this PR. It would be nice to have a failing end-to-end test.
