### PR TITLE
fix: derived table join column expression to be part of add join predicate on rewrite

### LINKED ISSUE #15957: Joins with derived table and aliases produces bad plan
For a query that can be merged into a single route, if one of the tables is a derived tables, and it is aliasing a column that is used in 
a join predicate, Vitess produces the wrong query.

For the query:

```sql
select 1 
from user 
  join (
     select id as uid 
     from user) as t 
where t.uid = user.id
```

vtgate is now producing the following route:

```json
{
  "OperatorType": "Route",
  "Variant": "Scatter",
  "Keyspace": {
    "Name": "user",
    "Sharded": true
  },
  "FieldQuery": "select 1 from (select id as uid from `user` where 1 != 1) as t, `user` where 1 != 1",
  "Query": "select 1 from (select id as uid from `user` where id = :user_id) as t, `user` where t.uid = `user`.id",
  "Table": "`user`"
}
```

This is the only operator in the plan - there is not join feeding the `:user_id` argument, so the query fails to run.

### PR DESCRIPTION
**Pull request by harshit-gangal**
## Description
Fixes issue when pushing a join predicate into a derived table.

This was introduced in V19, in #14974

## Related Issue(s)
Fixes #15957

## Checklist
-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vtgate/planbuilder/operators/rewriters.go [hunk 1]
```diff
@@ -218,6 +218,9 @@ func bottomUp(
 			childID = childID.Merge(resolveID(oldInputs[0]))
 		}
 		in, changed := bottomUp(operator, childID, resolveID, rewriter, shouldVisit, false)
+		if DebugOperatorTree && changed.Changed() {
+			fmt.Println(ToTree(in))
```
Comment (dbussink) [inline go/vt/vtgate/planbuilder/operators/rewriters.go:222]: Looks like some stray debugging here that's left?

**Review by dbussink — APPROVED** [review]
Good once the stray debugging information is removed.

File: go/vt/vtgate/planbuilder/operators/rewriters.go (hunk 1 above)
Comment (deepthi) [reply go/vt/vtgate/planbuilder/operators/rewriters.go:222]: To be clear, this will only be logged from testing code, not production code.
