### PR TITLE
VTOrc: fix `ReplicationStopped` + `PrimarySemiSyncBlocked` recovery deadlock

### LINKED ISSUE #19921: Bug Report: VTOrc fails to restart replication when PrimarySemiSyncBlocked and ReplicationStopped co-exist
### Overview of the Issue

When a primary's disk fills up _(or any scenario where the primary becomes temporarily unable to write)_, replicas' replication threads can stop. Once the disk is expanded/recovered, VTOrc should detect `ReplicationStopped` on the replicas and restart replication via `fixReplica`. However, it doesn't — it gets stuck in a loop

The root cause is `recheckPrimaryHealth()` in `executeCheckAndRecoverFunction()`. Before running any non-shard-wide recovery _(like `fixReplica`)_, VTOrc re-discovers the primary and re-analyses it. If the primary has a detected problem, the replica fix is aborted:

```
aborting ReplicationStopped, primary mitigation is required
```

The problem is the primary's detected issue is `PrimarySemiSyncBlocked` — which exists *because* the replicas aren't replicating. This creates a deadlock:

1. VTOrc detects `ReplicationStopped` on a replica, prepares to run `fixReplica`
2. `recheckPrimaryHealth()` re-discovers the primary, detects `PrimarySemiSyncBlocked`
3. VTOrc aborts the replica fix: _"primary mitigation is required"_
4. Next cycle: same thing, forever

The replicas can't be fixed because the primary has a problem. The primary problem can't resolve because the replicas aren't replicating. Neither side makes progress

### Reproduction Steps

1. Configure a shard with semi-sync replication enabled _(durability policy requiring >= 1 semi-sync acker)_
2. Fill the primary tablet's disk to 100%, causing the filesystem to go read-only
3. Observe that replica replication threads stop _(IO thread disconnects or errors)_
4. Expand the primary's disk so it's writable again
5. Observe VTOrc logs — `fixReplica` is repeatedly aborted with `"aborting ReplicationStopped, primary mitigation is required"` because the primary is detected as `PrimarySemiSyncBlocked`
6. Replication is never restarted without manual intervention

### Binary Version

Introduced by https://github.com/vitessio/vitess/pull/18234 (`recheckPrimaryHealth`), first released in `v0.23.0`. Also backported to `release-19.0` and `release-21.0`

### Operating System and Environment details

N/A — this is a logic bug in VTOrc's recovery prioritisation, not environment-specific

### Log Fragments

Expected VTOrc log pattern during the deadlock:

```
Recovery for ReplicationStopped on ks/0: Starting checkAndRecover
recheckPrimaryHealth: Primary recovery is required, Tablet alias: zone1-0000000100
aborting ReplicationStopped, primary mitigation is required
```

...repeating every analysis cycle, indefinitely

### PR DESCRIPTION
**Pull request by timvaillancourt**
## Description

Fixes a deadlock in VTOrc's recovery ordering where `recheckPrimaryHealth` would abort `fixReplica` for `ReplicationStopped` because the primary had `PrimarySemiSyncBlocked` detected — but the semi-sync block existed *because* replicas weren't replicating. Neither side could make progress

#### What changed

1. **`ReplicationStopped` declares `BeforeAnalyses: [PrimarySemiSyncBlocked]`** — one line on the existing static `BeforeAnalyses` field. This tells the ordering system that stopped replicas should be fixed before the shard-wide semi-sync recovery runs. All `ReplicationStopped` replicas _(including non-ackers like RDONLY)_ declare this dependency — a fair tradeoff since `fixReplica` on a non-acker completes quickly. Thanks @shlomi-noach for [the suggestion](https://github.com/vitessio/vitess/pull/19925#issuecomment-4321662484)

2. **`GetDetectionAnalysis` no longer blindly suppresses analyses when a shard-wide action is detected** — previously, `hasShardWideAction` would `return nil` for all subsequent tablets. Now the matching loop still runs, and `declaresBefore()` / `declaresAfter()` check whether the tablet's matched problem has a static dependency on the shard-wide action. If it does, the analysis survives suppression _(and the declaring problem is promoted to the chosen problem if needed)_

3. **`shardWideRecoveryIgnoredTablets`** — reachable-but-unhealthy primaries _(like `PrimarySemiSyncBlocked` and `PrimaryDiskStalled`)_ are no longer skipped during the pre-recovery refresh, so `checkIfAlreadyFixed` evaluates fresh state. Dead primaries are still skipped since they're unreachable

4. **`recheckPrimaryHealth` recheck flow** — the boolean was inverted for clarity _(`recoveryRequired` → `alreadyFixed`)_ and the comment was updated to document how suppression interacts with `checkIfAlreadyFixed`

Existing static dependencies _(semi-sync must-be-set ordering, disk-stalled before dead-primary)_ are untouched

#### Why backport

This bug was introduced by #18234 (`recheckPrimaryHealth`), first released in `v0.23.0` and backported to `release-19.0` and `release-21.0`. This fix should be backported to at least `release-23.0` and `release-24.0`

## Related Issue(s)

Resolves: https://github.com/vitessio/vitess/issues/19921

## Checklist

- [x] "Backport to:" labels have been added if this change should be back-ported to release branches
- [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
- [x] Tests were added or are not required
- [x] Did the new or modified tests pass consistently locally and on CI?
- [x] Documentation was added or is not required

## Deployment Notes

No new flags or configuration. The fix changes VTOrc's internal recovery ordering behaviour — replicas with `ReplicationStopped` will now be fixed before `PrimarySemiSyncBlocked` is addressed, rather than being indefinitely blocked by `recheckPrimaryHealth`

### AI Disclosure

This PR was written primarily by Claude Code — I provided direction, design decisions, and review. Claude prepared this PR summary

### CODE REVIEW

File: go/vt/vtorc/inst/analysis_problem.go [hunk 1]
```diff
@@ -345,6 +405,31 @@ var detectionAnalysisProblems = []*DetectionAnalysisProblem{
...
+		BeforeAnalysesFunc: func(a *DetectionAnalysis, as []*DetectionAnalysis) []AnalysisCode {
+			// Only declare a dependency on PrimarySemiSyncBlocked if this
+			// replica is (or should be) a semi-sync acker. Restarting a
+			// non-acker replica won't unblock semi-sync, so it shouldn't
+			// delay the primary recovery.
+			if a == nil || !isSemiSyncAcker(a) {
+				return nil
+			}
+			for _, entry := range as {
+				if entry.Analysis == PrimarySemiSyncBlocked {
```
Comment (nickvanw) [inline go/vt/vtorc/inst/analysis_problem.go]: This dependency only takes effect if `PrimarySemiSyncBlocked` and the replica's `ReplicationStopped` are both present in `shardAnalyses`. Today `GetDetectionAnalysis` orders PRIMARY rows before REPLICA rows and returns early for the rest of the shard after a shard-wide action is selected (`analysis_dao.go`'s `ca.hasShardWideAction` path). So if the primary is already detected as `PrimarySemiSyncBlocked`, the stopped replica can still be suppressed before this dependency is considered, and VTOrc can remain on the primary-recovery path instead of fixing the stopped acker. I think we need to either collect/preserve the replica analyses that are ordered before the shard-wide problem, or otherwise make this bypass work even when the replica analysis was suppressed by that shard-wide action.

File: go/test/endtoend/vtorc/general/vtorc_test.go [hunk 2]
```diff
@@ -876,3 +876,64 @@ func TestSemiSyncRecoveryOrdering(t *testing.T) {
...
+
+	// Snapshot the FixReplica counter before stopping replication.
+	// VTOrc may have already incremented it during setup (e.g., for
+	// ReplicaSemiSyncMustBeSet under semi_sync durability).
+	fixReplicaCount := utils.GetSuccessfulRecoveryCount(t, vtorc, logic.FixReplicaRecoveryName, keyspace.Name, shard0.Name)
+
+	// Stop replication on the semi-sync acker (REPLICA). This causes
+	// PrimarySemiSyncBlocked on the primary. VTOrc should fix replication
+	// via the BeforeAnalysesFunc bypass in recheckPrimaryHealth.
+	_, err := utils.RunSQL(t, "STOP REPLICA", replica, "")
```
Comment (nickvanw) [inline go/test/endtoend/vtorc/general/vtorc_test.go:950]: This stops the semi-sync acker, but it does not force or assert that the primary has actually entered `PrimarySemiSyncBlocked` before we wait for `FixReplica`. Since `SemiSyncBlocked` is driven by blocked waiting writes, this test can pass through the normal `ReplicationStopped` recovery path without exercising the deadlock from the issue. Can we make the test create/observe the blocked primary condition first (for example by starting a write that blocks and/or waiting for VTOrc's detected problem/metric to show `PrimarySemiSyncBlocked`), then assert that `FixReplica` still completes?

**Review by nickvanw — COMMENTED** [review]
I left two inline comments. The main concern is that the new dynamic ordering still depends on both analyses making it into the shard analysis list, and the e2e test does not yet prove the primary-blocked half of the regression.

File: go/vt/vtorc/inst/analysis_problem.go (hunk 1 above)
Comment (nickvanw) [reply go/vt/vtorc/inst/analysis_problem.go]: Thinking about this more, I would avoid making the dependency function itself try to recover from missing shard context. The cleaner fix is probably in `GetDetectionAnalysis`: collect the candidate analyses for the shard first, then decide which ones to suppress once dependency ordering can be evaluated with the full shard picture.

Concretely, I’d want `PrimarySemiSyncBlocked` to remain the shard-wide action, but not suppress a semi-sync acker `ReplicationStopped` that declares it must run before `PrimarySemiSyncBlocked`. That keeps the special case expressed through the same Before/After dependency model this PR is adding, rather than adding a second bypass path in recovery. A focused unit test in `analysis_dao_test.go` should cover the important case: PRIMARY row is seen first, it matches `PrimarySemiSyncBlocked`, a later REPLICA row matches `ReplicationStopped` and is a semi-sync acker, and both analyses survive in the shard output with `ReplicationStopped` ordered first.

Comment (timvaillancourt) [reply go/vt/vtorc/inst/analysis_problem.go]: Updated in https://github.com/vitessio/vitess/pull/19925/commits/31e106a83e7ebecd41ed7c5679cfbd6f3629879b, please review 🙇

File: go/test/endtoend/vtorc/general/vtorc_test.go (hunk 2 above)
Comment (timvaillancourt) [reply go/test/endtoend/vtorc/general/vtorc_test.go:950]: Updated in https://github.com/vitessio/vitess/pull/19925/commits/31e106a83e7ebecd41ed7c5679cfbd6f3629879b, please review 🙇

**Review by mattlord — COMMENTED** [review]
I think the new dynamic-ordering framework is still only partially plumbed through the relevant code paths. In `go/vt/vtorc/inst/analysis_problem.go`, `compareDetectionAnalyses()` and `RequiresOrderedExecution()` treat `BeforeAnalysesFunc` and `AfterAnalysesFunc` as equivalent ways to express ordering, but in `go/vt/vtorc/inst/analysis_dao.go` the `hasShardWideAction` suppression bypass only checks `declaresBefore()`, i.e. only the suppressed problem’s `BeforeAnalysesFunc`. Once a shard-wide action has been seen, any dependency expressed only on the shard-wide side via `AfterAnalysesFunc` is still dropped before scheduling ever sees it. The current `ReplicationStopped` fix happens to work because the dependency is encoded on `ReplicationStopped` itself and the analysis query currently visits PRIMARY rows first (`ORDER BY vitess_tablet.tablet_type ASC`), but the API added here is still order-sensitive and incomplete AFAICT. I’d either move the preservation decision to a post-pass over the shard’s full matched set, or teach the suppression path to honor both sides of the dependency. A regression test that expresses the dependency via `AfterAnalysesFunc` would be ideal.

Or am I missing or misunderstanding something here?

**Comment by timvaillancourt** [comment]
Good catch @mattlord — you're right, this is actually a regression. The original implementation this PR had enforced ordering in the scheduling/recovery path where `compareDetectionAnalyses` checks both `BeforeAnalysesFunc` and `AfterAnalysesFunc`. When I moved the fix to the detection path (per reviewer feedback to keep it in the detection model), `declaresBefore()` only preserved the `BeforeAnalysesFunc` side.

The current fix works correctly because `ReplicationStopped` declares its dependency via `BeforeAnalysesFunc`, and the e2e test confirms the behavior. But `AfterAnalysesFunc` should also survive suppression for future use.

I'll fix the suppression path to honour both sides of the dependency and add a regression test that expresses the dependency via `AfterAnalysesFunc`. Thanks for catching this.

File: go/vt/vtorc/inst/analysis_dao.go [hunk 3]
```diff
@@ -446,7 +478,44 @@ func GetDetectionAnalysis(keyspace string, shard string, hints *DetectionAnalysi
...
+				// the shard-wide action. The dependency can be expressed
+				// from either side:
+				//   - the tablet's problem declares BeforeAnalysesFunc on
+				//     the shard-wide action, OR
+				//   - the shard-wide problem declares AfterAnalysesFunc on
+				//     the tablet's problem.
+				// If a non-chosen problem declares the dependency, promote
+				// it to the chosen problem so the recovery targets it.
+				survives := func(p *DetectionAnalysisProblem) bool {
+					return declaresBefore(p, a, ca.shardWideAnalysisCode) ||
```
Comment (nickvanw) [inline go/vt/vtorc/inst/analysis_dao.go]: Keeping the replica analysis here also leaves the original `PrimarySemiSyncBlocked` entry in the same shard analysis batch. `recoverShardAnalyses` will run the preserved `ReplicationStopped` first, but then it immediately processes the stale shard-wide entry from the same detection pass. That entry maps to `recoverDeadPrimaryFunc`, whose pre-recovery refresh path skips refreshing `analysisEntry.AnalyzedInstanceAlias`; for `PrimarySemiSyncBlocked`, that alias is the primary, not a dead/unreachable tablet. After `fixReplica` unblocks semi-sync, `checkIfAlreadyFixed` can still read stale primary state and proceed to ERS unnecessarily. Can we either drop/defer the shard-wide action when a before-dependency analysis is preserved, or explicitly refresh/revalidate the primary for `PrimarySemiSyncBlocked` before running it? A regression should also assert that no dead-primary/ERS recovery is attempted after `FixReplica` resolves the block.

**Review by nickvanw — COMMENTED** [review]
I found one production-risk issue in the current shape. The fix should make sure the preserved replica recovery cannot be followed by a stale `PrimarySemiSyncBlocked` shard-wide recovery that escalates to ERS after the replica has already been fixed.

File: go/vt/vtorc/inst/analysis_dao.go (hunk 3 above)
Comment (nickvanw) [reply go/vt/vtorc/inst/analysis_dao.go]: Concrete sequence I’m worried about:

1. One `GetDetectionAnalysis` call returns both `ReplicationStopped` on the acker and `PrimarySemiSyncBlocked` on the primary.
2. `GroupDetectionAnalysesByShard` sorts the acker first, so `recoverShardAnalyses` runs `fixReplica` first.
3. If `fixReplica` succeeds, that should unblock semi-sync, but the same in-memory batch still contains the old `PrimarySemiSyncBlocked` entry.
4. `recoverShardAnalyses` then processes that old shard-wide entry immediately.
5. Since `PrimarySemiSyncBlocked` maps to `recoverDeadPrimaryFunc`, the shard-wide pre-recovery refresh ignores `analysisEntry.AnalyzedInstanceAlias`; for this analysis that is the primary itself.
6. `checkIfAlreadyFixed` can therefore still evaluate stale primary state and allow ERS to run even though the replica fix may already have resolved the block.

The core thing I’d want guaranteed is: once a dependency recovery is preserved specifically because it can resolve the shard-wide problem, the stale shard-wide analysis from the same detection pass should not be able to trigger ERS without a fresh primary revalidation.

Comment (timvaillancourt) [reply go/vt/vtorc/inst/analysis_dao.go]: Thanks @nickvanw — good catch, this is a real risk. I've addressed it in this PR by deferring the shard-wide action when a before-dependency survives suppression. When `ReplicationStopped` on an acker is preserved, `postProcessAnalyses` now drops `PrimarySemiSyncBlocked` from the same detection pass. If the problem persists after `fixReplica`, it gets re-detected fresh on the next poll with current primary state.

The underlying issue — `PrimarySemiSyncBlocked` mapping to `recoverDeadPrimaryFunc` which skips refreshing a reachable primary — I've split into a follow-up: #19941. Wanted to keep this PR scoped to the deadlock fix.

Comment (timvaillancourt) [reply go/vt/vtorc/inst/analysis_dao.go]: @nickvanw I believe this is addressed in https://github.com/vitessio/vitess/pull/19925/commits/037afe9b1eeaaacfe6759074b102750ba403c832

**Review by nickvanw — DISMISSED** [review]
The latest commit addresses my concern by dropping the stale shard-wide `PrimarySemiSyncBlocked` action from the same detection pass once the dependency recovery is preserved. That removes the immediate stale-ERS risk after `fixReplica`.

The broader reachable-primary recovery path is tracked in #19941, which is the right follow-up. Approving this for the reported deadlock fix.

**Review by mattlord — COMMENTED** [review]
`deferShardWideAction` in `go/vt/vtorc/inst/analysis_dao.go` can starve the shard-wide recovery indefinitely, not just delay it by one poll. Once a dependency survives suppression, `GetDetectionAnalysis()` sets `ca.deferShardWideAction` and `postProcessAnalyses()` drops `PrimarySemiSyncBlocked` from the batch before we know whether `fixReplica` actually succeeded. If the acker stays `ReplicationStopped` because `FixReplica` fails, is skipped, or otherwise doesn’t clear the condition, the next poll rebuilds the same pair, defers the shard-wide action again, and VTOrc can loop forever on replica recovery without ever giving the current `PrimarySemiSyncBlocked -> recoverDeadPrimaryFunc` / ERS path a chance to run.

I don’t think punting the reachable-primary refresh to `#19941` is enough for this PR, because the workaround itself changes liveness. I’d either move the deferral decision into the recovery path so it only happens after a successful dependency recovery, or land the fresh-primary revalidation fix here and keep both analyses in the batch. A regression test where `FixReplica` keeps failing while `PrimarySemiSyncBlocked` persists would make this concrete.

**Review by mattlord — APPROVED** [review]
I still don’t see a focused regression that exercises this exact post-lock refresh/revalidation branch directly. `TestRecheckPrimaryHealth` covers the pre-lock dependency-preservation path, but it doesn’t prove the new “don’t ignore the analyzed primary” path that keeps a stale `PrimarySemiSyncBlocked` entry from reaching ERS after `fixReplica` succeeds. I won't block on that, but a targeted unit test around that branch would be good IMO.

**Comment by timvaillancourt** [comment]
> I still don’t see a focused regression that exercises this exact post-lock refresh/revalidation branch directly. `TestRecheckPrimaryHealth` covers the pre-lock dependency-preservation path, but it doesn’t prove the new “don’t ignore the analyzed primary” path that keeps a stale `PrimarySemiSyncBlocked` entry from reaching ERS after `fixReplica` succeeds. I won't block on that, but a targeted unit test around that branch would be good IMO.

@mattlord new tested added in https://github.com/vitessio/vitess/pull/19925/commits/71a40de73bcfb9f77cacebbea9e8be8a21af0144. Thanks for reviewing!

File: go/vt/vtorc/logic/topology_recovery.go [hunk 4]
```diff
@@ -950,11 +971,8 @@ func executeCheckAndRecoverFunction(analysisEntry *inst.DetectionAnalysis) (err
...
-			tabletsToIgnore := make([]*topodatapb.TabletAlias, 0)
-			if checkAndRecoverFunctionCode == recoverDeadPrimaryFunc {
-				tabletsToIgnore = append(tabletsToIgnore, analysisEntry.AnalyzedInstanceAlias)
-			}
-			// We ignore the dead primary tablet because it is going to be unreachable. If all the other tablets aren't able to reach this tablet either,
+			tabletsToIgnore := shardWideRecoveryIgnoredTablets(checkAndRecoverFunctionCode, analysisEntry)
+			// We ignore dead primary tablets because they are going to be unreachable. If all the other tablets aren't able to reach this tablet either,
 			// we can proceed with the dead primary recovery. We don't need to refresh the information for this dead tablet.
 			logger.Info("Force refreshing all shard tablets")
 			forceRefreshAllTabletsInShard(ctx, analysisEntry.AnalyzedKeyspace, analysisEntry.AnalyzedShard, tabletsToIgnore)
```
Comment (nickvanw) [inline go/vt/vtorc/logic/topology_recovery.go:978]: Refreshing the analyzed primary here is still best-effort, not a guarantee. `forceRefreshAllTabletsInShard()` just calls `DiscoverInstance(..., true)` and ignores refresh failures; if that discovery times out or errors, `ReadTopologyInstanceBufferable()` leaves the previous instance row in place and only updates last-check metadata. In that case `checkIfAlreadyFixed()` can still read a stale `PrimarySemiSyncBlocked` row and fall through to `recoverDeadPrimaryFunc`/ERS even after `fixReplica` already cleared the block. I think this path needs either a hard skip/abort when the primary revalidation fails, or an explicit success signal from the refresh before we trust the refreshed analysis.

**Review by nickvanw — COMMENTED** [review]
I found one production-risk issue in the new stale-revalidation path. The ordering changes make sense, but I don't think the new shard-wide refresh is strong enough yet to guarantee we won't still escalate a stale `PrimarySemiSyncBlocked` entry into ERS.

File: go/vt/vtorc/logic/topology_recovery.go (hunk 4 above)
Comment (timvaillancourt) [reply go/vt/vtorc/logic/topology_recovery.go:978]: :wave: @nickvanw Good catch — the concern is technically valid, but I think it's pre-existing rather than something introduced here. The fire-and-forget nature of `forceRefreshAllTabletsInShard` already exists for all `recoverDeadPrimaryFunc` cases (DeadPrimary, DeadPrimaryAndSomeReplicas, etc). This PR actually improves things for `PrimarySemiSyncBlocked` specifically — before this change the primary was skipped entirely during the refresh (same as dead primary cases), now it's included so `checkIfAlreadyFixed` has a better chance of seeing current state.

Also worth noting: if the primary can't respond to a `FullStatus` RPC within `RemoteOperationTimeout`, it's arguably still in trouble — a semi-sync blocked primary that's also unresponsive to health checks isn't exactly a false positive for ERS.

Happy to file a separate issue for hardening the refresh path (e.g. checking refresh success for the analyzed primary before trusting `checkIfAlreadyFixed`), or if you feel strongly I can include it in this PR's scope. What do you think?

**Review by nickvanw — APPROVED** [review]

**Comment by timvaillancourt** [comment]
@nickvanw regarding [the discussion in this thread](https://github.com/vitessio/vitess/pull/19925#pullrequestreview-4162963109): 

After thinking about this more, I think the concern is valid but describes a pre-existing architectural choice rather than something this PR introduces or can reasonably address
                                                                                                                                                                                                                
For better or worse, VTOrc's failure model treats a single failed `FullStatus` RPC as a tablet failure — everywhere, not just here. In `DeadPrimary`, we gain further confidence from replica I/O thread state, but for some problems this quorum is not possible and just the probe failing is the "signal". It's pessimistic and naive about its probe (one failure = unavailable), and quick to reach for ERS. So when the recovery refresh fails for `PrimarySemiSyncBlocked`, I'm hesitant to treat that as anything other than the primary having failed — which makes ERS the consistent and correct response within VTOrc's current model.                                                                                                                                                              
                                                                                                                                                                                                                
On `main` today, the primary is never refreshed for `PrimarySemiSyncBlocked` (it's in `tabletsToIgnore`, same as `DeadPrimary`), so ERS runs unconditionally every time. This PR makes it strictly better: the primary IS refreshed, so if the block cleared, `checkIfAlreadyFixed` sees fresh data and skips ERS. The only case where ERS still runs is when the primary can't respond — which is consistent with how VTOrc treats that everywhere else.                                                                                                                                                                                         
                                                                                                                                                                                                              
Adding special-case handling here (retry logic, abort-on-refresh-failure, etc.) would mean solving a broader VTOrc architecture issue in a scoped bugfix PR. I think that deserves its own discussion/issue if there's appetite for it.

So, I'm thinking we should exclude that idea: the PR demonstrates that it solves the problem it intended, and this hasn't introduced any new test failures in unit or e2e tests. That said, I'm going to spend a bit more time to see if I can add more testing (without slowing CI down) to gain further confidence - this may result in no realistic additions to testing. Curious what you thought? Thanks for reviewing

**Comment by shlomi-noach** [comment]
Great catch on a subtle bug — the interaction between `recheckPrimaryHealth` and shard-wide suppression is non-obvious and I can see why this ended up where it did.

Nice catch on the bug. There'sa lot for me to digest here as this PR builds on top of earlier changes I was not familiar with, namely the batching/grouping of `GroupDetectionAnalysesByShard` introduced in #19427.

With that said, I feel like this PR introduces new complexities which could be avoided.

The shift from `[]AnalysisCode` static slices to `func(*DetectionAnalysis, []*DetectionAnalysis) []AnalysisCode` pulls in a lot of surface area — new types, `GetBeforeAnalyses`/`GetAfterAnalyses` wrappers, `declaresBefore`/`declaresAfter` helpers, `isSemiSyncAcker`, signature changes on `compareDetectionAnalysisProblems` and `RequiresOrderedExecution`, and a rewrite of all existing tests to thread the new context argument. That's a lot of churn to support one conditional dependency.

I think the same correctness is achievable with the existing static `BeforeAnalyses []AnalysisCode` field, which `compareDetectionAnalysisProblems` and `RequiresOrderedExecution` already respect:

1. Add `BeforeAnalyses: []AnalysisCode{PrimarySemiSyncBlocked}` to the `ReplicationStopped` problem definition — 1 line, no new types.
2. Fix suppression in `GetDetectionAnalysis`: instead of the early `return nil` when `hasShardWideAction` is set, record the shard-wide analysis code, run matching anyway, and suppress only if no matched problem declares a `BeforeAnalyses` dependency on it.
3. The `shardWideRecoveryIgnoredTablets` extraction and the `recheckPrimaryHealth` logic are clean and should stay regardless.

The one thing the dynamic approach (as in this PR) gets that the static one (as I'm proposing above) doesn't: `isSemiSyncAcker()` precision — only actual ackers declare the dependency. With static `BeforeAnalyses`, all `ReplicationStopped` replicas (including RDONLY non-ackers) declare priority over `PrimarySemiSyncBlocked`. I think that's a fair tradeoff as `fixReplica` on a non-acker completes quickly.

So there's parts of this PR we could use as-is, and other parts we can avoid, to keep things simpler. Could I "challenge" you so to speak to try out a simpler approach?

**Comment by timvaillancourt** [comment]
@shlomi-noach I really appreciate the effort you went to, to provide this detailed review ❤️. I think we should prioritize simplicity in this code, given the immensity of the code - if we can achieve the same user-facing result with reduced complexity, this is a big win

As discussed offline, the lack of semi-sync awareness was raised as suggestion in PR review, which I actioned, but this made the approach more complex than necessary. For now I have implemented the simpler approach you suggest, where we do not add semi-sync awareness to the fix - avoiding lots of logic and changes

So decision made: we, for now, will not consider the semi-sync state of a replica. If it's stopped and `PrimarySemiSyncBlocked`, we will start replicas - any number, semi-sync or not. In practice the drawback-sounding parts of this statement are inconsequential, or we will address that separately 👍 

Thanks again!

**Review by shlomi-noach — APPROVED** [review]
Shipit 🚣

**Review by nickvanw — APPROVED** [review]
Approving. This is a net improvement for the reported VTOrc deadlock, and I’m okay with tracking the broader reachable-primary refresh hardening separately.
