### PR TITLE
Fixes the error messages in drop, create and alter database commands

### LINKED ISSUE #7396: Missing Error Number in CREATE DATABASE command
#### Overview of the Issue

In case of a `CREATE DATABASE` command and the database already exists, we do not send an error message number that is used by rails in `rails db:setup` command.

### PR DESCRIPTION
**Pull request by GuptaManan100**
Fixes the error messages in drop, create and alter database commands. Fixes #7396.

### CODE REVIEW

File: go/vt/vtgate/planbuilder/builder.go [hunk 1]
```diff
@@ -185,20 +187,20 @@ func buildDBDDLPlan(stmt sqlparser.Statement, vschema ContextVSchema) (engine.Pr
 			return engine.NewRowsPrimitive(make([][]sqltypes.Value, 0), make([]*querypb.Field, 0)), nil
 		}
 		if !ksExists {
-			return nil, vterrors.Errorf(vtrpcpb.Code_FAILED_PRECONDITION, "cannot drop database '%s'; database does not exists", ksName)
+			return nil, mysql.NewSQLError(mysql.ERDbDropExists, mysql.SSUnknownSQLState, "Can't drop database '%s'; database doesn't exists", ksName)
```
Comment (harshit-gangal) [inline go/vt/vtgate/planbuilder/builder.go:190]: nit: we can keep the error message as is. `Can't` `doesn't` does not seem good words to be in error message

Comment (GuptaManan100) [reply go/vt/vtgate/planbuilder/builder.go:190]: We took these messages from the mysql documentation https://dev.mysql.com/doc/mysql-errors/5.7/en/server-error-reference.html

**Review by harshit-gangal — APPROVED** [review]
