### PR TITLE
VReplication Atomic Copy Workflows: fix bugs around concurrent inserts

### LINKED ISSUE #17716: Atomic Copy: vttablet's panic in some cases when the copy phase starts
### Overview of the Issue

Some atomic copy `MoveTables` workflows are panicking if there is a non-null `lastPk` for a table. Not clear why the table has a non-null PK when the workflow starts. 

```
goroutine 3016 [running]:
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.(*TablePlan).appendFromRow(0xc000f2e1e0, 0xc000f3e638, 0xc000f1db60)
        vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/replicator_plan.go:634 +0xb72
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.(*TablePlan).applyBulkInsert(0xc000f2e1e0, 0xc000f3e638, {0xc000680480, 0xc, 0xc000beddd0?}, 0xc000beddb8)
        vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/replicator_plan.go:264 +0x23c
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.(*vcopierCopyWorker).insertRows(0xc0006ea390?, {0x2d1f7a8?, 0xc0003e0d90?}, {0xc000680480?, 0x12?, 0xc000d8f980?})
        vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/vcopier.go:1151 +0x56
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.(*vcopierCopyWorker).execute.func2({0x2d1f7a8?, 0xc0003e0d90?}, 0x0?)
        vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/vcopier.go:1069 +0x36
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.(*vcopierCopyTaskLifecycle).tryAdvance(0xc000c89d50, {0x2d1f7a8, 0xc0003e0d90}, 0xc001107240, 0x2, 0xc000bedf30)
        vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/vcopier.go:881 +0xaf
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.(*vcopierCopyWorker).execute(0xc000f3e600, {0x2d1f7a8, 0xc0003e0d90}, 0xc000c89d60)
        vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/vcopier.go:1111 +0x216
vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.(*vcopierCopyWorkQueue).enqueue.func1(0xc000bedf80?)
        vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/vcopier.go:771 +0x45
created by vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication.(*vcopierCopyWorkQueue).enqueue in goroutine 2645
        vitess.io/vitess/go/vt/vttablet/tabletmanager/vreplication/vcopier.go:779 +0x132
```

Confirmed in recent patch release of `v21`.

The panic happens on the first table being copied. However a simple `MoveTables` succeeds when copying just that one table.

### PR DESCRIPTION
**Pull request by rohit-nayak-ps**
## Description

Setting `--vreplication-parallel-insert-workers` greater than 1, had not been tested earlier for atomic copies. When a user attempted to do it, it caused a panic in `vttablet`. There were two fixes needed here:

1. The response needed to be cloned before passing it to the concurrent workers. This had been done for regular workflows but was missed in the atomic copy case.
2. The copy state for the last table was deleted incorrectly before the queue was closed (and all concurrent workers had stopped inserting). 

In addition the `TestFKWorkflow` e2e test has been changed to test with concurrent inserts. 

## Related Issue(s)

Fixes #17716 

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on CI?
-   [ ] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vttablet/tabletmanager/vreplication/vcopier_atomic.go [hunk 1]
```diff
@@ -205,7 +200,12 @@ func (vc *vcopier) copyAll(ctx context.Context, settings binlogplayer.VRSettings
 		log.Infof("copying table %s with lastpk %v", tableName, lastpkbv)
 		// Prepare a vcopierCopyTask for the current batch of work.
 		currCh := make(chan *vcopierCopyTaskResult, 1)
-		currT := newVCopierCopyTask(newVCopierCopyTaskArgs(resp.Rows, resp.Lastpk))
+
+		resp2 := resp
+		if parallelism > 1 {
+			resp2 = resp.CloneVT()
+		}
+		currT := newVCopierCopyTask(newVCopierCopyTaskArgs(resp2.Rows, resp2.Lastpk))
```
Comment (shlomi-noach) [inline go/vt/vttablet/tabletmanager/vreplication/vcopier_atomic.go:208]: Now that we know this was the bug, we can simplify the code:
```suggestion
		if parallelism > 1 {
			resp = resp.CloneVT()
		}
		currT := newVCopierCopyTask(newVCopierCopyTaskArgs(resp.Rows, resp.Lastpk))
```

**Review by shlomi-noach — APPROVED** [review]
Great catch! Minor code beauty suggestion, at your discretion.

**Review by mattlord — APPROVED** [review]
