### PR TITLE
Fix `vtctldclient`'s Root command to return an error on unknown command

### LINKED ISSUE #12480: vtctldclient exits 0 when given invalid command
### Overview of the Issue

When given an invalid subcommand (either due to something completely out of left field, or just a typo), `vtctldclient` should should display usage, an error message, and exit non-zero. Currently it only displays usage.

### Reproduction Steps

`vtctldclient foobarbaz >/dev/null || echo $?` shows nothing, but should show a number other than zero.

### Binary Version

```sh
v15.0.2
v16-rc1
```

### Operating System and Environment details

```sh
all OSes
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by ajm188**
## Description

Add a Run func to `vtctldclient`'s Root command to return an error on unknown command.

Cobra can't (and shouldn't!) be distinguish between "we didn't find a subcommand because the user made an error" and "we didn't find a subcommand because the user is trying to invoke a parent command with positional arguments", so we specify a run function (what cobra invokes when executing the command) on the root (top-level parent) and check if there are any positional arguments, which in our case we assume means the user was trying to run a subcommand that doesn't exist.

## Related Issue(s)

Closes #12480.

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by GuptaManan100 — APPROVED** [review]

**Review by GuptaManan100 — COMMENTED** [review]
Can we add a test to verify that it indeed returns an error?

**Comment by ajm188** [comment]
> Can we add a test to verify that it indeed returns an error?

Done!

**Comment by GuptaManan100** [comment]
Sweet! 🥇

File: go/cmd/vtctldclient/command/root.go [hunk 1]
```diff
@@ -78,6 +79,26 @@ var (
...
+		// we've structured things can only be a subcommand name, **and**
+		//
+		// (2) Cobra was unable to find a subcommand with that name for which to
+		// call a Run or RunE function.
+		//
+		// From this we conclude that the user was trying to either run a
+		// command that doesn't exist (e.g. "vtctldclient delete-my-data") or
+		// has misspelled a legitimate command (e.g. "vtctldclient StapReplication").
+		// If we think this has happened, return an error, which will get
+		// displayed to the user in main.go along with the usage.
```
Comment (mattlord) [inline go/cmd/vtctldclient/command/root.go:94]: Not something that I'm suggesting we bring in here but we could at some point use the "did you mean X" functionality that cobra provides via the `command.SuggestionsMinimumDistance = X` option. Maybe you explored it and there were downsides?

**Review by mattlord — APPROVED** [review]
Thanks!

File: go/cmd/vtctldclient/command/root.go (hunk 1 above)
Comment (ajm188) [reply go/cmd/vtctldclient/command/root.go:94]: i never explored it but i definitely want to at some point!
