### PR TITLE
dbconfigs: fix regression

### LINKED ISSUE #4870: utf8mb4 setting no longer honored by "-db-config-*-charset"
#### Overview of the Issue

We tried to upgrade our vttablets from [this commit](https://github.com/vitessio/vitess/commit/3818c0b21eb36d08cccfd249feda5bd75f74745e) to [this commit](https://github.com/vitessio/vitess/commit/fac849822e8fead6f35aae5aeefeeed44e0c3ec6) and found that we could no longer insert 4 byte unicode characters into tables that previously supported them. We have been setting the `-db-config-*-charset` flags on tablets to be `utf8mb4` and still are, but looking at the character sets in a mysql session connected through vtgates shows them defaulted to `utf8`:

```
mysql> SHOW SESSION VARIABLES LIKE 'character\_set\_%';');
+--------------------------+---------+
| Variable_name            | Value   |
+--------------------------+---------+
| character_set_client     | utf8    |
| character_set_connection | utf8    |
| character_set_database   | utf8mb4 |
| character_set_filesystem | binary  |
| character_set_results    | utf8    |
| character_set_server     | utf8mb4 |
| character_set_system     | utf8    |
+--------------------------+---------+
```

#### Reproduction Steps

I was able to reproduce this using the default vagrant setup from a clean repo with the [following modifications](https://github.com/tinyspeck/vitess/compare/master...tinyspeck:brirams_reproduce_charset_regression) where we:
- update `default-fast.cnf` to set client `default-character-set` and mysqld `character_set_server` and `collation_server` to `utf8mb4`
- update default character set on the examples `messages` table
- update `vttablet-up.sh` to set `-db-config-*-charset` to `utf8mb4`

From `master`:
- cherry pick settings change from https://github.com/tinyspeck/vitess/compare/master...tinyspeck:brirams_reproduce_charset_regression:

```
$ git cherry-pick brirams_reproduce_charset_regression
```

- setup and ssh into vagrant:

```
$ vagrant up && vagrant ssh`
```

- build and start test environment:

```
$ make build; ./vagrant-scripts/vitess/start.sh ; sleep 45; mysql --default-character-set='utf8mb4' -umysql_user -pmysql_password -h vitess -P 15306

mysql> SHOW SESSION VARIABLES LIKE 'character\_set\_%';');
+--------------------------+---------+
| Variable_name            | Value   |
+--------------------------+---------+
| character_set_client     | utf8    |
| character_set_connection | utf8    |
| character_set_database   | utf8mb4 |
| character_set_filesystem | binary  |
| character_set_results    | utf8    |
| character_set_server     | utf8mb4 |
| character_set_system     | utf8    |
+--------------------------+---------+

mysql> insert into messages(page,time_created_ns,message) values(5,2,'http://linkmoji.co/🗼 🚴😍');
ERROR 1366 (HY000): vtgate: http://vitess:15001/: execInsertSharded: target: test_keyspace.-.master, used tablet: test-100 (vitess): vttablet: rpc error: code = InvalidArgument desc = Incorrect string value: '\xF0\x9F\x97\xBC \xF0...' for column 'message' at row 1 (errno 1366) (sqlstate HY000) (CallerID: userData1): Sql: "insert into messages(page, time_created_ns, message) values (:_page0, :vtg2, :vtg3) /* vtgate:: keyspace_id:70bb023c810ca87a */", BindVars: {#maxLimit: "type:INT64 value:\"10001\" "_page0: "type:INT64 value:
```

From our previously working build, this _should_ be:

```
mysql> SHOW SESSION VARIABLES LIKE 'character\_set\_%';
+--------------------------+---------+
| Variable_name            | Value   |
+--------------------------+---------+
| character_set_client     | utf8mb4 |
| character_set_connection | utf8mb4 |
| character_set_database   | utf8mb4 |
| character_set_filesystem | binary  |
| character_set_results    | utf8mb4 |
| character_set_server     | utf8mb4 |
| character_set_system     | utf8    |
+--------------------------+---------+
7 rows in set (0.01 sec)

mysql> insert into messages(page,time_created_ns,message) values(5,2,'http://linkmoji.co/🗼 🚴😍');
Query OK, 1 row affected (0.00 sec)
```

#### Binary version
- built from current HEAD at the time of this writing: `ce908267c994cc49fa92b96acf21364d9cce8bee`

#### Operating system and Environment details

- vagrant setup provided on master

#### Notes

I've been trying to find the offending commit but that's been unsuccessful so far given the number of merges that have taken place since the last working version. What's interesting is that [this commit](https://github.com/vitessio/vitess/commit/1ab972b2298b6e3cb5a583b47175add66fad1390) is broken and [the commit immediately following it](https://github.com/vitessio/vitess/commit/cf1e37d4c694eeff6e6078420e201e45b3d80813) works but then breaks again on [next one](https://github.com/vitessio/vitess/commit/f0a9bc71a0e9e96d602ebc9b4888bf12827bab63). Diffing across branches, it's hard to pinpoint what exactly could have caused the breakage but hoping something jumps out at someone looking at this.

### PR DESCRIPTION
**Pull request by sougou**
@dasl @rafael @eeSeeGee @brirams 
Fixes #4870
PR #4814 introduced a regression where the base config would
override charset and flags even if the base config values for
those were not specified.

This change checks for those values before overriding them.

Signed-off-by: Sugu Sougoumarane <ssougou@gmail.com>

### CODE REVIEW

File: go/vt/dbconfigs/dbconfigs.go [hunk 1]
```diff
@@ -246,8 +246,12 @@ func Init(defaultSocketFile string) (*DBConfigs, error) {
 			uc.param.UnixSocket = defaultSocketFile
 		}
 
-		uc.param.Charset = baseConfig.Charset
-		uc.param.Flags = baseConfig.Flags
+		if baseConfig.Charset != "" {
```
Comment (dasl-) [inline go/vt/dbconfigs/dbconfigs.go]: it seems like the default `baseConfig.Charset` is `utf8`: https://github.com/planetscale/vitess/blob/65138f200afdf5d427e415dde9e22be5d5340f7d/go/vt/dbconfigs/dbconfigs.go#L97

Won't this only work if people override the `baseConfig.Charset` to be the empty string? I'd imagine most people who are using userconfig charsets are not overriding `baseConfig.Charset` to be the empty string?
