### PR TITLE
VTOrc: Update the primary key for all the tables from `hostname, port` to `alias`

### LINKED ISSUE #13112: Bug Report: DiscoverInstance (instance is nil) logs in VTOrc
### Overview of the Issue

It has been noticed that VTOrc sometimes has spurious logs like - `DiscoverInstance(10.10.10.10:3307) instance is nil in 0.002s (Backend: 0.002s, Instance: 0.000s), error=tablet alias is nil`.

I have looked at the code and I know how this is happening. Let's say initially you have a vttablet with hostname `h1`, port `p1`, and alias `a1`. Then, in the VTOrc backend, you would have 1 row in `vitess_tablet` for this tablet having all the three values `h1, p1 and a1` and you would have a record in `database_instance` for this tablet with the values `h1, p1` in it.

Now, let's say that this tablet gets evicted by Kubernetes and it restarts on a different machine. The tablet's alias remains the same, but the host and port would change, let's say to `h2` and `p2`. 

When VTOrc tries to refresh the information from the topo-server it would see this new record for the vttablet and try to insert a row into `vitess_tablet` with the values `h2, p2 and a1`. Since there is a uniqueness constraint on `alias` we end up replacing the row and the first row is automatically removed. We also load the MySQL information for this tablet and populate the data in `database_instance` with the values `h2, p2`. We don't store the alias in this table, so no uniqueness constraint fails and we have both the rows in the table now!

Now, we run the check to see what all tablets we need to forget about. This check runs by looking at the tablet aliases only and since the tablet alias for the given tablet didn't change, we conclude we have nothing to forget about.

Overall, this sequence of steps leads to a row in the `database_instance` table that should have actually been removed and is in the table without having a corresponding row in `vitess_tablet`. `ReadOutdatedInstanceKeys` picks up on this record and tries to refresh its information, but this errors out with `DiscoverInstance(10.10.10.10:3307) instance is nil in 0.002s (Backend: 0.002s, Instance: 0.000s), error=tablet alias is nil`

### Reproduction Steps

Described in the description.

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
all
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description

This PR updates the tables that VTOrc stores to use `alias` as the primary key instead of `hostname, port`. Before this refactor, I checked for the tables that weren't being used and cleaned up their usage entirely.

A lot of reading and writing to the database code has been fixed after making these changes. Tests for these have also been added in the PR. 

Moreover, I have also taken this oppurtunity to refactor and simplify some code as I was going along.

Test coverage before the changes - 
```go
~/vitess   main  go test -coverprofile cover.out ./go/vt/vtorc/... 
?       vitess.io/vitess/go/vt/vtorc/db [no test files]
?       vitess.io/vitess/go/vt/vtorc/discovery  [no test files]
ok      vitess.io/vitess/go/vt/vtorc/collection 0.280s  coverage: 37.2% of statements
ok      vitess.io/vitess/go/vt/vtorc/config     0.291s  coverage: 20.8% of statements
?       vitess.io/vitess/go/vt/vtorc/metrics    [no test files]
?       vitess.io/vitess/go/vt/vtorc/metrics/query      [no test files]
?       vitess.io/vitess/go/vt/vtorc/process    [no test files]
?       vitess.io/vitess/go/vt/vtorc/test       [no test files]
ok      vitess.io/vitess/go/vt/vtorc/inst       0.579s  coverage: 37.5% of statements
ok      vitess.io/vitess/go/vt/vtorc/logic      1.035s  coverage: 25.9% of statements
ok      vitess.io/vitess/go/vt/vtorc/server     0.831s  coverage: 6.4% of statements
ok      vitess.io/vitess/go/vt/vtorc/util       0.574s  coverage: 22.0% of statements
```

Test coverage after the changes - 
```go
?       vitess.io/vitess/go/vt/vtorc/db [no test files]
?       vitess.io/vitess/go/vt/vtorc/discovery  [no test files]
ok      vitess.io/vitess/go/vt/vtorc/collection 0.844s  coverage: 37.2% of statements
?       vitess.io/vitess/go/vt/vtorc/metrics    [no test files]
?       vitess.io/vitess/go/vt/vtorc/metrics/query      [no test files]
?       vitess.io/vitess/go/vt/vtorc/process    [no test files]
?       vitess.io/vitess/go/vt/vtorc/test       [no test files]
ok      vitess.io/vitess/go/vt/vtorc/config     1.110s  coverage: 20.8% of statements
ok      vitess.io/vitess/go/vt/vtorc/inst       2.509s  coverage: 60.6% of statements
ok      vitess.io/vitess/go/vt/vtorc/logic      2.296s  coverage: 26.1% of statements
ok      vitess.io/vitess/go/vt/vtorc/server     1.564s  coverage: 6.5% of statements
ok      vitess.io/vitess/go/vt/vtorc/util       0.718s  coverage: 22.0% of statements

```

## Related Issue(s)

- Fixes #13112 

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vtorc/db/generate_base.go [hunk 1]
```diff
@@ -23,6 +23,7 @@ DROP TABLE IF EXISTS database_instance
 `,
 	`
 CREATE TABLE database_instance (
```
Comment (deepthi) [inline go/vt/vtorc/db/generate_base.go:25]: If I'm reading this correctly, this is the only table where we still retain (hostname, port) because we do need that information. It's deleted from all other tables and replaced with alias, correct?

File: go/vt/vtorc/inst/analysis_dao_test.go [hunk 2]
```diff
@@ -672,3 +675,75 @@ func TestGetReplicationAnalysis(t *testing.T) {
 		})
 	}
 }
+
+// TestAuditInstanceAnalysisInChangelog tests the functionality of the auditInstanceAnalysisInChangelog function
+// and verifies that we write the correct amount of times to the database.
```
Comment (deepthi) [inline go/vt/vtorc/inst/analysis_dao_test.go:682]: nit: amount -> number

File: go/vt/vtorc/db/generate_base.go (hunk 1 above)
Comment (GuptaManan100) [reply go/vt/vtorc/db/generate_base.go:25]: Yes, we need the information because at the MySQL level we only the `source_host` and `source_port` and not the `source_alias`, so in order to know which tablet a certain MySQL instance is replicating from, we need to know the `host` and `port` of the tablet.

**Comment by GuptaManan100** [comment]
@deepthi -
> Why do we not need host name resolution anymore?

We haven't needed it for a while now. It was part of orchestrator to ensure that different addresses all corresponding to the same instance are treated differently, for example, `localhost:15999` vs `127.0.0.1:15999`. In VTOrc, we use the tablet record for the source of truth, so we don't need these unnecessary DNS lookups anymore.

> What was the downtime functionality and why is it not required anymore?

I am not entirely sure what it was used for in orchestrator, but in VTOrc `BeginDowntime` was an unused function. Deleting it, led to the entire table and corresponding code not being used at all. I think there were CLI commands and APIs to mark certain tablets downtimed so that they were treated differently and no failure fixes were run on them. In Vitess if a user wants to take down a tablet, they should just change its type to `SPARE`.

File: go/vt/vtorc/inst/analysis_dao_test.go (hunk 2 above)
Comment (GuptaManan100) [reply go/vt/vtorc/inst/analysis_dao_test.go]: Fixed!
