### PR TITLE
PlannedReparent fixes

### LINKED ISSUE #5991: PlannedReparent improvements
#### Overview of the Issue
During a planned reparent, it is possible that `PromoteSlaveWhenCaughtUp` succeeds without an error but the outer context has been canceled. In that situation, we still call `UndoDemoteMaster` with a background context. 
By design, the old master discovers that it is no longer master and changes its type to REPLICA. However, the call to UndoDemoteMaster is ~unnecessary~ insufficient in this situation (as explained further below).
When the outer context is canceled at a point where `PromoteSlaveWhenCaughtUp` has completed, other replicas are still pointing to the old master, so we can end up with a situation like this:

```
               New Master <---- Old Master <---- Other replicas
```
To prevent this, we should consider two additional safeguards:
- add logic in `PromoteSlaveWhenCaughtUp` to revert any partial changes in case of errors.
- create an `UndoPromoteSlave` that is called along with `UndoDemoteMaster`.

Code snippet for reference:
https://github.com/vitessio/vitess/blame/master/go/vt/wrangler/reparent.go#L605
```
		rp, err = wr.tmc.PromoteSlaveWhenCaughtUp(promoteCtx, masterElectTabletInfo.Tablet, rp)
		if err != nil || (ctx.Err() != nil && ctx.Err() == context.DeadlineExceeded) {
			// If we fail to promote the new master, try to roll back to the
			// original master before aborting.
			// It is possible that we have used up the original context, or that
			// not enough time is left on it before it times out.
			// But at this point we really need to be able to Undo so as not to
			// leave the cluster in a bad state.
			// So we create a fresh context based on context.Background().
			undoCtx, undoCancel := context.WithTimeout(context.Background(), *topo.RemoteOperationTimeout)
			defer undoCancel()
			if err1 := wr.tmc.UndoDemoteMaster(undoCtx, oldMasterTabletInfo.Tablet); err1 != nil {
				log.Warningf("Encountered error %v while trying to undo DemoteMaster", err1)
			}
			return fmt.Errorf("master-elect tablet %v failed to catch up with replication or be upgraded to master: %v", masterElectTabletAliasStr, err)
		}
```

### PR DESCRIPTION
**Pull request by deepthi**
This PR implements parts 1-3 listed in #5991. Part 4 will be done as a separate PR.

## RELEASE NOTE: ACTION REQUIRED
When updating from a version before this PR to a version after it, it is critical that you follow the [recommended upgrade order](https://vitess.io/docs/user-guides/upgrading/#upgrade-order). In particular, you must upgrade all the vttablets in the cluster before upgrading any of the vtctlds.

Similarly, if you need to downgrade from a version after this PR to a version before it, you must downgrade in the reverse order: downgrade all vtctlds before downgrading any vttablets.

### CODE REVIEW

File: go/mysql/slave_status.go [hunk 1]
```diff
@@ -57,8 +59,14 @@ func ProtoToSlaveStatus(s *replicationdatapb.Status) SlaveStatus {
 	if err != nil {
 		panic(vterrors.Wrapf(err, "cannot decode Position"))
 	}
+	rpos, err := DecodePosition(s.RelayLogPosition)
+	if err != nil {
+		panic(vterrors.Wrapf(err, "cannot decode Position"))
```
Comment (enisoc) [inline go/mysql/slave_status.go:64]:
```suggestion
		panic(vterrors.Wrapf(err, "cannot decode RelayLogPosition"))
```

File: go/vt/vttablet/tabletmanager/rpc_replication.go [hunk 2]
```diff
@@ -421,12 +421,28 @@ func (agent *ActionAgent) demoteMaster(ctx context.Context, revertPartialFailure
...
+		pos, err := agent.MysqlDaemon.MasterPosition()
+		if err != nil {
+			return "", err
+		}
+		return mysql.EncodePosition(pos), nil
+	}
+	rs, err := agent.MysqlDaemon.SlaveStatus()
 	if err != nil {
-		return "", err
+		// fall back to masterPosition
```
Comment (enisoc) [inline go/vt/vttablet/tabletmanager/rpc_replication.go:438]: I'd feel better if we only fall back if the error is specifically `ErrNotSlave`. If it's something else, we don't really know whether it's safe to fall back.

File: go/vt/vttablet/tabletmanager/rpc_replication.go [hunk 3]
```diff
@@ -421,12 +421,28 @@ func (agent *ActionAgent) demoteMaster(ctx context.Context, revertPartialFailure
...
+		pos, err := agent.MysqlDaemon.MasterPosition()
+		if err != nil {
+			return "", err
+		}
+		return mysql.EncodePosition(pos), nil
 	}
-	return mysql.EncodePosition(pos), nil
+	return mysql.EncodePosition(rs.RelayLogPosition), nil
```
Comment (enisoc) [inline go/vt/vttablet/tabletmanager/rpc_replication.go:445]: Currently, if there are errant transactions on this replica, they'll show up in the returned position. Does that end up protecting us against any scenario? Do we lose that if we return the relay log pos instead?

Maybe we should check for this case and fail if our expected invariant does not hold? If one of relayPos or masterPos are a superset of the other (`AtLeast()`), then return the one that's farther ahead. If neither is a superset of the other, return an error saying we detected errant transactions and this replica should not be used as a master.

File: go/vt/vttablet/tabletmanager/rpc_replication.go [hunk 4]
```diff
@@ -744,14 +763,14 @@ func (agent *ActionAgent) StopReplicationAndGetStatus(ctx context.Context) (*rep
 	return mysql.SlaveStatusToProto(rs), nil
 }
 
-// PromoteSlave makes the current tablet the master
-func (agent *ActionAgent) PromoteSlave(ctx context.Context) (string, error) {
+// PromoteReplica makes the current tablet the master
+func (agent *ActionAgent) PromoteReplica(ctx context.Context) (replicationPosition string, finalErr error) {
```
Comment (enisoc) [inline go/vt/vttablet/tabletmanager/rpc_replication.go:767]: Is this behaviorally different from the deprecated method, or are they the same other than the name? The way git had chosen to show the diffs, it's hard to tell.

File: go/vt/wrangler/reparent.go [hunk 5]
```diff
@@ -599,11 +607,34 @@ func (wr *Wrangler) plannedReparentShardLocked(ctx context.Context, ev *events.R
 		wr.logger.Infof("promote replica %v", masterElectTabletAliasStr)
 		event.DispatchUpdate(ev, "promoting replica")
 
+		waitCtx, waitCancel := context.WithTimeout(ctx, waitReplicasTimeout)
+		defer waitCancel()
+
+		err = wr.tmc.WaitForPosition(waitCtx, masterElectTabletInfo.Tablet, rp)
+
+		if err != nil || ctx.Err() != nil && ctx.Err() == context.DeadlineExceeded {
```
Comment (enisoc) [inline go/vt/wrangler/reparent.go:615]: This can be simplified, right?

```suggestion
		if err != nil || ctx.Err() == context.DeadlineExceeded {
```

File: go/vt/wrangler/reparent.go [hunk 6]
```diff
@@ -599,11 +607,34 @@ func (wr *Wrangler) plannedReparentShardLocked(ctx context.Context, ev *events.R
...
+			// not enough time is left on it before it times out.
+			// But at this point we really need to be able to Undo so as not to
+			// leave the cluster in a bad state.
+			// So we create a fresh context based on context.Background().
+			undoCtx, undoCancel := context.WithTimeout(context.Background(), *topo.RemoteOperationTimeout)
+			defer undoCancel()
+			if err1 := wr.tmc.UndoDemoteMaster(undoCtx, oldMasterTabletInfo.Tablet); err1 != nil {
+				log.Warningf("Encountered error %v while trying to undo DemoteMaster", err1)
+			}
+			if err != nil {
```
Comment (enisoc) [inline go/vt/wrangler/reparent.go:628]: By the time I get down here, I've lost track of what call produced `err`. Can we make a new var called `waitErr`?

File: go/vt/wrangler/reparent.go [hunk 7]
```diff
@@ -599,11 +607,34 @@ func (wr *Wrangler) plannedReparentShardLocked(ctx context.Context, ev *events.R
...
+			// we try to roll back to the original master before aborting.
+			// It is possible that we have used up the original context, or that
+			// not enough time is left on it before it times out.
+			// But at this point we really need to be able to Undo so as not to
+			// leave the cluster in a bad state.
+			// So we create a fresh context based on context.Background().
+			undoCtx, undoCancel := context.WithTimeout(context.Background(), *topo.RemoteOperationTimeout)
+			defer undoCancel()
+			if err1 := wr.tmc.UndoDemoteMaster(undoCtx, oldMasterTabletInfo.Tablet); err1 != nil {
+				log.Warningf("Encountered error %v while trying to undo DemoteMaster", err1)
```
Comment (enisoc) [inline go/vt/wrangler/reparent.go:626]: I prefer to print errors at the end since they can often be long:

```suggestion
				log.Warningf("Encountered error while trying to undo DemoteMaster: %v", err1)
```

File: go/vt/wrangler/reparent.go [hunk 8]
```diff
@@ -599,11 +607,34 @@ func (wr *Wrangler) plannedReparentShardLocked(ctx context.Context, ev *events.R
...
+			return vterrors.New(vtrpcpb.Code_DEADLINE_EXCEEDED, "PlannedReparent timed out, please try again.")
+		}
+
 		promoteCtx, promoteCancel := context.WithTimeout(ctx, waitReplicasTimeout)
 		defer promoteCancel()
-
-		rp, err = wr.tmc.PromoteSlaveWhenCaughtUp(promoteCtx, masterElectTabletInfo.Tablet, rp)
-		if err != nil || (ctx.Err() != nil && ctx.Err() == context.DeadlineExceeded) {
+		rp, err = wr.tmc.PromoteReplica(promoteCtx, masterElectTabletInfo.Tablet)
+		if err != nil {
```
Comment (enisoc) [inline go/vt/wrangler/reparent.go:637]: Isn't this the one where we can't be sure it's ok to undo, so we decided to require that they run PRS again to either retry or roll back?

File: go/vt/wrangler/reparent.go [hunk 9]
```diff
@@ -616,7 +647,10 @@ func (wr *Wrangler) plannedReparentShardLocked(ctx context.Context, ev *events.R
 			if err1 := wr.tmc.UndoDemoteMaster(undoCtx, oldMasterTabletInfo.Tablet); err1 != nil {
 				log.Warningf("Encountered error %v while trying to undo DemoteMaster", err1)
 			}
-			return fmt.Errorf("master-elect tablet %v failed to catch up with replication or be upgraded to master: %v", masterElectTabletAliasStr, err)
+			return fmt.Errorf("master-elect tablet %v failed to be upgraded to master: %v", masterElectTabletAliasStr, err)
+		} else if ctx.Err() != nil && ctx.Err() == context.DeadlineExceeded {
```
Comment (enisoc) [inline go/vt/wrangler/reparent.go:651]: This doesn't need to be an else, does it?

File: go/vt/wrangler/reparent.go [hunk 10]
```diff
@@ -763,9 +797,11 @@ func (maxPosSearch *maxReplPosSearch) processTablet(tablet *topodatapb.Tablet) {
 		maxPosSearch.wrangler.logger.Warningf("failed to get replication status from %v, ignoring tablet: %v", topoproto.TabletAliasString(tablet.Alias), err)
 		return
 	}
-	replPos, err := mysql.DecodePosition(status.Position)
+	// The replica that is most progressed may actually be the one with the furthest
```
Comment (enisoc) [inline go/vt/wrangler/reparent.go:800]: I think we should check both positions and use the one that's a superset of the other. If neither is a true superset, then we have detected errant transactions and it isn't safe to promote this replica.

File: go/vt/wrangler/reparent.go [hunk 11]
```diff
@@ -934,27 +970,28 @@ func (wr *Wrangler) emergencyReparentShardLocked(ctx context.Context, ev *events
 	if !ok {
 		return fmt.Errorf("couldn't get master elect %v replication position", topoproto.TabletAliasString(masterElectTabletAlias))
 	}
-	masterElectPos, err := mysql.DecodePosition(masterElectStatus.Position)
+	// Use RelayLogPosition to determine most advanced tablet
+	masterElectPos, err := mysql.DecodePosition(masterElectStatus.RelayLogPosition)
```
Comment (enisoc) [inline go/vt/wrangler/reparent.go:974]: I have the same suggestion here about looking at both positions whenever both are known.

File: go/mysql/slave_status.go (hunk 1 above)
Comment (deepthi) [reply go/mysql/slave_status.go:64]: Thank you, I missed that one.

File: go/vt/vttablet/tabletmanager/rpc_replication.go (hunk 4 above)
Comment (deepthi) [reply go/vt/vttablet/tabletmanager/rpc_replication.go:767]: The behavior is different because we now write to topo _before_ calling SetReadOnly. We used to do it _after_. But.. looks like I also changed the old RPC to have the new behavior. I can change it back if we want to preserve it. WDYT?

File: go/vt/wrangler/reparent.go (hunk 5 above)
Comment (deepthi) [reply go/vt/wrangler/reparent.go:615]: haha, yes. Don't know what I was thinking..

File: go/vt/wrangler/reparent.go (hunk 6 above)
Comment (deepthi) [reply go/vt/wrangler/reparent.go:628]: Good suggestion. In fact, I'll change each block to have its own err var, similar to how we did contexts. That will be much more readable.

File: go/vt/vttablet/tabletmanager/rpc_replication.go (hunk 2 above)
Comment (deepthi) [reply go/vt/vttablet/tabletmanager/rpc_replication.go:440]: Done

File: go/vt/vttablet/tabletmanager/rpc_replication.go (hunk 3 above)
Comment (deepthi) [reply go/vt/vttablet/tabletmanager/rpc_replication.go:453]: Actually, if masterPos is a superset of relayPos, that is exactly the errant transaction situation. The latest commit addresses this.

**Comment by deepthi** [comment]
> This is going to be another one of those changes that makes it critical to use the recommended upgrade order since vtctld expects a new tabletmanager RPC, right? What's the process for making a sufficient amount of noise about that?

Fair point. We will announce this on vitess slack, and put it in release notes. I will also edit the PR description and add a notice.

File: go/vt/vttablet/tabletmanager/rpc_replication.go (hunk 4 above)
Comment (enisoc) [reply go/vt/vttablet/tabletmanager/rpc_replication.go:775]: Hm yeah I think it makes sense to keep the old RPC with the old behavior. It may have been ok anyway, but it seems safer to be conservative since the switch to a new RPC gives us that option.

File: go/vt/wrangler/reparent.go (hunk 8 above)
Comment (deepthi) [reply go/vt/wrangler/reparent.go:636]: I was hoping that an error from `PromoteReplica` meant that the replica is still read-only. But looking at the code, that is not the last thing we do, so we can't be sure.
Fixed to not call Undo here any more.

File: go/vt/vttablet/tabletmanager/rpc_replication.go (hunk 3 above)
Comment (deepthi) [reply go/vt/vttablet/tabletmanager/rpc_replication.go:453]: Based on experiments with relayLogPosition, we have decided to exclude that logic from this PR, and do it as a separate PR.

File: go/vt/vttablet/tabletmanager/rpc_replication.go (hunk 4 above)
Comment (deepthi) [reply go/vt/vttablet/tabletmanager/rpc_replication.go]: Done.

File: go/vt/wrangler/reparent.go (hunk 10 above)
Comment (deepthi) [reply go/vt/wrangler/reparent.go]: Deferred to a future PR.

File: go/vt/wrangler/reparent.go (hunk 11 above)
Comment (deepthi) [reply go/vt/wrangler/reparent.go]: Using RelayLogPosition has been deferred to a future PR.

File: go/vt/wrangler/reparent.go (hunk 9 above)
Comment (deepthi) [reply go/vt/wrangler/reparent.go]: Fixed.

File: go/vt/wrangler/reparent.go [hunk 12]
```diff
@@ -518,17 +518,25 @@ func (wr *Wrangler) plannedReparentShardLocked(ctx context.Context, ev *events.R
...
 		reparentJournalPos = rp
 	} else if topoproto.TabletAliasEqual(currentMaster.Alias, masterElectTabletAlias) {
-		refreshCtx, refreshCancel := context.WithTimeout(ctx, *topo.RemoteOperationTimeout)
-		defer refreshCancel()
+		// It is possible that a previous attempt to reparent failed to SetReadWrite
+		// so call it here to make sure underlying mysql is ReadWrite
+		rwCtx, rwCancel := context.WithTimeout(ctx, *topo.RemoteOperationTimeout)
+		defer rwCancel()
 
+		if err := wr.tmc.SetReadWrite(rwCtx, masterElectTabletInfo.Tablet); err != nil {
```
Comment (enisoc) [inline go/vt/wrangler/reparent.go:532]: I can't put my finger on it, but this makes me feel vaguely uneasy. Is it clear in your mind how we're confident at this point that no other tablet's mysqld is read-write? I'm having trouble putting together that chain of reasoning.

Comment (sougou) [reply go/vt/wrangler/reparent.go:532]: Let's replay the steps:
1. Mark old master read-only
2. Designate new master in topo (mastership+timestamp)
3. Mark new master read-write
4. Do the rest of the steps

If something fails after step 1, the topo will return the old one as master, and we just have to PRS on it.
If something fails after step 2, the topo will return the new one as master, and we perform steps 3 onwards.

This is probably your discomfort (which I also feel a bit): Is there a situation where the topo will return the old one as master after we complete step 2? By our reasoning of timestamps, it should not, because we compare all timestamps before identifying the true master.

I would feel slightly better if we marked the old master as replica before step 2, at least as best effort. But you and deepthi convinced me that it's unnecessary.

Comment (deepthi) [reply go/vt/wrangler/reparent.go:532]: This reasoning seems sound. I had included a new test that re-runs PRS on the candidate master after first simulating a failure in step 2. I could add more tests like that (simulating failures at other points in the sequence).

Comment (enisoc) [reply go/vt/wrangler/reparent.go:532]: I'm convinced as well. Thanks.
