### PR TITLE
vtgate: defer implicit transaction start until after query planning

### LINKED ISSUE #19276: Bug Report: `autocommit=0` starts transactions too early
### Overview of the Issue

When `autocommit` on a shard or tablet targetted connection is set to `0`, Vitess will use a reserved connection to execute all following sql statements until `autocommit` is switched back to `1`.

On this reserved connection, queries will be prepended with a `BEGIN` statement if the connection is not yet inside of a transaction. Effectively, Vitess tries to emulate `autocommit=0` on a connection that has autocommit enabled.

Unfortunately, this is too aggressive in some cases. For example, even for `SET` and `SHOW` queries, we will end up starting an explicit transaction. This is different from what MySQL does (where a transaction is only started for "transactional" statements).

This works fine _most_ of the time, but can cause unexpected issues, e.g. when `SET TRANSACTION ISOLATION LEVEL ...` is executed, because that statement can't be executed when inside of a transaction.

### Reproduction Steps

N/A

### Binary Version

```sh
N/A
```

### Operating System and Environment details

```sh
N/A
```

### Log Fragments

```sh
N/A
```

### PR DESCRIPTION
**Pull request by arthurschreiber**
## Description

Before https://github.com/vitessio/vitess/pull/19318 was merged, `SET SESSION TRANSACTION ISOLATION LEVEL` statements were failing with MySQL error 1568 on a targeted `autocommit=0` connection:

```
Transaction characteristics can't be changed while a transaction is in progress
```

This was because `SET SESSION TRANSACTION ISOLATION LEVEL` was wrongly turned into `SET TRANSACTION ISOLATION LEVEL`, but was prepended by a `BEGIN` statement when in `autocommit=0` mode.

On non-targeted `autocommit=0` connections (and on targeted `autocommit=0` connections after https://github.com/vitessio/vitess/pull/19318 was merged), this would instead simply cause the transaction isolation level to not be active until a transaction commit.

---

Both of these issues are caused by `vtgate` eagerly starting implicit transactions where MySQL itself would not. For example, `SET` statements, `SELECT` statements against `dual` and many `SHOW` statements **do not** start an implicit transaction in `autocommit=0`. This pull request tries to align the Vitess behavior more closely with MySQL behavior.

---

`startTxIfNecessary()` was called unconditionally before query planning, starting an implicit transaction for ALL statements. When the SET statement later executed via `ReserveBeginExecute`, MySQL rejected it because a transaction was already in progress.

Move `startTxIfNecessary()` to run after plan creation, and only call it for statement types that actually need transactions. Session management statements (SET, SHOW, USE, COMMENT, EXPLAIN) now skip implicit transaction start, matching MySQL's behavior.

---

I'm not sure this is a full/proper fix for this behavior. I feel like maybe we should change how `autocommit=0` works so that we don't need to implicitly implement transactions around the statements being executed. If we have a reserved connection (which from my understanding we always do when `autocommit=0`, then shouldn't we be able to set `autocommit` to `0` on the reserved connection and have MySQL handle everything? 🤔 

## Related Issue(s)

Fixes #19276.

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/test/endtoend/vtgate/reservedconn/sysvar_test.go [hunk 1]
```diff
@@ -452,6 +452,76 @@ func TestSysVarTxIsolation(t *testing.T) {
...
+	utils.Exec(t, conn, "SET @@autocommit = 0")
+
+	// Check initial state and connection ID
+	qr := utils.Exec(t, conn, "SELECT @@transaction_isolation, @@autocommit, connection_id()")
+	t.Logf("Initial state: %v", qr.Rows)
+
+	// Test 1: Setting isolation level with autocommit=0 should work
+	// This was failing with error 1568 because Vitess was incorrectly starting
+	// a transaction before sending the SET statement to MySQL
+	utils.Exec(t, conn, "SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED")
```
Comment (arthurschreiber) [inline go/test/endtoend/vtgate/reservedconn/sysvar_test.go]: This needs to be changed to call `SET TRANSACTION ISOLATION LEVEL`. There's a separate bug with the `SESSION` level setting of this variable, but I'll tackle that in a different PR.

File: go/vt/vtgate/plan_execute.go [hunk 2]
```diff
@@ -278,6 +282,50 @@ func (e *Executor) startTxIfNecessary(ctx context.Context, safeSession *econtext
...
+func planStartsImplicitTx(plan *engine.Plan, stmt sqlparser.Statement) bool {
+	switch plan.QueryType {
+	case sqlparser.StmtSelect, sqlparser.StmtInsert, sqlparser.StmtReplace, sqlparser.StmtUpdate, sqlparser.StmtDelete:
+		// Only start an implicit tx if the plan accesses real tables, not just dual.
+		for _, table := range plan.TablesUsed {
+			if !strings.HasSuffix(table, ".dual") {
+				return true
+			}
+		}
+		return false
```
Comment (mhamza15) [inline go/vt/vtgate/plan_execute.go:299]: Nit: could use [`slices.ContainsFunc`](https://pkg.go.dev/slices#ContainsFunc).

File: go/vt/vtgate/plan_execute.go [hunk 3]
```diff
@@ -278,6 +282,50 @@ func (e *Executor) startTxIfNecessary(ctx context.Context, safeSession *econtext
...
+		}
+		switch basic.Command {
+		case sqlparser.Table, sqlparser.Database, sqlparser.Column, sqlparser.Index,
+			sqlparser.Trigger, sqlparser.TableStatus,
+			sqlparser.Charset, sqlparser.Collation,
+			sqlparser.Function, sqlparser.Procedure:
+			return true
+		default:
+			return false
+		}
```
Comment (mhamza15) [inline go/vt/vtgate/plan_execute.go]: Nit: a constant + `slices.Contains` might be clearer? `commandsNeedingImplicitTransactions` or something (that's a mouthful 😆)

File: go/test/endtoend/vtgate/reservedconn/sysvar_test.go [hunk 4]
```diff
@@ -191,6 +191,35 @@ func TestSetSystemVariableAndThenSuccessfulAutocommitDML(t *testing.T) {
...
+	defer conn1.Close()
+
+	conn2, err := mysql.Connect(context.Background(), &vtParams)
+	require.NoError(t, err)
+	defer conn2.Close()
+
+	utils.Exec(t, conn1, "delete from test")
+	utils.Exec(t, conn1, "delete from test_vdx")
+
+	utils.Exec(t, conn1, "set autocommit = 1")
```
Comment (mhamza15) [inline go/test/endtoend/vtgate/reservedconn/sysvar_test.go]: We wanna test autocommit = 0, no?

Comment (arthurschreiber) [reply go/test/endtoend/vtgate/reservedconn/sysvar_test.go]: Ugh, yeah, totally. I had both versions (to ensure one failed and the other didn't), and deleted the wrong version. 🙈

**Comment by arthurschreiber** [comment]
Note to self: I will add a few more test cases later (to cover some of the other statements that should not be starting new transactions). I just wasn't sure yet where exactly to put them.

File: go/test/endtoend/vtgate/reservedconn/sysvar_test.go (hunk 4 above)
Comment (arthurschreiber) [reply go/test/endtoend/vtgate/reservedconn/sysvar_test.go]: Done.

File: go/vt/vtgate/plan_execute.go (hunk 2 above)
Comment (arthurschreiber) [reply go/vt/vtgate/plan_execute.go:299]: Done.

File: go/vt/vtgate/plan_execute.go (hunk 3 above)
Comment (arthurschreiber) [reply go/vt/vtgate/plan_execute.go]: I feel like that wouldn't make this much better (while costing a bit of performance), so I'll skip changing this. 🙇

Comment (mhamza15) [reply go/vt/vtgate/plan_execute.go]: For sure, no worries!

Comment (mhamza15) [reply go/vt/vtgate/plan_execute.go]: (I meant a map, but still no worries to ignore)

**Comment by arthurschreiber** [comment]
> Note to self: I will add a few more test cases later (to cover some of the other statements that should not be starting new transactions). I just wasn't sure yet where exactly to put them.

I added an exhaustive set of test cases.

File: go/vt/vtgate/plan_execute.go [hunk 5]
```diff
@@ -269,15 +272,84 @@ func (e *Executor) handleTransactions(
...
+//
+// The default is to start a transaction (matching the previous behavior),
+// and we opt out for specific statement types we've verified against MySQL
+// that don't start implicit transactions.
+func planStartsImplicitTx(plan *engine.Plan, stmt sqlparser.Statement) bool {
+	switch plan.QueryType {
+	case sqlparser.StmtSelect:
+		// Only start an implicit tx if the plan accesses real tables, not just dual.
+		return slices.ContainsFunc(plan.TablesUsed, func(table string) bool {
+			return !strings.HasSuffix(table, ".dual")
```
Comment (mattlord) [inline go/vt/vtgate/plan_execute.go:296]: I think we need a better determination here. I say that as e.g. queries against information_schema (only some tables not using InnoDB or views against the data dictionary), performance_schema (has its own storage engine), or sys schema tables/views — more precisely, anything NOT using the InnoDB storage engine — also do not begin a transaction. Can we instead check the qualified DB name of the table?

Comment (arthurschreiber) [reply go/vt/vtgate/plan_execute.go:296]: > I think we need a better determination here. I say that as e.g. queries against information_schema (only some tables not using InnoDB or views against the data dictionary), performance_schema (has its own storage engine), or sys schema tables/views — more precisely, anything NOT using the InnoDB storage engine — also do not begin a transaction. Can we instead check the qualified DB name of the table?

For future reference, @mlord and I d discussed this, but it seems to be a bit more complicated. For example, `information_schema.tables` is backed by InnoDB, while `information_schema.innodb_trx` is not. We'd have to maintain a full list of all the tables/views to understand which ones would start a transaction and which ones won't.

The "proper" fix would be to actually use a MySQL connection that is running with `autocommit=0` and use the `SERVER_STATUS_IN_TRANS` flag that's returned as part of the `OK` packet to understand whether a transaction was started or not. But that'd require a bigger set of changes in the APIs used for communication between vtgate and vttablet, which is out of the scope of this pull request.
