### PR TITLE
Fix Vtorc recovery time during `DeadPrimary`

### LINKED ISSUE #12578: Bug Report: vtorc waits 15-30s to reach a dead primary before recovery
### Overview of the Issue

When vtorc is recovering a dead (unreachable) primary, it first does a full refresh of all tablet via [forceRefreshAllTabletsInShard](https://github.com/vitessio/vitess/blob/0817f32c57e9ab264fa76f8cf8bb0fdf606da260/go/vt/vtorc/logic/topology_recovery.go#L666), which does a [FullStatus](https://github.com/vitessio/vitess/blob/0817f32c57e9ab264fa76f8cf8bb0fdf606da260/go/vt/vtorc/inst/tablet_dao.go#L140) on each tablet, attempting to connect to it. This will of course hang on the dead primary, but the timeout here is `RemoteOperationTimeout`, which is 15-30s depending on your Vitess version. That makes recovery needlessly slow. Our workaround is to make this timeout 3s instead, which brings out total recovery time to 15s instead of something much longer.

### Reproduction Steps

To kill a primary running in kube, I do: 
1. `pkill -9 mysqlctld`
2. `kubectl delete pod $pod_name --grace-period=1`(fast shutdown)

You can then see a bunch of logs like:
```
topology_recovery.go:1005] executeCheckAndRecoverFunction: proceeding with DeadPrimary detection on 172.18.127.104:3306; isActionable?: true; skipProcesses: false
locks.go:373] Locking shard VitessTest/0 for action Orc Recovery
```

for quite some time, until the timeout

Unfortunately, if the pod you deleted comes back faster than the timeout, vtorc then chooses to make that one the primary again instead of doing ERS (in our setup, a dead primary has suspect data and should be restored instead of made primary again)

### Binary Version

```sh
Vitess 16, through commit https://github.com/vitessio/vitess/commit/aa7ab6578078cdb761c1eb6f12f4c7ea509ad06a
```

### Operating System and Environment details

```sh
Centos8, Linux 5.4.141-hs22.el8.x86_64
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by rsajwani**
## Description
This PR resolve an issue during `DeadPrimary` recovery where it was taking unnecessarily 15-30s depending on the Vitess version. (--remote_operation_timeout)

## Context

When vtorc is recovering a dead (unreachable) primary, it first does a full refresh of all tablet via [forceRefreshAllTabletsInShard](https://github.com/vitessio/vitess/blob/0817f32c57e9ab264fa76f8cf8bb0fdf606da260/go/vt/vtorc/logic/topology_recovery.go#L666), which does a [FullStatus](https://github.com/vitessio/vitess/blob/0817f32c57e9ab264fa76f8cf8bb0fdf606da260/go/vt/vtorc/inst/tablet_dao.go#L140) on each tablet, attempting to connect to it. This will of course hang on the dead primary, but the timeout here is RemoteOperationTimeout, which is 15-30s depending on your Vitess version. That makes recovery needlessly slow.

## Fix

The implemented fix is to not try and refresh the dead primary tablet in question. We ignore the dead primary tablet because it is going to be unreachable. If all the other tablets aren't able to reach this tablet either, we can proceed with the dead primary recovery. We don't need to refresh the information for this dead tablet.

## Adding api/discovery-metrics-aggregated?seconds=xxx
In order to test this fix, I have to make discovery metrics accessible. To do that I have added another endpoint 'api/discovery-metrics-aggregated?seconds=xxx'. This will expose all the discovery related aggregate metrics(go/vt/vtorc/discovery/aggregated.go).

I realized that aggregated.go needs some refactoring and code clean but I will not address that in this PR. For now I just used the existing framework for the metrics.

## Related Issue(s)

Fixes #12578

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vtorc/logic/topology_recovery.go [hunk 1]
```diff
@@ -663,7 +663,12 @@ func executeCheckAndRecoverFunction(analysisEntry inst.ReplicationAnalysis, cand
 		// of a shard because a new tablet could have been promoted, and we need to have this visibility before we
 		// run a cluster operation of our own.
 		if isClusterWideRecovery(checkAndRecoverFunctionCode) {
-			forceRefreshAllTabletsInShard(ctx, analysisEntry.AnalyzedKeyspace, analysisEntry.AnalyzedShard)
+			log.Infof("isClusterWideRecovery ---> 1, %+v detection", analysisEntry.Analysis)
+			if analysisEntry.Analysis == inst.DeadPrimary {
+				forceRefreshAllTabletsInShard(ctx, analysisEntry.AnalyzedKeyspace, analysisEntry.AnalyzedShard, true)
+			} else {
+				forceRefreshAllTabletsInShard(ctx, analysisEntry.AnalyzedKeyspace, analysisEntry.AnalyzedShard, false)
```
Comment (GuptaManan100) [inline go/vt/vtorc/logic/topology_recovery.go:670]: We should check the `checkAndRecoverFunctionCode` instead of the `analysisEntry.Analysis`. There are multiple analyses, having the same recovery `recoverDeadPrimaryFunc`.

Also, the if can be simplified to `forceRefreshAllTabletsInShard(ctx, analysisEntry.AnalyzedKeyspace, analysisEntry.AnalyzedShard, checkAndRecoverFunctionCode== recoverDeadPrimaryFunc)`

**Review by GuptaManan100 — COMMENTED** [review]
I think the changes in this PR will solve the issue, but I would rather ignore tablets by name specifically instead of their type in the refresh. I want to guard against the situation where there are multiple vttablets claiming to be primary.

File: go/vt/vtorc/logic/topology_recovery.go (hunk 1 above)
Comment (rsajwani) [reply go/vt/vtorc/logic/topology_recovery.go:670]: fixed

File: examples/common/scripts/vttablet-up.sh [hunk 2]
```diff
@@ -29,9 +29,9 @@ tablet_hostname=''
 printf -v tablet_logfile 'vttablet_%010d_querylog.txt' $uid
 
 tablet_type=replica
-if [[ "${uid: -1}" -gt 1 ]]; then
- tablet_type=rdonly
-fi
+#if [[ "${uid: -1}" -gt 1 ]]; then
```
Comment (rsajwani) [inline examples/common/scripts/vttablet-up.sh:32]: This is for local testing purpose. I will remove this before final commit to the PR.

File: go/test/endtoend/vtorc/primaryfailure/primary_failure_test.go [hunk 3]
```diff
@@ -64,11 +64,13 @@ func TestDownPrimary(t *testing.T) {
 	// check that the replication is setup correctly before we failover
 	utils.CheckReplication(t, clusterInfo, curPrimary, []*cluster.Vttablet{rdonly, replica, crossCellReplica}, 10*time.Second)
 
+	utils.WaitForInstancePollSecondsExceededCount(t, vtOrcProcess, "InstancePollSecondsExceeded", 0, true)
```
Comment (rsajwani) [inline go/test/endtoend/vtorc/primaryfailure/primary_failure_test.go:67]: Before any failure, we should expect '0' value for InstancePollSecondsExceeded.

**Comment by rsajwani** [comment]
> I think the changes in this PR will solve the issue, but I would rather ignore tablets by name specifically instead of their type in the refresh. I want to guard against the situation where there are multiple vttablets claiming to be primary.

Are you referring to this check (https://github.com/vitessio/vitess/pull/12870/files#diff-fc3768f6253db9e6d8ca7e48e6cde64620aab7722df99c1146e2283e61d584e2R229). Can you explain bit more

File: go/test/endtoend/cluster/vtorc_process.go [hunk 4]
```diff
@@ -37,14 +37,15 @@ import (
...
-	LogDir     string
-	ExtraArgs  []string
-	ConfigPath string
-	Config     VTOrcConfiguration
-	WebPort    int
-	proc       *exec.Cmd
-	exit       chan error
+	Port        int
+	LogDir      string
+	LogFileName string
```
Comment (rsajwani) [inline go/test/endtoend/cluster/vtorc_process.go:42]: This is done to expose log file name, which is used in test

File: go/vt/vtorc/discovery/aggregated.go [hunk 5]
```diff
@@ -34,6 +34,7 @@ type AggregatedDiscoveryMetrics struct {
 	CountDistinctFailedInstanceKeys int       // number of distinct Instances which failed
 	FailedDiscoveries               uint64    // number of failed discoveries
 	SuccessfulDiscoveries           uint64    // number of successful discoveries
+	InstancePollSecondsExceeded     uint64    // number of times discoverInstance exceeded InstancePollSeconds
```
Comment (rsajwani) [inline go/vt/vtorc/discovery/aggregated.go:37]: include InstancePollSecondsExceeded in the metric object

File: go/vt/vtorc/logic/orchestrator.go [hunk 6]
```diff
@@ -240,14 +243,15 @@ func DiscoverInstance(instanceKey inst.InstanceKey, forceDiscovery bool) {
 
 	if instance == nil {
 		failedDiscoveriesCounter.Inc(1)
-		_ = discoveryMetrics.Append(&discovery.Metric{
+		metric = &discovery.Metric{
```
Comment (rsajwani) [inline go/vt/vtorc/logic/orchestrator.go:246]: preserve metric address so we can use it in defer.

**Comment by deepthi** [comment]
Can you describe the fix in the PR description? You have described the issue but not the fix.

File: go/vt/vtorc/logic/tablet_discovery.go [hunk 7]
```diff
@@ -229,6 +226,9 @@ func refreshTablets(tablets map[string]*topo.TabletInfo, query string, args []an
 		wg.Add(1)
 		go func() {
 			defer wg.Done()
+			if tablet.Type == topodatapb.TabletType_PRIMARY && dontRefreshPrimary {
+				return
+			}
```
Comment (GuptaManan100) [inline go/vt/vtorc/logic/tablet_discovery.go:231]: I don't like this way of ignoring all the tablets that have a type PRIMARY. We should be ignoring tablet explicitly by their alias and not by the type. You can be in a situation where 2 tablets have a type PRIMARY, but we only want to ignore the one that the DeadPrimary recovery is being run on

**Review by GuptaManan100 — COMMENTED** [review]
Just a couple of things. I am okay with us adding a metric to `AggregatedDiscoveryMetrics`, but we should eventually move all of those metrics to use counters and gauges in Vitess. The other change is around how we ignore tablets. I think we should pass in a list of tablet aliases to ignore explicitly and not do it by tablet type

**Comment by olyazavr** [comment]
I tried this out on our setup, and it was faster than my initial attempt of just adding a 1s timeout to the FullStatus call!

I did
```
primaryTabletRecord, err = inst.ReadTablet(analysisEntry.AnalyzedInstanceKey)
```

and passed that into where you have `dontRefreshPrimary bool` (but mine was `ignoreTabletAlias`), and then skipped over that alias in the same place you skip over the primary

**Comment by GuptaManan100** [comment]
Website docs - https://github.com/vitessio/website/pull/1468

File: go/test/endtoend/vtorc/utils/utils.go [hunk 8]
```diff
@@ -964,3 +966,34 @@ func WaitForSuccessfulRecoveryCount(t *testing.T, vtorcInstance *cluster.VTOrcPr
 	successCount := successfulRecoveriesMap[recoveryName]
 	assert.EqualValues(t, countExpected, successCount)
 }
+
+// WaitForInstancePollSecondsExceededCount wait for 30 seconds and then query api/aggregated-discovery-metrics.
```
Comment (deepthi) [inline go/test/endtoend/vtorc/utils/utils.go:970]:
```suggestion
// WaitForInstancePollSecondsExceededCount waits for 30 seconds and then queries api/aggregated-discovery-metrics.
```

**Review by deepthi — APPROVED** [review]
LGTM except for a nit in one of the comments.
Let's make a note on the new API that this is intended for internal use only. When we have the proper metrics we should remove this API.

**Review by GuptaManan100 — APPROVED** [review]

File: go/test/endtoend/vtorc/utils/utils.go (hunk 8 above)
Comment (GuptaManan100) [reply go/test/endtoend/vtorc/utils/utils.go]: Fixed

**Comment by GuptaManan100** [comment]
I have closed the website docs PR because we don't want to document this API endpoint.
