### PR TITLE
show vitess_tablets should show new master's timestamp after reparenting

### LINKED ISSUE #6292: show vitess_tablets is incorrect after reparenting
#### Overview of the Issue

vtgate's `show vitess_tablets` command does not show the timestamp for a new master.

#### Reproduction Steps

Run local example (101_initial_cluster.sh). Connect to vtgate.
```
$ mysql
mysql> show vitess_tablets;
+-------+----------+-------+------------+---------+------------------+------------------+----------------------+
| Cell  | Keyspace | Shard | TabletType | State   | Alias            | Hostname         | MasterTermStartTime  |
+-------+----------+-------+------------+---------+------------------+------------------+----------------------+
| zone1 | commerce | 0     | MASTER     | SERVING | zone1-0000000100 |<hostname redacted>| 2020-06-09T18:08:09Z |
| zone1 | commerce | 0     | REPLICA    | SERVING | zone1-0000000101 |<hostname redacted>|                      |
| zone1 | commerce | 0     | RDONLY     | SERVING | zone1-0000000102 |<hostname redacted>|                      |
+-------+----------+-------+------------+---------+------------------+------------------+----------------------+
3 rows in set (0.00 sec)
```
From another shell, reparent to tablet 101
```
$ vtctlclient PlannedReparentShard -keyspace_shard=commerce/0 -new_master=zone1-0000000101
I0609 11:14:31.899712   25100 main.go:64] I0609 18:14:31.897724 reparent.go:559] Checking replication on master-elect zone1-0000000101
I0609 11:14:31.919441   25100 main.go:64] I0609 18:14:31.919056 reparent.go:594] demote current master cell:"zone1" uid:100 
I0609 11:14:32.780261   25100 main.go:64] I0609 18:14:32.779588 reparent.go:692] populating reparent journal on new master zone1-0000000101
I0609 11:14:32.780739   25100 main.go:64] I0609 18:14:32.779916 reparent.go:675] setting new master on replica zone1-0000000102
I0609 11:14:32.780794   25100 main.go:64] I0609 18:14:32.779966 reparent.go:675] setting new master on replica zone1-0000000100
```
Now look at tablet status again
```
mysql> show vitess_tablets;
+-------+----------+-------+------------+---------+------------------+------------------+----------------------+
| Cell  | Keyspace | Shard | TabletType | State   | Alias            | Hostname         | MasterTermStartTime  |
+-------+----------+-------+------------+---------+------------------+------------------+----------------------+
| zone1 | commerce | 0     | MASTER     | SERVING | zone1-0000000101 |<hostname redacted>|                      |
| zone1 | commerce | 0     | REPLICA    | SERVING | zone1-0000000100 |<hostname redacted>| 2020-06-09T18:08:09Z |
| zone1 | commerce | 0     | RDONLY     | SERVING | zone1-0000000102 |<hostname redacted>|                      |
+-------+----------+-------+------------+---------+------------------+------------------+----------------------+
3 rows in set (0.00 sec)
```
Notice that tablet 101 is now MASTER but it's MasterTermStartTime is still empty.

#### Binary version
```
$ vtgate --version
Version: 945e105aa (Git branch 'master') built on Tue Jun  9 12:35:29 PDT 2020 by <redacted> using go1.13.6 linux/amd64
```
#### Operating system and Environment details
```
$ uname -a
Linux <hostname redacted> 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by deepthi**
Fixes #6292 

* vtgate was using the wrong time fields from health cache.
* agentMasterTermTime should be reset to 0 when a tablet is demoted from MASTER.
* change examples to use new gateway.

Signed-off-by: deepthi <deepthi@planetscale.com>

### CODE REVIEW

File: go/vt/vttablet/tabletmanager/rpc_replication.go [hunk 1]
```diff
@@ -533,6 +533,7 @@ func (agent *ActionAgent) setMasterLocked(ctx context.Context, parentAlias *topo
 	if tablet.Type == topodatapb.TabletType_MASTER {
 		tablet.Type = topodatapb.TabletType_REPLICA
 		tablet.MasterTermStartTime = nil
+		agent.setMasterTermStartTime(time.Time{})
```
Comment (deepthi) [inline go/vt/vttablet/tabletmanager/rpc_replication.go:536]: @sougou I had to add this line to get the tests to pass. Ideally we should set MasterTermStartTime on agent and push it to tablet, instead we are setting it separately on both.
