### PR TITLE
[topo/helpers] Make CopyShardReplications idempotent

### LINKED ISSUE #9844: topo2topo copy of shard replication is not idempotent
### Overview of the Issue

While using topo2topo to migrate topology data, we noticed that while the copying of all other topology data are idempotent, the copying of shard replication is not. Instead, it appends the tablets to the ShardReplication struct every time copy is run.

The code is doing a protobuf merge, which is probably simply appending:
https://github.com/vitessio/vitess/blob/main/go/vt/topo/helpers/copy.go#L172

### Reproduction Steps

1. Follow [this guide](https://github.com/aquarapid/vitess_examples/blob/master/topo2topo/README.md) to copy topology data , but run `topo2topo -do-shard-replications` twice
2. Run `topo2topo -do-shard-replications -compare` and the validation will fail.
3. Use topology specified CLI tool (e.g. etcdcli) to view the shard replication data

### Binary Version

```shell
n/a
```

### Operating System and Environment details

```shell
n/a
```

### Log Fragments

```shell
n/a
```

### PR DESCRIPTION
**Pull request by ajm188**
## Description

This updates `helpers.CopyShardReplications` to build a set of tablet aliases in the fromTS topo so that repeated copies are idempotent.

## Related Issue(s)

Fixes #9844 

## Checklist
- [x] Should this PR be backported? **no**
- [x] Tests were added or are not required
- [x] Documentation was added or is not required **n/a**

### CODE REVIEW

File: go/vt/topo/helpers/copy.go [hunk 1]
```diff
@@ -168,8 +170,27 @@ func CopyShardReplications(ctx context.Context, fromTS, toTS *topo.Server) {
 					continue
 				}
 
+				sriNodes := sets.NewString()
```
Comment (vmg) [inline go/vt/topo/helpers/copy.go:173]: This `k8s.io/apimachinery` dependency seems a bit out of place. We don't usually depend on these helpers in Vitess. Since all you need is a simple String Set, you can make one with a `map[string]struct{}` that would be just as readable/ergonomic.

**Review by vmg — CHANGES_REQUESTED** [review]

**Review by vmg — APPROVED** [review]
Lookin gucci. Thanks!
