### PR TITLE
[reparentutil / ERS] confirm at least one replica succeeded to `SetMaster`, or fail

### LINKED ISSUE #7480: [vtctl/reparentutil] During ERS, any errors from SetMaster on replica are lost
#### Overview of the Issue

This was discussed in #7464, and am filing this issue to follow up on [that conversation](https://github.com/vitessio/vitess/pull/7464#discussion_r571687210).

It's described in more detail in the code comments [here](https://github.com/vitessio/vitess/blob/master/go/vt/vtctl/reparentutil/emergency_reparenter.go#L153-L159):

> // A question while migrating: Is this by design? By my read,
	// there's nothing consuming that error channel, meaning any replica that
	// fails to SetMaster will actually block trying to send to the errCh. In
	// addition, the only way an operator will ever notice these errors will be
	// in the logs on the tablet, and not from any error propagation in
	// vtctl/wrangler, so a shard will continue to attempt to serve (probably?)
	// after a partially-failed ERS.

After reading the [original design](https://github.com/vitessio/vitess/issues/6206), this section jumped out to me:

> 4. Reparent all other tablets to the winning candidate.
>     - Wait for at least one successful reparent, rest are best effort.

So, putting aside the leaking blocked goroutines, I think this code is technically correct, but _only_ in the case when you're running with semi-sync enabled, since the call to `PopulateReparentJournal` on the new primary does have its error checked, and that call will fail if 0 replicas are able to reparent.

### PR DESCRIPTION
**Pull request by ajm188**
## Description

This introduces two background goroutines and contexts derived from
`context.Background()` to poll and signal for (1) at least one replica
finished successfully and (2) all replicas finished, regardless of
status, respectively.

The overall `promotePrimary` function returns error conditions based on
which of those contexts gets signaled first. We still fail if
`PromoteReplica` fails, which gets checked first, but this covers the
case where we're not running with semi-sync, and none of the replicas
are able to reparent even if the new primary is able to populate its
reparent journal (in the semi-sync case, if 0 replicas succeed to
`SetMaster`, than the primary will fail to `PromoteReplica`, so this was
already covered there).

Fixes #7480 

Signed-off-by: Andrew Mason <amason@slack-corp.com>

## Related Issue(s)

- Fixes #7480 

## Checklist
- [ ] Should this PR be backported? **no**
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [x]  Cluster Management
- [ ]  Build/CI
- [ ]  VTAdmin

### CODE REVIEW

**Comment by ajm188** [comment]
Okay I seem to have made those tests flaky .... taking a look. Hilariously they passed the few times I ran them locally, but if I run them enough times in a row I can get them to fail in a few ways.

**Review by doeg — COMMENTED** [review]
This makes sense to me. The comments + tests are great, as usual. :sparkles: 

I'm not yet confident enough in my Vitess or Go concurrency skillz to give you an _official_ approval on this, though, since ERS is... rather important! 😎 

@deepthi or @setassociative would you mind reviewing this one, too, when you get a chance? 🙇‍♀️

**Comment by PrismaPhonic** [comment]
I'm a little concerned with encouraging use of EmergencyReparent in cases where a user isn't using semi-sync, because you would very likely experience data loss. Certainly I think it's questionable that we could select an appropriate replica on behalf of the user in those cases. We could have a `--force` mode that takes the tablet supplied by the user, and forces reparenting to it, with the acknowledgement that very bad things could happen in that case.

File: go/vt/vtctl/reparentutil/emergency_reparenter.go [hunk 1]
```diff
@@ -199,7 +224,24 @@ func (erp *EmergencyReparenter) promoteNewPrimary(
 		return vterrors.Wrapf(primaryErr, "failed to PopulateReparentJournal on master: %v", primaryErr)
 	}
 
-	return nil
+	select {
+	case <-replSuccessCtx.Done():
+		// At least one replica was able to SetMaster successfully
+		return nil
+	case <-allReplicasDoneCtx.Done():
+		if len(rec.Errors) >= numReplicas {
```
Comment (PrismaPhonic) [inline go/vt/vtctl/reparentutil/emergency_reparenter.go:232]: Why would summed up errors exceed the number of replicas? I think if it should never be greater than this is an odd thing to write in code.

File: go/vt/vtctl/reparentutil/replication.go [hunk 2]
```diff
@@ -142,6 +142,10 @@ func FindValidEmergencyReparentCandidates(
 // ReplicaWasRunning returns true if a StopReplicationStatus indicates that the
 // replica had running replication threads before being stopped.
 func ReplicaWasRunning(stopStatus *replicationdatapb.StopReplicationStatus) bool {
+	if stopStatus.Before == nil {
```
Comment (PrismaPhonic) [inline go/vt/vtctl/reparentutil/replication.go:145]: I'm not sure false is the right thing to return here. If before is nil we can't know if it was running or not. Not getting `Before` at all, IMO, should be a panic case.

**Review by deepthi — COMMENTED** [review]
LGTM except for the comment on the comment.

**Comment by deepthi** [comment]
> I'm a little concerned with encouraging use of EmergencyReparent in cases where a user isn't using semi-sync, because you would very likely experience data loss. Certainly I think it's questionable that we could select an appropriate replica on behalf of the user in those cases. We could have a `--force` mode that takes the tablet supplied by the user, and forces reparenting to it, with the acknowledgement that very bad things will probably happen in that case.

I don't see that we are encouraging it. Can you elaborate?

**Comment by PrismaPhonic** [comment]
@deepthi Just saw your reply. I edited my comment to clarify that I was referring to the authors comments in their description and related issue.

**Comment by deepthi** [comment]
@PrismaPhonic Re semi-sync, I think we should also fix https://github.com/vitessio/vitess/issues/7441
Right now semi-sync gets set only on `REPLICA` tablets.

File: go/vt/vtctl/reparentutil/emergency_reparenter.go (hunk 1 above)
Comment (ajm188) [reply go/vt/vtctl/reparentutil/emergency_reparenter.go:232]: My thinking was that being more permissive here means the code still works if `handleReplica` is ever updated to record multiple errors per replica.

File: go/vt/vtctl/reparentutil/emergency_reparenter.go [hunk 3]
```diff
@@ -150,47 +151,71 @@ func (erp *EmergencyReparenter) promoteNewPrimary(
...
+	// Create a context and cancel function to watch for the first successful
+	// SetMaster call on a replica. We use a background context so that this
+	// context is only ever Done when its cancel is called by the background
+	// goroutine we're about to spin up.
+	//
+	// Similarly, create a context and cancel for the replica waiter goroutine
+	// to signal when all replica goroutines have finished. In the case where at
+	// least one replica succeeds, replSuccessCtx will be canceled first, while
+	// allReplicasDoneCtx is guaranteed to be canceled within
+	// opts.WaitReplicasTimeout plus some jitter.
```
[the remark this answers is not in the document]
Comment (ajm188) [reply go/vt/vtctl/reparentutil/emergency_reparenter.go:163]: Precisely!

File: go/vt/vtctl/reparentutil/emergency_reparenter.go [hunk 4]
```diff
@@ -150,47 +151,71 @@ func (erp *EmergencyReparenter) promoteNewPrimary(
...
+			replWg.Add(1)
+			numReplicas++
 			go handleReplica(alias, ti)
 		}
 	}
 
+	// Spin up a background goroutine to wait until all replica goroutines
+	// finished. If one replica is slow, but another finishes quickly, the main
+	// thread of execution in this function while this goroutine will run until
+	// the parent context times out, without slowing down the flow of ERS.
```
[the remark this answers is not in the document]
Comment (ajm188) [reply go/vt/vtctl/reparentutil/emergency_reparenter.go:213]: Yeah, let me take a shot at editing that.

**Comment by ajm188** [comment]
R.e. semi-sync, happy to talk more about that outside the PR, but I don't think it has any bearing here. This doesn't change the behavior in that case; it only fixes the case where if you were running semi-sync, and all your replicas failed to `SetMaster`, then you would have a bunch of goroutines (one per replica, _per ERS where this condition happens_) blocked forever on the vtctld until you restarted the service).

For the actual safety/integrity of your vttablet components (not running semi-sync), that is unchanged as a result of this PR.

File: go/vt/vtctl/reparentutil/emergency_reparenter.go (hunk 1 above)
Comment (PrismaPhonic) [reply go/vt/vtctl/reparentutil/emergency_reparenter.go:232]: I think if that's the case it should get updated when that happens. This code path implies this is a valid state of existence. (I'm required as a reader to read into the comment to understand that this is simply defensive programming, and for a reality we don't live in yet)

Comment (deepthi) [reply go/vt/vtctl/reparentutil/emergency_reparenter.go:232]: or you could 
```
if len(rec.Errors) > numReplicas - 1
```

Comment (deepthi) [reply go/vt/vtctl/reparentutil/emergency_reparenter.go:232]: I guess 
```
if len(rec.Errors) == numReplicas
```
feels weirdly specific, but I agree with @PrismaPhonic that if we ever record more than one error from each goroutine, this will need to change anyway. So it is probably best to check for the specific condition.

Comment (ajm188) [reply go/vt/vtctl/reparentutil/emergency_reparenter.go:232]: > This code path implies this is a valid state of existence. 

The code directly states that this is an error state and not a valid state.

If I change this to `len(rec.Errors) == numReplicas` then we can return success in places where we definitely shouldn't.  Open to suggestions on how to make the comments more clear, though!

File: go/vt/vtctl/reparentutil/emergency_reparenter.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (ajm188) [reply go/vt/vtctl/reparentutil/emergency_reparenter.go]: Let me know if the newest version makes more sense, or if you have other suggestions!

File: go/vt/vtctl/reparentutil/emergency_reparenter.go (hunk 1 above)
Comment (ajm188) [reply go/vt/vtctl/reparentutil/emergency_reparenter.go:237]: How about:

```go
switch {
case len(rec.Errors) == numReplicas:
    // original error case in question
case len(rec.Errors) > numReplicas:
    return vterrors.Wrapf(rec.Error(), "received more errors (= %d) than replicas (= %d), which should be impossible", len(rec.Errors), numReplicas)
default:
    return nil
}
```

Comment (deepthi) [reply go/vt/vtctl/reparentutil/emergency_reparenter.go:237]: This lgtm.

File: go/vt/vtctl/reparentutil/emergency_reparenter.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (deepthi) [reply go/vt/vtctl/reparentutil/emergency_reparenter.go]: Much better.

File: go/vt/vtctl/reparentutil/replication.go (hunk 2 above)
Comment (ajm188) [reply go/vt/vtctl/reparentutil/replication.go:145]: I think we shouldn't have code in the critical path of an ERS that can panic, because we'd either need to add `recover` defers and figure out how to recover from ... any point where the process can fail, or risk leaving the cluster in a worse state than when we started.

How about:

```go
func ReplicaWasRunning(stopStatus *replicationdatapb.StopReplicationStatus) (bool, error) {
	if stopStatus.Before == nil {
		return false, errors.New("...")
	}

	return stopStatus.Before.IoThreadRunning || stopStatus.Before.SqlThreadRunning, nil
}
```

Comment (deepthi) [reply go/vt/vtctl/reparentutil/replication.go]: Better error than panic :) This lgtm.

**Review by deepthi — APPROVED** [review]

File: go/vt/vtctl/reparentutil/emergency_reparenter.go (hunk 1 above)
Comment (PrismaPhonic) [reply go/vt/vtctl/reparentutil/emergency_reparenter.go]: I still am not seeing how we would return success in cases when we shouldn't if we truly think that errors will never exceeed count of num replicas. This does seem overly defensive to me, but I do think this newer version is better.

File: go/vt/vtctl/reparentutil/replication.go (hunk 2 above)
Comment (PrismaPhonic) [reply go/vt/vtctl/reparentutil/replication.go]: This looks better

**Review by PrismaPhonic — APPROVED** [review]
