### PR TITLE
remove excessive logging

### LINKED ISSUE #11480: Too many warning log statements during backup
### Overview of the Issue

While doing backup we see a lot of statements for pargzip doesn't support compression as belowl.
(compression.go:182] engine "pargzip" doesn't support decompression, using "pgzip" instead)

We can print this once instead of many times, let’s log at INFO/WARNING level instead of ERROR

### Reproduction Steps

repro-able to all the env.
Create backup using pargzip as compressor and then try to restore it

### Binary Version

```sh
v15
```

### Operating System and Environment details

```sh
all Os
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by rsajwani**
Signed-off-by: Rameez Sajwani <rameezwazirali@hotmail.com>

## Description

This is an enhancement where we are doing excessive logging during decompression. Instead of logging warning for every file we moved the warning to every restore we run.

Logs before this change
=================
```
/usr/local/go/bin/go tool test2json -t /private/var/folders/3q/njsb_8v13978qdmq4j5c25gh0000gn/T/GoLand/___backup_only_test_go.test -test.v -test.paniconexit0 -test.run ^\QTestTabletInitialBackup\E|\QTestTabletBackupOnly\E$
=== RUN   TestTabletInitialBackup
E1014 19:35:33.155605   78850 query.go:83] ExecuteFetch(ALTER TABLE _vt.reparent_journal CHANGE COLUMN master_alias primary_alias VARBINARY(32) NOT NULL) failed: Unknown column 'master_alias' in 'reparent_journal' (errno 1054) (sqlstate 42S22) during query: ALTER TABLE _vt.reparent_journal CHANGE COLUMN master_alias primary_alias VARBINARY(32) NOT NULL
W1014 19:35:57.194316   80804 compression.go:196] engine "pargzip" doesn't support decompression, using "pgzip" instead
W1014 19:35:57.194366   80804 compression.go:196] engine "pargzip" doesn't support decompression, using "pgzip" instead
W1014 19:35:57.194395   80804 compression.go:196] engine "pargzip" doesn't support decompression, using "pgzip" instead
W1014 19:35:57.194483   80804 compression.go:196] engine "pargzip" doesn't support decompression, using "pgzip" instead
W1014 19:35:57.254949   80804 compression.go:196] engine "pargzip" doesn't support decompression, using "pgzip" instead
W1014 19:35:57.255043   80804 compression.go:196] engine "pargzip" doesn't support decompression, using "pgzip" instead
...
<redacted>
...
W1014 19:35:59.288801   80804 mysqld.go:283] MySQL version has built-in upgrade, skipping RunMySQLUpgrade
--- PASS: TestTabletInitialBackup (86.19s)
=== RUN   TestTabletBackupOnly
E1014 19:36:59.548629   85230 backup.go:306] no backup to restore on BackupStorage for directory ks/0. Starting up empty.
--- PASS: TestTabletBackupOnly (45.60s)
PASS
```
Logs after this change
=================
```
/usr/local/go/bin/go tool test2json -t /private/var/folders/3q/njsb_8v13978qdmq4j5c25gh0000gn/T/GoLand/___backup_only_test_go.test -test.v -test.paniconexit0 -test.run ^\QTestTabletInitialBackup\E|\QTestTabletBackupOnly\E$
=== RUN   TestTabletInitialBackup
E1014 19:30:32.856072   68553 query.go:83] ExecuteFetch(ALTER TABLE _vt.reparent_journal CHANGE COLUMN master_alias primary_alias VARBINARY(32) NOT NULL) failed: Unknown column 'master_alias' in 'reparent_journal' (errno 1054) (sqlstate 42S22) during query: ALTER TABLE _vt.reparent_journal CHANGE COLUMN master_alias primary_alias VARBINARY(32) NOT NULL
W1014 19:30:58.207658   70513 builtinbackupengine.go:612] engine "pargzip" doesn't support decompression, using "pgzip" instead
W1014 19:31:00.338380   70513 mysqld.go:283] MySQL version has built-in upgrade, skipping RunMySQLUpgrade
--- PASS: TestTabletInitialBackup (86.84s)
=== RUN   TestTabletBackupOnly
E1014 19:32:01.249594   74926 backup.go:306] no backup to restore on BackupStorage for directory ks/0. Starting up empty.
W1014 19:32:14.666754   74926 vtbackup.go:248] Failed to remove temporary tablet directory: unlinkat /Users/rameezsajwani/Code/fork/vitess/vtdataroot/vtroot_8901/vt_1817924007: directory not empty
--- PASS: TestTabletBackupOnly (47.91s)
PASS
```

## Related Issue(s)

closes #11480

## Checklist

-   [ ] "Backport me!" label has been added if this change should be backported
-   [x] Tests were added or are not required
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/mysqlctl/builtinbackupengine.go [hunk 1]
```diff
@@ -606,6 +606,17 @@ func (be *BuiltinBackupEngine) ExecuteRestore(ctx context.Context, params Restor
 // restoreFiles will copy all the files from the BackupStorage to the
 // right place.
 func (be *BuiltinBackupEngine) restoreFiles(ctx context.Context, params RestoreParams, bh backupstorage.BackupHandle, bm builtinBackupManifest) error {
+	// For optimization, we are replacing pargzip with pgzip, so newBuiltinDecompressor doesn't have to compare and print warning for every file
```
Comment (deepthi) [inline go/vt/mysqlctl/builtinbackupengine.go:609]: There should be some place where we are deleting similar code?

**Review by deepthi — COMMENTED** [review]
`mysql80` unit test is fixed in #11475 (not merged yet)

File: go/vt/mysqlctl/builtinbackupengine.go (hunk 1 above)
Comment (rsajwani) [reply go/vt/mysqlctl/builtinbackupengine.go:609]: It is in compression.go (newbuiltindecompressor method).. since its a helper method and even though no one else is calling it but from library point of view anyone can call that method independently. So I left that code untouched.

Comment (deepthi) [reply go/vt/mysqlctl/builtinbackupengine.go:609]: but doesn't that mean that we will continue to print a line for every file + one line at the beginning?
Sorry I'm not seeing how this is being fixed.

File: go/vt/mysqlctl/builtinbackupengine.go [hunk 2]
```diff
@@ -606,6 +606,17 @@ func (be *BuiltinBackupEngine) ExecuteRestore(ctx context.Context, params Restor
...
+	// since newBuiltinDecompressor is helper method and does not hold any state, it was hard to do it in that method itself.
+	if bm.CompressionEngine == PargzipCompressor {
+		originalEngineValue := bm.CompressionEngine
+		params.Logger.Warningf("engine \"pargzip\" doesn't support decompression, using \"pgzip\" instead")
+		bm.CompressionEngine = PgzipCompressor
+		defer func() {
+			bm.CompressionEngine = originalEngineValue
+		}()
```
Comment (GuptaManan100) [inline go/vt/mysqlctl/builtinbackupengine.go:617]: Do we even need the `originalEngineValue` as a variable at all? I mean we check that `bm.CompressionEngine` is equal to `PargzipCompressor`, so we could just use that value directly

File: go/vt/mysqlctl/builtinbackupengine.go [hunk 3]
```diff
@@ -606,6 +606,17 @@ func (be *BuiltinBackupEngine) ExecuteRestore(ctx context.Context, params Restor
 // restoreFiles will copy all the files from the BackupStorage to the
 // right place.
 func (be *BuiltinBackupEngine) restoreFiles(ctx context.Context, params RestoreParams, bh backupstorage.BackupHandle, bm builtinBackupManifest) error {
+	// For optimization, we are replacing pargzip with pgzip, so newBuiltinDecompressor doesn't have to compare and print warning for every file
+	// since newBuiltinDecompressor is helper method and does not hold any state, it was hard to do it in that method itself.
+	if bm.CompressionEngine == PargzipCompressor {
+		originalEngineValue := bm.CompressionEngine
+		params.Logger.Warningf("engine \"pargzip\" doesn't support decompression, using \"pgzip\" instead")
```
Comment (GuptaManan100) [inline go/vt/mysqlctl/builtinbackupengine.go:613]: We can use backticked string to make it more readable i.e.
```
`engine "pargzip" doesn't support decompression, using "pzgip" instead`
```

File: go/vt/mysqlctl/builtinbackupengine.go (hunk 1 above)
Comment (rsajwani) [reply go/vt/mysqlctl/builtinbackupengine.go:609]: in compressor , we print this warning and set compression engine to pgzip, if we have following condition as true
if bm.CompressionEngine == PargzipCompressor { ...
now that we set enginevalue at the caller level, we never get true for above statement at calle and hence no warning will be printed there.

**Comment by deepthi** [comment]
Can you include the log snippet in the description? That will be verification that this is working as intended.

**Comment by rsajwani** [comment]
> Can you include the log snippet in the description? That will be verification that this is working as intended.

I have updated description with the logs...

**Review by deepthi — APPROVED** [review]
