### PR TITLE
Fix for Query Serving when Toposerver is Down

### LINKED ISSUE #7191: Vitess returns error when Consul topology service is unavailable
#### Overview of the Issue

We are using consul as topology service in our setup. Last week we observed an issue that looks like the opposite of what is documented. 

Our consul leader node died during an internal maintenance and it forced consul cluster to re-elect the leader. During this period consul was unavailable in our environment and we noticed vitess returned errors to queries coming from our application. When we checked the [documentations](https://vitess.io/docs/reference/features/topology-service/) we saw following line which indicates availability of the topology service is not important for serving queries:

```text
Vitess will not use the global or local topology service as part of serving individual queries. The Topology Service is only used to get the topology information at startup and in the background.
```

If this is not the expected behavior of vitess in this scenario, how can we prevent this from happening again ? If not, how should we handle outages where consul is unavailable ?

Note: For internal reasons we have to keep consul as topology service.

#### Reproduction Steps

To reproduce the problem you can follow the steps described [here](https://github.com/serhatcetinkaya/vitess-consul-poc). The PoC is created particularly for this issue and it is almost the same as our production environment.

#### Binary version

We use a custom built version of binaries and containers on our end. We built the components from commit `60322344f`. The PoC uses the same versions as we have on our end. For the sake of this issue I built the docker image locally and pushed it to docker hub.

#### Operating system and Environment details

- Consul version: v1.8.0
- Kubernetes version (production): v1.18.9-eks-d1db3c
- Minikube version (PoC): v1.5.2
- Kubernetes version (PoC): v1.16.2 

#### Log Fragments

Logs from vtgate during the incident is like following:

```text
E1201 14:00:38.818835   16528 throttled.go:77] Execute: skipped 2956 log messages
E1201 14:00:41.970980   16528 resilient_server.go:467] Initial WatchSrvKeyspace failed for us_east_1/**CENSORED**: Unexpected response code: 500
E1201 14:00:41.970998   16528 resilient_server.go:470] WatchSrvKeyspace clearing cached entry for us_east_1/**CENSORED**
E1201 14:00:41.971161   16528 vtgate.go:448] Execute: Code: UNKNOWN
keyspace **CENSORED** fetch error: Unexpected response code: 500
paramsAnyShard, request: map[BindVariables:map[vtg1:type:INT64 value:"594"  vtg2:type:INT64 value:"149878845" ] Session:in_transaction:true target_string:"**CENSORED**" options:<included_fields:ALL client_found_rows:true > last_insert_id:74761 row_count:-1 Sql:select level0_.level_no as level_no1_17_0_, level0_.user_id as user_id2_17_0_, level0_.score as score3_17_0_, level0_.star_count as star_cou4_17_0_ from level level0_ where level0_.level_no=594 and level0_.user_id=149878845]
W1201 14:00:43.988144   16528 resilient_server.go:559] Error watching vschema for cell us_east_1 (will wait 5s before retrying): Unexpected response code: 500
E1201 14:00:46.971289   16528 throttled.go:77] Execute: skipped 2917 log messages
E1201 14:00:50.293447   16528 resilient_server.go:467] Initial WatchSrvKeyspace failed for us_east_1/**CENSORED**: Unexpected response code: 500
E1201 14:00:50.293483   16528 resilient_server.go:470] WatchSrvKeyspace clearing cached entry for us_east_1/**CENSORED**
E1201 14:00:50.293637   16528 vtgate.go:448] Execute: Code: UNKNOWN
keyspace **CENSORED** fetch error: Unexpected response code: 500
paramsAnyShard, request: map[BindVariables:map[vtg1:type:INT64 value:"4714"  vtg2:type:INT64 value:"56030872" ] Session:in_transaction:true target_string:"**CENSORED**" options:<included_fields:ALL client_found_rows:true > last_insert_id:88634 row_count:-1 Sql:select level0_.level_no as level_no1_17_0_, level0_.user_id as user_id2_17_0_, level0_.score as score3_17_0_, level0_.star_count as star_cou4_17_0_ from level level0_ where level0_.level_no=4714 and level0_.user_id=56030872]
E1201 14:00:55.293760   16528 throttled.go:77] Execute: skipped 2578 log messages
W1201 14:00:56.230927   16528 resilient_server.go:559] Error watching vschema for cell us_east_1 (will wait 5s before retrying): Unexpected response code: 500
E1201 14:00:58.484769   16528 resilient_server.go:467] Initial WatchSrvKeyspace failed for us_east_1/**CENSORED**: Unexpected response code: 500
E1201 14:00:58.484789   16528 resilient_server.go:470] WatchSrvKeyspace clearing cached entry for us_east_1/**CENSORED**
E1201 14:00:58.484959   16528 vtgate.go:448] Execute: Code: UNKNOWN
keyspace **CENSORED** fetch error: Unexpected response code: 500
```

### PR DESCRIPTION
**Pull request by harshit-gangal**
## Related Issue(s)

- Fixes #7191 

## Checklist
- [ ] Should this PR be backported?
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

## Impacted Areas in Vitess
Components that this PR will affect:

- [x]  Query Serving

### CODE REVIEW

File: go/test/endtoend/cluster/cluster_process.go [hunk 1]
```diff
@@ -173,6 +174,8 @@ func (cluster *LocalProcessCluster) StartTopo() (err error) {
 	if cluster.Cell == "" {
 		cluster.Cell = DefaultCell
 	}
+
+	topoFlavor = cluster.TopoFlavorString()
```
Comment (deepthi) [inline go/test/endtoend/cluster/cluster_process.go:178]: This variable is hiding the global, which is confusing. You could as well call the func directly in line 181.

File: go/test/endtoend/cluster/topo_process.go [hunk 2]
```diff
@@ -230,7 +230,7 @@ func (topo *TopoProcess) TearDown(Cell string, originalVtRoot string, currentRoo
 		// Attempt graceful shutdown with SIGTERM first
 		_ = topo.proc.Process.Signal(syscall.SIGTERM)
 
-		if !*keepData {
+		if !(*keepData || keepdata) {
```
Comment (deepthi) [inline go/test/endtoend/cluster/topo_process.go:233]: Why was this change needed? checking for nil?

**Review by deepthi — COMMENTED** [review]
Mostly looks good. Just a couple of minor questions/comments.

File: go/test/endtoend/cluster/cluster_process.go (hunk 1 above)
Comment (harshit-gangal) [reply go/test/endtoend/cluster/cluster_process.go:178]: We are updating the global. global is used multiple places and this is seems a viable option as it is a test framework

File: go/test/endtoend/cluster/topo_process.go (hunk 2 above)
Comment (harshit-gangal) [reply go/test/endtoend/cluster/topo_process.go:233]: `keepData` is global and `keepdata` is passed a function parameter, we do not want the data to be deleted when we take down topo server inside the test.

Comment (deepthi) [reply go/test/endtoend/cluster/topo_process.go:233]: I now see the difference between the two. Terrible choice of variable names but we don't have to fix it in this PR.

**Review by deepthi — APPROVED** [review]
