### PR TITLE
prepared statement testcases

### LINKED ISSUE #5524: Prepared_statement test triggers segfault
I have had it consistently fail locally when running `make docker_bootstrap && go run test.go -pull=false prepared_statement` for a while.

In https://github.com/vitessio/vitess/pull/5382 I made changes which require a rebootstrap (pulling down new versions of python dependencies etc.) and now it fails in Travis CI as well.

You should be able to reliably reproduce against master as long as you are not using the cached docker image:

```
make docker_bootstrap && go run test.go -pull=false prepared_statement
```

### PR DESCRIPTION
**Pull request by princeparmar**
verifies insert,update,delete and select for prepared statements.
Fixes #5524 

Signed-off-by: pradip parmar <prince.soamedia@gmail.com>

### CODE REVIEW

File: go/test/endtoend/prepare-statement/main_test.go [hunk 1]
```diff
@@ -0,0 +1,272 @@
...
+	"testing"
+
+	"vitess.io/vitess/go/test/endtoend/cluster"
+
+	"github.com/go-sql-driver/mysql"
+	"github.com/golang/glog"
+	"github.com/stretchr/testify/require"
+)
+
+// tableData is tmp structure to select data.
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/main_test.go]:
```suggestion
// tableData is a temporary structure to hold selected data.
```

File: go/test/endtoend/prepare-statement/main_test.go [hunk 2]
```diff
@@ -0,0 +1,272 @@
...
+	jsonExample           = `{
+		"quiz": {
+			"sport": {
+				"q1": {
+					"question": "Which one is correct team name in NBA?",
+					"options": [
+						"New York Bulls",
+						"Los Angeles Kings",
+						"Golden State Warriors",
+						"Huston Rocket"
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/main_test.go]: Did you mean `Houston Rockets`? `Golden State Warriors` is also a valid name :)

File: go/test/endtoend/prepare-statement/main_test.go [hunk 3]
```diff
@@ -0,0 +1,272 @@
...
+
+var (
+	clusterInstance       *cluster.LocalProcessCluster
+	dbInfo                DBInfo
+	hostname              = "localhost"
+	keyspaceName          = "test_keyspace"
+	testingID             = 1
+	tableName             = "vt_prepare_stmt_test"
+	cell                  = "zone1"
+	mysqlAuthServerStatic = "/mysql_auth_server_static.json"
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/main_test.go]: Do you need the leading `/` here?

File: go/test/endtoend/prepare-statement/main_test.go [hunk 4]
```diff
@@ -0,0 +1,272 @@
...
+
+}
+
+// ConnectionString generates the connection string using dbinfo.
+func (db DBInfo) ConnectionString(params ...string) string {
+	return fmt.Sprintf("%s:%s@tcp(%s:%d)/%s?%s", db.Username, db.Password, db.Host,
+		db.Port, db.KeyspaceName, strings.Join(append(db.Params, params...), "&"))
+}
+
+// createConfig create file in to Tmp dir in vtdataroot and write the given data.
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/main_test.go]:
```suggestion
// createConfig creates a config file in TmpDir in vtdataroot and writes the given data.
```

File: go/test/endtoend/prepare-statement/main_test.go [hunk 5]
```diff
@@ -0,0 +1,272 @@
...
+	if data == "" {
+		return nil
+	}
+
+	// write the given data
+	_, err = fmt.Fprint(f, data)
+	return err
+}
+
+// GetORM will connect the vtgate through mysql protocol.
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/main_test.go]: Why is this called `GetORM`? It looks like you are opening a connection, so why not `GetConnection`? or `Connect`?

File: go/test/endtoend/prepare-statement/main_test.go [hunk 6]
```diff
@@ -0,0 +1,272 @@
...
+func GetORM(t *testing.T, params ...string) *sql.DB {
+	dbo, err := sql.Open("mysql", dbInfo.ConnectionString(params...))
+	require.Nil(t, err)
+	return dbo
+}
+
+// execWithIgnore executes the prepared query, and ignore the given error codes.
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/main_test.go]:
```suggestion
// execWithIgnore executes the prepared query, and ignores the given error codes.
```

File: go/test/endtoend/prepare-statement/main_test.go [hunk 7]
```diff
@@ -0,0 +1,272 @@
...
+func execWithIgnore(t *testing.T, dbo *sql.DB, errorCodes []uint16, stmt string, params ...interface{}) {
+	if _, err := dbo.Exec(stmt, params...); err != nil {
+		require.Contains(t, errorCodes, err.(*mysql.MySQLError).Number)
+		glog.Info("error_ignored", err)
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/main_test.go]: Are we adding a dependency to `glog` or is this an existing dependency?
In any case, we should be using only `t.Logf` methods, not anything else.

File: go/test/endtoend/prepare-statement/main_test.go [hunk 8]
```diff
@@ -0,0 +1,272 @@
...
+	}
+}
+
+// exec executes the query using the params.
+func exec(t *testing.T, dbo *sql.DB, stmt string, params ...interface{}) {
+	require.Nil(t, execErr(dbo, stmt, params...))
+}
+
+// execErr execute the query and return error.
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/main_test.go]:
```suggestion
// execErr executes the query and returns an error if one occurs.
```

File: go/test/endtoend/prepare-statement/main_test.go [hunk 9]
```diff
@@ -0,0 +1,272 @@
...
+func execErr(dbo *sql.DB, stmt string, params ...interface{}) *mysql.MySQLError {
+	if _, err := dbo.Exec(stmt, params...); err != nil {
+		return err.(*mysql.MySQLError)
+	}
+	return nil
+}
+
+// selectWhere select the row corresponds to the where condition.
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/main_test.go]:
```suggestion
// selectWhere select the row corresponding to the where condition.
```

File: go/test/endtoend/prepare-statement/stmt_methods_test.go [hunk 10]
```diff
@@ -0,0 +1,170 @@
...
+)
+
+// TestSelect simple select the data without any condition.
+func TestSelect(t *testing.T) {
+	dbo := GetORM(t)
+	defer dbo.Close()
+	selectWhere(t, dbo, "")
+}
+
+// TestInsertUpdateDelete validate all insert, update and
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/stmt_methods_test.go]:
```suggestion
// TestInsertUpdateDelete validates all insert, update and
```

File: go/test/endtoend/prepare-statement/stmt_methods_test.go [hunk 11]
```diff
@@ -0,0 +1,170 @@
...
+// delete method on prepared statements.
+func TestInsertUpdateDelete(t *testing.T) {
+
+	dbo := GetORM(t)
+	defer dbo.Close()
+	// prepared insert statement for the insert testing
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/stmt_methods_test.go]:
```suggestion
	// prepare insert statement
```

File: go/test/endtoend/prepare-statement/stmt_methods_test.go [hunk 12]
```diff
@@ -0,0 +1,170 @@
...
+	insertStmt := `insert into ` + tableName + ` values(?,  ?,  ?,  ?,  ?,  ?,  ?,  
+		?,  ?,  ?,  ?,  ?,  ?,  ?,  ?,  ?,  ?,  ?, ?,  ?,  ?,  ?,  ?,  ?, ?, ?, ?);`
+
+	textValue := fake.FullName()
+	largeComment := fake.Paragraph()
+
+	// inserting the multiple data in to test table
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/stmt_methods_test.go]:
```suggestion
	// inserting multiple rows into test table
```

File: go/test/endtoend/prepare-statement/stmt_methods_test.go [hunk 13]
```diff
@@ -0,0 +1,170 @@
...
+	for i := 1; i <= 100; i++ {
+		// preparing value for the insert testing
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/stmt_methods_test.go]:
```suggestion
		// preparing values for insert testing
```

File: go/test/endtoend/prepare-statement/stmt_methods_test.go [hunk 14]
```diff
@@ -0,0 +1,170 @@
...
+	// validate value of msg column in data
+	assert.Equal(t, fmt.Sprintf("%d21", testingID), data[0].Msg)
+
+	// testing record update
+	updateRecord(t, dbo)
+
+	// testing record deletion
+	deleteRecord(t, dbo)
+
+	// testing recontion and deleted data validation
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/stmt_methods_test.go]:
```suggestion
	// testing reconnection and deleted data validation
```

File: go/test/endtoend/prepare-statement/stmt_methods_test.go [hunk 15]
```diff
@@ -0,0 +1,170 @@
...
+	reconnectAndTest(t)
+}
+
+// testcount validates inserted rows count with expected count.
+func testcount(t *testing.T, dbo *sql.DB, except int) {
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/stmt_methods_test.go]:
```suggestion
func testCount(t *testing.T, dbo *sql.DB, except int) {
```

File: go/test/endtoend/prepare-statement/stmt_methods_test.go [hunk 16]
```diff
@@ -0,0 +1,170 @@
...
+	r, err := dbo.Query("SELECT count(1) FROM " + tableName)
+	require.Nil(t, err)
+
+	// read output of query in var i
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/stmt_methods_test.go]: you can remove this comment, it adds no value

File: go/test/endtoend/prepare-statement/stmt_methods_test.go [hunk 17]
```diff
@@ -0,0 +1,170 @@
...
+		time.Date(2009, 5, 5, 0, 0, 0, 0, time.UTC),
+		time.Now(),
+		time.Date(2009, 5, 5, 0, 0, 0, 0, time.UTC),
+		1, 1, 1, 1, 1, 1, 1, 1, 1, jsonExample, fake.DomainName(), fake.Paragraph(),
+	}
+
+	exec(t, dbo, insertStmt, insertValue...)
+}
+
+// deleteRecord test deletion opeation corresponds to the testingID.
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/stmt_methods_test.go]:
```suggestion
// deleteRecord test deletion operation corresponds to the testingID.
```

File: go/test/endtoend/prepare-statement/stmt_methods_test.go [hunk 18]
```diff
@@ -0,0 +1,170 @@
...
+func deleteRecord(t *testing.T, dbo *sql.DB) {
+	// delete the record with id 1
+	exec(t, dbo, "DELETE FROM "+tableName+" WHERE id = ?;", testingID)
+
+	data := selectWhere(t, dbo, "id = ?", testingID)
+	assert.Equal(t, 0, len(data))
+
+}
+
+// updateRecord test update opeation corresponds to the testingID.
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/stmt_methods_test.go]:
```suggestion
// updateRecord test update operation corresponds to the testingID.
```

File: go/test/endtoend/prepare-statement/stmt_methods_test.go [hunk 19]
```diff
@@ -0,0 +1,170 @@
...
+	assert.Equal(t, 0, len(data))
+
+}
+
+// TestWrongTableName query database using invalid
+// tablename and validate error.
+func TestWrongTableName(t *testing.T) {
+	dbo := GetORM(t)
+	defer dbo.Close()
+	execWithIgnore(t, dbo, []uint16{1105}, "select * from teseting_table;")
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/stmt_methods_test.go]: The test will also pass if there is no error. We need to assert that the expected error has actually occurred.

File: test/config.json [hunk 20]
```diff
@@ -442,6 +433,15 @@
 			"RetryMax": 0,
 			"Tags": []
 		},
+		"prepare_statement": {
+			"File": "stmt_method_test.go",
+			"Args": ["vitess.io/vitess/go/test/endtoend/prepare-statement"],
```
Comment (deepthi) [inline test/config.json]: vitess convention is no underscores or dashes in directories. Please rename the directory (to preparestmt or preparestatement, the choice is up to you).

File: go/test/endtoend/prepare-statement/main_test.go [hunk 21]
```diff
@@ -0,0 +1,272 @@
...
+		}`
+		if err := createConfig(mysqlAuthServerStatic, SQLConfig); err != nil {
+			return 1, err
+		}
+
+		// add extra arguments
+		clusterInstance.VtGateExtraArgs = []string{
+			"-mysql_auth_server_impl", "static",
+			"-mysql_server_query_timeout", "1s",
+			"-mysql_auth_server_static_file", clusterInstance.TmpDirectory + mysqlAuthServerStatic,
```
Comment (deepthi) [inline go/test/endtoend/prepare-statement/main_test.go]: I suggest removing the `/` from the value of mysqlAuthServerStatic and adding a `+ "/" +` here.

**Comment by deepthi** [comment]
You will need to resolve the DCO and merge conflict.
Please get @ajeetj or @arindamnayak to help if needed.

**Comment by deepthi** [comment]
sorry, merging your other PR creates conflicts in this one. Can you resolve them?
