### PR TITLE
Better handling of partial dml query exec in transaction

### LINKED ISSUE #9266: RFC: Rollback of partial failed query in an explicit transaction
# Problem Statement
In a transaction, when a single DML (data manipulation language) query is broken into sub-queries like a scatter query or a vindex query. Then, any error in executing those queries leads to the rollback of the complete transaction.

This helps in guaranteeing that no unexpected data is committed on the transaction but it also leads to a bad user experience on handling distributed query errors inside transactions.

# Proposed Solution
In an explicit transaction created by the user, any DML query that executes on the multi-shard or needs a vindex update will execute in the scope of a savepoint. If there is any partial failure then the effect of that DML query will be rollback to the savepoint. In case the query completes successfully, savepoint will not be released, and only on a commit/rollback by the user, it will be cleared.

In an auto-commit mode, when a DML goes to multi-shard or vindex is updated, the implicit transaction created at the VTGate level will still have the same behavior of rollback of the transaction i.e. no impact of the failed DML query on the database.

# Test Cases

| S.No. | Test Case | Expectation |
| ----- | ------------- | ------------- |
| 1 | Begin -> partial failing query | transaction remains open; partial change rolled back |
| 2 | Begin -> partial vindex failing query | transaction remains open; partial change rolled back |
| 3 | Autocommit false -> partial failing query | transaction remains open; partial change rolled back|
| 4 | Autocommit false -> partial vindex failing query | transaction remains open; partial change rolled back |
| 5 | Partial change rollback failed (rollback to savepoint) | transaction is rolled back |
| 6 | Autcommit true -> partial failed query | Transaction is rolled back; No change on the database |

All 4 the cases in OLTP, OLTP-reserved, OLAP, OLAP-reserved

### PR DESCRIPTION
**Pull request by harshit-gangal**
## Description

This PR reverses the effect of partial dml query execution instead of rolling back the complete transaction when the transaction is explicitly created by the user.

## Related Issue(s)

- Closes #9266 

## Checklist
- [X] Tests were added or are not required
- [X] Documentation was added or is not required

### CODE REVIEW

File: go/test/endtoend/vtgate/partialfailure/main_test.go [hunk 1]
```diff
@@ -0,0 +1,561 @@
...
+			utils.AssertContainsError(t, conn, `insert into test(id, val1) values (1,'D'),(4,'E')`, `transaction rolled back to reverse changes of partial DML execution`)
+			utils.AssertMatches(t, conn, `select id, val1 from test order by id`, `[[INT64(1) VARCHAR("A")] [INT64(2) VARCHAR("B")] [INT64(3) VARCHAR("C")]]`)
+			utils.Exec(t, conn, `rollback`)
+			utils.AssertMatches(t, conn, `select id, val1 from test order by id`, `[[INT64(1) VARCHAR("A")] [INT64(2) VARCHAR("B")] [INT64(3) VARCHAR("C")]]`)
+		})
+	}
+}
+
+func TestPartialVindexQueryFailureAutoCommitRollback(t *testing.T) {
+	tcases := []struct {
```
Comment (systay) [inline go/test/endtoend/vtgate/partialfailure/main_test.go:529]: nit: this pattern is copy pasted over and over again in this file. I think we should extract to a single place

File: go/vt/vtexplain/vtexplain.go [hunk 2]
```diff
@@ -336,6 +341,26 @@ func ExplainsAsText(explains []*Explain) string {
 	return b.String()
 }
 
+func specialHandlingOfSavepoints(q *MysqlQuery) {
+	if strings.Contains(q.SQL, "savepoint") {
+		stmt, _ := sqlparser.Parse(q.SQL)
```
Comment (systay) [inline go/vt/vtexplain/vtexplain.go:346]: we should not ignore the error, and we should use a checked type conversion so we don't panic if we got something other than a savepoint

File: go/vt/vtgate/executor.go [hunk 3]
```diff
@@ -582,34 +582,51 @@ func (e *Executor) handleSavepoint(ctx context.Context, safeSession *SafeSession
...
+	qr, err := e.executeSPInAllSessions(ctx, safeSession, sql, ignoreMaxMemoryRows)
+	safeSession.SetCommitOrder(orig)
 	if err != nil {
 		return nil, err
 	}
 	safeSession.StoreSavepoint(sql)
 	return qr, nil
 }
 
+func (e *Executor) executeSPInAllSessions(ctx context.Context, safeSession *SafeSession, sql string, ignoreMaxMemoryRows bool) (*sqltypes.Result, error) {
```
Comment (systay) [inline go/vt/vtgate/executor.go:603]: maybe it's too early, but I'm not sure what SPI means here. Would you mind adding a comment explaining?

File: go/vt/vtgate/executor.go [hunk 4]
```diff
@@ -1432,6 +1449,18 @@ func (e *Executor) getPlan(vcursor *vcursorImpl, sql string, comments sqlparser.
 	return e.checkThatPlanIsValid(stmt, plan)
 }
 
+func ignoreMaxPayloadSize(stmt sqlparser.Statement) bool {
```
Comment (systay) [inline go/vt/vtgate/executor.go:1452]: why not add this to `sqlparser.IgnoreMaxPayloadSizeDirective` instead?

File: go/vt/vtgate/executor_dml_test.go [hunk 5]
```diff
@@ -53,12 +55,8 @@ func TestUpdateEqual(t *testing.T) {
 		Sql:           "update `user` set a = 2 where id = 1",
 		BindVariables: map[string]*querypb.BindVariable{},
 	}}
-	if !reflect.DeepEqual(sbc1.Queries, wantQueries) {
-		t.Errorf("sbc1.Queries: %+v, want %+v\n", sbc1.Queries, wantQueries)
-	}
-	if sbc2.Queries != nil {
-		t.Errorf("sbc2.Queries: %+v, want nil\n", sbc2.Queries)
-	}
+	testQueries(t, sbc1, wantQueries)
```
Comment (systay) [inline go/vt/vtgate/executor_dml_test.go:58]: should we rename this to `assertQueries` or something? this method is just asserting that we got the right queries back, right?

File: go/vt/vtgate/executor_framework_test.go [hunk 6]
```diff
@@ -572,10 +571,47 @@ func executorStream(executor *Executor, sql string) (qr *sqltypes.Result, err er
...
+		}
+		require.Equal(t, query.BindVariables, wantQueries[idx].BindVariables)
+		got := query.Sql
+		expected := wantQueries[idx].Sql
+		idx++
+		assert.Equal(t, expected, got)
+	}
+}
+
+func testQueriesWithSavepoint(t *testing.T, sbc *sandboxconn.SandboxConn, wantQueries []*querypb.BoundQuery) {
```
Comment (systay) [inline go/vt/vtgate/executor_framework_test.go:592]: same this as above - since this method is just asserting state, could we name it something with assert, check or require?

File: go/vt/vtgate/safe_session.go [hunk 7]
```diff
@@ -40,6 +40,11 @@ type SafeSession struct {
 	mustRollback    bool
 	autocommitState autocommitState
 	commitOrder     vtgatepb.CommitOrder
+	savepointState  savepointState
+	// rollbackOnPartialExec is set if any DML was successfully
```
Comment (systay) [inline go/vt/vtgate/safe_session.go:44]: set to what? why is this a string?

File: go/vt/vtgate/vcursor_impl.go [hunk 8]
```diff
@@ -423,6 +421,8 @@ func (vc *vcursorImpl) StreamExecutePrimitive(primitive engine.Primitive, bindVa
 	return vterrors.New(vtrpcpb.Code_UNAVAILABLE, "upstream shards are not available")
 }
 
+const txRollback = "Rollback Transaction"
```
Comment (systay) [inline go/vt/vtgate/vcursor_impl.go:424]: nit: weird placement for a const

File: go/vt/vtgate/executor.go (hunk 3 above)
Comment (frouioui) [reply go/vt/vtgate/executor.go:603]: I think the function's name translates to "Execute Save Points In All Sessions", but we could add a comment explaining what "sp" means. In `vtexplain.go:302` I also got confused the first time I saw "sp".

File: go/vt/vtgate/executor_framework_test.go (hunk 6 above)
Comment (frouioui) [reply go/vt/vtgate/executor_framework_test.go:592]: I am thinking we could probably move these two methods in the `sandboxconn` package and make them public so we can reuse them everywhere.

File: go/vt/vtgate/plan_execute.go [hunk 9]
```diff
@@ -179,6 +179,10 @@ func (e *Executor) insideTransaction(ctx context.Context, safeSession *SafeSessi
 	// at the beginning, but never after.
 	safeSession.SetAutocommittable(mustCommit)
 
+	// If we to instantly commit the query, then there is no need to add savepoints.
```
Comment (frouioui) [inline go/vt/vtgate/plan_execute.go:182]: `// If we to instantly` => `// If we want to instantly`

File: go/vt/vtgate/safe_session.go [hunk 10]
```diff
@@ -166,6 +187,33 @@ func (session *SafeSession) AutocommitApproval() bool {
 	return false
 }
 
+// SetSavepointState sets the state to insertSavepoints if true and noInsertSavepoints if false
```
Comment (frouioui) [inline go/vt/vtgate/safe_session.go:190]:
```suggestion
// SetSavepointState sets the state to insertSavepoints if true and noInsertSavepoints is false
```

File: go/vt/vttablet/sandboxconn/sandboxconn.go [hunk 11]
```diff
@@ -55,6 +55,9 @@ type SandboxConn struct {
 	MustFailStartCommit         int
 	MustFailSetRollback         int
 	MustFailConcludeTransaction int
+	// MustFailExecute is keyed by the statement type and stores the number
+	// of errors to return for that statement type.
+	MustFailExecute map[sqlparser.StatementType]int
```
Comment (frouioui) [inline go/vt/vttablet/sandboxconn/sandboxconn.go:60]: The name is a little confusing considering the comment

File: go/vt/vtgate/executor_framework_test.go (hunk 6 above)
Comment (harshit-gangal) [reply go/vt/vtgate/executor_framework_test.go:592]: they are used only for executor tests, if it is used/required anywhere else we can move it later.

File: go/vt/vtgate/safe_session.go (hunk 7 above)
Comment (harshit-gangal) [reply go/vt/vtgate/safe_session.go:44]: rollbackOnPartialExec will store the `rollback to <savepoint>` sql query which is generated randomly when doing MarkSavepoint.

File: go/vt/vtgate/vcursor_impl.go (hunk 8 above)
Comment (harshit-gangal) [reply go/vt/vtgate/vcursor_impl.go:424]: earlier it was near to usage, then the code the moved,
now moved it back to the usage.

File: go/vt/vtgate/safe_session.go (hunk 10 above)
Comment (harshit-gangal) [reply go/vt/vtgate/safe_session.go:190]: the statement is correct, suggestion means that it is not clear, will rephrase it.

File: go/vt/vttablet/sandboxconn/sandboxconn.go (hunk 11 above)
Comment (harshit-gangal) [reply go/vt/vttablet/sandboxconn/sandboxconn.go:60]: it is similar to the naming convention of other MustFails in the struct.

Comment (harshit-gangal) [reply go/vt/vttablet/sandboxconn/sandboxconn.go:60]: added more comment for clarity

File: go/vt/vtgate/autocommit_test.go [hunk 12]
```diff
@@ -385,10 +385,10 @@ func TestAutocommitTransactionStarted(t *testing.T) {
 	_, err := executor.Execute(context.Background(), "TestExecute", NewSafeSession(session), sql, map[string]*querypb.BindVariable{})
 	require.NoError(t, err)
 
-	testQueries(t, "sbc1", sbc1, []*querypb.BoundQuery{{
-		Sql:           "update `user` set a = 2 where id = 1",
-		BindVariables: map[string]*querypb.BindVariable{},
-	}})
+	require.Equal(t, 2, len(sbc1.Queries))
+	require.Contains(t, sbc1.Queries[0].Sql, "savepoint")
+	require.Equal(t, sbc1.Queries[1].Sql, "update `user` set a = 2 where id = 1")
```
Comment (frouioui) [inline go/vt/vtgate/autocommit_test.go:390]: the expected value is the second argument and the actual value is the third argument of `require.Equal`
```suggestion
	require.Equal(t, "update `user` set a = 2 where id = 1", sbc1.Queries[1].Sql)
```

File: go/vt/vttablet/sandboxconn/sandboxconn.go (hunk 11 above)
Comment (frouioui) [reply go/vt/vttablet/sandboxconn/sandboxconn.go]: okay got it

**Review by frouioui — APPROVED** [review]
Looks good to me. Agreed with @systay on https://github.com/vitessio/vitess/pull/9269#discussion_r758064993, we should avoid the repetition in the test suite to make adding/changing tests easier

File: go/vt/vtexplain/vtexplain.go [hunk 13]
```diff
@@ -333,7 +341,40 @@ func ExplainsAsText(explains []*Explain) string {
 		fmt.Fprintf(&b, "\n")
 	}
 	fmt.Fprintf(&b, "----------------------------------------------------------------------\n")
-	return b.String()
+	return b.String(), nil
+}
+
+func specialHandlingOfSavepoints(q *MysqlQuery) error {
+	if !strings.Contains(q.SQL, "savepoint") {
```
Comment (systay) [inline go/vt/vtexplain/vtexplain.go:348]: nit: can't we just skip this string check since we are looking at the type of the AST below?

Comment (harshit-gangal) [reply go/vt/vtexplain/vtexplain.go:348]: This is just to avoid parsing overhead.

File: go/vt/vtgate/safe_session.go (hunk 7 above)
Comment (systay) [reply go/vt/vtgate/safe_session.go:44]: we should add :point_up: to the comment

File: go/vt/vtgate/safe_session.go [hunk 14]
```diff
@@ -166,6 +187,34 @@ func (session *SafeSession) AutocommitApproval() bool {
 	return false
 }
 
+// SetSavepointState sets the state only once for the complete query execution life.
+// Calling the function multiple times will have no effect, only the first call would be used.
+// Default state is savepointStateNotSet,
+// if savepoint needed (spNeed true) then it will be set to savepointNeeded otherwise savepointNotNeeded.
+
+func (session *SafeSession) SetSavepointState(spNeed bool) {
```
Comment (systay) [inline go/vt/vtgate/safe_session.go:195]: comment missing

File: go/vt/vtgate/safe_session.go [hunk 15]
```diff
@@ -576,3 +625,24 @@ func (session *SafeSession) getSelectLimit() int {
...
 }
+
+func (session *SafeSession) isTxOpen() bool {
+	session.mu.Lock()
+	defer session.mu.Unlock()
+
+	return len(session.ShardSessions) > 0 || len(session.PreSessions) > 0 || len(session.PostSessions) > 0
+}
+
+func (session *SafeSession) GetSessions() []*vtgatepb.Session_ShardSession {
```
Comment (systay) [inline go/vt/vtgate/safe_session.go:636]: comment missing

**Review by systay — COMMENTED** [review]
I was too late to accept it, but I would have if given the chance :)

LGTM :+1:

File: go/vt/vtexplain/vtexplain.go (hunk 13 above)
Comment (systay) [reply go/vt/vtexplain/vtexplain.go:348]: in vtexplain? doesn't feel like it's part of the code where we need to squeeze extra drops of performance. ¯\_(ツ)_/¯

File: go/vt/vtgate/safe_session.go (hunk 14 above)
Comment (harshit-gangal) [reply go/vt/vtgate/safe_session.go:195]: there was extra line, comments are there :)

File: go/vt/vtgate/safe_session.go (hunk 15 above)
Comment (harshit-gangal) [reply go/vt/vtgate/safe_session.go:636]: added in #9294
