### PR TITLE
restore: Run PITR through mysqlctl

### LINKED ISSUE #13124: Bug Report: PITR recovery uses local mysql directly
### Overview of the Issue

When running PITR recovery, the local `mysql` and `mysqlbinlog` tools are used, but when we run with a different MySQL pod, it means it runs with the incorrect versions of those tools.

Instead, we should execute this through `mysqlctl` like we do for example for the MySQL upgrade process as well. 

### Reproduction Steps

Use PITR with a separate MySQL container.

### Binary Version

```sh
Any
```

### Operating System and Environment details

```sh
-
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by dbussink**
When we run a restore remotely on the vttablet, we need to run the PITR logic through mysqlctl to ensure we run it with the correct MySQL binaries.

It adds additional safety checks for using the `Mysqld` type because it's reused between both the local MySQL interaction and `mysqlctl` but also as a remote interface used from `vttablet`.

This safety check means that we should never run certain things when running remotely inside `vttablet`, which is identified by the `socketFile` being set or not. When it is set, we now panic on certain actions we know are not going to work.

By adding this panic we can ensure we catch uses like the restore usage earlier since it would break if we do anything unsupported.

## Related Issue(s)

Fixes #13124

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/mysqlctl/capabilityset.go [hunk 1]
```diff
@@ -51,18 +52,6 @@ func (c *capabilitySet) hasMaria104InstallDb() bool {
...
-// As of MySQL 8.0.21, you can disable redo logging using the ALTER INSTANCE
-// DISABLE INNODB REDO_LOG statement. This functionality is intended for
-// loading data into a new MySQL instance. Disabling redo logging speeds up
-// data loading by avoiding redo log writes and doublewrite buffering.
-//
-//	https://dev.mysql.com/doc/refman/8.0/en/innodb-redo-log.html#innodb-disable-redo-logging
-func (c *capabilitySet) hasDisableRedoLog() bool {
-	return c.isMySQLLike() && c.version.atLeast(ServerVersion{Major: 8, Minor: 0, Patch: 21})
-}
-
```
Comment (dbussink) [inline go/vt/mysqlctl/capabilityset.go:65]: I have removed this function since nothing is using atm. I'd like to reduce anything that checks capabilities to as little as possible, since this PR also further restricts that these capabilities can only be used properly inside `mysqlctl` and with less surface, we have less potential issues where it can be used wrong.

File: go/vt/mysqlctl/mysqld.go [hunk 2]
```diff
@@ -157,6 +157,12 @@ func NewMysqld(dbcfgs *dbconfigs.DBConfigs) *Mysqld {
 		log.Info("mysqld is unmanaged or remote. Skipping flavor detection")
 		return result
 	}
+
+	if socketFile != "" {
+		log.Info("mysqld is remote. Skipping flavor detection")
+		return result
+	}
```
Comment (dbussink) [inline go/vt/mysqlctl/mysqld.go:164]: This ensures we don't set up capabilities when we can't correctly detect them.

File: go/vt/mysqlctl/mysqld.go [hunk 3]
```diff
@@ -286,7 +293,7 @@ func (mysqld *Mysqld) RunMysqlUpgrade() error {
 			return fmt.Errorf("can't dial mysqlctld: %v", err)
 		}
 		defer client.Close()
-		return client.RunMysqlUpgrade(context.TODO())
+		return client.RunMysqlUpgrade(ctx)
 	}
```
Comment (dbussink) [inline go/vt/mysqlctl/mysqld.go:297]: Seems simplest to pass in the context we already have in all the callers further up in the call chain.

File: go/vt/mysqlctl/mysqld.go [hunk 4]
```diff
@@ -635,6 +642,7 @@ func execCmd(name string, args, env []string, dir string, input io.Reader) (cmd
 // binaryPath does a limited path lookup for a command,
 // searching only within sbin and bin in the given root.
 func binaryPath(root, binary string) (string, error) {
+	noSocketFile()
```
Comment (dbussink) [inline go/vt/mysqlctl/mysqld.go:645]: Anywhere we're going to check if a certain binary is available, implies we need to be running inside `mysqlctl`. This ensures we error out hard when we try to end up calling this somewhere else.

Everything is correct here today, this is a safety mechanism so that we don't accidentally add broken usage in the future.

File: go/vt/mysqlctl/mysqld.go [hunk 5]
```diff
@@ -1176,9 +1184,20 @@ func buildLdPaths() ([]string, error) {
...
+		return ""
+	}
+	if len(qr.Rows) != 1 {
+		log.Errorf("Unexpected number of rows: %v", qr.Rows)
+		return ""
+	}
+	res := qr.Named().Row()
+	version, _ := res.ToString("@@global.version")
+	return version
 }
```
Comment (dbussink) [inline go/vt/mysqlctl/mysqld.go:1201]: Similar to `GetVersionComment`, we get the version number here at runtime from the actual running MySQL instance. This ensures we get the right version and not the local binary.

File: go/vt/mysqlctl/mysqld.go [hunk 6]
```diff
@@ -1195,9 +1214,18 @@ func (mysqld *Mysqld) GetVersionComment(ctx context.Context) string {
...
+func (mysqld *Mysqld) ApplyBinlogFile(ctx context.Context, binlogFile string, restorePos mysql.Position) error {
+	if socketFile != "" {
+		log.Infof("executing Mysqld.ApplyBinlogFile() remotely via mysqlctld server: %v", socketFile)
+		client, err := mysqlctlclient.New("unix", socketFile)
+		if err != nil {
+			return fmt.Errorf("can't dial mysqlctld: %v", err)
+		}
+		defer client.Close()
+		return client.ApplyBinlogFile(ctx, binlogFile, mysql.EncodePosition(restorePos))
+	}
```
Comment (dbussink) [inline go/vt/mysqlctl/mysqld.go:1228]: This is now part of the interface and also has a remote version so we can run this correctly for restores through `mysqlctl`.

File: go/vt/mysqlctl/mysqld.go [hunk 7]
```diff
@@ -1195,9 +1214,18 @@ func (mysqld *Mysqld) GetVersionComment(ctx context.Context) string {
 	return versionComment
 }
 
-// applyBinlogFile extracts a binary log file and applies it to MySQL. It is the equivalent of:
+// ApplyBinlogFile extracts a binary log file and applies it to MySQL. It is the equivalent of:
 // $ mysqlbinlog --include-gtids binlog.file | mysql
-func (mysqld *Mysqld) applyBinlogFile(binlogFile string, includeGTIDs mysql.GTIDSet) error {
+func (mysqld *Mysqld) ApplyBinlogFile(ctx context.Context, binlogFile string, restorePos mysql.Position) error {
```
Comment (dbussink) [inline go/vt/mysqlctl/mysqld.go:1219]: Changing this to `mysql.Position` makes it easier to serialize / deserialize and better matches how we use a GTID position in other places here.

File: go/vt/mysqlctl/grpcmysqlctlclient/client.go [hunk 8]
```diff
@@ -84,6 +83,18 @@ func (c *client) RunMysqlUpgrade(ctx context.Context) error {
...
 }
 
+// ApplyBinlogFile is part of the MysqlctlClient interface.
+func (c *client) ApplyBinlogFile(ctx context.Context, binlogFileName, binlogRestorePosition string) error {
+	req := &mysqlctlpb.ApplyBinlogFileRequest{
+		BinlogFileName:        binlogFileName,
+		BinlogRestorePosition: binlogRestorePosition,
+	}
+	return c.withRetry(ctx, func() error {
+		_, err := c.c.ApplyBinlogFile(ctx, req)
```
Comment (shlomi-noach) [inline go/vt/mysqlctl/grpcmysqlctlclient/client.go:93]: Not a fan of `c.c.` but unrelated to this PR

File: go/vt/mysqlctl/mysqld.go [hunk 9]
```diff
@@ -1176,9 +1184,20 @@ func buildLdPaths() ([]string, error) {
...
+	qr, err := mysqld.FetchSuperQuery(ctx, "select @@global.version")
+	if err != nil {
+		log.Errorf("Error fetching MySQL version: %v", err)
+		return ""
+	}
+	if len(qr.Rows) != 1 {
+		log.Errorf("Unexpected number of rows: %v", qr.Rows)
+		return ""
+	}
+	res := qr.Named().Row()
```
Comment (shlomi-noach) [inline go/vt/mysqlctl/mysqld.go:1198]: BTW the function `Row()` returns `nil` if the number of rows `!= 1`. So if you wanted, you could rewrite the integrity check above from `if len(qr.Rows) != 1 {` to (down in this line) `if res == nil`. Whichever you feel more comfortable with, seeing that the former is more explicit and the latter is implied.

**Review by shlomi-noach — APPROVED** [review]

File: go/vt/mysqlctl/grpcmysqlctlclient/client.go (hunk 8 above)
Comment (dbussink) [reply go/vt/mysqlctl/grpcmysqlctlclient/client.go:93]: Copied this basically from the other things we have to be consistent.

File: go/vt/mysqlctl/mysqld.go (hunk 9 above)
Comment (dbussink) [reply go/vt/mysqlctl/mysqld.go:1198]: Same here, this is basically a copy paste of how the comment version works and mostly the same to stay consistent with that.

**Review by harshit-gangal — APPROVED** [review]
