### PR TITLE
Fixes function call in default value of a column in CREATE TABLE statement

### LINKED ISSUE #8424: Function calls in DEFAULT value of CREATE TABLE statement
#### Overview of the Issue

Default value example in the MySQL 8.0 docs that fails in Vitess but works in local MySQL 8:

```sql
417/test> CREATE TABLE t4 (uid BINARY(16) DEFAULT (UUID_TO_BIN(UUID())));
ERROR 1064 (42000): target: 417.-.master: vttablet: rpc error: code = InvalidArgument desc = You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'UUID_TO_BIN(UUID()))' at line 2 (errno 1064) (sqlstate 42000) (CallerID: unsecure_grpc_client): Sql: "create table t4 (\n\tuid BINARY(16) default UUID_TO_BIN(UUID())\n)", BindVars: {}
```

```sql
mysql> select @@version;
+-----------+
| @@version |
+-----------+
| 8.0.25    |
+-----------+
1 row in set (0.00 sec)

mysql> CREATE TABLE t4 (uid BINARY(16) DEFAULT (UUID_TO_BIN(UUID())));
Query OK, 0 rows affected (0.01 sec)
```

#### Reproduction Steps

Run the create table statement in Vitess and MySQL

#### Binary version
Release 9.0 onwards

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description
This PR fixes function call in default value of a column in CREATE TABLE statement. The function calls must be parenthesised according to the syntax. 

## Related Issue(s)
- Fixes #8424 

## Checklist
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/sqlparser/ast.go [hunk 1]
```diff
@@ -2220,7 +2220,14 @@ func (ct *ColumnType) Format(buf *TrackedBuffer) {
...
 	if ct.Default != nil {
-		opts = append(opts, keywordStrings[DEFAULT], String(ct.Default))
+		opts = append(opts, keywordStrings[DEFAULT])
+		_, isLiteral := ct.Default.(*Literal)
+		_, isNullVal := ct.Default.(*NullVal)
+		if isLiteral || isNullVal {
+			opts = append(opts, String(ct.Default))
+		} else {
+			opts = append(opts, "("+String(ct.Default)+")")
+		}
```
Comment (frouioui) [inline go/vt/sqlparser/ast.go:2230]: Why don't we need to check if  `_, isFuncExpr := ct.Default.(*FuncExpr); isFuncExpr == true` ?

**Review by harshit-gangal — APPROVED** [review]

**Comment by harshit-gangal** [comment]
e2e tests are failing

```
2021-07-07T15:16:02.5552905Z     misc_test.go:520: 
2021-07-07T15:16:02.5553418Z         	Error Trace:	misc_test.go:549
2021-07-07T15:16:02.5553949Z         	            				misc_test.go:520
2021-07-07T15:16:02.5554495Z         	Error:      	Received unexpected error:
2021-07-07T15:16:02.5557520Z         	            	vtgate: http://fv-az184-575.3ow45vhwbzuu5incsxmygykede.cx.internal.cloudapp.net:16225/: target: ks.-80.master, used tablet: test-9087 (localhost): vttablet: rpc error: code = InvalidArgument desc = You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(TRIM(' check '))
2021-07-07T15:16:02.5560411Z         	            	)' at line 2 (errno 1064) (sqlstate 42000) (CallerID: userData1): Sql: "create table function_default (\n\tx varchar(25) default (TRIM(' check '))\n)", BindVars: {}
2021-07-07T15:16:02.5562404Z         	            	target: ks.80-.master, used tablet: test-9090 (localhost): vttablet: rpc error: code = InvalidArgument desc = You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(TRIM(' check '))
2021-07-07T15:16:02.5564699Z         	            	)' at line 2 (errno 1064) (sqlstate 42000) (CallerID: userData1): Sql: "create table function_default (\n\tx varchar(25) default (TRIM(' check '))\n)", BindVars: {} (errno 1064) (sqlstate 42000) during query: create table function_default (x varchar(25) DEFAULT (TRIM(" check ")))
2021-07-07T15:16:02.5566140Z         	Test:       	TestFunctionInDefault
2021-07-07T15:16:02.5566907Z         	Messages:   	for query: create table function_default (x varchar(25) DEFAULT (TRIM(" check ")))
2021-07-07T15:16:02.5567847Z --- FAIL: TestFunctionInDefault (0.01s)
```

File: go/vt/sqlparser/ast.go (hunk 1 above)
Comment (GuptaManan100) [reply go/vt/sqlparser/ast.go:2230]: Because stuff like this is also possible 🤯  -
```sql
MySQL root@(none):test> create table function_default3 (x bool DEFAULT (true AND false));
Query OK, 0 rows affected
Time: 0.008s
MySQL root@(none):test> insert into function_default3 values ();
Query OK, 1 row affected
Time: 0.002s
MySQL root@(none):test> select * from function_default3;
+---+
| x |
+---+
| 0 |
+---+
1 row in set
Time: 0.007s
```

Comment (GuptaManan100) [reply go/vt/sqlparser/ast.go:2230]: Added a parse test for this case too

Comment (systay) [reply go/vt/sqlparser/ast.go:2230]: yeah, we keep talking about function calls here, but the syntax rules say "arbitrary expression".

Comment (frouioui) [reply go/vt/sqlparser/ast.go:2230]: makes sense, thank you

**Review by systay — APPROVED** [review]
