### PR TITLE
bugfix: Truncate columns even when sorting on vtgate

### LINKED ISSUE #11261: Bug Report: Vitess returns `weight_string(...)` as column incorrectly during certain conditions
### Overview of the Issue

In certain settings for our use case, we can see that using a vindex `where V in (A, B, C)` where V is a regular (non-primary) vindex, an unwanted extra column is returned from the vtgate as shown below in an example.

Unfortunately, I haven't been able to set up an environment where this has reproduced, but it is reproducable on commit `e35a118344e79e17833450c7833aab27c3d4ee52` in our env.

### Reproduction Steps

1. Deploy the following `vschema`:
```
{
  "mainkeyspace": {
    "sharded": true,
    "vindexes": {
      "hash": {
        "type": "hash"
      },
      "md5": {
        "type": "unicode_loose_md5",
        "params": {},
        "owner": ""
      },
      "users_id_ks_idx": {
        "type": "lookup_unique",
        "params": {
          "table": "users_id_ks_idx",
          "from": "id",
          "table": "keyspace_id",
        },
        "owner": "users"
      }
    },
    "tables": {
      "users": {
        "column_vindexes": [
          {
            "column": "other_id",
            "name": "hash"
          },
          {
            "column": "id",
            "name": "users_id_ks_idx"
          }
        ],
        "columns": [
          {
            "name": "id",
            "type": "UINT64"
          },
          {
            "name": "other_id",
            "type": "UINT64"
          },
          {
            "name": "name",
            "type": "BINARY"
          }
        ],
        "auto_increment": null
      }
    }
  }
}
```

2. Deploy the following `schema`:
```
CREATE TABLE users(
  id bigint,
  other_id bigint not null,
  name varbinary(1024) not null,
  primary key(id)
);

CREATE TABLE users_id_ks_idx(
  id bigint(20) NOT NULL,
  keyspace_id varbinary(128) NOT NULL,
  PRIMARY KEY (id)
);
```

3. Run `SELECT users.name FROM users where users.id in (56) ORDER BY users.name ASC;

4. View error:
```
+------------------------+------------------------------+
| user                   | weight_string(user.name)     |
+------------------------+------------------------------+
| my-name                | my-name                      |
+------------------------+------------------------------+
```

### Binary Version

```sh
Version: 15.0.0-SNAPSHOT (Git revision e35a118344e79e17833450c7833aab27c3d4ee52 branch 'main') built on Tue Sep 20 07:43:57 UTC 2022 by codespace@codespaces-574135 using go1.19.1 linux/amd64
```

### Operating System and Environment details

```sh
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

Linux 5.4.0-1090

x86_64
```

### Log Fragments

```sh
N/A
```

### PR DESCRIPTION
**Pull request by systay**
## Description
When we have to do the sorting on the vtgate level, we were not correctly truncating the columns to match the number of columns the user asked for.

## Related Issue(s)
Fixes #11261

## Checklist

-   [x] "Backport me!" label has been added if this change should be backported
-   [x] Tests were added or are not required
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by harshit-gangal — APPROVED** [review]

**Review by arthurschreiber — APPROVED** [review]

File: go/test/endtoend/vtgate/queries/orderby/without_schematracker/main_test.go [hunk 1]
```diff
@@ -0,0 +1,95 @@
+/*
+Copyright 2021 The Vitess Authors.
```
Comment (frouioui) [inline go/test/endtoend/vtgate/queries/orderby/without_schematracker/main_test.go:2]: nit: 2022

File: go/test/endtoend/vtgate/queries/orderby/without_schematracker/main_test.go [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+			SchemaSQL: schemaSQL,
+			VSchema:   vschema,
+		}
+		clusterInstance.VtGateExtraArgs = []string{"--schema_change_signal=false"}
+		err = clusterInstance.StartKeyspace(*keyspace, []string{"-80", "80-"}, 1, true)
+		if err != nil {
+			return 1
+		}
+
+		clusterInstance.VtGateExtraArgs = append(clusterInstance.VtGateExtraArgs, "--enable_system_settings=true")
```
Comment (frouioui) [inline go/test/endtoend/vtgate/queries/orderby/without_schematracker/main_test.go:72]: I think we can remove the `--enable_system_settings=true` flag or merge both appends together

File: go/test/endtoend/vtgate/queries/orderby/without_schematracker/orderby_test.go [hunk 3]
```diff
@@ -0,0 +1,58 @@
+/*
+Copyright 2021 The Vitess Authors.
```
Comment (frouioui) [inline go/test/endtoend/vtgate/queries/orderby/without_schematracker/orderby_test.go:2]: nit: 2022 too

**Review by frouioui — APPROVED** [review]
LGTM
