### PR TITLE
healthcheck: attempt to update primary only if the current tablet is serving

### LINKED ISSUE #8120: Spurious warning from vtgate healthcheck
#### Overview of the Issue
When running PlannedReparentShard, vtgate logs show a confusing warning. At this point tablet 100 is no longer "SERVING", so there is no reason to even attempt to mark it as "Up".

#### Reproduction Steps
Run local example and `tail -f $VTDATAROOT/tmp/vtgate.out` 
```
$ ./101_initial_cluster.sh
...
$ vtctlclient PlannedReparentShard -keyspace_shard=commerce/0 -new_master=zone1-101
```
#### Binary version
```
Version: 11.0.0-SNAPSHOT (Git revision 125117e86d branch 'master') built on Thu May 13 15:16:07 PDT 2021
```
#### Operating system and Environment details
Ubuntu 18.04.5 LTS

#### Log Fragments
```
W0513 15:18:41.139387   16148 healthcheck.go:441] not marking healthy master zone1-0000000100 as Up for commerce/0 because its MasterTermStartTime is smaller than the highest known timestamp from previous MASTERs zone1-0000000101: 1620944271 < 1620944316 
```

### PR DESCRIPTION
**Pull request by deepthi**
## Description
Fixes #8120 

## Checklist
- [x] Tests were added or are not required 
- [x] Documentation was added or is not required

### CODE REVIEW

**Comment by deepthi** [comment]
Before logs:
```
I0513 16:12:29.116383   29038 tablet_health_check.go:111] HealthCheckUpdate(Serving State): tablet: zone1-102 serving false => true for commerce/0 (RDONLY) reason: healthCheck update
I0513 16:12:51.023130   29038 tablet_health_check.go:111] HealthCheckUpdate(Serving State): tablet: zone1-100 serving true => false for commerce/0 (MASTER) reason: healthCheck update
E0513 16:12:51.465923   29038 healthcheck.go:478] Adding 1 to MasterPromoted counter for target: keyspace:"commerce" shard:"0" tablet_type:REPLICA , tablet: zone1-0000000101, tabletType: MASTER
W0513 16:12:56.023628   29038 healthcheck.go:441] not marking healthy master zone1-0000000100 as Up for commerce/0 because its MasterTermStartTime is smaller than the highest known timestamp from previous MASTERs zone1-0000000101: 1620947548 < 1620947571 
I0513 16:13:01.480794   29038 tablet_health_check.go:111] HealthCheckUpdate(Serving State): tablet: zone1-100 serving false => true for commerce/0 (REPLICA) reason: healthCheck update
```
After logs:
```
I0513 15:59:34.332740   25307 tablet_health_check.go:111] HealthCheckUpdate(Serving State): tablet: zone1-102 serving false => true for commerce/0 (RDONLY) reason: healthCheck update
I0513 16:07:51.464763   25307 tablet_health_check.go:111] HealthCheckUpdate(Serving State): tablet: zone1-100 serving true => false for commerce/0 (MASTER) reason: healthCheck update
E0513 16:07:52.192940   25307 healthcheck.go:478] Adding 1 to MasterPromoted counter for target: keyspace:"commerce" shard:"0" tablet_type:REPLICA , tablet: zone1-0000000101, tabletType: MASTER
I0513 16:08:02.202323   25307 tablet_health_check.go:111] HealthCheckUpdate(Serving State): tablet: zone1-100 serving false => true for commerce/0 (REPLICA) reason: healthCheck update
```

File: go/vt/discovery/tablet_health_check.go [hunk 1]
```diff
@@ -200,7 +200,7 @@ func (thc *tabletHealthCheck) processResponse(hc *HealthCheckImpl, shr *query.St
 	thc.setServingState(serving, reason)
 
 	// notify downstream for master change
-	hc.updateHealth(thc.SimpleCopy(), prevTarget, trivialUpdate, true)
+	hc.updateHealth(thc.SimpleCopy(), prevTarget, trivialUpdate, thc.Serving)
```
Comment (narcsfz) [inline go/vt/discovery/tablet_health_check.go:203]: nit: `thc.Serving` should not be false in practice (?) might want to add a warning log here when we change master to a tablet that is still down.

**Review by narcsfz — APPROVED** [review]
lgtm

File: go/vt/discovery/tablet_health_check.go (hunk 1 above)
Comment (deepthi) [reply go/vt/discovery/tablet_health_check.go:203]: It can be true or false, and this gets called for all tablet types. It is just that we only do anything with that value if the tablet_type is MASTER.
The `healthy` list update code inside the call to `updateHealth` is pretty solid, I think. It handles the true/false cases correctly. It will never replace with a `down` master.
Does this address your concern?

Comment (narcsfz) [reply go/vt/discovery/tablet_health_check.go:203]: ah got it. so this code actually "incorrectly" always claim `isPrimaryUp=true` in health update
this looks good
