### PR TITLE
planbuilder: fix message inserts w/PassthroughDMLs

### LINKED ISSUE #4615: queryserver-config-passthrough-dmls breaks message inserts
When `queryserver-config-passthrough-dmls` is set, it returns the query plan before analyzing message inserts, which breaks message operations, since the message insert adds field default values for "hidden" message columns.

https://github.com/vitessio/vitess/blob/master/go/vt/vttablet/tabletserver/planbuilder/dml.go#L328-L347

### PR DESCRIPTION
**Pull request by derekperkins**
Fixes #4615

### CODE REVIEW

**Comment by derekperkins** [comment]
@demmer This seems like it keeps with the spirit of your original changes.

File: go/vt/vttablet/tabletserver/planbuilder/dml.go [hunk 1]
```diff
@@ -323,6 +323,12 @@ func analyzeInsert(ins *sqlparser.Insert, tables map[string]*schema.Table) (plan
 	}
 	table, tableErr := plan.setTable(tableName, tables)
 
+	// message inserts need to continue being strict, even in passthrough dml mode,
+	// because field defaults are set here
+	if tableErr == nil && table.Type == schema.Message {
```
Comment (sougou) [inline go/vt/vttablet/tabletserver/planbuilder/dml.go]: I think we should never return a default plan if table type is Message. So, we require the following changes:

If tableErr is not nil, it will end up returning the pass-through plan. This check should instead be:
```
if table.Type == schema.Message {
  if tableErr != nil {
    return nil, tableErr
  }
  return analizeInsertMessage(...)
}
```

The change also skips the `HasPrimary` check. There is a re-check in the `analyzeInsertMessage` for it (look for Dead code comment).

That should be changed to return an error instead.

We also need tests that demonstrate the new behavior. I can think of three cases:
1. Show that we error out if tableErr != nil even if PassthroughDMLs is true.
2. Show that plan is being built even if PassthroughDMLs is true.
3. Show that we generate an error if table has no PK.

Comment (sougou) [reply go/vt/vttablet/tabletserver/planbuilder/dml.go]: Actually, if tableErr != nil, then table.Type will never be set.
So, ignore my first suggestion.

That should also reduce the number of tests to two.

Comment (derekperkins) [reply go/vt/vttablet/tabletserver/planbuilder/dml.go]: I just refactored the logic so that #2 is the only new behavior. It's a much more readable change with fewer branching paths. Tests now included.
