### PR TITLE
Point in time recovery: fix cross-tablet GTID evaluation

### LINKED ISSUE #13517: Bug Report: incremental backup & restore: failure to take incremental backups in a multi tablet scenario
### Overview of the Issue

In a cluster with multiple `REPLICA`/`RDONLY` tablets, it's possible to create a situation where `vtctlclient -- Backup --incremental_from_pos=auto` fails to take the backup.

This gist of the scenario is if one of the tablets is restored from backup (which wipes out its binary logs, setting `gtid_purged`), takes incremental backup (runs fine), and then an attempt is made to take incremental backup on the _other_ tablet.

### Reproduction Steps

Use `examples/local`. Assume:

- `PRIMARY` tablet is `zone1-0000000101`
- `REPLICA` is `zone1-0000000100`
- `RDONLY` is `zone1-0000000102`

Run the following sequence. Note that the interleaved `ApplySchema` commands are there just to generate sufficient changelog in between the operations.

```
vtctlclient -- Backup zone1-0000000102
vtctldclient ApplySchema --ddl-strategy="vitess" --sql "alter table corder force" commerce && sleep 2
vtctlclient -- Backup --incremental_from_pos=auto zone1-0000000102
vtctldclient ApplySchema --ddl-strategy="vitess" --sql "alter table corder force" commerce && sleep 2
vtctldclient RestoreFromBackup zone1-0000000102
vtctldclient ApplySchema --ddl-strategy="vitess" --sql "alter table corder force" commerce && sleep 2
vtctlclient -- Backup --incremental_from_pos=auto zone1-0000000102
vtctldclient ApplySchema --ddl-strategy="vitess" --sql "alter table corder force" commerce && sleep 2
vtctlclient -- Backup --incremental_from_pos=auto zone1-0000000100
```

The last `--incremental_from_pos=auto zone1-0000000100` commands yields with something similar to:
```
I0717 07:47:43.728526 2090851 main.go:96] I0717 07:47:43.728145 backup.go:110] I0717 07:47:43.727878 builtinbackupengine.go:202] Executing Backup at 2023-07-17 07:47:43.727768003 +0000 UTC m=+217.129511829 for keyspace/shard commerce/0 on tablet zone1-0000000100, concurrency: 4, compress: true, incrementalFromPos: auto
I0717 07:47:43.741621 2090851 main.go:96] I0717 07:47:43.741426 backup.go:110] I0717 07:47:43.741189 builtinbackupengine.go:260] auto evaluating incremental_from_pos
I0717 07:47:43.742018 2090851 main.go:96] I0717 07:47:43.741901 backup.go:110] I0717 07:47:43.741720 builtinbackupengine.go:279] auto evaluated incremental_from_pos: MySQL56/b696e26a-2475-11ee-9d38-0a43f95f28a3:563-571
E0717 07:47:43.765510 2090851 main.go:96] E0717 07:47:43.765311 backup.go:110] E0717 07:47:43.765064 backup.go:163] backup is not usable, aborting it: [Code: FAILED_PRECONDITION
Mismatching GTID entries. Requested backup pos has entries not found in the binary logs, and binary logs have entries not found in the requested backup pos. Neither fully contains the other. Requested pos=b696e26a-2475-11ee-9d38-0a43f95f28a3:563-571, binlog pos=b696e26a-2475-11ee-9d38-0a43f95f28a3:1-269

cannot get binary logs to backup in incremental backup]
Backup Error: rpc error: code = Unknown desc = TabletManager.Backup on zone1-0000000100 error: cannot get binary logs to backup in incremental backup: Mismatching GTID entries. Requested backup pos has entries not found in the binary logs, and binary logs have entries not found in the requested backup pos. Neither fully contains the other. Requested pos=b696e26a-2475-11ee-9d38-0a43f95f28a3:563-571, binlog pos=b696e26a-2475-11ee-9d38-0a43f95f28a3:1-269: cannot get binary logs to backup in incremental backup: Mismatching GTID entries. Requested backup pos has entries not found in the binary logs, and binary logs have entries not found in the requested backup pos. Neither fully contains the other. Requested pos=b696e26a-2475-11ee-9d38-0a43f95f28a3:563-571, binlog pos=b696e26a-2475-11ee-9d38-0a43f95f28a3:1-269
E0717 07:47:43.790505 2090851 main.go:105] remote error: rpc error: code = Unknown desc = TabletManager.Backup on zone1-0000000100 error: cannot get binary logs to backup in incremental backup: Mismatching GTID entries. Requested backup pos has entries not found in the binary logs, and binary logs have entries not found in the requested backup pos. Neither fully contains the other. Requested pos=b696e26a-2475-11ee-9d38-0a43f95f28a3:563-571, binlog pos=b696e26a-2475-11ee-9d38-0a43f95f28a3:1-269: cannot get binary logs to backup in incremental backup: Mismatching GTID entries. Requested backup pos has entries not found in the binary logs, and binary logs have entries not found in the requested backup pos. Neither fully contains the other. Requested pos=b696e26a-2475-11ee-9d38-0a43f95f28a3:563-571, binlog pos=b696e26a-2475-11ee-9d38-0a43f95f28a3:1-269
```

The last successful incremental backup on `102` is:
```json
{
  "BackupMethod": "builtin",
  "Position": "MySQL56/b696e26a-2475-11ee-9d38-0a43f95f28a3:563-571",
  "PurgedPosition": "MySQL56/b696e26a-2475-11ee-9d38-0a43f95f28a3:1-562",
  "FromPosition": "MySQL56/b696e26a-2475-11ee-9d38-0a43f95f28a3:1-562",
  "Incremental": true,
  "BackupTime": "2023-07-17T07:47:43Z",
  "FinishedTime": "2023-07-17T07:47:43Z",
  "ServerUUID": "34bb1d4c-2476-11ee-85a9-0a43f95f28a3",
  "TabletAlias": "zone1-0000000102",
  "Keyspace": "commerce",
  "Shard": "0",
  "MySQLVersion": "/home/shlomi/opt/mysql/8.0.23/bin/mysqld  Ver 8.0.23 for Linux on x86_64 (Source distribution)\n",
  "UpgradeSafe": false,
  "CompressionEngine": "pargzip",
  "FileEntries": [
    {
      "Base": "BinLog",
      "Name": "vt-0000000102-bin.000001",
      "Hash": "4925e8df",
      "ParentPath": ""
    }
  ],
  "SkipCompress": false,
  "ExternalDecompressor": ""
}
```

The issue is we do not calculate `gtid_purged` correctly.

### Binary Version

```sh
v17, v18
```

### Operating System and Environment details

```sh
-
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by shlomi-noach**
## Description

This PR fixes https://github.com/vitessio/vitess/issues/13517, and the entire essense of the PR is built upon the addition of this single line of code in `go/vt/mysqlctl/binlogs_gtid.go`:

```go
	// The backup position is the GTISset of the last binary log (taken from Previous-GTIDs of the one-next binary log), and we
	// also include gtid_purged ; this complies with the "standard" way MySQL "thinks" about GTIDs: there's gtid_executed, which includes
	// everything that's ever been applied, and a subset of that is gtid_purged, which are the event no longer available in binary logs.
	// When we consider Vitess incremental backups, what's important for us is "what's the GTIDSet that's true when this backup was taken,
	// and which will be true when we restore this backup". The answer to this is the GTIDSet that includes the purged GTIDs.
	// It's also nice for icnremental backups that are taken on _other_ tablets, so that they don't need to understand what exactly was purged
	// on _this_ tablet. They don't care, all they want to know is "what GTIDSet can we get from this".
	incrementalBackupToPosition.GTIDSet = incrementalBackupToPosition.GTIDSet.Union(gtidPurged.GTIDSet)
```

The rest of the PR supports this change as follows:

1. Create an elaborate `endtoend` test that interleaves backups and restores on two different tablets, creating the scenario described in #13517 
2. To that effect, edit `backup_utils.go` to support backup/restore on two different tablets
3. Still on that same file, remove excessive code that assumes backups and tablets should be destroyed
4. Enriching `BackupManifest` with `FromName` field: in an incremental backup where position is `auto` calculated, this field indicated the name of the backup that was picked as the starting point for our incremental backup.
5. Some cleanup and niceties: e.g. in incremental backup, when searching for successful backups, skip our own partial backup handle which kinda exists but not really there yet -- which caused warning messages in the log.
6. Of course some more `unit` tests.

## Related Issue(s)

Fixes #13517
RFC: #11227 

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [ ] Documentation was added or is not required

### CODE REVIEW

**Comment by shlomi-noach** [comment]
Converting to draft as there's actually more to it.

**Comment by shlomi-noach** [comment]
Added a further tests sequence that validates incremental backups fail when binlog data is purged, but that the situation is salvaged once a full backup runs (and that this works cross-tablet).

File: go/vt/mysqlctl/backupengine.go [hunk 1]
```diff
@@ -399,9 +402,16 @@ func (p *RestorePath) String() string {
...
+func FindLatestSuccessfulBackup(ctx context.Context, logger logutil.Logger, bhs []backupstorage.BackupHandle, excludeBackupName string) (backupstorage.BackupHandle, *BackupManifest, error) {
 	for index := len(bhs) - 1; index >= 0; index-- {
 		bh := bhs[index]
+		if bh.Name() == excludeBackupName {
+			// skip this bh. Use case: in an incremental backup, as we look for previous successful backups,
+			// the new incremental backup handle is partial: the directory exists, it will show in ListBackups, but
+			// the MANIFEST file does nto exist yet. So we avoid the errors/warnings associated with reading this partial backup,
+			// and just skip it.
+			continue
+		}
```
Comment (shlomi-noach) [inline go/vt/mysqlctl/backupengine.go:414]: Not strictly related to the purpose of the PR, but during my experiments I noticed that the backup logs were noisy with warnings that shouldn't really be there. This is the mitigation.

File: go/vt/mysqlctl/mysqld.go [hunk 2]
```diff
@@ -1387,7 +1392,7 @@ func (mysqld *Mysqld) ReadBinlogFilesTimestamps(ctx context.Context, req *mysqlc
 			return matchedTime, false, err
 		}
 		go scan()
-		if err := mysqlbinlogCmd.Wait(); err != nil {
+		if err := mysqlbinlogCmd.Wait(); err != nil && !intentionalKill {
```
Comment (shlomi-noach) [inline go/vt/mysqlctl/mysqld.go:1395]: Again, not strictly part of the purpose of the PR, but I noticed a scenario where the backup process would hang. This mitigates the scenario.

File: go/vt/mysqlctl/binlogs_gtid.go [hunk 3]
```diff
@@ -94,13 +94,21 @@ func ChooseBinlogsForIncrementalBackup(
...
 		if i == 0 {
+			// Ummm... there _is no_ previous binary log.
 			return nil, "", "", vterrors.Errorf(vtrpc.Code_FAILED_PRECONDITION, "Required entries have been purged. Oldest binary log %v expects entries not found in backup pos. Expected pos=%v", binlog, previousGTIDsPos)
 		}
-		if !prevGTIDsUnion.Union(purgedGTIDSet).Contains(backupFromGTIDSet) {
+		// The other thing to validate, is that we can't allow a situation where the backup-GTIDs have entries not covered
+		// by our binary log's Previous-GTIDs (padded with purged GTIDs). Because that means we can't possibly restore to
+		// such position.
+		prevGTIDsUnionPurged := prevGTIDsUnion.Union(purgedGTIDSet)
+		if !prevGTIDsUnionPurged.Contains(backupFromGTIDSet) {
```
Comment (GuptaManan100) [inline go/vt/mysqlctl/binlogs_gtid.go:108]: I'm sorry if this is a stupid question, but I don't see what changed in the code. According to the description these line changes are the central change in the PR, but isn't the conditional check the same as before. Aren't we just storing the intermediate value in `prevGTIDsUnionPurged` to print later in the logs? There doesn't seem like there is any change to the logic?

**Review by GuptaManan100 — APPROVED** [review]

File: go/vt/mysqlctl/binlogs_gtid.go (hunk 3 above)
Comment (shlomi-noach) [reply go/vt/mysqlctl/binlogs_gtid.go:108]: You're absolutely right and I must have dozed off when writing the original comment. I quoted the wrong change. The relevant one liner change is:
```go
	// The backup position is the GTISset of the last binary log (taken from Previous-GTIDs of the one-next binary log), and we
	// also include gtid_purged ; this complies with the "standard" way MySQL "thinks" about GTIDs: there's gtid_executed, which includes
	// everything that's ever been applied, and a subset of that is gtid_purged, which are the event no longer available in binary logs.
	// When we consider Vitess incremental backups, what's important for us is "what's the GTIDSet that's true when this backup was taken,
	// and which will be true when we restore this backup". The answer to this is the GTIDSet that includes the purged GTIDs.
	// It's also nice for icnremental backups that are taken on _other_ tablets, so that they don't need to understand what exactly was purged
	// on _this_ tablet. They don't care, all they want to know is "what GTIDSet can we get from this".
	incrementalBackupToPosition.GTIDSet = incrementalBackupToPosition.GTIDSet.Union(gtidPurged.GTIDSet)
```

Comment (shlomi-noach) [reply go/vt/mysqlctl/binlogs_gtid.go:108]: Edited the original comment.

File: go/test/endtoend/backup/pitr/backup_pitr_test.go [hunk 4]
```diff
@@ -55,3 +55,13 @@ func TestIncrementalBackupAndRestoreToTimestamp(t *testing.T) {
 	}
 	backup.ExecTestIncrementalBackupAndRestoreToTimestamp(t, tcase)
 }
+
+// TestIncrementalBackupOnTwoTablets
+func TestIncrementalBackupOnTwoTablets(t *testing.T) {
```
Comment (frouioui) [inline go/test/endtoend/backup/pitr/backup_pitr_test.go:60]: nit: We should have a proper comment on top of the test function

File: go/test/endtoend/backup/vtctlbackup/pitr_test_framework.go [hunk 5]
```diff
@@ -425,3 +440,186 @@ func ExecTestIncrementalBackupAndRestoreToTimestamp(t *testing.T, tcase *PITRTes
 		})
 	})
 }
+
+// ExecTestIncrementalBackupAndRestoreToPos runs a series of interleaved backups on two different replicas: full and incremental.
+// Specifically, it's designed to test how incremental backups are taken by interleaved replicas, so that they successfully build on
+// one another.
+func ExecTestIncrementalBackupOnTwoTablets(t *testing.T, tcase *PITRTestCase) {
```
Comment (frouioui) [inline go/test/endtoend/backup/vtctlbackup/pitr_test_framework.go:447]: Comment and function name are not matching

**Review by frouioui — APPROVED** [review]

File: go/test/endtoend/backup/vtctlbackup/pitr_test_framework.go (hunk 5 above)
Comment (shlomi-noach) [reply go/test/endtoend/backup/vtctlbackup/pitr_test_framework.go]: fixed
