### PR TITLE
prevent vtctld from creating tons of S3 connections

### LINKED ISSUE #15335: Bug Report: vtctlds can create an excessive amount of connections when receiving concurrent GetBackups() calls
### Overview of the Issue

We run a backup check that calls GetBackups() on all shards and we always noticed some S3 connections errors and retries, but this has been getting more common and causing some issues as we expand the number of shards and we want the check to run more quickly. We execute up to 10x GetBackups() calls in parallel until we have gone across all shards.

We noticed the vtctld can have around 500 established connections to S3 during this time, which is a bit excessive. This seems to be because the connections are not reused in between calls and we are just opening more of them each time we get a new request.

### Reproduction Steps

With a vtctld in a cluster with a high number of shards (thousands), if you call `GetBackups()` for all of them with some concurrency, you will see a high number of connections to S3 (on port 443) by using system tools like `netstat` or `lsof`.

### Binary Version

```sh
Tested this on v14, but given how it hasn't change it should impact any newer versions.
```

### Operating System and Environment details

```sh
Ubuntu 22.04, Linux 6.2.0-1018-aws, x86_64
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by rvrangel**
## Description

This fixes the issue described in #15335. It seems the bug was introduced in #4200.

The default transport was changed in favour of one were we could skip validating S3 certificates, but instead of cloning the default transport and adjusting the settings, we are creating a new transport from scratch but not setting any defaults ([see current Go defaults for](https://cs.opensource.google/go/go/+/refs/tags/go1.22.0:src/net/http/transport.go;l=43-54) `DefaultTransport`). By doing so, we don't set keepalives, timeouts, max idle connections, etc and other values in `Transport` and since some default to zero it basically means "no limit". To make matters worse, since we are creating a new transport for every client (in this case, for each request from what I understand), there is no sharing of connections between different requests, so the first call to `GetBackups()` will open some S3 connections and keep them on its private transport instead of sharing it across different requests.

After this fix, the number of established connections seems to be consistently below 5, and from initial testing it seems S3 connection errors seem to be gone.

## Related Issue(s)

- fixes #15335

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/mysqlctl/s3backupstorage/s3.go [hunk 1]
```diff
@@ -496,6 +497,19 @@ func objName(parts ...string) *string {
...
+// transport on subsequent calls so connections can be reused as part of the same transport.
+func getS3Transport() *http.Transport {
+	if defaultS3Transport == nil {
+		tlsClientConf := &tls.Config{InsecureSkipVerify: tlsSkipVerifyCert}
+
+		defaultS3Transport = http.DefaultTransport.(*http.Transport).Clone()
+		defaultS3Transport.TLSClientConfig = tlsClientConf
+	}
+
+	return defaultS3Transport
```
Comment (dbussink) [inline go/vt/mysqlctl/s3backupstorage/s3.go:510]: Is this concurrency safe / does it need to be? Since it doesn't seem like it is. 

I'm also not a big fan of having a global for this, those tend to bite us later on. Can we move it at least into `S3BackupStorage` instead then? That's still kinda global, but at least a tad better then.

Comment (dbussink) [reply go/vt/mysqlctl/s3backupstorage/s3.go:510]: We can then also initialize it already in the `init()` to avoid the whole concurrency question / potential problem?

**Review by deepthi — COMMENTED** [review]
Good one.
Can you please take the description and split out the problem part of it into a new issue? How it is being fixed can be kept in the PR description.
We may want to backport this too.

File: go/vt/mysqlctl/s3backupstorage/s3.go (hunk 1 above)
Comment (rvrangel) [reply go/vt/mysqlctl/s3backupstorage/s3.go:510]: yes, it should be, specially considering the default on the SDK already uses `http.DefaultClient`, which in turn uses `http.DefaultTransport`, this would have been a shared default in most projects that don't define their transport/client from scratch, see the `Config` [docs](https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config).

I thought the `S3BackupStorage` would be created for each request being processed, but if that is not the case we could move it there. I will test it out and report back.

if the above is not possible and setting it up on `init()` is preferred I can do that too

**Comment by rvrangel** [comment]
thanks @deepthi , I created #15335 and mentioned it here in the PR description

File: go/vt/mysqlctl/s3backupstorage/s3.go (hunk 1 above)
Comment (deepthi) [reply go/vt/mysqlctl/s3backupstorage/s3.go:510]: I see that you added a unit test for this. What's the conclusion?
@dbussink time for a re-review?

File: go/vt/mysqlctl/s3backupstorage/s3.go [hunk 2]
```diff
@@ -496,6 +497,19 @@ func objName(parts ...string) *string {
 	return &res
 }
 
+// This creates a new transport based off http.DefaultTransport the first time and returns the same
+// transport on subsequent calls so connections can be reused as part of the same transport.
+func getS3Transport() *http.Transport {
+	if defaultS3Transport == nil {
+		tlsClientConf := &tls.Config{InsecureSkipVerify: tlsSkipVerifyCert}
+
+		defaultS3Transport = http.DefaultTransport.(*http.Transport).Clone()
```
Comment (mattlord) [inline go/vt/mysqlctl/s3backupstorage/s3.go:506]: This seems correct after reading through: https://github.com/golang/go/issues/26013

File: go/vt/mysqlctl/s3backupstorage/s3_test.go [hunk 3]
```diff
@@ -276,3 +276,16 @@ func TestSSECustomerFileBase64Key(t *testing.T) {
 	assert.Nil(t, sseData.customerKey, "customerKey expected to be nil")
 	assert.Nil(t, sseData.customerMd5, "customerMd5 expected to be nil")
 }
+
+func Test_getS3Transport(t *testing.T) {
```
Comment (mattlord) [inline go/vt/mysqlctl/s3backupstorage/s3_test.go:280]: Nit, but `TestGetS3Transport` would be the typical name in the code base.

File: go/vt/mysqlctl/s3backupstorage/s3.go (hunk 2 above)
Comment (mattlord) [reply go/vt/mysqlctl/s3backupstorage/s3.go:506]: I think that we should get rid of this getter and instead initialize the variable in `init()` though. This is a more clear signal of our intent and a more standard pattern. Does that make sense?

File: go/vt/mysqlctl/s3backupstorage/s3.go [hunk 4]
```diff
@@ -83,6 +83,9 @@ var (
 
 	// path component delimiter
 	delimiter = "/"
+
+	// use a shared transport for all connections
+	defaultS3Transport *http.Transport
```
Comment (mattlord) [inline go/vt/mysqlctl/s3backupstorage/s3.go:88]: Nit, but s3 is redundant here. We can just call it `defaultTransport` as s3 is the package.

**Review by mattlord — COMMENTED** [review]
Thanks, @rvrangel ! I only had a few small nits/suggestions. Please let me know what you think. I can come back quickly and review again and help to get it merged.

File: go/vt/mysqlctl/s3backupstorage/s3.go (hunk 1 above)
Comment (dbussink) [reply go/vt/mysqlctl/s3backupstorage/s3.go:510]: @deepthi I’m back next week but I don’t see a refactor of this or a reason why that couldn’t be done. I strongly prefer not having a global like this if that can reasonably be avoided. 

Also happy to push up that refactor once I’m back.

File: go/vt/mysqlctl/s3backupstorage/s3.go (hunk 2 above)
Comment (rvrangel) [reply go/vt/mysqlctl/s3backupstorage/s3.go:506]: yes, that makes sense. I will move it to the `init()` function. I will updated the PR tomorrow

File: go/vt/mysqlctl/s3backupstorage/s3.go (hunk 1 above)
Comment (rvrangel) [reply go/vt/mysqlctl/s3backupstorage/s3.go]: I have moved this to inside the `S3BackupStorage` and re-run our tests and seems the connections are getting re-used, so I have update the PR to reflect that, thanks for pointing it out!

File: go/vt/mysqlctl/s3backupstorage/s3_test.go (hunk 3 above)
Comment (rvrangel) [reply go/vt/mysqlctl/s3backupstorage/s3_test.go]: I updated it to `TestGetTransport` to avoid the redundancy

File: go/vt/mysqlctl/s3backupstorage/s3.go (hunk 4 above)
Comment (rvrangel) [reply go/vt/mysqlctl/s3backupstorage/s3.go]: got rid of the global variable 😌

File: go/vt/mysqlctl/s3backupstorage/s3.go [hunk 5]
```diff
@@ -427,6 +428,20 @@ func (bs *S3BackupStorage) WithParams(params backupstorage.Params) backupstorage
 	return &S3BackupStorage{params: params}
 }
 
+// This creates a new transport based off http.DefaultTransport the first time and returns the same
+// transport on subsequent calls so connections can be reused as part of the same transport.
+func (bs *S3BackupStorage) getTransport() *http.Transport {
+	if bs.transport == nil {
```
Comment (dbussink) [inline go/vt/mysqlctl/s3backupstorage/s3.go:434]: Same question as before though, does this get run concurrently? 

I think we can create the transport whenever we create the struct instead to avoid that?

Comment (rvrangel) [reply go/vt/mysqlctl/s3backupstorage/s3.go:434]: it is possible, considering that we will have multiple checks on different backups can happen at the same time. perhaps adding a mutex here would be better so it is always safe, regardless if it is set when we create the struct or when we first call this function, what do you think?

Comment (rvrangel) [reply go/vt/mysqlctl/s3backupstorage/s3.go:434]: actually, this is only called on `S3BackupStorage.client()` which acquires a mutex when it is running, so we shouldn't see this running concurrently

https://github.com/vitessio/vitess/blob/eff2a9276a9cc970e5835a33a505f31fc3d6012f/go/vt/mysqlctl/s3backupstorage/s3.go#L457-L463

Comment (dbussink) [reply go/vt/mysqlctl/s3backupstorage/s3.go:434]: @rvrangel i think we can then also move the initialization there too? No need to wrap it in another lazy loading function?

Comment (dbussink) [reply go/vt/mysqlctl/s3backupstorage/s3.go:434]: Sorry, that’s wrong. I mean where `bs` is initialized.

Comment (rvrangel) [reply go/vt/mysqlctl/s3backupstorage/s3.go:434]: yeah, we can do that if you prefer - originally I didn't to make it easier to have a unit test around this (and the existing `client()` function doesn't have a test, looks like it makes a call to S3 to validate it) and since we are not using a contructor function like `New()` to create this struct - everything gets done in this function - it is harder to mock the S3 client that makes an actual `HeadBucket()` call.

so my question is, would you be okay with moving this into `client()` without a unit test, or do you want to make this into a bigger PR where we can mock that call and change how `S3BackupStorage` gets created?

Comment (rvrangel) [reply go/vt/mysqlctl/s3backupstorage/s3.go:434]: there is also the consideration that we might have a single `S3BackupStorage` but we might call `S3BackupStorage.client()` for each request - which then will use a different transport for each client we initialise, while the current approach uses the same transport for all clients generated by the same `S3BackupStorage`

Comment (dbussink) [reply go/vt/mysqlctl/s3backupstorage/s3.go:434]: I think a small refactor with a (private) constructor and then testing transport is fine?

I don’t see how we create different transports though? We can then set directly `bs.transport`?

Comment (rvrangel) [reply go/vt/mysqlctl/s3backupstorage/s3.go:434]: taking a better look at the code, we do that initialisation under `init()` so it should be easy enough to update it with a `new()` method instead of the current line, so I will update it tomorrow:
https://github.com/vitessio/vitess/blob/eff2a9276a9cc970e5835a33a505f31fc3d6012f/go/vt/mysqlctl/s3backupstorage/s3.go#L512-L513

but if we set `bs.transport` directly, the problem is the functions in this struct were designed in a way to call `bs.client()` every time, like here:
https://github.com/vitessio/vitess/blob/eff2a9276a9cc970e5835a33a505f31fc3d6012f/go/vt/mysqlctl/s3backupstorage/s3.go#L292-L294

as an example take `S3BackupStorage.ListBackups()`, every time we call it, it will in turn call `S3BackupStorage.client()` which will set `bs.transport = ` again, making it a different transport each time. or unless you meant to lazy load it inside the `client()` function as we are doing in the current chage?

Comment (rvrangel) [reply go/vt/mysqlctl/s3backupstorage/s3.go]: @dbussink I have moved this to a private constructor as we talked, and instead of setting `bs.transport` inside `client()` it is now only set on the constructor - and I have removed the lazy loading, but that will cause issues if there is any place where we use `S3StorageBackup{}` without initialising the transport, but it doesn't seem like we do?

let me know if this looks good to you or if you want to add extra safety on the `client()` function

**Review by dbussink — APPROVED** [review]
I like how this is now much simpler imho.

**Comment by deepthi** [comment]
This is a really great contribution @rvrangel! Thank you.
