### PR TITLE
vtadmin: allow cluster IDs with underscores by sanitizing resolver scheme

### LINKED ISSUE #15721: Bug Report: gRPC custom name resolvers don't work with underscores
### Overview of the Issue

vtadmin-api fails to connect to vtgate & vtctld if there are underscores (`_`) in the cluster ID name. I think this is because gRPC doesn't handle custom name resolvers with `_`.

### Reproduction Steps

Modify `clustername` in vtadmin-up.sh to a name with underscores:
```
cluster_name="local_test"
```

vtadmin-api will fail to connect to vtgate and vtctld.

### Binary Version

```sh
vtadmin version Version: 17.0.0-SNAPSHOT (Git revision e5de85346b7ddcc6d0b69bcbab2dda4e5f661526 branch 'debug-image') built on Fri Apr 12 14:48:12 PDT 2024 by francesthai@localhost.local using go1.21.9 darwin/amd64

(also present on v18-v20)
```

### Operating System and Environment details

```sh
- Operating system: macOS 14.4.1 (23E224)
- Kernel version: Darwin 23.4.0
- Architecture: x86_64
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by gopoto**
## Description

vtadmin’s discovery resolver was treating the cluster ID as the URL scheme when dialing vtgate and vtctld, which breaks if the cluster ID contains characters that are not valid in a URI scheme (e.g. `_`). This manifested as vtadmin-api failing to connect to vtgate/vtctld when a cluster ID such as `local_test` was used.

This change introduces a small `sanitizeScheme` helper in the vtadmin cluster resolver to strip or replace invalid characters and ensure the scheme starts with a letter. The resolver now keeps the original cluster ID around for logging/debugging but advertises the sanitized scheme to gRPC. vtctldclient and vtsql continue to use the original cluster ID.

To exercise this path an end‐to‐end vtadmin test now overrides its cluster ID to `local_test`, and a unit test was added to verify `sanitizeScheme` behavior.

## Related Issue(s)

Fixes #15721

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [ ] Documentation was added or is not required

## Deployment Notes

No special deployment steps are required beyond rolling out an updated vtadmin-api. Existing clusters can now safely use IDs containing underscores.

---

This PR was generated by an AI system in collaboration with maintainers @rbranson, @GuptaManan100, @rohit-nayak-ps, @systay.

### CODE REVIEW

File: go/vt/vtadmin/cluster/resolver/resolver.go [hunk 1]
```diff
@@ -145,11 +154,48 @@ type Options struct {
...
+		clusterID: clusterID,
+		opts:      *opts,
+	}
+}
+
+// sanitizeScheme returns a string derived from the input that is safe to use
+// as a URL scheme per RFC 3986: ALPHA *( ALPHA / DIGIT / "+" / "-" / "." ).
+// Any runes outside of this set are replaced with '-' characters. If the first
+// character is not a letter, we prefix it with 'x' to make a valid scheme.
+func sanitizeScheme(id string) string {
```
Comment (rohit-nayak-ps) [inline go/vt/vtadmin/cluster/resolver/resolver.go:176]: We could probably write this more succinctly as:
```
func sanitizeScheme(id string) string {
	if id == "" {
		return "vtadmin"
	}
	// Map runes: letters, digits, '+', '-', '.' are kept; others become '-'
	s := strings.Map(func(r rune) rune {
		if unicode.IsLetter(r) || unicode.IsDigit(r) || r == '+' || r == '-' || r == '.' {
			return r
		}
		return '-'
	}, id)

	// Ensure the scheme starts with a letter.
	if s == "" || !unicode.IsLetter(rune(s[0])) {
		s = "x" + s
	}
	return s
}
```

**Review by rohit-nayak-ps — APPROVED** [review]
Suggested minor improvements. Otherwise looks good.

File: go/vt/vtadmin/cluster/resolver/resolver.go (hunk 1 above)
Comment (gopoto) [reply go/vt/vtadmin/cluster/resolver/resolver.go:177]: Makes sense—switched to using `strings.Map` and `unicode.IsLetter/IsDigit` to trim down the `sanitizeScheme` logic as you suggested.

File: go/test/endtoend/cluster/vtadmin_process.go [hunk 2]
```diff
@@ -103,7 +106,20 @@ func (vp *VtAdminProcess) Setup() (err error) {
...
 		"--rbac",
 		"--rbac-config", rbacFile,
-		"--cluster", fmt.Sprintf(`id=local,name=local,discovery=staticfile,discovery-staticfile-path=%s,tablet-fqdn-tmpl=http://{{ .Tablet.Hostname }}:15{{ .Tablet.Alias.Uid }},schema-cache-default-expiration=1m`, discoveryFile),
+		"--cluster", fmt.Sprintf(`id=%s,name=%s,discovery=staticfile,discovery-staticfile-path=%s,tablet-fqdn-tmpl=http://{{ .Tablet.Hostname }}:15{{ .Tablet.Alias.Uid }},schema-cache-default-expiration=1m`,
+			func() string {
+				if vp.ClusterID != "" {
+					return vp.ClusterID
+				}
+				return "local"
+			}(),
```
Comment (GuptaManan100) [inline go/test/endtoend/cluster/vtadmin_process.go:115]: This function definition is repeated twice. It can be extracted out into a local function declaration, and then reused for both.

**Review by GuptaManan100 — APPROVED** [review]
Rest LGTM

File: go/vt/vtadmin/cluster/resolver/resolver.go (hunk 1 above)
Comment (gopoto) [reply go/vt/vtadmin/cluster/resolver/resolver.go:177]: Updated sanitizeScheme in the last round to use strings.Map and unicode helpers, which matches your suggestion.

File: go/test/endtoend/cluster/vtadmin_process.go (hunk 2 above)
Comment (gopoto) [reply go/test/endtoend/cluster/vtadmin_process.go]: Good catch; refactored the duplicated anonymous functions into a single clusterID variable in Setup.

**Review by GuptaManan100 — APPROVED** [review]
