### PR TITLE
Enforce rollback for each connection when shutdown occurs

### LINKED ISSUE #5553: VTGate does not rollback in-flight transactions when shut down
We experience a bunch of 

```
vttablet: rpc error: code = ResourceExhausted desc = transaction pool connection limit exceeded
```

errors each time we deploy VTGate. After [discussing this problem in Slack](https://vitess.slack.com/archives/C0PQY0PTK/p1575988316498700) @sougou [noted](https://vitess.slack.com/archives/C0PQY0PTK/p1576082927016000?thread_ts=1575988316.498700&cid=C0PQY0PTK) that VTGate does not rollback in-flight transactions on [shut down](
https://github.com/vitessio/vitess/blob/253b9ea692064c4e2c54b41dc9a89d557b85b05c/go/vt/vtgate/plugin_mysql_server.go#L413)

To avoid leaving transactions unfinished in the tablet where they would linger until the transactions timeout, we probably want them to rollback once the lame duck period has expired? 

/cc @drogart and @tomkrouper
/cc @dweitzman who might also be interested in this issue

### PR DESCRIPTION
**Pull request by saifalharthi**
This fixes #5553

### CODE REVIEW

File: go/vt/vtgate/plugin_mysql_server.go [hunk 1]
```diff
@@ -436,9 +452,17 @@ func shutdownMysqlProtocolAndDrain() {
 	}
 }
 
+func rollbackAtShutdown() {
```
Comment (sougou) [inline go/vt/vtgate/plugin_mysql_server.go]: Need to hold mutex here, because you're accessing `connections`. However, you'll run into a deadlock because `ConnectionClosed` also obtains the mutex. 

I recommend implementing a `CloseAllConnections` instead of `ConnectionClosed`, that obtains the mutex and closes all conections in a loop.

And then, you can change `servenv.OnClose(rollbackAtShutdown)` -> `servenv.OnClose(vtgateHandler.CloseAllConnections)`
