### PR TITLE
Healthcheck - limit healthchecks by keyspace

### LINKED ISSUE #5387: keyspaces_to_watch does not limit vtgate->tablet health checks
### Summary
VTgates support a `keyspaces_to_watch` flag which exists to provide data isolation. Once of the side effects of this is that it shouldn't need to maintain a healthcheck to tablets that exist in a keyspace it can't reach.

### Reproduction Steps

1. Run a vtgate passing `--keyspaces_to_watch`
2. view vtgate logs and observe that there are healthchecks ongoing for keyspaces not listed in the arg above

### PR DESCRIPTION
**Pull request by spark4**
### Overview
Currently, vtgates support a `keyspaces_to_watch` flag which can enable data isolation by keyspace. However, vtgates still perform healthchecks against all tablets regardless of the value provided to this flag.  

This PR introduces changes to healthchecks such that when the `keyspaces_to_watch` flag is utilized, vtgates will only maintain healthchecks on tablets in keyspaces that the vtgate has access to. 

--
This closes #5387.
Relevant PR: https://github.com/vitessio/vitess/pull/4420

### Implementation
1. Introduce a new TabletRecorder filter, `FilterByKeyspace`, which will only add tablets from keyspaces that the vtgate has access to
2. Update the discovery gateway to use this filter when values for `keyspaces_to_watch` is passed in

### Testing
In addition to unit testing, I performed the following manual tests:
- Confirmed that vtgates that use the `keyspaces_to_watch` flag were only performing healthchecks on tablets from the desired keyspace
- Confirmed that vtgates that do _not_ use the `keyspaces_to_watch` flag performed health checks on the expected tablets
- Confirmed on a vtctld that various keyspace commands continue to work as expected
- Confirmed that backups continue to work as expected

### CODE REVIEW

File: go/vt/discovery/topology_watcher.go [hunk 1]
```diff
@@ -437,3 +437,54 @@ func (fbs *FilterByShard) isIncluded(tablet *topodatapb.Tablet) bool {
 	}
 	return false
 }
+
+// FilterByKeyspace is a TabletRecorder filter that filters tablets by
+// keyspace
+type FilterByKeyspace struct {
+	tr TabletRecorder
+
+	keyspaces map[string]bool
```
Comment (rafael) [inline go/vt/discovery/topology_watcher.go]: nit - wondering if we should call this selectKeyspaces to keep it consistent with the naming in:  https://github.com/vitessio/vitess/pull/4420/files

File: go/vt/discovery/topology_watcher.go [hunk 2]
```diff
@@ -437,3 +437,54 @@ func (fbs *FilterByShard) isIncluded(tablet *topodatapb.Tablet) bool {
...
+// RemoveTablet is part of the TabletRecorder interface.
+func (fbk *FilterByKeyspace) RemoveTablet(tablet *topodatapb.Tablet) {
+	if fbk.isIncluded(tablet) {
+		fbk.tr.RemoveTablet(tablet)
+	}
+}
+
+// ReplaceTablet is part of the TabletRecorder interface.
+func (fbk *FilterByKeyspace) ReplaceTablet(old, new *topodatapb.Tablet, name string) {
+	if fbk.isIncluded(old) && fbk.isIncluded(new) {
```
Comment (rafael) [inline go/vt/discovery/topology_watcher.go]: The check for: ```fbk.isIncluded(new)``` might be redundant. A tablet shouldn't be able to change keyspaces. So if it was included in the old it should be included in new.

File: go/vt/discovery/topology_watcher_test.go [hunk 3]
```diff
@@ -410,3 +410,32 @@ func TestFilterByShard(t *testing.T) {
...
+	{"ks3", false},
+	{"ks4", true},
+	{"ks5", true},
+	{"ks6", false},
+	{"ks7", false},
+}
+
+func TestFilterByKeyspace(t *testing.T) {
+	selectedKeyspaces := []string{"ks1", "ks2", "ks4", "ks5"}
+	fbk := NewFilterByKeyspace(nil, selectedKeyspaces)
```
Comment (rafael) [inline go/vt/discovery/topology_watcher_test.go]: For completeness and If there is a tablet recorder for unit tests, I think it will be good to use it here. Then you can add tests for `AddTablet`, `RemoveTablet` and `ReplaceTablet` and add assertion for those as well.

File: go/vt/discovery/topology_watcher.go (hunk 2 above)
Comment (deepthi) [reply go/vt/discovery/topology_watcher.go]: In that case, maybe we should check for those failure conditions - `isIncluded(new) && !isIncluded(old)` and the reverse - and return a `FAILED_PRECONDITION` error.

**Comment by deepthi** [comment]
Nicely written PR description!
Can you clarify the following?

> * Confirmed that vtgates that use the `keyspaces_to_watch` flag were only performing healthchecks on tablets from the desired keyspace.
> * Confirmed that vtgates that do use the `keyspaces_to_watch` flag performed health checks on the expected tablets.

These two look similar. Maybe the second case was for vtgates that *don't* use the `keyspaces_to_watch` flag?

**Comment by spark4** [comment]
Hey @deepthi - good catch. Yes, the second one was meant to say do *not* use. I will update the PR description now!

File: go/vt/discovery/topology_watcher.go (hunk 1 above)
Comment (spark4) [reply go/vt/discovery/topology_watcher.go]: Ah! I was following the below naming convention for the other TabletRecorder filter in the file here: https://github.com/vitessio/vitess/blob/master/go/vt/discovery/topology_watcher.go#L361

I am happy to change it though, if you prefer to stay consistent with the naming conventions for the filtering server.

File: go/vt/discovery/topology_watcher.go (hunk 2 above)
Comment (spark4) [reply go/vt/discovery/topology_watcher.go]: > if it was included in the old it should be included in new.

☝️ I'm probably missing some important context here -- can you expand more about what you mean here? My understanding is that given that tablets can't change keyspaces, the `fbk.isIncluded(old)` is the unnecessary check here (as opposed to `fbk.isIncluded(new)`).

File: go/vt/discovery/topology_watcher_test.go (hunk 3 above)
Comment (spark4) [reply go/vt/discovery/topology_watcher_test.go]: Good idea - let me see what I can whip up here.

File: go/vt/discovery/topology_watcher.go (hunk 2 above)
Comment (spark4) [reply go/vt/discovery/topology_watcher.go]: Looks like I posted the above comment on a non-refreshed page - just now seeing @deepthi's comment.

@deepthi it looks like the callers of `ReplaceTablet` do not have mechanisms for handling these types of errors. Do we know what the expected behavior for FAILED_PRECONDITION errors during tablet replacement is?

Given the low likelihood of us hitting this case, would logging be sufficient here?

Comment (deepthi) [reply go/vt/discovery/topology_watcher.go]: Oh I see.. the interface won't let you return an error.
Yes, logging it would be fine.
