### PR TITLE
Fix a number of encoding issues when evaluating expressions with the evalengine

### LINKED ISSUE #13493: Bug Report: Expression evaluated in EvalEngine lacks encoding information on result
### Overview of the Issue

When a query is executed that can be directly evaluated by the `evalengine` without having to go to a `vttablet` instance, we lack encoding information in the result. The result is also not transcoded to the proper connection character set / collation either. 

### Reproduction Steps

Run the following query against Vitess, see also the separate `--column-type-info` flag to show the returned type information (including the collation).

#### Vitess

```
mysql -u root --socket=/tmp/mysql.sock --column-type-info

mysql> select 'test';
Field   1:  `:vtg1 /* VARCHAR */`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  ? (0)
Length:     0
Max_length: 4
Decimals:   0
Flags:      


+---------------------+
| :vtg1 /* VARCHAR */ |
+---------------------+
| test                |
+---------------------+
1 row in set (0.00 sec)
```

What can be seen here, is that the `Collation` information is lacking. When running this against MySQL:

#### MySQL

```
mysql> select 'test';
Field   1:  `test`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_0900_ai_ci (255)
Length:     16
Max_length: 4
Decimals:   31
Flags:      NOT_NULL 


+------+
| test |
+------+
| test |
+------+
1 row in set (0.00 sec)
```

Here it can be seen that the collation is properly set with `utf8mb4_0900_ai_ci`. This bug can break clients that depend on the collation information to determine if things are internally a UTF8 string or binary data.

This bug though hides another underlying bug. It's not just the collation that is not set, it's also not transcoding to that client collation. Take a look at the following example in MySQL:

#### MySQL

```
mysql> select _latin1 0xff, collation(_latin1 0xff);
Field   1:  `_latin1 0xff`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_0900_ai_ci (255)
Length:     4
Max_length: 2
Decimals:   31
Flags:      NOT_NULL 

Field   2:  `collation(_latin1 0xff)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  utf8mb4_0900_ai_ci (255)
Length:     256
Max_length: 17
Decimals:   31
Flags:      


+--------------+-------------------------+
| _latin1 0xff | collation(_latin1 0xff) |
+--------------+-------------------------+
| ÿ            | latin1_swedish_ci       |
+--------------+-------------------------+
1 row in set (0.00 sec)
```

What can be seen here, is that even though the expression `_latin1 0xff` has a collation of `latin1_swedish_ci`, it is translated to `utf8mb4_0900_ai_ci` as that is the connection collation. So the output here is a UTF-8 character of `ÿ` (which is encoded in `latin1` the value `255`). 

When running this against Vitess:

#### Vitess

```
mysql> select _latin1 0xff, collation(_latin1 0xff);
Field   1:  `_latin1 :vtg1 /* HEXNUM */`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  ? (0)
Length:     0
Max_length: 4
Decimals:   0
Flags:      

Field   2:  `collation(_latin1 :vtg1 /* HEXNUM */)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       VAR_STRING
Collation:  ? (0)
Length:     0
Max_length: 17
Decimals:   0
Flags:      


+----------------------------+---------------------------------------+
| _latin1 :vtg1 /* HEXNUM */ | collation(_latin1 :vtg1 /* HEXNUM */) |
+----------------------------+---------------------------------------+
| 0xff                       | latin1_swedish_ci                     |
+----------------------------+---------------------------------------+
1 row in set (0.00 sec)
```

Here you can see that while Vitess knows the correct collation of the expression, it doesn't actually transcode the value when returning it. It also doesn't show the collation information for the expression. So there's another deeper bug that we don't do this transcoding for results.

### Binary Version

```sh
All known Vitess versions
```

### Operating System and Environment details

```sh
-
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by dbussink**
As described in #13493 we have various bugs where we transcode inputs incorrectly and where we lack collation information in the results returned.

The changes here fix a number of things:

- Ensure that we always return collation information for `querypb.Field` instances. This also updates a lot of the static mocked inputs to ensure that they match what real queries would return. Many of the changes associated with this part of the fixes is ensuring the mocks are expectations are updated properly.
- Introduce an IntroduceExpr in the evalengine. One of the issues identified is that we didn't correctly handle hex escaped values and we would never see them being unescaped if a charset introducer was used. The cause of this is that we directly would change the collation information on the expression. This is wrong in the case of a HexNum or HexVal, since we loose information we need to transcode those. We could work around this for the AST evaluator, but the compiler couldn't be fixed as the real underlying value was not available with the actual hex encoded value. By introducing a new expression, we can also now properly compile this.
- No flags information was sent along with evaluated results. This is similar to the collation information, although usually not as important for clients. We opted here to fix this nonetheless and match MySQL as closely as possible.
- Introduce a `collations.SystemCollation` to use consistently for all internal table / column names information. It was using mostly the constant for utf8mb3 or no information at all which would be problematic as it means we woulnd't know what encoding it was.
- Convert outputs to the connection collation / charset. This was entirely missing from Vitess but is behavior that MySQL has. If you read from say a `latin1` encoded column with a connection charset of `utf8mb4`, the value is converted before it's sent over the wire to `utf8mb4`. This fix also applies for the `evalengine` tests where we can now test also non UTF-8 compatible encodings, fixing a bunch of todos. This uncovered some other small bugs in the `evalengine` where we were converting things wrong.
- The rowstreamer would return collation information from the result set, but that is now wrong because of the above conversion fixes. This means we need to use the actual fields information which we already have available to see the proper collation. We can copy all the attributes for the PK column.
- To be explicit, it includes a rename from `collations.CollationUtf8ID` to `collations.CollationUtf8mb3ID` to be explicit about this collation name and match how MySQL is also changing this to be explicit.
- Refactor all cases of `NewBindVar` and `NewColumn` to require explicitly the type and collation information. This way we are explicit also at the call site with what information we have and we always initialize it correctly, also if we don't know the information.
- Pass through additional type information in the `planbuilder`. This ensures we now know the proper type for more cases, avoiding the need for `weight_string` and it allows for better printing of collation debug information or not.

## Related Issue(s)

Fixes #13493

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/mysql/binlog/binlog_json_test.go [hunk 1]
```diff
@@ -450,12 +450,12 @@ func TestMarshalJSONToSQL(t *testing.T) {
...
 			name:     `opaque string [2 202 254]`,
 			data:     []byte{15, 15, 2, 202, 254},
-			expected: `CAST(x'02cafe' as JSON)`,
+			expected: `CAST(x'02CAFE' as JSON)`,
 		},
 		{
 			name:     `opaque blob [2 202 254]`,
 			data:     []byte{15, 252, 2, 202, 254},
-			expected: `CAST(x'02cafe' as JSON)`,
+			expected: `CAST(x'02CAFE' as JSON)`,
```
Comment (dbussink) [inline go/mysql/binlog/binlog_json_test.go:458]: We're now consistent with MySQL which upcases by default for hex literals.

File: go/mysql/hex/hex.go [hunk 2]
```diff
@@ -0,0 +1,64 @@
+package hex
```
Comment (systay) [inline go/mysql/hex/hex.go:1]: license header missing

File: go/mysql/collations/env.go [hunk 3]
```diff
@@ -194,7 +194,7 @@ func makeEnv(version collver) *Environment {
 // A few interesting character set values.
 // See http://dev.mysql.com/doc/internals/en/character-set.html#packet-Protocol::CharacterSet
 const (
-	CollationUtf8ID        = 33
+	CollationUtf8mb3ID     = 33
```
Comment (dbussink) [inline go/mysql/collations/env.go:197]: As mentioned, rename for explicitness.

File: go/test/endtoend/vtgate/queries/orderby/without_schematracker/orderby_test.go [hunk 4]
```diff
@@ -54,5 +54,5 @@ func TestSimpleOrderBy(t *testing.T) {
 
 	mcmp.Exec("insert into user(id, name) values (0,'Apa'),(1,'Banan'),(3,'Ceasar'),(4,'David')")
 	mcmp.AssertMatches(`SELECT name FROM user WHERE id in (0,4) ORDER BY name ASC`,
-		`[[VARCHAR("Apa")] [VARCHAR("David)]]`)
+		`[[VARCHAR("Apa")] [VARCHAR("David")]]`)
```
Comment (dbussink) [inline go/test/endtoend/vtgate/queries/orderby/without_schematracker/orderby_test.go:57]: This was a test we probably are not running? Not sure how this could have been passing at all. Failed when running locally.

File: go/vt/sqlparser/normalizer.go [hunk 5]
```diff
@@ -352,24 +353,31 @@ func SQLToBindvar(node SQLNode) *querypb.BindVariable {
...
-			v, err = sqltypes.NewValue(sqltypes.HexNum, node.Bytes())
+			buf := make([]byte, 0, len(node.Bytes()))
+			buf = append(buf, "0x"...)
+			buf = append(buf, bytes.ToUpper(node.Bytes()[2:])...)
+			v, err = sqltypes.NewValue(sqltypes.HexNum, buf)
 		case HexVal:
 			// We parse the `x'7b7d'` string literal into a hex encoded string of `7b7d` in the parser
 			// We need to re-encode it back to the original MySQL query format before passing it on as a bindvar value to MySQL
-			var vbytes []byte
-			vbytes, err = node.encodeHexOrBitValToMySQLQueryFormat()
```
Comment (dbussink) [inline go/vt/sqlparser/normalizer.go:360]: Replaced and removed this function with a much simpler approach without a regex.

File: go/vt/vtexplain/testdata/multi-output/selectsharded-output.txt [hunk 6]
```diff
@@ -137,10 +137,10 @@ select name from user where exists (select id from t1) /* non-correlated subquer
...
 select * from name_info order by info /* select * and order by varchar column */
 
-1 ks_sharded/-40: select `name`, info, weight_string(info) from name_info order by info asc limit 10001 /* select * and order by varchar column */
-1 ks_sharded/40-80: select `name`, info, weight_string(info) from name_info order by info asc limit 10001 /* select * and order by varchar column */
-1 ks_sharded/80-c0: select `name`, info, weight_string(info) from name_info order by info asc limit 10001 /* select * and order by varchar column */
-1 ks_sharded/c0-: select `name`, info, weight_string(info) from name_info order by info asc limit 10001 /* select * and order by varchar column */
+1 ks_sharded/-40: select `name`, info from name_info order by info asc limit 10001 /* select * and order by varchar column */
+1 ks_sharded/40-80: select `name`, info from name_info order by info asc limit 10001 /* select * and order by varchar column */
+1 ks_sharded/80-c0: select `name`, info from name_info order by info asc limit 10001 /* select * and order by varchar column */
+1 ks_sharded/c0-: select `name`, info from name_info order by info asc limit 10001 /* select * and order by varchar column */
```
Comment (dbussink) [inline go/vt/vtexplain/testdata/multi-output/selectsharded-output.txt:143]: No need for `weight_string` anymore here!

File: go/vt/vtgate/engine/fake_vcursor_test.go [hunk 7]
```diff
@@ -104,7 +104,7 @@ func (t *noopVCursor) SetContextWithValue(key, value interface{}) func() {
 
 // ConnCollation implements VCursor
 func (t *noopVCursor) ConnCollation() collations.ID {
-	return collations.CollationUtf8mb4ID
+	return collations.Default()
```
Comment (dbussink) [inline go/vt/vtgate/engine/fake_vcursor_test.go:107]: To be consistent with what we use in non-test code.

File: go/vt/vtgate/planbuilder/expression_converter.go [hunk 8]
```diff
@@ -63,8 +63,7 @@ func booleanValues(astExpr sqlparser.Expr) evalengine.Expr {
 func identifierAsStringValue(astExpr sqlparser.Expr) evalengine.Expr {
 	colName, isColName := astExpr.(*sqlparser.ColName)
 	if isColName {
-		// TODO@collations: proper collation for column name
```
Comment (dbussink) [inline go/vt/vtgate/planbuilder/expression_converter.go:66]: Yay, a fixed `TODO`!

File: go/vt/vtgate/semantics/semantic_state.go [hunk 9]
```diff
@@ -263,15 +263,6 @@ func (st *SemTable) TypeForExpr(e sqlparser.Expr) (sqltypes.Type, collations.ID,
...
 
-// CollationForExpr returns the collation name of expressions in the query
-func (st *SemTable) CollationForExpr(e sqlparser.Expr) collations.ID {
-	typ, found := st.ExprTypes[e]
-	if found {
-		return typ.Collation
-	}
-	return collations.Unknown
-}
-
```
Comment (dbussink) [inline go/vt/vtgate/semantics/semantic_state.go:274]: Everything now uses `TypeForExpr` since we always want both type and collation.

File: go/test/endtoend/vtgate/queries/orderby/without_schematracker/orderby_test.go (hunk 4 above)
[the remark this answers is not in the document]
Comment (harshit-gangal) [reply go/test/endtoend/vtgate/queries/orderby/without_schematracker/orderby_test.go:57]: may be it not part of the CI run. should check in config.json

[the remark this answers is not in the document]
Comment (shlomi-noach) [reply go/test/endtoend/vtgate/queries/orderby/without_schematracker/orderby_test.go:57]: Looks to me like it's not running. In `test/config.json` we do run:
```json
		"vtgate_queries_orderby": {
			"File": "unused.go",
			"Args": ["vitess.io/vitess/go/test/endtoend/vtgate/queries/orderby", "-timeout", "20m"],
			"Command": [],
			"Manual": false,
			"Shard": "vtgate_queries",
			"RetryMax": 2,
			"Tags": ["upgrade_downgrade_query_serving_queries"]
		},
```
but we do not run "vitess.io/vitess/go/test/endtoend/vtgate/queries/orderby/without_schematracker", which is a different path.

**Review by shlomi-noach — COMMENTED** [review]
This is out of my comfort zone. Overall looks good to me with all the tests. Added a few comments, but then at some point blanked out and did not complete the full change review.

File: go/vt/vtgate/engine/delete_test.go [hunk 10]
```diff
@@ -121,7 +122,7 @@ func TestDeleteEqualMultiCol(t *testing.T) {
 	})
 
 	// Failure case
-	expr := evalengine.NewBindVar("aa")
+	expr := evalengine.NewBindVar("aa", -1, collations.CollationBinaryID)
```
[the remark this answers is not in the document]
Comment (dbussink) [reply go/vt/vtgate/engine/delete_test.go:125]: I don't think we should have helpers for this, I think we should explicitly write out that we have missing type information in these cases explicitly. Having a helper kinda hides that and the way the code was structured before allowed creating objects that didn't have all things set. That was a significant contributing factor in what caused this bug in the first place. So hence me opting for being explicit and verbose everywhere.

File: go/vt/vtgate/engine/distinct_test.go [hunk 11]
```diff
@@ -133,6 +134,7 @@ func TestWeightStringFallBack(t *testing.T) {
 	checkCols := []CheckCol{{
 		Col:       0,
 		WsCol:     &offsetOne,
+		Type:      -1,
```
[the remark this answers is not in the document]
Comment (dbussink) [reply go/vt/vtgate/engine/distinct_test.go:137]: Yeah, `-1` means here "type unknown" as `0` already stands for `0` (and these constants are afaik compatible at the wire / bit level with MySQL so we can't change the meaning to `0` meaning `unknown`. I can add one for this and replace the occurrences we have.

File: go/vt/vtexplain/testdata/multi-output/selectsharded-output.txt (hunk 6 above)
Comment (dbussink) [reply go/vt/vtexplain/testdata/multi-output/selectsharded-output.txt:143]: Because we now pass through the correct type information in more cases. This means we don't need to query for the weight string anymore since we know the collation of the results here. Before we missed that information and vtgate could not sort things correctly and therefore asked for the weight string.

File: go/vt/vtgate/engine/distinct_test.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (dbussink) [reply go/vt/vtgate/engine/distinct_test.go:137]: Added a constant!

File: go/vt/vtgate/planbuilder/operator_transformers.go [hunk 12]
```diff
@@ -177,12 +180,11 @@ func transformProjection(ctx *plancontext.PlanningContext, op *operators.Project
 		case operators.Eval:
 			return e.EExpr
 		case operators.Offset:
-			t := ctx.SemTable.ExprTypes[e.Expr]
-			return &evalengine.Column{
-				Offset:    e.Offset,
-				Type:      t.Type,
-				Collation: collations.TypedCollation{},
+			t, found := ctx.SemTable.ExprTypes[e.Expr]
```
Comment (systay) [inline go/vt/vtgate/planbuilder/operator_transformers.go:183]: hmm... shouldn't we use `ctx.SemTable.TypeForExpr` here? I know the old code wasn't doing it, but I don't see why we should touch the internals in this case

File: go/vt/vtgate/planbuilder/testdata/info_schema57_cases.json [hunk 13]
```diff
@@ -191,29 +191,28 @@
...
-          "12: binary",
-          "13: binary",
-          "(14:27)",
-          "(15:28)",
-          "(16:29)",
-          "(17:30)",
-          "18: binary",
-          "(19:31)",
-          "(20:32)"
+          "0: utf8mb4_0900_ai_ci",
```
Comment (systay) [inline go/vt/vtgate/planbuilder/testdata/info_schema57_cases.json:194]: this is how happy this makes me
very happy

**Review by systay — APPROVED** [review]
Very nice! A significant step forward for our runtime ❤️

File: go/vt/vtgate/planbuilder/operator_transformers.go (hunk 12 above)
Comment (dbussink) [reply go/vt/vtgate/planbuilder/operator_transformers.go]: Agreed, cleaned this up!

File: go/vt/vtgate/evalengine/compiler_test.go [hunk 14]
```diff
@@ -448,6 +448,22 @@ func TestCompilerSingle(t *testing.T) {
...
+			expression: `_latin1 0xFF`,
+			result:     `VARCHAR("ÿ")`,
+		},
+		{
+			expression: `TRIM(_latin1 0xA078A0 FROM _utf8mb4 0xC2A078C2A0)`,
+			result:     `VARCHAR("")`,
+		},
+		{
+			expression: `CONCAT_WS("😊😂🤢", date '2000-01-01', _latin1 0xFF)`,
+			result:     `VARCHAR("2000-01-01😊😂🤢ÿ")`,
```
Comment (frouioui) [inline go/vt/vtgate/evalengine/compiler_test.go:461]: haha

**Comment by harshit-gangal** [comment]
Here the test TestSelectScatterOrderByVarChar does not have weight_string in the query but similar test with stream is still having weight_string in the query TestStreamSelectScatterOrderBy. In the second test, the column is infact an integer.
Is this a miss in the planner?

**Comment by dbussink** [comment]
> In the second test, the column is infact an integer.
> Is this a miss in the planner?

No, it looks like we're not having the schema information in the vschema. If I change this locally, it doesn't need the weight_string anymore:

```
diff --git i/go/vt/vtgate/testdata/executorVSchema.json w/go/vt/vtgate/testdata/executorVSchema.json
index da12a3b994..38eecc1c39 100644
--- i/go/vt/vtgate/testdata/executorVSchema.json
+++ w/go/vt/vtgate/testdata/executorVSchema.json
@@ -151,6 +151,14 @@
                                "sequence": "user_seq"
                        },
                        "columns": [
+                               {
+                                       "name": "id",
+                                       "type": "INT32"
+                               },
+                               {
+                                       "name": "col",
+                                       "type": "INT32"
+                               },
                                {
                                        "name": "textcol",
                                        "type": "VARCHAR"
```

**Review by frouioui — APPROVED** [review]
Long but much appreciated PR, thank you 🙇🏻
