### PR TITLE
[vipersync] deflake TestWatchConfig

### LINKED ISSUE #13498: Flaky Test: vipersync.TestWatchConfig
### Overview of the Issue

The `vipersync.TestWatchConfig` tests are increasingly flaky in CI, and slightly less so on a local machine.

We've skipped them for now, but we need to rewrite these tests to re-enable them, as that code is currently untested.

### Reproduction Steps

go test -race run "TestWatchConfig" ./go/viperutil/internal/vipersync

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
N/A
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by ajm188**
## Description

Turns out this is very tricky to repro locally, so I temporarily rewrote the test to do the following:

```go
func TestWatchConfig(t *testing.T) {
	t.Parallel()

	type config struct {
		A, B int
	}

	writeConfig := func(tmp *os.File, a, b int) error {
		stat, err := os.Stat(tmp.Name())
		if err != nil {
			return err
		}

		data, err := json.Marshal(&config{A: a, B: b})
		if err != nil {
			return err
		}

		err = os.WriteFile(tmp.Name(), data, stat.Mode())
		if err != nil {
			return err
		}

		data, err = os.ReadFile(tmp.Name())
		if err != nil {
			return err
		}

		var cfg config
		if err := json.Unmarshal(data, &cfg); err != nil {
			return err
		}

		if cfg.A != a || cfg.B != b {
			return fmt.Errorf("config did not persist; want %+v got %+v", config{A: a, B: b}, cfg)
		}

		return nil
	}
	writeRandomConfig := func(tmp *os.File) error {
		a, b := rand.Intn(100), rand.Intn(100)
		return writeConfig(tmp, a, b)
	}

	for i := 0; i < 10; i++ {
		t.Run("", func(t *testing.T) {
			t.Parallel()

			tmp, err := os.CreateTemp(".", "TestWatchConfig_*.json")
			require.NoError(t, err)
			t.Cleanup(func() { os.Remove(tmp.Name()) })

			require.NoError(t, writeRandomConfig(tmp))

			v := viper.New()
			v.SetConfigFile(tmp.Name())
			require.NoError(t, v.ReadInConfig())

			wCh, rCh := make(chan struct{}), make(chan struct{})
			v.OnConfigChange(func(event fsnotify.Event) {
				select {
				case <-rCh:
					return
				default:
				}

				wCh <- struct{}{}
				// block forever to prevent this viper instance from double-updating.
				<-rCh
			})
			v.WatchConfig()

			// Make sure that basic, unsynchronized WatchConfig is set up before
			// beginning the actual test.
			a, b := v.GetInt("a"), v.GetInt("b")
			require.NoError(t, writeConfig(tmp, a+1, b+1))
			<-wCh // wait for the update to finish

			require.Equal(t, a+1, v.GetInt("a"))
			require.Equal(t, b+1, v.GetInt("b"))

			rCh <- struct{}{}
		})
	}

	return
}
```

From there I was able to reproduce the failure locally with `go test -failfast -count=1000 -run TestWatchConfig ./go/viperutil/internal/sync`

I then changed the following line:

```diff
-			tmp, err := os.CreateTemp(".", "TestWatchConfig_*.json")
+			tmp, err := os.CreateTemp(t.TempDir(), "TestWatchConfig_*.json")
```

and the failures vanished. (incidentally, since `go test` manages cleanup of the test's tempdir, we don't need to manually remove the file during a `Cleanup` func anymore)

My working theory is this is happening because `inotify` watches the directory of the file you tell it to watch, and this causes a watch to run at O(N) of the number of files in that directory. For us, this is the vitess checkout dir and combined with the tighter constraints of the runners vs a dedicated laptop doing nothing but running this test, causes the failures to happen pretty much only in CI.

## Related Issue(s)

Fixes #13498 

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by mattlord — APPROVED** [review]

File: go/viperutil/internal/sync/sync_test.go [hunk 1]
```diff
@@ -75,19 +72,22 @@ func TestWatchConfig(t *testing.T) {
...
 	}
-	writeRandomConfig := func() error {
+	writeRandomConfig := func(tmp *os.File) error {
 		a, b := rand.Intn(100), rand.Intn(100)
-		return writeConfig(a, b)
+		return writeConfig(tmp, a, b)
 	}
 
-	require.NoError(t, writeRandomConfig())
+	tmp, err := os.CreateTemp(t.TempDir(), "TestWatchConfig_*.json")
```
Comment (mattlord) [inline go/viperutil/internal/sync/sync_test.go:80]: Noting that this is the key fix, as we're using a dedicated directory for our config files rather than the (very deep) PWD for the tests of the vitess root dir.

**Review by deepthi — APPROVED** [review]
