### PR TITLE
go/vt/mysqlctl: fix dup open/close backup stats

### LINKED ISSUE #12946: Bug Report: backup stats {Destination,Source}:Close reported too many times
### Overview of the Issue

Found a bug in the backup stats code (that I wrote) where these stats are being reported too many times. Silly, but easy to fix.

### Reproduction Steps

Just need to look at the [code](https://github.com/vitessio/vitess/blob/a8363189ce2c3c2bf8e5abea6abcc99bf18ec74b/go/vt/mysqlctl/builtinbackupengine.go) to see the error.

### Binary Version

```sh
a8363189ce2c3c2bf8e5abea6abcc99bf18ec74b
```

### Operating System and Environment details

```sh
All.
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by maxenglander**
## Description

Found a silly bug (in code I wrote) where the `Destination:Close` and `Source:Close` stats are being reported multiple times. Removing the duplications and adding a test.

## Related Issue(s)

Fixes #12946 

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by harshit-gangal — APPROVED** [review]

File: go/vt/mysqlctl/builtinbackupengine.go [hunk 1]
```diff
@@ -51,7 +51,7 @@ import (
 )
 
 const (
-	builtinBackupEngineName = "builtin"
+	BuiltinBackupEngineName = "builtin"
```
Comment (deepthi) [inline go/vt/mysqlctl/builtinbackupengine.go:54]: Why do you need to export this? I see no usages outside the package.

Comment (maxenglander) [reply go/vt/mysqlctl/builtinbackupengine.go:54]: Huh can't remember why I did this.. will revert

**Review by deepthi — APPROVED** [review]
