### PR TITLE
[MySQL] Fix EOFPacket handling for queries

### LINKED ISSUE #3934: MySQL Client EOF Handling is Incorrect
Per https://dev.mysql.com/doc/internals/en/packet-EOF_Packet.html, an EOF is only an EOF if it is < 9 bytes  long. Otherwise it's a length encoded integer (which typically precedes a length-encoded string: https://dev.mysql.com/doc/internals/en/string.html#packet-Protocol::LengthEncodedString).

I am not sure how widely this affects queries, but it came up when I had a string that exceeded 2^24-1 in size (i.e. required multiple packets).

Affects here https://github.com/vitessio/vitess/blob/master/go/mysql/query.go#L375 (and other relevant callsites).

Fix should just be to only EOF if the packet len is fine. When I patched that in locally things seemed to work okay.

See, e.g. go-sql-driver implementation: https://github.com/go-sql-driver/mysql/blob/master/packets.go#L752

Other refs:
https://dev.mysql.com/doc/internals/en/protocoltext-resultset.html

### PR DESCRIPTION
**Pull request by danieltahara**
Per https://dev.mysql.com/doc/internals/en/packet-EOF_Packet.html, an
EOF is only an EOF if it is < 9 bytes long. Otherwise it's a length
encoded integer (which typically precedes a length-encoded string:
https://dev.mysql.com/doc/internals/en/string.html#packet-Protocol::LengthEncodedString).

Resolves #3934 

Signed-off-by: Daniel Tahara <tahara@dropbox.com>

### CODE REVIEW

File: go/mysql/query.go [hunk 1]
```diff
@@ -350,6 +350,10 @@ func (c *Conn) ReadQueryResult(maxrows int, wantfields bool) (result *sqltypes.R
 		}
 		switch data[0] {
 		case EOFPacket:
+			if len(data) != EOFPacketPayloadLen {
```
Comment (demmer) [inline go/mysql/query.go]: IMO the style in the go driver seems cleaner than this switch, e.g. I think this is more straightforward:

```
if (data[0] == EOFPacket && len(data) == EOFPacketPayloadLen) {
    // This is what we expect.
    // Warnings and status flags are ignored.
    c.recycleReadPacket()
}
else if (data[0] == ErrPacket) {
    // Error packet.
    defer c.recycleReadPacket()
    return nil, ParseErrorPacket(data)
}
else {
    defer c.recycleReadPacket()
    return nil, fmt.Errorf("unexpected packet after fields: %v", data)
}
```

In fact, I think a utility function of `isEOFPacket(data)` that checks the first byte and the length makes this even more clear.

File: go/mysql/query.go [hunk 2]
```diff
@@ -416,6 +423,9 @@ func (c *Conn) drainResults() error {
...
```
Comment (demmer) [inline go/mysql/query.go]: Same comment as above...

File: go/mysql/query.go (hunk 1 above)
Comment (danieltahara) [reply go/mysql/query.go]: Yep seems reasonable. There's still something strange going on based on my integration tests that I'll have to dig into.

Also there's this strange nugget of == 1: https://github.com/go-sql-driver/mysql/blob/master/packets.go#L649. No idea what's up there.

File: go/vt/vttest/environment.go [hunk 3]
```diff
@@ -154,7 +154,7 @@ func (env *LocalTestEnv) MySQLManager(mycnf []string, snapshot string) (MySQLMan
 		InitFile:  path.Join(os.Getenv("VTTOP"), "config/init_db.sql"),
 		Directory: env.TmpPath,
 		Port:      env.PortForProtocol("mysql", ""),
-		MyCnf:     append(mycnf, env.DefaultMyCnf...),
+		MyCnf:     append(env.DefaultMyCnf, mycnf...),
```
Comment (danieltahara) [inline go/vt/vttest/environment.go]: needed to the extras are treated as overrides rather than potentially being clobbered by the base cnfs.

**Comment by demmer** [comment]
Changes LGTM!
