### PR TITLE
fix: `Unescape(Escape(str))` now returns the original string

### LINKED ISSUE #14992: Bug Report: `Unescape(Escape())` does not return the original string in `go/sqlescape`
### Overview of the Issue

`EscapeID` for the string ``` a`a ``` returns ``` `a``a` ``` but `UnescapeID` doesn't reverse it. Currently, it simply returns ``` a``a ```, removing the outer backticks without halving the ones inside the string.

related: #14987

### Reproduction Steps

run this code:
```go
package main

import (
	"fmt"

	"vitess.io/vitess/go/sqlescape"
)

func main() {
	str := "a`a"
	escaped := sqlescape.EscapeID(str)
	unescaped := sqlescape.UnescapeID(escaped)
	unescaped2 := sqlescape.UnescapeID("`a`a`")
	fmt.Printf("String: %s\nEscaped: %s\nUnescaped: %s\nUnescaped2: %s", str, escaped, unescaped, unescaped2)
}
```

output should be:
```
String: a`a
Escaped: `a``a`
Unescaped: a``a
Unescaped2: a`a
```

### Binary Version

```sh
vtgate version Version: 18.0.3-SNAPSHOT
```

### Operating System and Environment details

```sh
- Operating system macOS 14.0
- Kernel version Darwin 23.0.0
- Architecture arm64
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by Maniktherana**
## Description
`UnescapeID(str)` will now also halve any backticks found within a string.
Associated tests will be added via #14987

## Related Issue(s)
Fixes #14992

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/sqlescape/ids.go [hunk 1]
```diff
@@ -52,11 +52,21 @@ func EscapeIDs(identifiers []string) []string {
 	return result
 }
 
-// UnescapeID reverses any backticking in the input string.
+// UnescapeID reverses any backticking in the input string by EscapeID.
 func UnescapeID(in string) string {
```
[the remark this answers is not in the document]
Comment (Maniktherana) [reply go/sqlescape/ids.go:56]: I do see your point, one concern is that returning an error could be a breaking change. Previously the function would handle cases like ``` `foo ```, `aa`, ``` a`a ``` etc by returning them as is.

If that's not an issue, I'll go ahead and make the changes

[the remark this answers is not in the document]
Comment (dbussink) [reply go/sqlescape/ids.go:56]: I think we should make the change yeah. Because not doing it also carries a security risk since it means you can trust escaping anymore. That’s more serious imho.

[the remark this answers is not in the document]
Comment (Maniktherana) [reply go/sqlescape/ids.go]: Added the suggested changes

[the remark this answers is not in the document]
Comment (dbussink) [reply go/sqlescape/ids.go]: > Is this the right way to go about it? I'll have to refactor 27 usages of the `UnescapeID` function across 6 files.

Yep, that's the consequence here but I think that's good since those call sites now know if it couldn't actually be unescaped. And also further bubble up the error then.

File: go/sqlescape/ids.go [hunk 2]
```diff
@@ -53,20 +54,29 @@ func EscapeIDs(identifiers []string) []string {
 }
 
 // UnescapeID reverses any backticking in the input string by EscapeID.
-func UnescapeID(in string) string {
+func UnescapeID(in string) (string, error) {
 	l := len(in)
 	if l >= 2 && in[0] == '`' && in[l-1] == '`' {
 		in = in[1 : l-1]
+
+		if !strings.ContainsRune(in, '`') {
```
Comment (dbussink) [inline go/sqlescape/ids.go:62]: You can directly use `IndexByte` here since that's what ends up being used anyway for single byte characters.

**Comment by Maniktherana** [comment]
@dbussink I've refactored usages of `UnescapeID` so that unit tests now run.
Issue is now tests involving the use of this function fail in the following components:
 - `vt/wrangler`
 - `vt/mysqlctl`
 - `vt/vtexplain`

This is because the tests relied on `UnescapeID` returning the original string if it was not enclosed in backticks whereas now it throws an error for such cases.

The rest of the components refactored components are passing unit tests.

File: go/sqlescape/ids.go (hunk 2 above)
Comment (Maniktherana) [reply go/sqlescape/ids.go]: Made the change

**Comment by Maniktherana** [comment]
yikes did my changes ping the entire vitess team?

**Comment by systay** [comment]
> yikes did my changes ping the entire vitess team?

no worries. this is as expected

nice work! :)

**Comment by dbussink** [comment]
> This is because the tests relied on `UnescapeID` returning the original string if it was not enclosed in backticks whereas now it throws an error for such cases.

Right, so I wasn't clear enough. I think that allowing the original string if it's already correctly unescaped is safe to do. So we can also have an explicit case to allow for this. This means that something like `foo` is ok, but ``` `foo ``` is not for example. I think that makes all existing usages also work properly? And only then errors on invalidly escaped strings.

**Comment by Maniktherana** [comment]
> This means that something like `foo` is ok, but `` `foo `` is not for example. I think that makes all existing usages also work properly? And only then errors on invalidly escaped strings.

Okay, made changes accordingly. Tests were passing locally for the affected files

File: go/sqlescape/ids_test.go [hunk 3]
```diff
@@ -26,12 +29,97 @@ func TestEscapeID(t *testing.T) {
...
+			err: false,
+		},
+	}
+	for _, tc := range testcases {
+		t.Run(tc.in, func(t *testing.T) {
+			out, err := UnescapeID(tc.in)
+			assert.Equal(t, tc.out, out, "output mismatch")
+			if tc.err {
+				require.Error(t, err)
+			}
```
Comment (shlomi-noach) [inline go/sqlescape/ids_test.go:121]: If there's an error, then we don't care about the output. Also, missing validation that there _isn't_ an error:
```suggestion
			if tc.err {
				require.Error(t, err)
			} else {
				require.NoError(t, err)
				assert.Equal(t, tc.out, out, "output mismatch")
			}
```

File: go/sqlescape/ids_test.go [hunk 4]
```diff
@@ -26,12 +29,97 @@ func TestEscapeID(t *testing.T) {
...
+		{
+			in:  "foo`",
+			out: "",
+			err: true,
+		},
+		{
+			in:  "`fo`o",
+			out: "",
+			err: true,
+		},
```
Comment (shlomi-noach) [inline go/sqlescape/ids_test.go:88]: another test case:
```suggestion
		{
			in:  "`fo`o",
			out: "",
			err: true,
		},
		{
			in:  "`fo`o`",
			out: "",
			err: true,
		},
```

File: go/sqlescape/ids_test.go [hunk 5]
```diff
@@ -26,12 +29,97 @@ func TestEscapeID(t *testing.T) {
...
+		})
+	}
+}
+
+func TestUnescapeID(t *testing.T) {
+	testcases := []struct {
+		in, out string
+		err     bool
+	}{
+		{
```
Comment (shlomi-noach) [inline go/sqlescape/ids_test.go:54]: What is the expected result of `in: ""` ? Please add a test.

File: go/vt/vtctl/workflow/traffic_switcher.go [hunk 6]
```diff
@@ -487,23 +487,32 @@ func (ts *trafficSwitcher) dropParticipatingTablesFromKeyspace(ctx context.Conte
...
+			sanitizedPrimaryDbName, err := sqlescape.UnescapeID(source.GetPrimary().DbName())
+			if err != nil {
+				return err
+			}
+			primaryDbName := sqlescape.EscapeID(sanitizedPrimaryDbName)
+			sanitizedTableName, err := sqlescape.UnescapeID(tableName)
+			if err != nil {
+				return err
+			}
+			tableName := sqlescape.EscapeID(sanitizedTableName)
```
Comment (shlomi-noach) [inline go/vt/vtctl/workflow/traffic_switcher.go:499]: Feels like a pattern here. You `UnescapeID` then `EscapeID`. Perhaps this should be a single function called something like `EnsureEscaped() (string, error)` which does both actions in a single call?

Then you'd do something like:
```go
primaryDbName, err := sqlescape.EnsureEscaped(source.GetPrimary().DbName())
...
tableName, err := sqlescape.EnsureEscaped(tableName)
```

**Review by shlomi-noach — COMMENTED** [review]
Thank you for this change. I do believe we should introduce a new, `EnsureEscaped() (string, error)` function, to solve the recurring unescape-introduce-new-variable-escape-perhaps-yet-another-new-variable pattern. Please see inline comments.

File: go/sqlescape/ids_test.go (hunk 5 above)
Comment (Maniktherana) [reply go/sqlescape/ids_test.go:54]: That one's been added already (lines 115-117)

File: go/sqlescape/ids_test.go [hunk 7]
```diff
@@ -26,12 +29,104 @@ func TestEscapeID(t *testing.T) {
...
 	for _, tc := range testcases {
-		out := EscapeID(tc.in)
-		if out != tc.out {
-			t.Errorf("EscapeID(%s): %s, want %s", tc.in, out, tc.out)
-		}
+		t.Run(tc.in, func(t *testing.T) {
+			out := EscapeID(tc.in)
+			if out != tc.out {
+				assert.Equal(t, out, tc.out)
+			}
```
Comment (shlomi-noach) [inline go/sqlescape/ids_test.go:44]: This is superfluous. No point in asserting that something is true right after it's verified to be false. Plain `assert` is the way to go.
```suggestion
			assert.Equal(t, out, tc.out)
```

Comment (Maniktherana) [reply go/sqlescape/ids_test.go]: Done

File: go/vt/vtctl/workflow/traffic_switcher.go (hunk 6 above)
Comment (Maniktherana) [reply go/vt/vtctl/workflow/traffic_switcher.go]: made the suggested changes

**Review by shlomi-noach — APPROVED** [review]

File: go/sqlescape/ids.go [hunk 8]
```diff
@@ -52,11 +53,61 @@ func EscapeIDs(identifiers []string) []string {
...
 	l := len(in)
-	if l >= 2 && in[0] == '`' && in[l-1] == '`' {
-		return in[1 : l-1]
+
+	if l == 0 {
+		return in, nil
+	}
+
+	first, last := in[0], in[l-1]
+
```
Comment (dbussink) [inline go/sqlescape/ids.go:65]: Can further checks here be simplified by handling `l == 1` first explicitly? 

```go
	if l == 1 {
		if in[0] == `'` {
			return "", <error>
		}
		return in
	}
```

That way you then don't have to check `l >= 2` all the time in each case.

Comment (Maniktherana) [reply go/sqlescape/ids.go:72]: Added the check

File: go/sqlescape/ids_test.go [hunk 9]
```diff
@@ -26,12 +29,182 @@ func TestEscapeID(t *testing.T) {
...
+
+func TestUnescapeID(t *testing.T) {
+	testcases := []struct {
+		in, out string
+		err     bool
+	}{
+		{
+			in:  "``",
+			out: "",
+			err: false,
```
Comment (dbussink) [inline go/sqlescape/ids_test.go:55]: I think this case should also error since the empty string is not a valid identifier.

File: go/sqlescape/ids_test.go [hunk 10]
```diff
@@ -26,12 +29,182 @@ func TestEscapeID(t *testing.T) {
...
+		},
+		{
+			in:  "f`oo",
+			out: "",
+			err: true,
+		},
+		{
+			in:  "",
+			out: "",
+			err: false,
```
Comment (dbussink) [inline go/sqlescape/ids_test.go:120]: Same here, empty identifier also isn't a valid identifier.

File: go/sqlescape/ids_test.go (hunk 9 above)
Comment (Maniktherana) [reply go/sqlescape/ids_test.go]: done

File: go/vt/vtctl/workflow/traffic_switcher.go [hunk 11]
```diff
@@ -487,23 +487,29 @@ func (ts *trafficSwitcher) dropParticipatingTablesFromKeyspace(ctx context.Conte
...
+				return err
+			}
+
+			query := fmt.Sprintf("drop table %s.%s", primaryDbName, tableName)
 			if removalType == DropTable {
 				ts.Logger().Infof("%s: Dropping table %s.%s\n",
 					source.GetPrimary().String(), source.GetPrimary().DbName(), tableName)
 			} else {
-				renameName := getRenameFileName(tableName)
+				renameName, err := sqlescape.EnsureEscaped(getRenameFileName(tableName))
```
Comment (dbussink) [inline go/vt/vtctl/workflow/traffic_switcher.go:504]: This is wrong. It's causing CI to fail, because it doesn't first unescape `tableName`, then do `getRenameFileName` and then escapes it again. So you get an error like:

```
 code = Unknown desc = UnescapeID err: no outer backticks found in the identifier '_`customer2`_old'
```

because of the broken table name.

File: go/vt/wrangler/traffic_switcher.go [hunk 12]
```diff
@@ -1772,23 +1772,28 @@ func getRenameFileName(tableName string) string {
 func (ts *trafficSwitcher) removeSourceTables(ctx context.Context, removalType workflow.TableRemovalType) error {
 	err := ts.ForAllSources(func(source *workflow.MigrationSource) error {
 		for _, tableName := range ts.Tables() {
-			query := fmt.Sprintf("drop table %s.%s",
-				sqlescape.EscapeID(sqlescape.UnescapeID(source.GetPrimary().DbName())),
-				sqlescape.EscapeID(sqlescape.UnescapeID(tableName)))
+			PrimaryDbName, err := sqlescape.EnsureEscaped(source.GetPrimary().DbName())
```
Comment (dbussink) [inline go/vt/wrangler/traffic_switcher.go:1775]: Seems off to have `primaryDbName` with a capital `P` here, that isn't afaik right Go variable naming style.

File: go/vt/vtctl/workflow/traffic_switcher.go (hunk 11 above)
Comment (Maniktherana) [reply go/vt/vtctl/workflow/traffic_switcher.go:504]: made the changes, CI is also passing

**Review by dbussink — APPROVED** [review]
