### PR TITLE
[vtadmin] propagate error contexts

### LINKED ISSUE #7633: [vtadmin] refactor error-handling to wrap errors with additional context
We have a lot of functions in the vtadmin tree that have multiple failure points, and each one simply forwards the error back up to the caller, making debugging exactly what failed where trickier than I would like sometimes.

We should wrap each of those errors before returning with some additional context to help with debugging. In particular I'm thinking about functions further down in the stack, in particular those in `vtctldclient.VtctldClientProxy` and `vtsql.VTGateProxy`.

### PR DESCRIPTION
**Pull request by ajm188**
## Description

This PR wraps a bunch of places where errors happen with additional context around what failed. Because debugging should be less hard.

## Related Issue(s)

- Closes #7633 

## Checklist
- [ ] Should this PR be backported? **no**
- [ ] Tests were added or are not required **n/a**
- [ ] Documentation was added or is not required **n/a**

## Impacted Areas in Vitess
Components that this PR will affect:

- [ ]  Query Serving
- [ ]  VReplication
- [ ]  Cluster Management
- [ ]  Build/CI
- [x]  VTAdmin

### CODE REVIEW

File: go/vt/vtadmin/api.go [hunk 1]
```diff
@@ -796,15 +796,14 @@ func (api *API) VTExplain(ctx context.Context, req *vtadminpb.VTExplainRequest)
...
+		return nil, fmt.Errorf("%w: %s", errors.ErrUnsupportedCluster, req.Cluster)
 	}
 
 	tablet, err := c.FindTablet(ctx, func(t *vtadminpb.Tablet) bool {
 		return t.Tablet.Keyspace == req.Keyspace && topo.IsInServingGraph(t.Tablet.Type) && t.Tablet.Type != topodatapb.TabletType_MASTER && t.State == vtadminpb.Tablet_SERVING
 	})
-
 	if err != nil {
-		return nil, err
+		return nil, fmt.Errorf("cannot find serving, non-MASTER tablet in keyspace=%s: %w", req.Keyspace, err)
```
Comment (doeg) [inline go/vt/vtadmin/api.go:806]: How about `non-PRIMARY`?

**Review by doeg — APPROVED** [review]
Thank you!

File: go/vt/vtadmin/api.go (hunk 1 above)
Comment (ajm188) [reply go/vt/vtadmin/api.go:806]: yeah, i was trying to stick to the value of the enum (hence why it's all-caps) but screw it; let's change the english now!

**Review by doeg — APPROVED** [review]
