### PR TITLE
planner: fix predicate simplifier

### LINKED ISSUE #12645: Bug Report: Predicate rewriting of non-trivial or out-of-order OR conditions goes wild
### Overview of the Issue

In https://github.com/vitessio/vitess/pull/11765 (merged in 16.0.0) some new condition-rewriting logic was introduced which attempts to simplify `OR` conditions, especially into `IN()` lists. However, it is implemented in an overly simplistic way such that it requires conditions to be ordered in order for the simplification to work, and when they are not, or when they are less simple, it's easy to make it produce very questionable (and potentially incorrect) rewrites.

### ((A, 1), (A, 2), (A, 3))

For instance, this simple query is correctly rewritten:

`select * from products where (tenant_key="A" and id=1) or (tenant_key="A" and id=2) or (tenant_key="A" and id=3)`

to:

`select id from products where tenant_key = 'A' and id in (1, 2, 3)`

### ((A, 1), (A, 2), (B, 3))

A minor variation of it is also correctly rewritten (although mainly because part of it isn't simplified at all):

`select id from products where (tenant_key="A" and id=1) or (tenant_key="A" and id=2) or (tenant_key="B" and id=3)`

to:

`select id from products where tenant_key = 'A' and id in (1, 2) or tenant_key = 'B' and id = 3`

### ((A, 1), (A, 2), (B, 3), (B, 4))

Simply adding one additional condition on the first part makes it go a bit wild:

`select id from products where (tenant_key="A" and id=1) or (tenant_key="A" and id=2) or (tenant_key="B" and id=3) or (tenant_key="B" and id=4)`

expected:

`select id from products where tenant_key = 'A' and id in (1, 2) or tenant_key = 'B' and id in (3, 4)`

actual:

`select id from products where (tenant_key = 'A' and id in (1, 2) or tenant_key = 'B' and id = 3 or tenant_key = 'B') and (tenant_key = 'A' and id in (1, 2) or tenant_key = 'B' and id = 3 or id = 4)`

### ((A, 1), (B, 2), (A, 3))

Simply having conditions interleaved causes unexpected results:

`select id from products where (tenant_key="A" and id=1) or (tenant_key="B" and id=2) or (tenant_key="A" and id=3)`

expected:

`select id from products where tenant_key = 'A' and id in (1, 3) or tenant_key = 'B' and id = 2`

actual:

`select id from products where (tenant_key = 'A' and id = 1 or tenant_key = 'B' and id = 2 or tenant_key = 'A') and (tenant_key = 'A' and id = 1 or tenant_key = 'B' and id = 2 or id = 3)`

### ((A, 1), (B, 2), (A, 3), (B, 4))

However, things get much worse when the conditions in the first part are interleaved:

`select id from products where (tenant_key="A" and id=1) or (tenant_key="B" and id=2) or (tenant_key="A" and id=3) or (tenant_key="B" and id=4)`

expected:

`select id from products where tenant_key = 'A' and id in (1, 3) or tenant_key = 'B' and id in (2, 4)`

actual:

`select id from products where (tenant_key = 'A' and id = 1 or tenant_key = 'B' and id = 2 or tenant_key = 'A') and (tenant_key = 'A' and id = 1 or tenant_key = 'B' and id = 2 or id = 3) or tenant_key = 'B' and id = 4`

### Reproduction Steps

Set up a sharded table, and run some simple queries with conditions of the form `(... AND ...) OR (... AND ...)` as above, and observe the questionable rewrites.

The following test case additions also reproduce the issues within the test suite:

```diff
diff --git a/go/vt/sqlparser/predicate_rewriting_test.go b/go/vt/sqlparser/predicate_rewriting_test.go
index 1c86dec61a..c9bfd1ac68 100644
--- a/go/vt/sqlparser/predicate_rewriting_test.go
+++ b/go/vt/sqlparser/predicate_rewriting_test.go
@@ -120,6 +120,15 @@ func TestRewritePredicate(in *testing.T) {
        }, {
                in:       "(a=1 or a IN (1,2)) or (a = 2 or a = 3)",
                expected: "a in (1, 2, 3)",
+       }, {
+               in:       "(A and C) or (A and D) or (B and E) or (B and F)",
+               expected: "A and (C or D) or B and (E or F)",
+       }, {
+               in:       "(A and C) or (B and D) or (A and E)",
+               expected: "A and (C or D) or B and E",
+       }, {
+               in:       "(A and C) or (B and D) or (A and E) or (B and F)",
+               expected: "A and (C or E) or B and (D or F)",
        }}
 
        for _, tc := range tests {
```

And you can see the `actual` rewrites as follows:

```
$ go test ./go/vt/sqlparser/ -run TestRewritePredicate
--- FAIL: TestRewritePredicate (0.00s)
    --- FAIL: TestRewritePredicate/(A_and_C)_or_(A_and_D)_or_(B_and_E)_or_(B_and_F) (0.00s)
        predicate_rewriting_test.go:140: 
                Error Trace:    /home/jeremycole/git/vitess/go/vt/sqlparser/predicate_rewriting_test.go:140
                Error:          Not equal: 
                                expected: "A and (C or D) or B and (E or F)"
                                actual  : "(A and (C or D) or B and E or B) and (A and (C or D) or B and E or F)"
                                
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -A and (C or D) or B and (E or F)
                                +(A and (C or D) or B and E or B) and (A and (C or D) or B and E or F)
                Test:           TestRewritePredicate/(A_and_C)_or_(A_and_D)_or_(B_and_E)_or_(B_and_F)
    --- FAIL: TestRewritePredicate/(A_and_C)_or_(B_and_D)_or_(A_and_E) (0.00s)
        predicate_rewriting_test.go:140: 
                Error Trace:    /home/jeremycole/git/vitess/go/vt/sqlparser/predicate_rewriting_test.go:140
                Error:          Not equal: 
                                expected: "A and (C or D) or B and E"
                                actual  : "(A and C or B and D or A) and (A and C or B and D or E)"
                                
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -A and (C or D) or B and E
                                +(A and C or B and D or A) and (A and C or B and D or E)
                Test:           TestRewritePredicate/(A_and_C)_or_(B_and_D)_or_(A_and_E)
    --- FAIL: TestRewritePredicate/(A_and_C)_or_(B_and_D)_or_(A_and_E)_or_(B_and_F) (0.00s)
        predicate_rewriting_test.go:140: 
                Error Trace:    /home/jeremycole/git/vitess/go/vt/sqlparser/predicate_rewriting_test.go:140
                Error:          Not equal: 
                                expected: "A and (C or E) or B and (D or F)"
                                actual  : "(A and C or B and D or A) and (A and C or B and D or E) or B and F"
                                
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -A and (C or E) or B and (D or F)
                                +(A and C or B and D or A) and (A and C or B and D or E) or B and F
                Test:           TestRewritePredicate/(A_and_C)_or_(B_and_D)_or_(A_and_E)_or_(B_and_F)
FAIL
FAIL    vitess.io/vitess/go/vt/sqlparser        0.014s
FAIL
```

### Binary Version

```sh
Version: 16.0.0-SNAPSHOT (Git revision 299a36101f57e8e2b3712f62ea2637d8f4114216 branch 'HEAD') built on Fri Dec 16 16:33:58 UTC 2022 by vitess@buildkitsandbox using go1.19.4 linux/amd64
```

### Operating System and Environment details

```sh
n/a
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by systay**
## Description
In the predicate rewriting that we added recently, a bug snuck in that can mangle predicates in a bad way.

This PR fixes that, and also introduces fuzz testing that should find any other problems

## Related Issue(s)
Fixes #12645

## Checklist
-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/sqlparser/predicate_rewriting.go [hunk 1]
```diff
@@ -16,35 +16,72 @@ limitations under the License.
...
+var logger *log.Logger
+
+// Set☝️to something not nil to get debug output
+// var logger *log.Logger = log.New(os.Stdout, "", 0)
+
+func f(e Expr) func() Expr {
+	return func() Expr {
+		return e
+	}
+}
```
Comment (frouioui) [inline go/vt/sqlparser/predicate_rewriting.go:39]: It may be useful to either change the name of the function or add a comment explaining why the function is doing this.

File: go/vt/sqlparser/predicate_rewriting.go [hunk 2]
```diff
@@ -16,35 +16,72 @@ limitations under the License.
...
 	Changed  RewriteState = true
 	NoChange RewriteState = false
 )
 
 type RewriteState bool
 
+var logger *log.Logger
+
+// Set☝️to something not nil to get debug output
+// var logger *log.Logger = log.New(os.Stdout, "", 0)
```
[the remark this answers is not in the document]
Comment (frouioui) [reply go/vt/sqlparser/predicate_rewriting.go:33]: Ah, now I understand after reading the code more. You can ignore the comment above :)

File: go/vt/vtgate/evalengine/testcases/cases.go [hunk 3]
```diff
@@ -874,3 +875,10 @@ func InStatement(yield Query) {
 		yield(fmt.Sprintf("%s IN (%s, %s, %s)", inputs[0], inputs[1], inputs[2], inputs[0]), nil)
 	})
 }
+
+func BoolNot(yield Query) {
+	inputs := []string{"true", "false", "null"}
+	for _, input := range inputs {
+		yield(fmt.Sprintf("NOT %s", input), nil)
+	}
+}
```
Comment (frouioui) [inline go/vt/vtgate/evalengine/testcases/cases.go:884]: This is failing in CI `--- FAIL: TestMySQL/BoolNot (0.00s)`. 

```
=== RUN   TestMySQL/BoolNot
    comparison_test.go:201: evaluation type mismatch: eval=INT64 vs typeof=UINT64
        local: INT64(0)
        query: SELECT NOT true (SIMPLIFY=false)
    comparison_test.go:201: evaluation type mismatch: eval=INT64 vs typeof=UINT64
        local: INT64(1)
        query: SELECT NOT false (SIMPLIFY=false)
    --- FAIL: TestMySQL/BoolNot (0.00s)
```

After running it locally it seems like there is type mismatch between MySQL and my local version.

File: go/vt/vtgate/planbuilder/predicate_rewrite_test.go [hunk 4]
```diff
@@ -0,0 +1,156 @@
...
+			Left:  tc.createPredicate(lvl + 1),
+			Right: tc.createPredicate(lvl + 1),
+		}
+	case XOR:
+		return &sqlparser.XorExpr{
+			Left:  tc.createPredicate(lvl + 1),
+			Right: tc.createPredicate(lvl + 1),
+		}
+	}
+	panic("oops")
```
Comment (frouioui) [inline go/vt/vtgate/planbuilder/predicate_rewrite_test.go:81]: nit:
```suggestion
	panic("unexpected nodeType")
```

File: go/vt/vtgate/planbuilder/predicate_rewrite_test.go [hunk 5]
```diff
@@ -0,0 +1,156 @@
...
+}
+
+func TestFuzzRewriting(t *testing.T) {
+	// This test, that runs for one second only, will produce lots of random boolean expressions,
+	// mixing AND, NOT, OR, XOR and column expressions.
+	// It then takes the predicate and simplifies it
+	// Finally, it runs both the original and simplified predicate with all combinations of column
+	// values - trying TRUE, FALSE and NULL. If the two expressions do not return the same value,
+	// this is considered a test failure.
```
Comment (frouioui) [inline go/vt/vtgate/planbuilder/predicate_rewrite_test.go:90]: Love this 🙏🏻

File: go/vt/vtgate/planbuilder/predicate_rewrite_test.go [hunk 6]
```diff
@@ -0,0 +1,156 @@
...
+		require.NoError(t, err)
+		assert.Equal(t, v1.Value(), v2.Value())
+		if len(env.Row) > i+1 {
+			testValues(t, env, i+1, original, simpler)
+		}
+	}
+}
+
+type lookup struct {
+}
```
Comment (frouioui) [inline go/vt/vtgate/planbuilder/predicate_rewrite_test.go:143]: nit:
```suggestion
type lookup struct {}
```

**Review by frouioui — APPROVED** [review]
Left a few comments, mostly nit and something about a test that fails both in CI and locally. Otherwise looks to me 🙏🏻

File: go/vt/sqlparser/predicate_rewriting.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (harshit-gangal) [reply go/vt/sqlparser/predicate_rewriting.go:33]: How about using existing logger `vitess.io/vitess/go/vt/log` and have a `DEBUG` bool constant with default `false` ?

File: go/vt/vtgate/evalengine/testcases/cases.go (hunk 3 above)
Comment (systay) [reply go/vt/vtgate/evalengine/testcases/cases.go]: I removed this commit from this PR since this was merge on main already
