### PR TITLE
Fix initialization code to also stop replication to prevent crash

### LINKED ISSUE #10880: Bug Report: Semi-sync not setup correctly on VTTablet startup
### Overview of the Issue

This bug was found when investigating flakiness in an EmergencyReparentShard test `TestERSPromoteRdonly`. 

It was observed that the following sequence of steps were followed - 
1. We bring up a new cluster with new tablets
2. We try to run PRS
3. Meanwhile, tablets go to RESTORE mode as part of the startup
4. PRS sees the tablets are of type RESTORE and doesn’t set semi-sync on them
5. Tablet complete RESTORE and go to type REPLICA (but semi-sync is off)
6. Test fails assuming semi-sync is on (Blocks on a write)

This uncovered a deeper problem. A vttablet on startup won't set its semi-sync properly. 
The reason for this is quite clear. Earlier vttablets used the `enable_semi_sync` flag which meant that when the replication manager repaired replication (even on startup), semi-sync was automatically fixed.

This however changed, since we started sending the semi-sync information in the RPCs. This led us to not fix semi-sync at all on startup.

### Reproduction Steps

1. Setup a cluster with `semi_sync` durability
2. Bring up a new `REPLICA` tablet
3. Wait and see that semi-sync is off on the tablet.

### Binary Version

```sh
main. release-14.0 and before used the flag, so they are unaffected.
```

### Operating System and Environment details

Found on CI.

### Log Fragments

_No response_

### LINKED ISSUE #12533: Bug Report: Vttablet restart when MySQL replication is running crashes
### Overview of the Issue

Restarting a vttablet when MySQL replication is running crashes the vttablet.
This happens only when `--restore_from_backup` flag is not provided or set to false.

The logs say - 
```
I0301 22:52:17.809336   63118 tm_init.go:871] Getting a new durability policy for semi_sync
I0301 22:52:17.809355   63118 replication.go:633] Setting semi-sync mode: primary=false, replica=true
I0301 22:52:17.809717   63118 query.go:80] exec SET GLOBAL rpl_semi_sync_master_enabled = 0, GLOBAL rpl_semi_sync_slave_enabled = 1
I0301 22:52:17.810129   63118 query.go:80] exec RESET SLAVE ALL
E0301 22:52:17.810274   63118 query.go:82] ExecuteFetch(RESET SLAVE ALL) failed: This operation cannot be performed with running replication threads; run STOP SLAVE FOR CHANNEL '' first (errno 3081) (sqlstate HY000) during query: RESET SLAVE ALL
I0301 22:52:17.810310   63118 tm_state.go:101] In tmState.Open()

F0301 22:52:17.853669   63118 vttablet.go:128] failed to parse --tablet-path or initialize DB credentials: ExecuteFetch(RESET SLAVE ALL) failed: This operation cannot be performed with running replication threads; run STOP SLAVE FOR CHANNEL '' first (errno 3081) (sqlstate HY000) during query: RESET SLAVE ALL
MysqlDaemon.SetReplicationSource failed
```

This bug was originally introduced by https://github.com/vitessio/vitess/pull/10881

### Reproduction Steps

Start a cluster.
Restart a running vttablet.

### Binary Version

```sh
main, release-16, release-15
```

### Operating System and Environment details

```sh
all
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description

This PR fixes the bug described in #12533 by fixing the initialization code to also stop replication before it tries to `reset slave  all`. The old code assumed that replication is already stopped when a new vttablet was coming up, but that assumption is incorrect. We should stop replication irrespective before we try to change the primary hostname, and port.

This PR is a follow-up to: https://github.com/vitessio/vitess/pull/10881 which was originally created to resolve #10880.

## Related Issue(s)

 - Fixes #12533 

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [ ] Documentation was added or is not required

### CODE REVIEW

File: go/test/endtoend/reparent/newfeaturetest/reparent_test.go [hunk 1]
```diff
@@ -96,3 +96,16 @@ func TestSingleReplicaERS(t *testing.T) {
...
+	defer cluster.PanicHandler(t)
+	clusterInstance := utils.SetupReparentCluster(t, "semi_sync")
+	defer utils.TeardownCluster(clusterInstance)
+	tablets := clusterInstance.Keyspaces[0].Shards[0].Vttablets
+
+	utils.StopTablet(t, tablets[1], false)
+	tablets[1].VttabletProcess.ServingStatus = "SERVING"
+	err := tablets[1].VttabletProcess.Setup()
+	require.NoError(t, err)
+}
```
Comment (mattlord) [inline go/test/endtoend/reparent/newfeaturetest/reparent_test.go:111]: This fails on `main`?

File: go/vt/vttablet/tabletmanager/tm_init.go [hunk 2]
```diff
@@ -882,7 +882,7 @@ func (tm *TabletManager) initializeReplication(ctx context.Context, tabletType t
 		log.Warningf("primary tablet in the shard record does not have mysql hostname specified, possibly because that tablet has been shut down.")
 		return nil, nil
 	}
-	if err := tm.MysqlDaemon.SetReplicationSource(ctx, currentPrimary.Tablet.MysqlHostname, currentPrimary.Tablet.MysqlPort, false /* stopReplicationBefore */, true /* startReplicationAfter */); err != nil {
+	if err := tm.MysqlDaemon.SetReplicationSource(ctx, currentPrimary.Tablet.MysqlHostname, currentPrimary.Tablet.MysqlPort, true /* stopReplicationBefore */, true /* startReplicationAfter */); err != nil {
```
Comment (mattlord) [inline go/vt/vttablet/tabletmanager/tm_init.go:885]: Looks like this was introduced in https://github.com/vitessio/vitess/pull/10881 then (so 15.0.0 and later). We should note that in the description and in the Related Issues. Suggestion there:
```
  - Follow-up to: https://github.com/vitessio/vitess/pull/10881
```

That change was made to address: https://github.com/vitessio/vitess/issues/10880

**Review by mattlord — APPROVED** [review]
Approving as it's definitely an improvement. I'm not certain, however, that this eliminates the general race condition as a human, tablet repair, vtorc, etc could still start replication in between right? I feel like perhaps we should continue retrying to achieve desired config and error after a number of attempts.

**Comment by mattlord** [comment]
From the issue, does the process end here?
```
F0301 22:52:17.853669   63118 vttablet.go:128] failed to parse --tablet-path or initialize DB credentials: ExecuteFetch(RESET SLAVE ALL) failed: This operation cannot be performed with running replication threads; run STOP SLAVE FOR CHANNEL '' first (errno 3081) (sqlstate HY000) during query: RESET SLAVE ALL
MysqlDaemon.SetReplicationSource failed
```
If so, then I would guess we have a nil pointer dereference or something that flows from this. That would seem like a separate issue to address, as ideally we should retry to reach the desired state during init and then shutdown gracefully if we fail to. Otherwise I think we may still be still prone to the process simply “disappearing” w/o a trace or clue because of race conditions around this.

File: go/test/endtoend/reparent/newfeaturetest/reparent_test.go (hunk 1 above)
Comment (GuptaManan100) [reply go/test/endtoend/reparent/newfeaturetest/reparent_test.go:111]: Yes, it does.

File: go/vt/vttablet/tabletmanager/tm_init.go (hunk 2 above)
Comment (GuptaManan100) [reply go/vt/vttablet/tabletmanager/tm_init.go:885]: Okay 👍

**Comment by GuptaManan100** [comment]
@mattlord It's not really a race. Its just that this part of code didn't stop replication before it started changing the primary information. It assumed that replication would be stopped already, which is an incorrect assumption.
As far as the question for a race with someone fixing the replication (vtorc, or manual) is concerned, I don't think that is an issue because of how `SetReplicationSource` is written. It accumulates all the commands it has to run and then runs them all one after the other.
```go
        cmds := []string{}
	if replicationStopBefore {
		cmds = append(cmds, conn.StopReplicationCommand())
	}
	// Reset replication parameters commands makes the instance forget the source host port
	// This is required because sometimes MySQL gets stuck due to improper initialization of
	// master info structure or related failures and throws errors like
	// ERROR 1201 (HY000): Could not initialize master info structure; more error messages can be found in the MySQL error log
	// These errors can only be resolved by resetting the replication parameters, otherwise START SLAVE fails.
	// Therefore, we have elected to always reset the replication parameters whenever we try to set the source host port
	// Since there is no real overhead, but it makes this function robust enough to also handle failures like these.
	cmds = append(cmds, conn.ResetReplicationParametersCommands()...)
	smc := conn.SetReplicationSourceCommand(params, host, port, int(replicationConnectRetry.Seconds()))
	cmds = append(cmds, smc)
	if replicationStartAfter {
		cmds = append(cmds, conn.StartReplicationCommand())
	}
	return mysqld.executeSuperQueryListConn(ctx, conn, cmds)
```

I think that the idea of having a retry is still a good one. We could also just ignore the error, instead of exiting on it and let VTOrc repair the replication later.

This is what we have in `Start` - 
```
_, err = tm.initializeReplication(ctx, tm.Tablet().Type)
	tm.tmState.Open()
	return err
```
Maybe we should ignore that error, because that error gets propagated up the stack eventually doing `log.Exitf`. An error in initializing replication shouldn't really shutdown the tablet. I am still in two-minds about that though. WDYT?

**Comment by GuptaManan100** [comment]
@mattlord Me and @deepthi had a chat about this PR today morning. She also feels that we shouldn't be ignoring an error during start-up. Also, we both think that a retry for initializing replication isn't required especially since VTOrc has already become compulsory. 

Other than that, I have pushed fixes to the tests so this PR should be good to go. If something does turn up, please feel free to resolve it as you both see fit since I'll be off for about 11 days.

**Review by deepthi — APPROVED** [review]
