### PR TITLE
Correct Handling of UNION Queries with Literals in the Vitess Planner

### LINKED ISSUE #16228: UNION with literals and grouping fails planning
The Vitess planner is sometimes unable to plan UNION queries with literals in them. Example query:

```sql
select 'a' as type, 0 as id from user group by 2 
union all 
select 'c' as type, 0 as id from user_extra as t
```

Results in:
```
VT12001: unsupported: argument offsets did not line up for UNION
```

### PR DESCRIPTION
**Pull request by systay**
## Description
The Vitess planner was previously unable to handle UNION queries that included literals, resulting in an error. For example, the following query:

```sql
select 'a' as type, 0 as id from user group by 2 
union all 
select 'c' as type, 0 as id from user_extra as t
```

Results in:
```
VT12001: unsupported: argument offsets did not line up for UNION
```

## Solution:
To address this issue, the solution ensures that all operators that truncate columns actually perform the truncation during the planning phase. This alignment guarantees that the argument offsets match correctly for UNION queries, preventing the aforementioned error.

## Related Issue(s)
Fixes #16228

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on CI?
-   [ ] Documentation was added or is not required

### CODE REVIEW

**Review by frouioui — APPROVED** [review]
Looks good to me. Should we merge this to `release-20.0`/`-rc` since it's a bug fix?

File: go/vt/vtgate/planbuilder/operators/aggregator.go [hunk 1]
```diff
@@ -141,11 +144,18 @@ func (a *Aggregator) FindCol(ctx *plancontext.PlanningContext, in sqlparser.Expr
...
 	}
 	return -1
 }
 
+func (a *Aggregator) checkOffset(offset int) {
+	if a.ResultColumns > 0 && a.ResultColumns <= offset {
+		a.ResultColumns = offset + 1
+	}
+}
+
```
Comment (harshit-gangal) [inline go/vt/vtgate/planbuilder/operators/aggregator.go:158]: nice catch, we should add a comment here.

File: go/vt/vtgate/planbuilder/operators/aggregator.go [hunk 2]
```diff
@@ -157,6 +167,7 @@ func (a *Aggregator) AddColumn(ctx *plancontext.PlanningContext, reuse bool, gro
 	if reuse {
 		offset := a.findColInternal(ctx, ae, groupBy)
 		if offset >= 0 {
+			a.checkOffset(offset)
```
Comment (harshit-gangal) [inline go/vt/vtgate/planbuilder/operators/aggregator.go:170]: these are in two places here while returning, should we add a defer call instead?

**Review by GuptaManan100 — APPROVED** [review]

**Review by harshit-gangal — COMMENTED** [review]
Earlier, we wanted the truncation to happen only at the topmost operator that supported truncation. With the current changes, is there a case where the truncation is done by multiple operators?

**Review by harshit-gangal — APPROVED** [review]
