### PR TITLE
vreplication: fix infinite retry loop when terminal error message contains binary data

### LINKED ISSUE #19422: Bug Report: Online DDL / VReplication can enter infinite retry loop when terminal error message contains binary data
## Overview of the Issue

When an Online DDL migration (VReplication strategy) encounters a terminal error while copying a table that contains binary data (e.g., `VARBINARY`, `BLOB` columns with high bytes 0x80-0xFF), the migration can get stuck in `running` state indefinitely instead of transitioning to `failed`.

This occurs when the bulk INSERT query is large enough that the error message — which includes the full query text — exceeds the truncation limit. The message is truncated to 950 bytes by `MessageTruncate`, but when re-encoded for the UPDATE statement by `EncodeStringSQL`, invalid UTF-8 bytes in the binary data expand from 1 byte to 3 bytes each (U+FFFD replacement character). This can cause the stored value to exceed the `_vt.vreplication` `message` column limit (`varbinary(1000)`), and MySQL rejects the UPDATE with errno 1406 ("Data too long").

In practice, this requires a combination of sufficiently large binary column values and enough rows in a single copy batch so that the truncated error message still contains enough raw binary bytes for the encoding expansion to overflow.

When `setState()` fails, the controller in `runBlp()` returns the original non-nil error (`return err`), which causes `run()` to retry after a delay — creating an infinite loop. The VReplication stream never reaches `Error` state, so the Online DDL migration never transitions to `failed`.

The root cause is an encoding asymmetry: `encodeBytesSQLBytes2` (used to build the INSERT query) iterates over `[]byte` with `WriteByte`, preserving raw high bytes as single bytes. But `BufEncodeStringSQL` (used to encode the error message for the UPDATE) iterates over `string` with `range` (UTF-8 rune decoding) and `WriteRune`, expanding each invalid byte to 3 bytes.

## Reproduction Steps

1. Create a table with a binary column containing data with high bytes:
    ```sql
    CREATE TABLE t (
      id INT AUTO_INCREMENT PRIMARY KEY,
      bin_data VARBINARY(256) NOT NULL
    );
    -- Insert enough rows with high-byte binary data so the bulk INSERT
    -- query in the error message exceeds 950 bytes after truncation.
    INSERT INTO t (bin_data) VALUES (UNHEX(REPEAT('FF80FE90FD82FC83', 16)));
    -- Repeat ~20 times
    ```

2. Run an Online DDL that adds a NOT NULL column without a DEFAULT value:
    ```sql
    ALTER TABLE t ADD COLUMN new_col BIGINT NOT NULL;
    ```

3. The migration stays in `running` state indefinitely. In vttablet logs you'll see repeating errors:
    ```
    INTERNAL: unable to setState() in controller: could not set state: ... Data too long for column 'message'
    error in stream N, will retry after 5s: terminal error: ...
    ```

The same ALTER without binary data (e.g., on a table with only INT columns) correctly transitions to `failed` state. The existing `fail-no-default-value` vrepl_suite test passes for this reason.

## Binary Version

`main` branch at commit e881dd8e41 (and likely all prior versions since the encoding asymmetry has existed since the introduction of `MessageTruncate`).

## Operating System and Environment details

Any — the bug is in Go code, not platform-specific.

## Log Fragments

```
Failed to set error state: could not set message: update _vt.vreplication set message='task error: failed inserting rows: Field \'new_col\' doesn\'t have a default value (errno 1364) (sqlstate HY000) during query: insert into _vt_vrp_..._(id,bin_data) values (1,_binary\'<binary data>\') ... [TRUNCATED] ... ' where id=1

INTERNAL: unable to setState() in controller: could not set state: update _vt.vreplication set state='Error', message='terminal error: task error: ...' where id=1: Data too long for column 'message' at row 1 (errno 1406) (sqlstate 22001)

error in stream 1, will retry after 5s: terminal error: task error: failed inserting rows: Field 'new_col' doesn't have a default value (errno 1364) ...
```

The cycle repeats every 5 seconds indefinitely.

### PR DESCRIPTION
**Pull request by nickvanw**
## Description

When VReplication encounters a terminal error while copying a table with binary data (`VARBINARY`, `BLOB` columns containing bytes 0x80-0xFF), the migration can get stuck in `running` state indefinitely instead of transitioning to `failed`.

The error message includes the full INSERT query with raw binary bytes. `MessageTruncate` truncates to 950 bytes, but `EncodeStringSQL` expands invalid UTF-8 bytes from 1 to 3 bytes each (U+FFFD replacement character), causing the stored value to exceed the `varbinary(1000)` message column limit. `setState()` fails with errno 1406 ("Data too long"), and the controller returns the original non-nil error — creating an infinite retry loop.

The fix adds a three-tier fallback when `setState()` fails:
1. Retry with an aggressively truncated message (300 bytes — 300×3=900, fits even in the worst case)
2. Fall back to a static error message
3. Always return `nil` to stop the retry loop

Also adds a unit test documenting the encoding asymmetry and an e2e test (`fail-binary-no-default-value`) that reproduces the exact scenario.

## Related Issue(s)

Fixes #19422

## Checklist

- [x] "Backport to:" labels have been added if this change should be back-ported to release branches
- [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
- [x] Tests were added or are not required
- [x] Did the new or modified tests pass consistently locally and on CI?
- [x] Documentation was added or is not required

## Deployment Notes

No schema or configuration changes required. The fix only changes error handling behavior in the VReplication controller — terminal errors that previously caused infinite retry loops will now correctly transition to `Error` state.

### AI Disclosure

This PR was written primarily by Claude Code with human direction on the fix approach.

### CODE REVIEW

File: go/vt/binlog/binlogplayer/message_truncate_test.go [hunk 1]
```diff
@@ -0,0 +1,103 @@
+/*
+Copyright 2025 The Vitess Authors.
```
Comment (mattlord) [inline go/vt/binlog/binlogplayer/message_truncate_test.go]: We should use the current year. And, sometimes surprising to many of us, that year is 2026 :D

**Review by mattlord — COMMENTED** [review]
This seems OK to me, but I'm wondering why we should not go with a much simpler and failsafe method of:
```
diff --git a/go/vt/vttablet/tabletmanager/vreplication/vreplicator.go b/go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
index c63e63f9db..ca0a07d081 100644
--- a/go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
+++ b/go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
@@ -515,7 +515,7 @@ func (vr *vreplicator) setState(state binlogdatapb.VReplicationWorkflowState, me
 		})
 	}
 	vr.stats.State.Store(state.String())
-	query := fmt.Sprintf("update _vt.vreplication set state=%v, message=%v where id=%v", encodeString(state.String()), encodeString(binlogplayer.MessageTruncate(message)), vr.id)
+	query := fmt.Sprintf("update _vt.vreplication set state=%v, message=left(%v, 1000) where id=%v", encodeString(state.String()), encodeString(binlogplayer.MessageTruncate(message)), vr.id)
 	// If we're batching a transaction, then include the state update
 	// in the current transaction batch.
 	if vr.dbClient.InTransaction && vr.dbClient.maxBatchSize > 0 {
```

With these changes in the branch, the new test still passes:
```
diff --git a/go/vt/vttablet/tabletmanager/vreplication/controller.go b/go/vt/vttablet/tabletmanager/vreplication/controller.go
index 32ffb0c4f5..b5415597ae 100644
--- a/go/vt/vttablet/tabletmanager/vreplication/controller.go
+++ b/go/vt/vttablet/tabletmanager/vreplication/controller.go
@@ -312,20 +312,7 @@ func (ct *controller) runBlp(ctx context.Context) (err error) {
 			err = vterrors.Wrapf(err, TerminalErrorIndicator)
 			if errSetState := vr.setState(binlogdatapb.VReplicationWorkflowState_Error, err.Error()); errSetState != nil {
 				log.Error(fmt.Sprintf("INTERNAL: unable to setState() in controller: %v. Could not set error text to: %v.", errSetState, err))
-				// The message column is varbinary(1000). The normal truncation limit
-				// (950 bytes) can still overflow after SQL encoding when the error
-				// contains binary data with invalid UTF-8 bytes, which EncodeStringSQL
-				// expands from 1 byte to 3 bytes each. Retry with an aggressively
-				// truncated message: 300 bytes * 3 = 900, which fits even in the
-				// pathological worst case where every byte is invalid UTF-8.
-				if errRetry := vr.setState(binlogdatapb.VReplicationWorkflowState_Error, binlogplayer.LimitString(err.Error(), 300)); errRetry != nil {
-					log.Error(fmt.Sprintf("INTERNAL: unable to setState() with truncated message: %v", errRetry))
-					// Last resort: set the error state with a static message.
-					if errEmpty := vr.setState(binlogdatapb.VReplicationWorkflowState_Error, "terminal error: failed to save error message; check vttablet logs"); errEmpty != nil {
-						log.Error(fmt.Sprintf("INTERNAL: unable to setState() even with static message: %v", errEmpty))
-					}
-				}
-				return nil // still stop the retry loop; continuing to retry will not help
+				return err // yes, err and not errSetState.
 			}
 			log.Error(fmt.Sprintf("vreplication stream %d going into error state due to %+v", ct.id, err))
 			return nil // this will cause vreplicate to quit the workflow
diff --git a/go/vt/vttablet/tabletmanager/vreplication/vreplicator.go b/go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
index c63e63f9db..ca0a07d081 100644
--- a/go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
+++ b/go/vt/vttablet/tabletmanager/vreplication/vreplicator.go
@@ -515,7 +515,7 @@ func (vr *vreplicator) setState(state binlogdatapb.VReplicationWorkflowState, me
 		})
 	}
 	vr.stats.State.Store(state.String())
-	query := fmt.Sprintf("update _vt.vreplication set state=%v, message=%v where id=%v", encodeString(state.String()), encodeString(binlogplayer.MessageTruncate(message)), vr.id)
+	query := fmt.Sprintf("update _vt.vreplication set state=%v, message=left(%v, 1000) where id=%v", encodeString(state.String()), encodeString(binlogplayer.MessageTruncate(message)), vr.id)
 	// If we're batching a transaction, then include the state update
 	// in the current transaction batch.
 	if vr.dbClient.InTransaction && vr.dbClient.maxBatchSize > 0 {

```

```
go test -test.fullpath=true -timeout 30s -run ^TestMessageTruncateWithBinaryData$ vitess.io/vitess/go/vt/binlog/binlogplayer

ok  	vitess.io/vitess/go/vt/binlog/binlogplayer	1.383s
```

**Review by mattlord — APPROVED** [review]
LGTM! Thanks, @nickvanw !
