### PR TITLE
Change local_metadata.value to MEDIUMBLOB

### LINKED ISSUE #5377: Snapshot Keyspaces: RestorePosition doesn't fit in local_metadata table
I'm blocked from restoring a backup because the replication position string is too long to fit in the local_metadata table, which was added for Snapshot Keyspaces:

```
F1029 23:40:46.360537       1 action_agent.go:324] RestoreFromBackup failed: Data too long for column 'value' at row 1 (errno 1406) (sqlstate 22001) during query: INSERT INTO _vt.local_metadata (name,value, db_name) VALUES ('RestorePosition','MySQL56/6b4b6b75-b8b8-11e9-8b73-6ae328f38128:1-15,7f2cc2a3-9b0b-11e9-94c3-760882732513:1-3,935a9f52-9b0b-11e9-999b-ce1b53fb507c:1-8,93a9ad68-9b0b-11e9-a3cd-cebf76dff321:1-33,93b17ec0-9b0b-11e9-9a45-be1232742c40:1-24,9e6432bf-ace3-11e9-a9e1-924619225ecf:1-8','vt_main') ON DUPLICATE KEY UPDATE value = 'MySQL56/6b4b6b75-b8b8-11e9-8b73-6ae328f38128:1-15,7f2cc2a3-9b0b-11e9-94c3-760882732513:1-3,935a9f52-9b0b-11e9-999b-ce1b53fb507c:1-8,93a9ad68-9b0b-11e9-a3cd-cebf76dff321:1-33,93b17ec0-9b0b-11e9-9a45-be1232742c40:1-24,9e6432bf-ace3-11e9-a9e1-924619225ecf:1-8'
```

The replication position string can technically grow without bound, but I suppose we have to decide on some larger column size for local_metadata. We can look at what size we use in places like the reparent journal. Hopefully it's straighforward to do an ALTER on startup. Or since it's local metadata, maybe we can just drop and recreate?

### PR DESCRIPTION
**Pull request by deepthi**
To accomodate long replication positions, change type of column.
Fixes #5377 

Signed-off-by: deepthi <deepthi@planetscale.com>

### CODE REVIEW

File: go/vt/mysqlctl/backup.go [hunk 1]
```diff
@@ -318,15 +319,14 @@ func Restore(ctx context.Context, params RestoreParams) (*BackupManifest, error)
...
-	//params.LocalMetadata["RestorePosition"] = mysql.EncodePosition(manifest.Position)
+	params.LocalMetadata["RestorePosition"] = mysql.EncodePosition(manifest.Position)
 
 	// Populate local_metadata before starting without --skip-networking,
 	// so it's there before we start announcing ourselves.
 	params.Logger.Infof("Restore: populating local_metadata")
 	err = PopulateMetadataTables(params.Mysqld, params.LocalMetadata, params.DbName)
 	if err != nil {
-		return nil, err
+		params.Logger.Errorf("Error populating metadata tables: %v, continuing..", err)
```
Comment (enisoc) [inline go/vt/mysqlctl/backup.go]: If local_metadata fails, it could cause integrations like Orchestrator to exhibit unexpected behavior. Did we ever have PopulateMetadataTables optional like this before? Or was it always required?

File: go/vt/mysqlctl/metadata_tables.go [hunk 2]
```diff
@@ -46,6 +46,9 @@ var (
 	sqlAlterLocalMetadataTable = []string{
 		`ALTER TABLE _vt.local_metadata ADD COLUMN db_name VARBINARY(255) NOT NULL DEFAULT ''`,
 		`ALTER TABLE _vt.local_metadata DROP PRIMARY KEY, ADD PRIMARY KEY(name, db_name)`,
+		// VARCHAR(255) is not long enough to hold replication positions, hence changing to
+		// MEDIUMBLOB.
+		`ALTER TABLE _vt.local_metadata CHANGE value value MEDIUMBLOB`,
```
Comment (enisoc) [inline go/vt/mysqlctl/metadata_tables.go]: If this is run again, does it result in the same `ERDupFieldName` error that we already ignore?

Also, do we need to add `NOT NULL` to match the CREATE TABLE version?

Comment (deepthi) [reply go/vt/mysqlctl/metadata_tables.go]: Running again produces no errors. 
We don't need to add `NOT NULL`. Changing the column type doesn't change it's nullable status.

File: go/vt/mysqlctl/backup.go (hunk 1 above)
Comment (deepthi) [reply go/vt/mysqlctl/backup.go]: From the time it was introduced, an error populating metadata has always been fatal.

Comment (deepthi) [reply go/vt/mysqlctl/backup.go]: I have reverted this change.

**Comment by deepthi** [comment]
Tested manually that the alter works correctly.
Test procedure:
```
git checkout master
make
cd examples/local
./101_initial_cluster.sh
./lvtctl.sh BackupShard commerce/0
cd ../..
git checkout ds-repl-pos-len
make
cd examples/local
CELL=zone1 KEYSPACE=commerce UID_BASE=500 ./vttablet-up.sh 
mysql -S ~/go/vtdataroot/vt_0000000500/mysql.sock -uroot
mysql> use _vt;
mysql> describe local_metadata;
+---------+----------------+------+-----+---------+-------+
| Field   | Type           | Null | Key | Default | Extra |
+---------+----------------+------+-----+---------+-------+
| name    | varchar(255)   | NO   | PRI | NULL    |       |
| value   | mediumblob     | NO   |     | NULL    |       |
| db_name | varbinary(255) | NO   | PRI | NULL    |       |
+---------+----------------+------+-----+---------+-------+
3 rows in set (0.00 sec)
mysql> select * from local_metadata;
+--------------------+--------------------------------------------------+-------------+
| name               | value                                            | db_name     |
+--------------------+--------------------------------------------------+-------------+
| Alias              | zone1-0000000500                                 | vt_commerce |
| ClusterAlias       | commerce.0                                       | vt_commerce |
| DataCenter         | zone1                                            | vt_commerce |
| PromotionRule      | neutral                                          | vt_commerce |
| RestoredBackupTime | 2019-10-30T22:00:49Z                             | vt_commerce |
| RestorePosition    | MySQL56/a5dc5cbb-fb60-11e9-84b6-34e12d1e6711:1-9 | vt_commerce |
+--------------------+--------------------------------------------------+-------------+
6 rows in set (0.00 sec)
```
