### PR TITLE
Fix #4288 vschema errors should not bring down vtgate

### LINKED ISSUE #4288: Bad VSchema Brings Down All vtgates
#### Overview of the Issue
A given Vitess installation might comprise multiple vschema JSON documents, corresponding to multiple keyspaces.  Vtgate binaries will (apprently) load and validate _all_ vschemas for all the keyspaces they are watching.

If a single bad vschema is submitted, all corresponding vtgates will attempt to load this vschema and crash.  This means that, despite the vtgates being loosely coupled (so one can fail without affecting the availability of others) by design, a bad vschema for a keyspace (that might not even be serving!) can actually destroy availability for other, unrelated keyspaces as the vtgates all go down.  In other words the vtgates are _tightly_ coupled through the vschema.

#### Reproduction Steps
Construct a two-keyspace Vitess installation with a vtgate.  Deploy a valid vschema for keyspace A.  Deploy a vschema with an error to keyspace B, such as defining a sequence which refers to a SQL table that doesn't exist.  All vtgates will fail to come up as they reject vschema B.

#### Binary version
(Need to check specific hash, this was initially encountered 10/3/2018)

#### Operating system and Environment details
Running in GKE

#### Log Fragments
Here we see vtgate complain that the SQL table `phinxlog_id_seq` does not exist.  This causes vtgate not to start up at all, so it won't even serve keyspace which _do_ have 100% valid mysql schema & vschema.

From vtgate:
```
E1004 14:22:44.987501       1 vtgate.go:1105] Execute: table dual not found, request: map[Sql:select @@version_comment limit 1 BindVariables:map[vtg1:type:INT64 value:"1" ] Session:autocommit:true options:<included_fields:ALL >]
E1004 14:22:49.987805       1 throttled.go:77] Execute: skipped 1 log messages
I1004 14:27:50.976403       1 zk_conn.go:304] zk conn: session for addr zk-app-0.zk-app-hs.default.svc.cluster.local:2181,zk-app-1.zk-app-hs.default.svc.cluster.local:2181,zk-app-2.zk-app-hs.default.svc.cluster.local:2181 event: {EventNodeDataChanged Unknown /vitess/app/SrvVSchema <nil> }
W1004 14:27:50.977908       1 vschema_manager.go:87] Error creating VSchema for cell app (will try again next update): cannot resolve sequence phinxlog_id_seq: table phinxlog_id_seq not found
E1004 14:27:50.989194       1 vtgate.go:1105] Execute: table dual not found, request: map[Session:autocommit:true options:<included_fields:ALL > Sql:select @@version_comment limit 1 BindVariables:map[vtg1:type:INT64 value:"1" ]]
E1004 14:27:55.989510       1 throttled.go:77] Execute: skipped 1 log messages
```

### PR DESCRIPTION
**Pull request by deepthi**
Save errors per keyspace in vschema instead of failing on the first
error so that keyspaces with valid vschema don't get invalidated by a
keyspace with vschema errors

Signed-off-by: deepthi <deepthi@planetscale.com>

### CODE REVIEW

File: go/vt/vtgate/vindexes/vschema.go [hunk 1]
```diff
@@ -97,10 +98,17 @@ func (ks *KeyspaceSchema) MarshalJSON() ([]byte, error) {
 		Sharded  bool              `json:"sharded,omitempty"`
 		Tables   map[string]*Table `json:"tables,omitempty"`
 		Vindexes map[string]Vindex `json:"vindexes,omitempty"`
+		Error    string            `json:"error,omitempty"`
 	}{
 		Sharded:  ks.Keyspace.Sharded,
 		Tables:   ks.Tables,
 		Vindexes: ks.Vindexes,
+		Error: func(ks *KeyspaceSchema) string {
```
Comment (sougou) [inline go/vt/vtgate/vindexes/vschema.go]: I think this is ok here, but should be used with care because inline functions incur additional overhead.

File: go/vt/vtgate/vindexes/vschema.go [hunk 2]
```diff
@@ -207,19 +209,22 @@ func buildTables(source *vschemapb.SrvVSchema, vschema *VSchema) error {
 			if table.Pinned != "" {
 				decoded, err := hex.DecodeString(table.Pinned)
 				if err != nil {
-					return fmt.Errorf("could not decode the keyspace id for pin: %v", err)
+					ksvschema.Error = fmt.Errorf("could not decode the keyspace id for pin: %v", err)
+					goto end
```
Comment (sougou) [inline go/vt/vtgate/vindexes/vschema.go]: Instead of this, you can tag the outer loop like this:
```
outer:
  for ksname...
```

and then you can `continue outer`.
