### PR TITLE
operator precedence must take associativity into consideration

### LINKED ISSUE #6734: Operator precedence issue
#### Overview of the Issue

sqlparser seems to not respect parentheses, `x * (a div b)` is executed as `x * a div b`. It works correctly when executed directly in MySQL.

#### Reproduction Steps

* Execute `select hex(0x4000000000000000*(1500 div 1000));`

**Expected output:**
```
+-----------------------------------------+
| hex(0x4000000000000000*(1500 div 1000)) |
+-----------------------------------------+
| 4000000000000000                        |
+-----------------------------------------+
1 row in set (0.00 sec)
```

**Actual output:**
```
ERROR 1690 (22003): vtgate: http://localhost:15001/: target: shard.0.master, used tablet: zone1-150 (localhost): vttablet: rpc error: code = InvalidArgument desc = BIGINT UNSIGNED value is out of range in '(0x4000000000000000 * 1500)' (errno 1690) (sqlstate 22003) (CallerID: userData1): Sql: "select hex(0x4000000000000000 * :vtg1 div :vtg2) from dual", BindVars: {#maxLimit: "type:INT64 value:\"10001\" "vtg1: "type:INT64 value:\"1500\" "vtg2: "type:INT64 value:\"1000\" "}
```

#### Operating system and Environment details

- Operating system: `Ubuntu 18.04.5 LTS`
- Kernel version: `Linux 5.3.0-62-generic`
- Architecture: `x86_64`

### PR DESCRIPTION
**Pull request by systay**
The Vitess AST printer was not taking associativity into consideration and stripping away parenthesis when it should not.

Fixes #6734

### CODE REVIEW

File: go/vt/sqlparser/precedence_test.go [hunk 1]
```diff
@@ -142,6 +142,14 @@ func TestParens(t *testing.T) {
 		{in: "(a | b) between (5) and (7)", expected: "a | b between 5 and 7"},
 		{in: "(a and b) between (5) and (7)", expected: "(a and b) between 5 and 7"},
 		{in: "(true is true) is null", expected: "(true is true) is null"},
+		{in: "3 * (100 div 3)", expected: "3 * (100 div 3)"},
+		{in: "100 div 2 div 2", expected: "100 div 2 div 2"},
+		{in: "100 div (2 div 2)", expected: "100 div (2 div 2)"},
+		{in: "(100 div 2) div 2", expected: "100 div 2 div 2"},
+		{in: "((((((1000))))))", expected: "1000"},
+		{in: "100 - (50 + 10)", expected: "100 - (50 + 10)"},
+		{in: "100 - 50 + 10", expected: "100 - 50 + 10"},
```
Comment (shlomi-noach) [inline go/vt/sqlparser/precedence_test.go:151]: Please add a test for `10 - 2 - 1`

**Review by shlomi-noach — CHANGES_REQUESTED** [review]
I'm not familiar with the codebase and I can't make much sense of the actual logic change; just one request for an additional test case which we saw was handled incorrectly.

**Review by shlomi-noach — APPROVED** [review]
