### PR TITLE
go/cmd: Audit and fix context.Background() usage

### LINKED ISSUE #15927: Bug Report: vtgate can crash on shutdown
### Overview of the Issue

It's possible that `vtgate` crashes on a shutdown:

```
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0xe53bb0]
goroutine 983 [running]:
vitess.io/vitess/go/vt/topo.(*Server).GetCellInfo(0xc0008a6380, {0x23a8b10, 0xc000b8e4b0}, {0x7ffd49199841, 0xe}, 0x0)
	vitess.io/vitess/go/vt/topo/cell_info.go:71 +0x110
vitess.io/vitess/go/vt/topo.(*Server).ConnForCell(0xc0008a6380, {0x23a8b10?, 0xc000b8e4b0?}, {0x7ffd49199841, 0xe})
	vitess.io/vitess/go/vt/topo/server.go:269 +0x159
vitess.io/vitess/go/vt/topo.(*Server).WatchSrvVSchema(0x7ffd49199841?, {0x23a8b10, 0xc000b8e4b0}, {0x7ffd49199841?, 0x0?})
	vitess.io/vitess/go/vt/topo/srv_vschema.go:43 +0x37
vitess.io/vitess/go/vt/srvtopo.NewResilientServer.NewSrvVSchemaWatcher.func2(0xc000a66140)
	vitess.io/vitess/go/vt/srvtopo/watch_srvvschema.go:44 +0xcb
created by vitess.io/vitess/go/vt/srvtopo.(*watchEntry).ensureWatchingLocked in goroutine 949
	vitess.io/vitess/go/vt/srvtopo/watch.go:117 +0x10c
```

### Reproduction Steps

This seems to happen because we've passed in a never expiring context into the watcher. This means when we shut down, the topo connection is closed but the context for the watcher is not cancelled, so it panics with this error.

### Binary Version

```sh
-
```

### Operating System and Environment details

```sh
-
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by dbussink**
This removes a bunch of the context.Background() usage for the command line entrypoints. In general, we should use the command context (which normally is context.Background(), but it's more semantically accurate).

There's a few cases where we need more fixes. Specifically in vtgate where we want to setup a cancellable context and cancel it when we shut down. This is the one that ends up running things like the topo watcher and this ensures things are closed appropriately.

Similarly in vtcombo we apply similar fixes so that we always correctly cancel the context on shutdown and the same for vttablet.

## Related Issue(s)

Fixes #15927

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/cmd/vtcombo/cli/main.go [hunk 1]
```diff
@@ -189,17 +189,20 @@ func run(cmd *cobra.Command, args []string) (err error) {
 		cmd.Flags().Set("log_dir", "$VTDATAROOT/tmp")
 	}
 
+	ctx, cancel := context.WithCancel(cmd.Context())
+	defer cancel()
```
Comment (dbussink) [inline go/cmd/vtcombo/cli/main.go:193]: This creates the toplevel context here and then uses it for example for creating the memory topo and other operations too. 

Once this cancels, it ensures that things like the topo and watchers etc. are closed in the right order.

File: go/cmd/vtcombo/cli/main.go [hunk 2]
```diff
@@ -333,22 +337,13 @@ func run(cmd *cobra.Command, args []string) (err error) {
...
+		startVschemaWatcher(ctx, vschemaPersistenceDir, ts)
 	}
 
 	servenv.OnRun(func() {
 		addStatusParts(vtg)
 	})
 
-	servenv.OnTerm(func() {
-		log.Error("Terminating")
-		// FIXME(alainjobart): stop vtgate
```
Comment (dbussink) [inline go/cmd/vtcombo/cli/main.go:345]: This is actually fixed now that the context is cancelled that is used to setup `vtgate`, so we can remove the TODO and the whole block here as it does nothing.

File: go/cmd/vtcombo/cli/main.go [hunk 3]
```diff
@@ -333,22 +337,13 @@ func run(cmd *cobra.Command, args []string) (err error) {
...
-	})
-	servenv.OnClose(func() {
-		// We will still use the topo server during lameduck period
-		// to update our state, so closing it in OnClose()
-		ts.Close()
-	})
```
Comment (dbussink) [inline go/cmd/vtcombo/cli/main.go:351]: Closing the topo isn't a long running operation or anything, so we can do it with a `defer` when we create it, removing the need for this callback to be used here at all. 

It doesn't change the order of things, since right after `RunDefault` below we return, and then we'd run the `defer` now to close `ts` as well.

File: go/cmd/vtgate/cli/cli.go [hunk 4]
```diff
@@ -146,7 +146,9 @@ func run(cmd *cobra.Command, args []string) error {
 	ts := topo.Open()
 	defer ts.Close()
 
-	resilientServer = srvtopo.NewResilientServer(context.Background(), ts, srvTopoCounts)
+	ctx, cancel := context.WithCancel(cmd.Context())
+	defer cancel()
+	resilientServer = srvtopo.NewResilientServer(ctx, ts, srvTopoCounts)
```
Comment (dbussink) [inline go/cmd/vtgate/cli/cli.go:151]: This fix ensures that during shutdown we don't hit the panic from #15927, because the context will have been cancelled always before the topo is closed (which is deferred right above here).

File: go/cmd/vttablet/cli/cli.go [hunk 5]
```diff
@@ -110,6 +110,12 @@ func init() {
 func run(cmd *cobra.Command, args []string) error {
 	servenv.Init()
 
+	ts := topo.Open()
+	defer ts.Close()
+
+	ctx, cancel := context.WithCancel(cmd.Context())
+	defer cancel()
```
Comment (dbussink) [inline go/cmd/vttablet/cli/cli.go:117]: This logic is moved here to match how `vtgate` is set up, so we open and defer close / cancel in the right order.

File: go/cmd/vttablet/cli/cli.go [hunk 6]
```diff
@@ -170,9 +175,6 @@ func run(cmd *cobra.Command, args []string) error {
 		// Close the tm so that our topo entry gets pruned properly and any
 		// background goroutines that use the topo connection are stopped.
 		tm.Close()
-
-		// tm uses ts. So, it should be closed after tm.
-		ts.Close()
```
Comment (dbussink) [inline go/cmd/vttablet/cli/cli.go:175]: We handle this with the above `defer`, so no need to close it here.

File: go/cmd/vttablet/cli/cli.go (hunk 5 above)
Comment (mattlord) [reply go/cmd/vttablet/cli/cli.go:117]: Can you also add a comment in the code to this effect as well? That will help to ensure that this implied behavior is not changed later by someone not fully realizing the important of the order here.

**Review by mattlord — APPROVED** [review]
This is a nice piece of cleanup! Thank you ❤️

**Review by frouioui — APPROVED** [review]
This is really nice

**Review by GuptaManan100 — APPROVED** [review]
LGTM!
