### PR TITLE
rollback changes made during PlannedReparent if we encounter errors

### LINKED ISSUE #4481: Cancel Reparent if PlannedReparentShard fails
Per a conversation on Slack with @sougou, the current behavior when `PlannedReparentShard` fails is dangerous, because it leaves things in a broken state.
https://vitess.slack.com/archives/C0PQY0PTK/p1545347205331200

- [ ] Implement a cancel / rollback of the reparent if it fails
- [ ] Have all actions use a short timeout by default. Should that decrease the default `action_timeout` or have all actions use `wait_slave_timeout` instead?

### PR DESCRIPTION
**Pull request by deepthi**
Fix #4481 
Attempt to undo changes made during reparenting if we encounter a failure in a critical phase (DemoteMaster / PromoteSlave). Once those steps are complete we have reached a point of no return and cannot rollback.
Rather than separating the cancel logic into a function, the approach taken here is to rollback as and when we encounter an error. That way we know exactly which steps have to be rolled back, and there are many. The exception is DemoteMaster, for which an Undo function has been implemented.
One thing that hasn't been done yet is to check the new master's replication lag before going ahead with DemoteMaster. That will be done as a separate PR.

Signed-off-by: deepthi <deepthi@planetscale.com>

### CODE REVIEW

**Comment by derekperkins** [comment]
References #4481

File: go/vt/wrangler/reparent.go [hunk 1]
```diff
@@ -426,6 +427,10 @@ func (wr *Wrangler) plannedReparentShardLocked(ctx context.Context, ev *events.R
 	event.DispatchUpdate(ev, "promoting slave")
 	rp, err = wr.tmc.PromoteSlaveWhenCaughtUp(ctx, masterElectTabletInfo.Tablet, rp)
 	if err != nil {
+		// if this fails it is not enough to return an error. we should rollback all the changes made by DemoteMaster
+		if err1 := wr.tmc.UndoDemoteMaster(ctx, oldMasterTabletInfo.Tablet); err1 != nil {
+			log.Warningf("Encountered error %v while trying to undo DemoteMaster", err1)
```
Comment (derekperkins) [inline go/vt/wrangler/reparent.go]: If this is encountered, I'm not sure where that leaves the state of the shard.

Comment (deepthi) [reply go/vt/wrangler/reparent.go]: if the previous call to DemoteMaster succeeded, then this should also succeed unless something changed in the meantime. if it does fail, then you are back in today's situation where PromoteSlave failed and the cluster is in an inconsistent state.

**Comment by deepthi** [comment]
> I don't know if this is worth a new flag or not, but it seems reasonable to me to say "if replication delay on the master-elect is greater than 10 seconds, error out early." @hmcgonig and @acharis at HubSpot are doing a similar check before they even run `PlannedReparentShard`.

@sougou and I discussed this and decided that the operator should be able to specify their tolerance, so yeah, a new flag.

File: go/vt/wrangler/reparent.go [hunk 2]
```diff
@@ -425,7 +426,11 @@ func (wr *Wrangler) plannedReparentShardLocked(ctx context.Context, ev *events.R
 	wr.logger.Infof("promote slave %v", masterElectTabletAliasStr)
 	event.DispatchUpdate(ev, "promoting slave")
 	rp, err = wr.tmc.PromoteSlaveWhenCaughtUp(ctx, masterElectTabletInfo.Tablet, rp)
-	if err != nil {
+	if err != nil || (ctx.Err() != nil && ctx.Err() == context.DeadlineExceeded) {
+		// if this fails it is not enough to return an error. we should rollback all the changes made by DemoteMaster
+		if err1 := wr.tmc.UndoDemoteMaster(ctx, oldMasterTabletInfo.Tablet); err1 != nil {
```
Comment (sougou) [inline go/vt/wrangler/reparent.go]: This will not work if the context has already expired. Is there a higher level context with longer timeout that we can use for this?

There should be one with the action timeout. Maybe use that, but with a shorter timeout.

Comment (deepthi) [reply go/vt/wrangler/reparent.go]: Ooh, I missed that. No, there is no higher level context, this is it.
