### PR TITLE
[cli] [tabletserver/tabletenv] Migrate tabletenv flags to pflags

### LINKED ISSUE #10984: Switch flag definitions to be on pflag instead of flag in `package go/vt/vttablet/tabletserver/tabletenv`
Part of https://github.com/vitessio/vitess/issues/10697.

Current flags:

```
$ git grep -E "\bflag\.[A-Z]" -- go/vt/vttablet/tabletserver/tabletenv/*.go
go/vt/vttablet/tabletserver/tabletenv/config.go:        queryLogHandler = flag.String("query-log-stream-handler", "/debug/querylog", "URL handler for streaming queries log")
go/vt/vttablet/tabletserver/tabletenv/config.go:        txLogHandler    = flag.String("transaction-log-stream-handler", "/debug/txlog", "URL handler for streaming transactions log")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.IntVar(&currentConfig.OltpReadPool.Size, "queryserver-config-pool-size", defaultConfig.OltpReadPool.Size, "query server read pool size, connection pool is used by regular queries (non streaming, not in a transaction)")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.IntVar(&currentConfig.OltpReadPool.PrefillParallelism, "queryserver-config-pool-prefill-parallelism", defaultConfig.OltpReadPool.PrefillParallelism, "query server read pool prefill parallelism, a non-zero value will prefill the pool using the specified parallism.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.IntVar(&currentConfig.OlapReadPool.Size, "queryserver-config-stream-pool-size", defaultConfig.OlapReadPool.Size, "query server stream connection pool size, stream pool is used by stream queries: queries that return results to client in a streaming fashion")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.IntVar(&currentConfig.OlapReadPool.PrefillParallelism, "queryserver-config-stream-pool-prefill-parallelism", defaultConfig.OlapReadPool.PrefillParallelism, "query server stream pool prefill parallelism, a non-zero value will prefill the pool using the specified parallelism")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.IntVar(&currentConfig.TxPool.Size, "queryserver-config-transaction-cap", defaultConfig.TxPool.Size, "query server transaction cap is the maximum number of transactions allowed to happen at any given point of a time for a single vttablet. E.g. by setting transaction cap to 100, there are at most 100 transactions will be processed by a vttablet and the 101th transaction will be blocked (and fail if it cannot get connection within specified timeout)")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.IntVar(&currentConfig.TxPool.PrefillParallelism, "queryserver-config-transaction-prefill-parallelism", defaultConfig.TxPool.PrefillParallelism, "query server transaction prefill parallelism, a non-zero value will prefill the pool using the specified parallism.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.IntVar(&currentConfig.MessagePostponeParallelism, "queryserver-config-message-postpone-cap", defaultConfig.MessagePostponeParallelism, "query server message postpone cap is the maximum number of messages that can be postponed at any given time. Set this number to substantially lower than transaction cap, so that the transaction pool isn't exhausted by the message subsystem.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.IntVar(&currentConfig.Oltp.MaxRows, "queryserver-config-max-result-size", defaultConfig.Oltp.MaxRows, "query server max result size, maximum number of rows allowed to return from vttablet for non-streaming queries.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.IntVar(&currentConfig.Oltp.WarnRows, "queryserver-config-warn-result-size", defaultConfig.Oltp.WarnRows, "query server result size warning threshold, warn if number of rows returned from vttablet for non-streaming queries exceeds this")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.PassthroughDML, "queryserver-config-passthrough-dmls", defaultConfig.PassthroughDML, "query server pass through all dml statements without rewriting")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.IntVar(&currentConfig.StreamBufferSize, "queryserver-config-stream-buffer-size", defaultConfig.StreamBufferSize, "query server stream buffer size, the maximum number of bytes sent from vttablet for each stream call. It's recommended to keep this value in sync with vtgate's stream_buffer_size.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.IntVar(&currentConfig.QueryCacheSize, "queryserver-config-query-cache-size", defaultConfig.QueryCacheSize, "query server query cache size, maximum number of queries to be cached. vttablet analyzes every incoming query and generate a query plan, these plans are being cached in a lru cache. This config controls the capacity of the lru cache.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.Int64Var(&currentConfig.QueryCacheMemory, "queryserver-config-query-cache-memory", defaultConfig.QueryCacheMemory, "query server query cache size in bytes, maximum amount of memory to be used for caching. vttablet analyzes every incoming query and generate a query plan, these plans are being cached in a lru cache. This config controls the capacity of the lru cache.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.QueryCacheLFU, "queryserver-config-query-cache-lfu", defaultConfig.QueryCacheLFU, "query server cache algorithm. when set to true, a new cache algorithm based on a TinyLFU admission policy will be used to improve cache behavior and prevent pollution from sparse queries")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.SignalWhenSchemaChange, "queryserver-config-schema-change-signal", defaultConfig.SignalWhenSchemaChange, "query server schema signal, will signal connected vtgates that schema has changed whenever this is detected. VTGates will need to have -schema_change_signal enabled for this to work")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.IntVar(&currentConfig.OltpReadPool.MaxWaiters, "queryserver-config-query-pool-waiter-cap", defaultConfig.OltpReadPool.MaxWaiters, "query server query pool waiter limit, this is the maximum number of queries that can be queued waiting to get a connection")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.IntVar(&currentConfig.OlapReadPool.MaxWaiters, "queryserver-config-stream-pool-waiter-cap", defaultConfig.OlapReadPool.MaxWaiters, "query server stream pool waiter limit, this is the maximum number of streaming queries that can be queued waiting to get a connection")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.IntVar(&currentConfig.TxPool.MaxWaiters, "queryserver-config-txpool-waiter-cap", defaultConfig.TxPool.MaxWaiters, "query server transaction pool waiter limit, this is the maximum number of transactions that can be queued waiting to get a connection")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.StrictTableACL, "queryserver-config-strict-table-acl", defaultConfig.StrictTableACL, "only allow queries that pass table acl checks")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.EnableTableACLDryRun, "queryserver-config-enable-table-acl-dry-run", defaultConfig.EnableTableACLDryRun, "If this flag is enabled, tabletserver will emit monitoring metrics and let the request pass regardless of table acl check results")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.StringVar(&currentConfig.TableACLExemptACL, "queryserver-config-acl-exempt-acl", defaultConfig.TableACLExemptACL, "an acl that exempt from table acl checking (this acl is free to access any vitess tables).")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.TerseErrors, "queryserver-config-terse-errors", defaultConfig.TerseErrors, "prevent bind vars from escaping in client error messages")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.AnnotateQueries, "queryserver-config-annotate-queries", defaultConfig.AnnotateQueries, "prefix queries to MySQL backend with comment indicating vtgate principal (user) and target tablet type")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.WatchReplication, "watch_replication_stream", false, "When enabled, vttablet will stream the MySQL replication stream from the local server, and use it to update schema when it sees a DDL.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.TrackSchemaVersions, "track_schema_versions", false, "When enabled, vttablet will store versions of schemas at each position that a DDL is applied and allow retrieval of the schema corresponding to a position")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.TwoPCEnable, "twopc_enable", defaultConfig.TwoPCEnable, "if the flag is on, 2pc is enabled. Other 2pc flags must be supplied.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.StringVar(&currentConfig.TwoPCCoordinatorAddress, "twopc_coordinator_address", defaultConfig.TwoPCCoordinatorAddress, "address of the (VTGate) process(es) that will be used to notify of abandoned transactions.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&enableHotRowProtection, "enable_hot_row_protection", false, "If true, incoming transactions for the same row (range) will be queued and cannot consume all txpool slots.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&enableHotRowProtectionDryRun, "enable_hot_row_protection_dry_run", false, "If true, hot row protection is not enforced but logs if transactions would have been queued.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.IntVar(&currentConfig.HotRowProtection.MaxQueueSize, "hot_row_protection_max_queue_size", defaultConfig.HotRowProtection.MaxQueueSize, "Maximum number of BeginExecute RPCs which will be queued for the same row (range).")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.IntVar(&currentConfig.HotRowProtection.MaxGlobalQueueSize, "hot_row_protection_max_global_queue_size", defaultConfig.HotRowProtection.MaxGlobalQueueSize, "Global queue limit across all row (ranges). Useful to prevent that the queue can grow unbounded.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.IntVar(&currentConfig.HotRowProtection.MaxConcurrency, "hot_row_protection_concurrent_transactions", defaultConfig.HotRowProtection.MaxConcurrency, "Number of concurrent transactions let through to the txpool/MySQL for the same hot row. Should be > 1 to have enough 'ready' transactions in MySQL and benefit from a pipelining effect.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.EnableTransactionLimit, "enable_transaction_limit", defaultConfig.EnableTransactionLimit, "If true, limit on number of transactions open at the same time will be enforced for all users. User trying to open a new transaction after exhausting their limit will receive an error immediately, regardless of whether there are available slots or not.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.EnableTransactionLimitDryRun, "enable_transaction_limit_dry_run", defaultConfig.EnableTransactionLimitDryRun, "If true, limit on number of transactions open at the same time will be tracked for all users, but not enforced.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.Float64Var(&currentConfig.TransactionLimitPerUser, "transaction_limit_per_user", defaultConfig.TransactionLimitPerUser, "Maximum number of transactions a single user is allowed to use at any time, represented as fraction of -transaction_cap.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.TransactionLimitByUsername, "transaction_limit_by_username", defaultConfig.TransactionLimitByUsername, "Include VTGateCallerID.username when considering who the user is for the purpose of transaction limit.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.TransactionLimitByPrincipal, "transaction_limit_by_principal", defaultConfig.TransactionLimitByPrincipal, "Include CallerID.principal when considering who the user is for the purpose of transaction limit.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.TransactionLimitByComponent, "transaction_limit_by_component", defaultConfig.TransactionLimitByComponent, "Include CallerID.component when considering who the user is for the purpose of transaction limit.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.TransactionLimitBySubcomponent, "transaction_limit_by_subcomponent", defaultConfig.TransactionLimitBySubcomponent, "Include CallerID.subcomponent when considering who the user is for the purpose of transaction limit.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&enableHeartbeat, "heartbeat_enable", false, "If true, vttablet records (if master) or checks (if replica) the current time of a replication heartbeat in the table _vt.heartbeat. The result is used to inform the serving state of the vttablet via healthchecks.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.DurationVar(&heartbeatInterval, "heartbeat_interval", 1*time.Second, "How frequently to read and write replication heartbeat.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.DurationVar(&heartbeatOnDemandDuration, "heartbeat_on_demand_duration", 0, "If non-zero, heartbeats are only written upon consumer request, and only run for up to given duration following the request. Frequent requests can keep the heartbeat running consistently; when requests are infrequent heartbeat may completely stop between requests")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.EnforceStrictTransTables, "enforce_strict_trans_tables", defaultConfig.EnforceStrictTransTables, "If true, vttablet requires MySQL to run with STRICT_TRANS_TABLES or STRICT_ALL_TABLES on. It is recommended to not turn this flag off. Otherwise MySQL may alter your supplied values before saving them to the database.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.Int64Var(&currentConfig.ConsolidatorStreamQuerySize, "consolidator-stream-query-size", defaultConfig.ConsolidatorStreamQuerySize, "Configure the stream consolidator query size in bytes. Setting to 0 disables the stream consolidator.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.Int64Var(&currentConfig.ConsolidatorStreamTotalSize, "consolidator-stream-total-size", defaultConfig.ConsolidatorStreamTotalSize, "Configure the stream consolidator total size in bytes. Setting to 0 disables the stream consolidator.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.DurationVar(&healthCheckInterval, "health_check_interval", 20*time.Second, "Interval between health checks")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.DurationVar(&degradedThreshold, "degraded_threshold", 30*time.Second, "replication lag after which a replica is considered degraded")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.DurationVar(&unhealthyThreshold, "unhealthy_threshold", 2*time.Hour, "replication lag after which a replica is considered unhealthy")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.DurationVar(&transitionGracePeriod, "serving_state_grace_period", 0, "how long to pause after broadcasting health to vtgate, before enforcing a new serving state")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&enableReplicationReporter, "enable_replication_reporter", false, "Use polling to track replication lag.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.EnableOnlineDDL, "queryserver_enable_online_ddl", true, "Enable online DDL.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.BoolVar(&currentConfig.SanitizeLogMessages, "sanitize_log_messages", false, "Remove potentially sensitive information in tablet INFO, WARNING, and ERROR log messages such as query parameters.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.Int64Var(&currentConfig.RowStreamer.MaxInnoDBTrxHistLen, "vreplication_copy_phase_max_innodb_history_list_length", 1000000, "The maximum InnoDB transaction history that can exist on a vstreamer (source) before starting another round of copying rows. This helps to limit the impact on the source tablet.")
go/vt/vttablet/tabletserver/tabletenv/config.go:        flag.Int64Var(&currentConfig.RowStreamer.MaxMySQLReplLagSecs, "vreplication_copy_phase_max_mysql_replication_lag", 43200, "The maximum MySQL replication lag (in seconds) that can exist on a vstreamer (source) before starting another round of copying rows. This helps to limit the impact on the source tablet.")
go/vt/vttablet/tabletserver/tabletenv/config.go:// Init must be called after flag.Parse, and before doing any other operations.
go/vt/vttablet/tabletserver/tabletenv/seconds.go:// SecondsVar is like a flag.Float64Var, but it works for Seconds.
go/vt/vttablet/tabletserver/tabletenv/seconds.go:       flag.Float64Var((*float64)(p), name, float64(value), usage)
```

### PR DESCRIPTION
**Pull request by rohit-nayak-ps**
## Description

Updates tabletenv related flag references specified in https://github.com/vitessio/vitess/issues/10984

## Related Issue(s)
Fixes #10984 

## Checklist

-   [ ] "Backport me!" label has been added if this change should be backported
-   [ ] Tests were added or are not required
-   [ ] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vtadmin/api_test.go [hunk 1]
```diff
@@ -4594,9 +4600,16 @@ func TestGetWorkflows(t *testing.T) {
 	}
 }
 
+func loadTabletEnvFlags() {
+	_flag.ParseFlagsForTest()
+	fs := pflag.NewFlagSet("TestFlags", pflag.ContinueOnError)
+	tabletenv.RegisterTabletEnvFlags(fs)
```
Comment (ajm188) [inline go/vt/vtadmin/api_test.go:4606]: i'm very confident that vtadmin doesn't use these flags, do the tests fail without this change?

Comment (rohit-nayak-ps) [reply go/vt/vtadmin/api_test.go:4606]: Only this flag is needed: `--queryserver-config-pool-size`. Otherwise we get the error pasted below. Should I separately define that for this test for better clarity or leave it as is?
```
--- FAIL: TestVTExplain (0.03s)
    --- FAIL: TestVTExplain/authorized_actor (0.01s)
panic: invalid/out of range capacity [recovered]
	panic: invalid/out of range capacity

goroutine 171 [running]:
testing.tRunner.func1.2({0x2138e60, 0xc001da1090})
	/usr/local/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
	/usr/local/go/src/testing/testing.go:1392 +0x39f
panic({0x2138e60, 0xc001da1090})
	/usr/local/go/src/runtime/panic.go:838 +0x207
vitess.io/vitess/go/pools.NewResourcePool(0xc001689c00?, 0x0?, 0x127e38e?, 0x3c2b040?, 0xc0016c4e10?, 0xc82485?, 0x2ce622a?)
	/home/rohit/vitess-ps/go/pools/resource_pool.go:127 +0x35a
vitess.io/vitess/go/vt/vttablet/tabletserver/connpool.(*Pool).Open(0xc001689c00, {0xc0001a2070?}, {0x3c2b040?}, {0xc0016c4ea0?})
	/home/rohit/vitess-ps/go/vt/vttablet/tabletserver/connpool/pool.go:126 +0x294
vitess.io/vitess/go/vt/vttablet/tabletserver.(*QueryEngine).Open(0xc0016dc360)
	/home/rohit/vitess-ps/go/vt/vttablet/tabletserver/query_engine.go:249 +0x29a
```

Comment (ajm188) [reply go/vt/vtadmin/api_test.go:4606]: so I think the problem is that `currentConfig` is no longer getting the values on `defaultConfig` copied in; i think for this code (not just this flag, more in general) to remain correct is for `currentConfig` to _start_ as exact copy of `defaultConfig`, instead of relying on the side effect of `init() { flag.Whatever }` from doing the copying over of the default values. 

let me know if that makes sense or not!

Comment (rohit-nayak-ps) [reply go/vt/vtadmin/api_test.go:4606]: You mean that we should be initialzing all the attributes of the `currentConfig` structure with the default values (same ones used in the flag definitions) as part of the `init()` in `tabletenv` ?

Comment (ajm188) [reply go/vt/vtadmin/api_test.go:4606]: yeah, we basically want `reflect.DeepEqual(defaultConfig, currentConfig)` to return true, i think

File: go/vt/vtadmin/api_test.go [hunk 2]
```diff
@@ -63,6 +59,11 @@ import (
 	"vitess.io/vitess/go/vt/proto/vttime"
 )
 
+func TestMain(m *testing.M) {
```
Comment (ajm188) [inline go/vt/vtadmin/api_test.go:62]: I don't follow. Why can't we use `go test -run` ?

Comment (rohit-nayak-ps) [reply go/vt/vtadmin/api_test.go:62]: On `main` it doesn't seem to be parse the test flags by default. I checked on `release13.0`, just so that I went back a bit and it works fine.

On `release13.0`
```
rohit@rohit-ubuntu:~/vitess-ps/go/vt/vtadmin$ go test -v -run TestGetGates
=== RUN   TestGetGates
=== PAUSE TestGetGates
=== CONT  TestGetGates
--- PASS: TestGetGates (0.00s)
PASS
ok  	vitess.io/vitess/go/vt/vtadmin	0.013s
```

On `main`
```
rohit@rohit-ubuntu:~/vitess-ps/go/vt/vtadmin$ go test -v -run TestGetGates
W0904 12:20:08.309102   29964 cache.go:119] BackfillEnqueueWaitTime (0s) must be positive, defaulting to 50ms
W0904 12:20:08.309322   29964 cache.go:124] BackfillRequestTTL (0s) must be positive, defaulting to 100ms
W0904 12:20:08.309456   29964 cache.go:119] BackfillEnqueueWaitTime (0s) must be positive, defaulting to 50ms
...
W0904 12:20:08.352305   29964 cache.go:124] BackfillRequestTTL (0s) must be positive, defaulting to 100ms
W0904 12:20:08.352516   29964 cache.go:119] BackfillEnqueueWaitTime (0s) must be positive, defaulting to 50ms
W0904 12:20:08.352524   29964 cache.go:124] BackfillRequestTTL (0s) must be positive, defaulting to 100ms
PASS
ok  	vitess.io/vitess/go/vt/vtadmin	0.071s
```

I added logs inside the go flag/testing modules and the issue seems to be that the `init()` in `test_tmclient.go` parses the command line without the test flags and then when the default `go test` main runs it finds that the flags are already parsed and hence the test flags never get parsed.

File: go/vt/vtadmin/api_test.go (hunk 1 above)
Comment (rohit-nayak-ps) [reply go/vt/vtadmin/api_test.go]: Fixed in the last commit from last week.

File: go/vt/vtexplain/vtexplain_test.go [hunk 3]
```diff
@@ -24,6 +24,12 @@ import (
...
 	"testing"
 
+	"github.com/spf13/pflag"
+
+	"vitess.io/vitess/go/vt/vttablet/tabletserver/tabletenv"
+
+	_flag "vitess.io/vitess/go/internal/flag"
+
 	"github.com/google/go-cmp/cmp"
 	"github.com/stretchr/testify/require"
```
Comment (ajm188) [inline go/vt/vtexplain/vtexplain_test.go:35]: nit: can you regroup these while you're resolving merge conflicts (sorry about that, btw) so that the vitess ones are pushed down below the other GitHub ones?

File: go/vt/vtadmin/api_test.go [hunk 4]
```diff
@@ -4596,7 +4603,6 @@ func TestGetWorkflows(t *testing.T) {
 
 func TestVTExplain(t *testing.T) {
 	t.Parallel()
-
```
Comment (ajm188) [inline go/vt/vtadmin/api_test.go:4599]: ?

File: go/vt/vttablet/endtoend/transaction_test.go [hunk 5]
```diff
@@ -21,6 +21,10 @@ import (
 	"testing"
 	"time"
 
+	"github.com/spf13/pflag"
+
+	_flag "vitess.io/vitess/go/internal/flag"
+
 	"google.golang.org/protobuf/proto"
```
Comment (ajm188) [inline go/vt/vttablet/endtoend/transaction_test.go:29]: same nit

File: go/vt/vttablet/endtoend/transaction_test.go [hunk 6]
```diff
@@ -203,7 +207,16 @@ func TestAutoCommit(t *testing.T) {
 	}
 }
 
+func loadTabletEnvFlags() {
```
Comment (ajm188) [inline go/vt/vttablet/endtoend/transaction_test.go:210]: i think we should make this a function in a package under `tabletenv` (`tabletenvtest`?) similar to [`tabletconntest`](https://github.com/vitessio/vitess/pull/11010/files#diff-17a621e19795298d33fa2a2bded2c4707bd2e7b33817355ebd48d0a2171e3eddR795-R803) provides

**Review by ajm188 — APPROVED** [review]
lgtm, some nits that you can address when resolving the conflicting test files

File: go/vt/vttablet/endtoend/transaction_test.go (hunk 6 above)
Comment (rohit-nayak-ps) [reply go/vt/vttablet/endtoend/transaction_test.go:210]: Currently it is called in two places.  I had thought of extracting it out so that it could be used from a common library but didn't see any obvious place right now.

`tabletconntest` does not export any functions: in our case we want this one function to be exported and used in vtexplain and vttablet/endtoend tests. Not sure if it is worth creating a new package just for this.

Maybe I could export this as a Test-only function inside tabletenv itself? We have precedence of such functions in other packages for use in tests only ... wdyt?

Comment (ajm188) [reply go/vt/vttablet/endtoend/transaction_test.go:205]: This is not true, it exports `SetProtocol` which is what I linked

Comment (rohit-nayak-ps) [reply go/vt/vttablet/endtoend/transaction_test.go]: Sorry,  that call was at the end of the file  didn't navigate all the way down. OK, added the new package as suggested.
