### PR TITLE
Vttablet panic in requests Wait

### LINKED ISSUE #14933: Bug Report: Panic in vttablet in requests Wait
### Overview of the Issue

It has been noticed that sometimes sync.Waitgroup for requests panics with the following error - 
```
panic: sync: WaitGroup is reused before previous Wait has returned
```

### Reproduction Steps

Run vitess and hope to see the error.

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
-
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description

This PR fixes the issue pointed out in https://github.com/vitessio/vitess/issues/14933. 

Reading the docs of `sync.WaitGroup` we see - 
```
// Note that calls with a positive delta that occur when the counter is zero
// must happen before a Wait. Calls with a negative delta, or calls with a
// positive delta that start when the counter is greater than zero, may happen
// at any time.
// Typically this means the calls to Add should execute before the statement
// creating the goroutine or other event to be waited for.
// If a WaitGroup is reused to wait for several independent sets of events,
// new Add calls must happen after all previous Wait calls have returned.
```

So, apparently, this panic happens, when we have started waiting for a `waitGroup` and then a bunch of `Done()` calls happen that take the counter to 0, but before the `Wait()` has been processed, an `Add()` call goes through and that leads to this panic.

The only way to properly fix this panic would be to ensure that we don't call `Add()` after we have started waiting for any request. To this end, we have added a new field to the statemanager that tracks the number of go routines that are waiting for the requests to be empty. We use this field to prevent `Add()` calls in `startRequests`.

## Related Issue(s)

- Fixes #14933
## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by systay — APPROVED** [review]

File: go/vt/vttablet/tabletserver/state_manager.go [hunk 1]
```diff
@@ -99,6 +99,10 @@ type stateManager struct {
 	alsoAllow      []topodatapb.TabletType
 	reason         string
 	transitionErr  error
+	// requestsWaitCounter is the number of goroutines that are waiting for requests to be empty.
+	// If this value is greater than zero, then we have to ensure that we don't Add to the requests
+	// to avoid any panics in the wait.
+	requestsWaitCounter int
```
Comment (harshit-gangal) [inline go/vt/vttablet/tabletserver/state_manager.go:105]: nit: can use atomic counter

Comment (harshit-gangal) [reply go/vt/vttablet/tabletserver/state_manager.go:105]: should this be a bool. as we want only one `sm.requests.Wait()` to happen at a time.

File: go/vt/vttablet/tabletserver/state_manager.go [hunk 2]
```diff
@@ -392,7 +410,9 @@ func (sm *stateManager) StartRequest(ctx context.Context, target *querypb.Target
 	}
 
 	shuttingDown := sm.wantState != StateServing
-	if shuttingDown && !allowOnShutdown {
+	// If requestsWaitCounter is not zero, then there are go-routines blocked on waiting for requests to be empty.
+	// We cannot allow adding to the requests to prevent any panics from happening.
+	if sm.requestsWaitCounter > 0 || (shuttingDown && !allowOnShutdown) {
```
Comment (harshit-gangal) [inline go/vt/vttablet/tabletserver/state_manager.go:415]: this condition looks wrong to me.
`requestsWaitCounter` will be `0` during shutdown till `request.Wait()` is not called. But we do not want all the request to go through unless `allowOnShutdown` is true.

Comment (harshit-gangal) [reply go/vt/vttablet/tabletserver/state_manager.go:415]: Ignore my comment. I this is good. just that we can reverse the condition check on `or` it may make it more understandable.

File: go/vt/vttablet/tabletserver/state_manager.go (hunk 1 above)
Comment (GuptaManan100) [reply go/vt/vttablet/tabletserver/state_manager.go:105]: We have mutex protection, so atomic counter would be the same thing. Plus I think its better to be consitant with the struct. If we have a mutex to protect all internal state changes of a struct, we should use it.
I made it an int instead of a boolean because even though theoritically we should only be calling `sm.requests.Wait()` only once, its not explicitly enforced or written down. int just feels a safer option and more future proof.

File: go/vt/vttablet/tabletserver/state_manager.go (hunk 2 above)
Comment (GuptaManan100) [reply go/vt/vttablet/tabletserver/state_manager.go:415]: Sure, I'll reverse them.

**Review by harshit-gangal — APPROVED** [review]
