### PR TITLE
vtgate/engine: Fix race condition in join logic

### LINKED ISSUE #14433: Bug Report: vtgate can panic due to a race condition in the join engine primitive
### Overview of the Issue

When running a query with zero results on an aggregation through the join engine, it can crash due to race conditions. 

This is visible today as "flakiness" in CI for the `TestEmptyTableAggr` test, but it's a real bug here. A previous attempt to fix this in https://github.com/vitessio/vitess/pull/14012 satisfied the Go race checker, but it did not actually fix the race. There's still a classic check-then-act style race bug.

### Reproduction Steps

Run the `TestEmptyTableAggr` tests with a higher count.

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
-
```

### Log Fragments

```sh
panic: runtime error: index out of range [0] with length 0

goroutine 420 [running]:
vitess.io/vitess/go/vt/vtgate/engine.newAggregation({0x0?, 0x30000007d?, 0x14000b15048?}, {0x1400007ef68, 0x1, 0x1042a98c0?})
	vitess.io/vitess/go/vt/vtgate/engine/aggregations.go:352 +0x824
vitess.io/vitess/go/vt/vtgate/engine.(*ScalarAggregate).TryStreamExecute.func2(0x14000df42a0)
	vitess.io/vitess/go/vt/vtgate/engine/scalar_aggregation.go:126 +0x120
vitess.io/vitess/go/vt/vtgate/engine.(*Projection).TryStreamExecute.func1(0x14000df42a0)
	vitess.io/vitess/go/vt/vtgate/engine/projection.go:123 +0x2f4
vitess.io/vitess/go/vt/vtgate/engine.(*Join).TryStreamExecute.func1(0x14000df4230)
	vitess.io/vitess/go/vt/vtgate/engine/join.go:168 +0x638
vitess.io/vitess/go/vt/vtgate/engine.(*Route).streamExecuteShards.func1(0x0?)
	vitess.io/vitess/go/vt/vtgate/engine/route.go:345 +0x158
vitess.io/vitess/go/vt/vttablet/queryservice.(*wrappedService).StreamExecute.func1.1(0x14000dee3f0?)
	vitess.io/vitess/go/vt/vttablet/queryservice/wrapped.go:198 +0x30
vitess.io/vitess/go/vt/vttablet/grpctabletconn.(*gRPCQueryClient).StreamExecute(0x1400093e778?, {0x10429b400?, 0x14000f0f4d0?}, 0x102646c84?, {0x14000432800, 0x5c}, 0x5c6eef79?, 0x14000800000?, 0x1400093e7d8?, 0x10265aae0?, ...)
	vitess.io/vitess/go/vt/vttablet/grpctabletconn/conn.go:190 +0x168
vitess.io/vitess/go/vt/vttablet/queryservice.(*wrappedService).StreamExecute.func1({0x10429b400, 0x14000f0f4d0}, 0x14000e02a80?, {0x1042b6af8, 0x140003f3400})
	vitess.io/vitess/go/vt/vttablet/queryservice/wrapped.go:196 +0xfc
vitess.io/vitess/go/vt/vtgate.(*TabletGateway).withRetry(0x140002524d0, {0x10429b400, 0x14000f0f4d0}, 0x14000bbfb60, {0x1400093ea88?, 0x102fe94c8?}, {0x40?, 0x104198cc0?}, 0x0, 0x14000e0fd00)
	vitess.io/vitess/go/vt/vtgate/tabletgateway.go:339 +0x3d8
vitess.io/vitess/go/vt/vttablet/queryservice.(*wrappedService).StreamExecute(0x140005108b8, {0x10429b400, 0x14000f0f4d0}, 0x3b?, {0x14000432800, 0x5c}, 0x14000f0f500, 0x0, 0x0, 0x14000d070e0, ...)
	vitess.io/vitess/go/vt/vttablet/queryservice/wrapped.go:194 +0x12c
vitess.io/vitess/go/vt/vtgate.(*ScatterConn).StreamExecuteMulti.func1(0x14000f10c48, 0x0, 0x14000e28300)
	vitess.io/vitess/go/vt/vtgate/scatter_conn.go:408 +0x1e0
vitess.io/vitess/go/vt/vtgate.(*ScatterConn).multiGoTransaction.func1(0x14000f10c48, 0x1028e6f54?)
	vitess.io/vitess/go/vt/vtgate/scatter_conn.go:640 +0x138
vitess.io/vitess/go/vt/vtgate.(*ScatterConn).multiGoTransaction.func2(0x0?, 0x0?)
	vitess.io/vitess/go/vt/vtgate/scatter_conn.go:668 +0x54
created by vitess.io/vitess/go/vt/vtgate.(*ScatterConn).multiGoTransaction in goroutine 361
	vitess.io/vitess/go/vt/vtgate/scatter_conn.go:666 +0x1c8
```

### PR DESCRIPTION
**Pull request by dbussink**
This change fixes a race condition in the join logic. This is a classic check-then-act style bug. The problem is that we were using a field to track if we already sent fields. This can lead to a concurrency issue though:

- Thread 1 checks if it needs to send fields and sees that it does.
- Thread 2 checks if it needs to send fields and sees it does not.
- Thread 2 sends the result with no fields.
- Downstream consumers crash because they get a first result set with no fields.

There's no locking around the critical section of checking if we need to send fields and actually calling the callback. We need both those to be covered under the same critical section. This change here introduces a lock around this to make sure this happens.

With the lock, it normally would not be necessary to use an atomic boolean flag, as we'd only read and write the flag inside the lock. We have another optimization here though, which is that we only want to ask the right hand side for fields once as well but it's called in each callback for the left hand side.

By using still an atomic, we can also read this value too. Note that this is still actually racy, but it's has a worse case condition of reading the fields of the right hand side twice which is not optimal, but it will not break things.

Now why is this only seemingly now happening / showing up in CI as much more flaky tests? I suspect the reason is that we're using a much more optimization aggregation implementation that makes this race more likely to happen as it's faster. 

In #14012 there was a previous attempt to fix this issue, as likely the Go race detector indicated a problem. While the change there does silence the race detector because of the introduction of an atomic boolean, it does not actually fix the underlying race problem. It merely masks it. 

## Related Issue(s)

Fixes #14433 

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/test/endtoend/cluster/cluster_util.go [hunk 1]
```diff
@@ -265,7 +265,7 @@ func WaitForReplicationPos(t *testing.T, tabletA *Vttablet, tabletB *Vttablet, v
 		msg := fmt.Sprintf("%s's replication position to catch up to %s's;currently at: %s, waiting to catch up to: %s", tabletB.Alias, tabletA.Alias, replicationPosB, replicationPosA)
 		select {
 		case <-ctx.Done():
-			assert.FailNowf(t, "Timeout waiting for condition '%s'", msg)
+			assert.FailNow(t, "Timeout waiting for condition '%s'", msg)
```
Comment (dbussink) [inline go/test/endtoend/cluster/cluster_util.go:268]: This was not printing the right thing before and also ran these tests to verify the utils change.

File: go/test/endtoend/utils/utils.go [hunk 2]
```diff
@@ -236,16 +236,17 @@ func WaitForAuthoritative(t *testing.T, ks, tbl string, readVSchema func() (*int
 		case <-timeout:
 			return fmt.Errorf("schema tracking didn't mark table t2 as authoritative until timeout")
 		default:
-			time.Sleep(1 * time.Second)
```
Comment (dbussink) [inline go/test/endtoend/utils/utils.go:239]: It's better to wait when we know we need to actually retry, so the tests are much faster in their happy path. Found this since I was running the racy test with a high number of counts and this speeds that up hugely. Now it takes 18 seconds for the full test to run 100 times, vs 120 seconds before. 

I have applied the same optimization to the other helpers here and reduced the retry time to 100ms instead of 1s to also speed it up in the failure path.

File: go/test/endtoend/cluster/cluster_util.go (hunk 1 above)
Comment (systay) [inline go/test/endtoend/cluster/cluster_util.go:268]: this change doesn't look right

File: go/vt/vtgate/engine/join.go [hunk 3]
```diff
@@ -115,22 +116,31 @@ func bindvarForType(t querypb.Type) *querypb.BindVariable {
 
 // TryStreamExecute performs a streaming exec.
 func (jn *Join) TryStreamExecute(ctx context.Context, vcursor VCursor, bindVars map[string]*querypb.BindVariable, wantfields bool, callback func(*sqltypes.Result) error) error {
-	var fieldNeeded atomic.Bool
-	fieldNeeded.Store(wantfields)
-	err := vcursor.StreamExecutePrimitive(ctx, jn.Left, bindVars, fieldNeeded.Load(), func(lresult *sqltypes.Result) error {
+	var mu sync.Mutex
```
Comment (systay) [inline go/vt/vtgate/engine/join.go:119]: we need either the mutex or the atomic.Bool, but not both, right?

**Comment by harshit-gangal** [comment]
This logic in changed in v18 only, before that the code was different. I suspect the issue will only be on v18

File: go/vt/vtgate/engine/join.go (hunk 3 above)
Comment (dbussink) [reply go/vt/vtgate/engine/join.go:119]: @systay We need both, as explained the following section in the PR body:

---

With the lock, it normally would not be necessary to use an atomic boolean flag, as we'd only read and write the flag inside the lock. We have another optimization here though, which is that we only want to ask the right hand side for fields once as well but it's called in each callback for the left hand side.

File: go/test/endtoend/cluster/cluster_util.go (hunk 1 above)
Comment (dbussink) [reply go/test/endtoend/cluster/cluster_util.go:268]: @systay It actually is! It looks confusing, but `Fallnowf` expects first a message and then a separate interpolation thingy. Just `Failnow` without the `f` already interpolates for the first string it's passed. It's confusing.

**Comment by dbussink** [comment]
> This logic in changed in v18 only, before that the code was different. I suspect the issue will only be on v18

https://github.com/vitessio/vitess/pull/14012 was back ported all the way to v15, so hence I marked this one as that as well.

**Review by systay — APPROVED** [review]

File: go/test/endtoend/cluster/cluster_util.go (hunk 1 above)
Comment (dbussink) [reply go/test/endtoend/cluster/cluster_util.go:268]: Going to pull this out as neither works as expected here and don't want to churn on this in this PR.

**Review by vmg — APPROVED** [review]
