### PR TITLE
[Java] JDBC mysql driver test

### LINKED ISSUE #7916: jdbc:mysql @replica is not working
When we were trying to use third-party tool TDDL to automatically separate READ transactions and WRITE transactions, to dispatch WRITE to master tablet only and READ to other replica tablets, we found the jdbc:mysql connection on replica does not work. For example: "jdbc:mysql://192.168.20.231:15306/dbname@replica" is actually connecting to the master tablet.

### PR DESCRIPTION
**Pull request by harshit-gangal**
## Description

Added MySQL JDBC driver to test it with Vitess and also shows that @<tablet_type> works in the connection string.

## Related Issue(s)

Closes #7916 

## Checklist
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

### CODE REVIEW

File: java/example/src/main/java/io/vitess/example/MysqlJDBCExample.java [hunk 1]
```diff
@@ -0,0 +1,179 @@
...
+      if (null != updateCounts) {
+        evalBatchResult(updateCounts);
+      }
+    }
+
+    try (Statement stmt = conn.createStatement()) {
+      Instant timeCreated = Instant.now();
+      int page = rand.nextInt(100) + 1;
+      System.out.println("Page selected for all dml operation: " + page);
+      stmt.addBatch("INSERT INTO messages (page,time_created_ns,message) VALUES (" + page + ","
```
Comment (systay) [inline java/example/src/main/java/io/vitess/example/MysqlJDBCExample.java:147]: nit: `String.Format` is your friend

**Review by systay — APPROVED** [review]

File: java/example/src/main/java/io/vitess/example/MysqlJDBCExample.java (hunk 1 above)
Comment (harshit-gangal) [reply java/example/src/main/java/io/vitess/example/MysqlJDBCExample.java:147]: I want to spend less time doing java.
