### PR TITLE
fix: handle aliases in UNIONs better

### LINKED ISSUE #18469: Bug Report: Scattered Union Broken With Column Alias + Limit
### Overview of the Issue

When using a LIMIT and a column alias in combination with `UNION ALL`, the planner gets the column names wrong.

### Reproduction Steps

1. vschema

```json
{
  "sharded": true,
  "tables": {
    "contacts": {
      "column_vindexes": [
        {
          "column": "id",
          "name": "hash"
        }
      ]
    }
  },
  "vindexes": {
    "hash": {
      "type": "xxhash"
    }
  }
}
```

2. schema

```sql
CREATE TABLE `contacts` (
  `id` bigint unsigned NOT NULL,
  `team_id` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `contacts_team_id_index` (`team_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

3. Run a query which involves UNION ALL of SELECT statements that use both LIMIT and column aliases that need to scatter.

```sql
(SELECT `team_id` AS `foo` FROM `contacts` WHERE `team_id` = 1 ORDER BY `id` DESC LIMIT 1)
UNION ALL
(SELECT `team_id` AS `foo` FROM `contacts` WHERE `team_id` = 2 ORDER BY `id` DESC LIMIT 1);
```

If I remove the column aliases, the query runs. Here is the vexplain for the query without the aliases:

```sql
{
	"OperatorType": "SimpleProjection",
	"ColumnNames": [
		"0:team_id"
	],
	"Columns": "0",
	"Inputs": [
		{
			"OperatorType": "Concatenate",
			"Inputs": [
				{
					"OperatorType": "Limit",
					"Count": ":vtg1",
					"Inputs": [
						{
							"OperatorType": "Route",
							"Variant": "Scatter",
							"Keyspace": {
								"Name": "voxie",
								"Sharded": true
							},
							"FieldQuery": "select team_id, id from contacts where 1 != 1",
							"OrderBy": "1 DESC",
							"Query": "select team_id, id from contacts where team_id = :team_id /* INT64 */ order by id desc limit :vtg1 /* INT64 */",
							"Table": "contacts"
						}
					]
				},
				{
					"OperatorType": "Limit",
					"Count": ":vtg2",
					"Inputs": [
						{
							"OperatorType": "Route",
							"Variant": "Scatter",
							"Keyspace": {
								"Name": "voxie",
								"Sharded": true
							},
							"FieldQuery": "select team_id, id from contacts where 1 != 1",
							"OrderBy": "1 DESC",
							"Query": "select team_id, id from contacts where team_id = :team_id1 /* INT64 */ order by id desc limit :vtg2 /* INT64 */",
							"Table": "contacts"
						}
					]
				}
			]
		}
	]
}
```

That plan looks ideal. It wants to run 2n queries, where n is the number of shards. We would like the very same plan for the query that has the column aliases.

### Binary Version

```sh
Vitess 21.0.5 / PlanetScale V21 are both reproducers.
```

### Operating System and Environment details

```sh
vttestserver image or PlanetScale are both reproducers.
```

### Log Fragments

```sh

```

### PR DESCRIPTION
**Pull request by systay**
## Description
When planning UNIONs, Vitess was having a hard time handling column aliases correctly.

## Related Issue(s)
Fixes #18469

## Checklist
-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vtgate/planbuilder/operators/union.go [hunk 1]
```diff
@@ -179,8 +179,11 @@ func (u *Union) AddColumn(ctx *plancontext.PlanningContext, reuse bool, gb bool,
 	case *sqlparser.ColName:
 		cols := u.GetColumns(ctx)
 		// here we deal with pure column access on top of the union
-		offset := slices.IndexFunc(cols, func(expr *sqlparser.AliasedExpr) bool {
-			return e.Name.EqualString(expr.ColumnName())
+		offset := slices.IndexFunc(cols, func(column *sqlparser.AliasedExpr) bool {
+			if column.ColumnName() == expr.ColumnName() {
```
Comment (dbussink) [inline go/vt/vtgate/planbuilder/operators/union.go:183]: I had to double check, but this looks to work also correctly if both sides don't have an alias set?

Comment (systay) [reply go/vt/vtgate/planbuilder/operators/union.go:183]: exactly. we have tests of both variations.

**Comment by GrahamCampbell** [comment]
Should this be backported?

**Comment by systay** [comment]
> Should this be backported?

I believe the rule is to only backport regressions or corruption bugs (corrupted data, but also corrupted results). Since this "just" fails to plan, we don't backport
