### PR TITLE
bugfix: wrong field type returned for SUM

### LINKED ISSUE #15200: Bug: output fields not typed not correct
When planning aggregations that are pushed under joins, we turn to the evalengine to perform arithmetic operations, such as multiplying to columns.

The fields are not set correctly for the result, with the decimal length set to 0.

```sql
-- Vitess
mysql> SELECT SUM(dec_value) FROM t1 JOIN t2 ON t1.t1_id % 2 = t2.id % 2;
Field   1:  `sum(dec_value)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       NEWDECIMAL
Collation:  binary (63)
Length:     0
Max_length: 12
Decimals:   0
Flags:      NUM

-- MySQL
mysql> SELECT SUM(dec_value) FROM t1 JOIN t2 ON t1.t1_id % 2 = t2.id % 2;
Field   1:  `SUM(dec_value)`
Catalog:    `def`
Database:   ``
Table:      ``
Org_table:  ``
Type:       NEWDECIMAL
Collation:  binary (63)
Length:     44
Max_length: 0
Decimals:   6
Flags:      BINARY NUM
```

### PR DESCRIPTION
**Pull request by systay**
## Description
For some arithmetic operations performed in the evalengine, we were not setting the resulting decimal length correctly.
The values were correct, but since the decimal length was set wrongly, some clients didn't read all the provided decimals and got the wrong results.

## Related Issue(s)
Fixes #15200

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vtgate/engine/opcode/constants.go [hunk 1]
```diff
@@ -169,6 +171,28 @@ func (code AggregateOpcode) Type(typ querypb.Type) querypb.Type {
...
+
+func (code AggregateOpcode) ResolveType(t evalengine.Type, env *collations.Environment) evalengine.Type {
+	sqltype := code.SQLType(t.Type())
+	collation := collations.CollationForType(sqltype, env.DefaultConnectionCharset())
+	nullable := code.Nullable()
+	size := t.Size()
+
+	scale := t.Scale()
+	if code == AggregateAvg {
+		scale += 4
```
Comment (dbussink) [inline go/vt/vtgate/engine/opcode/constants.go:191]: I hink we also have to increase `size` here too? I tested an `AVG` and the size was also increased. Which makes sense, since `size` for a decimal is the total number of digits, so if there's more digits behind the dot, it means the size also has to increase.

File: go/vt/vtgate/evalengine/expr_arithmetic.go [hunk 2]
```diff
@@ -434,6 +438,7 @@ func (op *opArithMod) compile(c *compiler, left, right IR) (ctype, error) {
 			c.asm.Mod_ff()
 		case sqltypes.Decimal:
 			ct.Type = sqltypes.Decimal
+			ct.Scale = max(lt.Scale, rt.Scale)
```
Comment (dbussink) [inline go/vt/vtgate/evalengine/expr_arithmetic.go:441]: Do we have to do the same with size here?

File: go/test/endtoend/utils/mysql.go [hunk 3]
```diff
@@ -229,6 +231,20 @@ func compareVitessAndMySQLResults(t *testing.T, query string, vtConn *mysql.Conn
 	return errors.New(errStr)
 }
 
+func checkFields(t *testing.T, columnName string, vtField, myField *querypb.Field) {
+	t.Helper()
+	if vtField.Type != myField.Type {
+		t.Errorf("for column %s field types do not match\nNot equal: \nMySQL: %v\nVitess: %v\n", columnName, myField.Type.String(), vtField.Type.String())
+	}
+
+	// ensure that Decimal types are properly sized
```
Comment (dbussink) [inline go/test/endtoend/utils/mysql.go:240]: Do we want to check size here too?

**Review by dbussink — COMMENTED** [review]
Looks like some legit unit test failures here too

**Comment by vmg** [comment]
@dbussink I'm not fixing the Size fields in this PR because they don't appear to affect correctness and their fix is significantly more involved, particularly for Decimals. We'll have to sit down and look at this together when you're back, I fear that some of the Size fields may not be computable statically! :dizzy:

File: go/test/endtoend/utils/mysql.go (hunk 3 above)
Comment (systay) [reply go/test/endtoend/utils/mysql.go:240]: no we don't

**Comment by systay** [comment]
It all looks great to me ✨ . Since I opened the PR, you'll have to approve it, @vmg

**Review by dbussink — APPROVED** [review]

**Review by vmg — APPROVED** [review]
AHA, SEAL OF SELF-APPROVAL :ok_hand:
