### PR TITLE
bugfix: add HAVING columns inside derived tables

### LINKED ISSUE #16965: Bug Report: Vitess returns rows with wrong columns
### Overview of the Issue

Starting Vitess v18 up to latest commit on the `main` branch, some queries can end up returning more column data than what was specified in the `SELECT` part of the query.

It seems to be caused by a combination of a subquery using a lookup vindex, using `GROUP BY`, `ORDER BY` and a subquery.

### Reproduction Steps

Here's a sql schema:

```sql
create table t3 (
    id bigint,
    sharding_key bigint,
    user_id bigint,
    t4_id bigint,
    primary key (id)
) Engine = InnoDB;

create table t3_id_idx (
    id bigint,
    keyspace_id varbinary(10),
    primary key (id)
) Engine = InnoDB;

create table t3_extra (
    id bigint,
    t3_id bigint,
    sharding_key bigint,
    primary key (id)
) Engine = InnoDB;

create table t4 (
    id bigint,
    sharding_key bigint,
    primary key (id)
) Engine = InnoDB;

create table t4_id_idx (
    id bigint,
    keyspace_id varbinary(10),
    primary key (id)
) Engine = InnoDB;
```

Plus a vschema:

```json
{
  "sharded": true,
  "vindexes": {
    "t3_id_vdx": {
      "type": "lookup_unique",
      "params": {
        "table": "t3_id_idx",
        "from": "id",
        "to": "keyspace_id",
        "autocommit": "true"
      },
      "owner": "t3"
    },
    "t4_id_vdx": {
      "type": "lookup_unique",
      "params": {
        "table": "t4_id_idx",
        "from": "id",
        "to": "keyspace_id",
        "autocommit": "true"
      },
      "owner": "t4"
    },
    "xxhash": {
      "type": "xxhash"
    }
  },
  "tables": {
    "t3_id_idx": {
      "column_vindexes": [
        {
          "columns": [
            "id"
          ],
          "name": "xxhash"
        }
      ]
    },
    "t4_id_idx": {
      "column_vindexes": [
        {
          "columns": [
            "id"
          ],
          "name": "xxhash"
        }
      ]
    },

    "t3": {
      "column_vindexes": [
        {
          "columns": [
            "sharding_key"
          ],
          "name": "xxhash"
        },
        {
          "columns": [
            "id"
          ],
          "name": "t3_id_vdx"
        },
        {
          "columns": [
            "t4_id"
          ],
          "name": "t4_id_vdx"
        }
      ]
    },
    "t3_extra": {
      "column_vindexes": [
        {
          "columns": [
            "sharding_key"
          ],
          "name": "xxhash"
        },
        {
          "columns": [
            "t3_id"
          ],
          "name": "t3_id_vdx"
        }
      ]
    },
    "t4": {
      "column_vindexes": [
        {
          "columns": [
            "sharding_key"
          ],
          "name": "xxhash"
        },
        {
          "columns": [
            "id"
          ],
          "name": "t4_id_vdx"
        }
      ]
    }
  }
}
```

And the offending query (plus setup data):

```sql
-- Data setup. Required to reproduce
INSERT INTO t4 (id, sharding_key) VALUES (1, 1);
INSERT INTO t3 (id, sharding_key, user_id, t4_id) VALUES (1, 1, 2, 1);
INSERT INTO t3_extra (id, sharding_key, t3_id) VALUES (1, 1, 1);

-- Query to reproduce
SELECT t3.user_id FROM t3 WHERE t3.t4_id = 1 AND (NOT EXISTS (SELECT 1 FROM t3_extra WHERE t3_extra.t3_id = t3.id)) GROUP BY t3.t4_id, t3.user_id, t3.id ORDER BY t3.id ASC
```

This query will return 2 columns - `t3.user_id` AND `t3.id`, although only one `t3.user_id` is selected.

### Binary Version

```sh
v18, v19, v20, main
```

### Operating System and Environment details

```sh
N/A
```

### Log Fragments

```sh
N/A
```

### PR DESCRIPTION
**Pull request by systay**
## Description
Make sure to add columns needed by HAVING to the derived table.

## Related Issue(s)
Fixes #16965

## Checklist
-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vtgate/planbuilder/plan_test.go [hunk 1]
```diff
@@ -293,7 +293,7 @@ func (s *planTestSuite) TestViews() {
 	s.testFile("view_cases.json", vschemaWrapper, false)
 }
 
-func (s *planTestSuite) TestOne() {
+func (s *planTestSuite) /**/ TestOne() {
```
Comment (arthurschreiber) [inline go/vt/vtgate/planbuilder/plan_test.go:296]: Was this change on purpose? 🤔 

```suggestion
func (s *planTestSuite) TestOne() {
```

**Review by arthurschreiber — APPROVED** [review]

File: go/vt/vtgate/planbuilder/plan_test.go (hunk 1 above)
Comment (systay) [reply go/vt/vtgate/planbuilder/plan_test.go]: not at all

**Review by frouioui — APPROVED** [review]

File: go/vt/vtgate/planbuilder/testdata/cte_cases.json [hunk 2]
```diff
@@ -379,25 +379,42 @@
...
           {
-            "OperatorType": "Aggregate",
-            "Variant": "Scalar",
-            "Aggregates": "any_value(0) AS id, sum_count_star(1) AS count(*)",
+            "OperatorType": "Projection",
+            "Expressions": [
+              ":0 as id",
+              "count(*) = 1 as count(*) = 1"
+            ],
             "Inputs": [
```
Comment (harshit-gangal) [inline go/vt/vtgate/planbuilder/testdata/cte_cases.json:394]: SimpleProjection on top of Projection 🤔

Comment (arthurschreiber) [reply go/vt/vtgate/planbuilder/testdata/cte_cases.json:394]: @systay Is this what is causing the multi nested derived table query on v19? 🤔
