### PR TITLE
Parser: Support CREATE TABLE ... SELECT Statement (#17983)

### LINKED ISSUE #17983: Bug Report: `CREATE TEMPORARY TABLE ... AS (SELECT ... )` prints a warning in the Vitess log while it just works
### Overview of the Issue

I noticed this in the Vitess logs 

```
W0318 15:28:05.312131       1 parser.go:85] ignoring error parsing DDL 'CREATE TEMPORARY TABLE it_departments AS (SELECT dept_no, dept_name FROM departments WHERE dept_no IN ('d005', 'd008'))': syntax error at position 41 near 'AS'
W0318 15:28:05.312894       1 parser.go:85] ignoring error parsing DDL 'CREATE TEMPORARY TABLE it_departments AS (SELECT dept_no, dept_name FROM departments WHERE dept_no IN ('d005', 'd008'))': syntax error at position 41 near 'AS'
W0318 15:28:05.313626       1 parser.go:85] ignoring error parsing DDL 'CREATE TEMPORARY TABLE it_departments AS (SELECT dept_no, dept_name FROM departments WHERE dept_no IN ('d005', 'd008'))': syntax error at position 41 near 'AS'
W0318 15:28:05.315061       1 parser.go:85] ignoring error parsing DDL 'CREATE TEMPORARY TABLE it_departments AS (SELECT dept_no, dept_name FROM departments WHERE dept_no IN ('d005', 'd008'))': syntax error at position 41 near 'AS'
```

### Reproduction Steps

```
mysql> SELECT * FROM departments;
+---------+--------------------+
| dept_no | dept_name          |
+---------+--------------------+
| d009    | Customer Service   |
| d005    | Development        |
| d002    | Finance            |
| d003    | Human Resources    |
| d001    | Marketing          |
| d004    | Production         |
| d006    | Quality Management |
| d008    | Research           |
| d007    | Sales              |
+---------+--------------------+
9 rows in set (0.12 sec)

mysql> CREATE TEMPORARY TABLE it_departments AS (SELECT dept_no, dept_name FROM departments WHERE dept_no IN ('d005', 'd008'));
Query OK, 2 rows affected (0.12 sec)

mysql> SHOW CREATE TABLE it_departments\G
*************************** 1. row ***************************
       Table: it_departments
Create Table: CREATE TEMPORARY TABLE `it_departments` (
  `dept_no` char(4) NOT NULL,
  `dept_name` varchar(40) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
1 row in set (0.12 sec)

mysql> SELECT * FROM it_departments;
+---------+-------------+
| dept_no | dept_name   |
+---------+-------------+
| d005    | Development |
| d008    | Research    |
+---------+-------------+
2 rows in set (0.12 sec)

mysql> SELECT @@version;
+---------------+
| @@version     |
+---------------+
| 8.0.34-Vitess |
+---------------+
1 row in set (0.11 sec)
```

### Binary Version

```sh
vttablet version Version: 21.0.0-SNAPSHOT (Git revision 32de268d18b4cb5ae1188d240134d3720b375ccd branch 'latest-21.0') built on Wed Feb 19 05:04:48 UTC 2025 by vitess@buildkitsandbox using go1.23.6 linux/amd64
```

### Operating System and Environment details

```sh
Linux/amd64 - Ubuntu
```

### Log Fragments

```sh

```

### PR DESCRIPTION
**Pull request by wukuai**
## Description
This PR implements support for `CREATE TABLE ... SELECT` statements in the parser, enabling users to create tables directly from SELECT query results. The implementation supports optional table specifications, IGNORE/REPLACE keywords, and temporary tables.

Examples of supported syntax:
  ```sql
  CREATE TABLE t2 SELECT * FROM t1;
  CREATE TABLE t2 AS SELECT * FROM t1;
  CREATE TABLE t2(id INT) AS SELECT * FROM t1;
  CREATE TABLE t2(id INT) AS (SELECT * FROM t1);
  CREATE TABLE IF NOT EXISTS t2(id INT) SELECT * FROM t1;
  CREATE TABLE t2 AS SELECT id, COUNT(*) AS count FROM t1 GROUP BY id HAVING count >= 1;
  CREATE TABLE t3 AS SELECT t1.id, t2.name FROM t1 JOIN t2 ON t1.id = t2.id WHERE t1.id > 10 ORDER BY t1.id LIMIT 10;
  CREATE TABLE ks.t2 AS SELECT id, name FROM unsharded_ks.t1;
  CREATE TEMPORARY TABLE t2 AS SELECT id FROM t1;
  CREATE TABLE t2(id INT UNIQUE KEY) IGNORE AS SELECT * FROM t1;
  CREATE TABLE t2 REPLACE SELECT * FROM t1;
  CREATE TABLE t2(id INT) ENGINE=INNODB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin PARTITION BY RANGE (id) (PARTITION p0 VALUES LESS THAN (100), PARTITION p1 VALUES LESS THAN (200)) AS SELECT * FROM t1;
```

Implementation references MySQL official documentation:
- [CREATE TABLE Statement](https://dev.mysql.com/doc/refman/8.4/en/create-table.html)
- [CREATE TABLE ... SELECT Statement](https://dev.mysql.com/doc/refman/8.4/en/create-table-select.html)
- [CREATE TEMPORARY TABLE Statement](https://dev.mysql.com/doc/refman/8.4/en/create-temporary-table.html)

## Related Issue(s)
Fixes #17983

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/sqlparser/ast.go [hunk 1]
```diff
@@ -574,13 +574,16 @@ type (
...
-		FullyParsed bool
+		Temp            bool
+		Table           TableName
+		IfNotExists     bool
+		TableSpec       *TableSpec
+		OptLike         *OptLike
+		Comments        *ParsedComments
+		Select          TableStatement
+		IgnoreOrReplace string
+		HasAs           bool
```
Comment (dbussink) [inline go/vt/sqlparser/ast.go]: Is this needed? In general, we don't keep different variations that semantically are 100% equivalent. We pick one form and normalize to that essentially. This is also important for things like AST equivalence operations that would otherwise see things as different queries that are not different things.

Comment (wukuai) [reply go/vt/sqlparser/ast.go]: You're right! `HasAs` was unnecessary since both forms are semantically identical. I've removed it and normalized all CREATE TABLE ... SELECT statements to always include "AS", ensuring proper AST equivalence.

File: tools/check_make_parser.sh [hunk 2]
```diff
@@ -20,7 +20,7 @@ fi
 
 mv $CUR $TMP
 output=$(go run ./goyacc -fo $CUR sql.y)
-expectedOutput=$'\nconflicts: 5 shift/reduce'
+expectedOutput=$'\nconflicts: 7 shift/reduce'
```
Comment (dbussink) [inline tools/check_make_parser.sh]: We should not add additional shift/reduce conflicts. Can you try to resolve these?

File: go/vt/sqlparser/sql.y [hunk 3]
```diff
@@ -8489,6 +8505,13 @@ ignore_opt:
 | IGNORE
   { $$ = true }
 
+ignore_or_replace_opt:
+  { $$ = "" }
+| IGNORE
+  { $$ = "ignore" }
+| REPLACE
+  { $$ = "replace" }
+
```
Comment (dbussink) [inline go/vt/sqlparser/sql.y:8525]: I think we should introduce an enum style integer for this instead of using strings. See for example this one:

```
type PartitionByType int8

// Constant for Enum Type - PartitionByType
const (
	HashType PartitionByType = iota
	KeyType
	RangeType
	ListType
)
```

Comment (wukuai) [reply go/vt/sqlparser/sql.y:8525]: Thanks! I've implemented the IgnoreOrReplaceType enum as suggested.

File: tools/check_make_parser.sh (hunk 2 above)
Comment (wukuai) [reply tools/check_make_parser.sh]: Yes! I tried multiple approaches to resolve this issue. The shift/reduce conflict count has been reduced from 7 to 5 (no new conflicts vs. original baseline).

**Review by dbussink — APPROVED** [review]
