### PR TITLE
vitessdriver: send string for binary result values

### LINKED ISSUE #19181: v23 regression: inserting JSON values throws an error
### Overview of the Issue

Inserting JSON that has worked for almost the full history of Vitess now throws an error. I tried rolling back vtgate first, and that had no effect. Rolling back vttablet resolved the issue.

`
target: workspaces.0.primary: vttablet: rpc error: code = Unknown desc = Cannot create a JSON value from a string with CHARACTER SET 'binary'. (errno 3144) (sqlstate 22032) (CallerID: unsecure_grpc_client): Sql: "insert into workspaces_rankings__pulls_by_team(workspace_id, team_id, pull_id, ranking_id, requested, keyword_id, keyword_sources) values (:v1, :v2, :v3, :v4, :v5, :v6, :v7)", BindVars: {v1: "type:INT64 value:\"15644401301101\""v2: "type:INT64 value:\"910629795084904\""v3: "type:INT64 value:\"2778530002\""v4: "type:INT64 value:\"2783412902\""v5: "type:INT64 value:\"1768867200\""v6: "type:INT64 value:\"101323530\""v7: "type:VARBINARY value:\"[]\""}
`

### Reproduction Steps

```sql
CREATE TABLE `json_test` (
  `pk` int NOT NULL AUTO_INCREMENT,
  `json_field` json DEFAULT NULL,
  PRIMARY KEY (`pk`)
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci
```

`INSERT INTO json_test (json_field) VALUES (?); ? = []`

_copied from comment below_

Looks like vttablet is treating string vs byte data differently.

Succeeds
```go
_, err := db.ExecContext(c, "INSERT INTO companies.json_test (json_field) VALUES (?)", string(`[]`))
```

Errors with `Cannot create a JSON value from a string with CHARACTER SET 'binary'`
```go
_, err := db.ExecContext(c, "INSERT INTO companies.json_test (json_field) VALUES (?)", []byte(`[]`))
```

Here's the relevant log line
```
E0120 19:44:05.059370   16952 tabletserver.go:1709] Cannot create a JSON value from a string with CHARACTER SET 'binary'. (errno 3144) (sqlstate 22032) (CallerID: unsecure_grpc_client): Sql: "insert into json_test(json_field) values (:v1)", BindVars: {v1: "type:VARBINARY value:\"[]\""}
```

### Binary Version

```sh
v23.0.0

Using Go vitessdriver `v0.10.3-0.20240819130500-fae754069009`
```

### Operating System and Environment details

```sh
GKE v1.33.5
```

### Log Fragments

```sh

```

### PR DESCRIPTION
**Pull request by derekperkins**
## Description
Apologies, my prior PR in #19527 did the string conversion the wrong direction, coming out of Vitess vs going into Vitess. This reverts that change and does a similar conversion before building the bind variable.

## Related Issue(s)
- fixes #19181 
- reverts #19527 

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### AI Disclosure

None

### CODE REVIEW

File: go/vt/vitessdriver/convert.go [hunk 1]
```diff
@@ -58,10 +54,19 @@ func (cv *converter) ToNative(v sqltypes.Value) (any, error) {
...
 
 func (cv *converter) BuildBindVariable(v any) (*querypb.BindVariable, error) {
-	if t, ok := v.(time.Time); ok {
+	switch t := v.(type) {
+	case time.Time:
 		return sqltypes.ValueBindVariable(NewDatetime(t, cv.location)), nil
+	case []byte:
+		if t == nil {
+			return sqltypes.NullBindVariable, nil
+		}
```
Comment (derekperkins) [inline go/vt/vitessdriver/convert.go:63]: I wasn't quite sure what the right behavior here was. There are three outcomes:
- `NullBindVariable`: what is happening here, which is an untyped null
- Typed `NULL` as `VARBINARY`: this is the only one I'm fairly confident that we don't want, as it is likely to trigger a similar error for json values
- Typed `NULL` as `VARCHAR`: this maintains the spirit of the string conversion here, but may be unnecessary

Is there any reason to choose a typed null over what is currently happening? This has to happen before the string conversion because string isn't nullable natively

**Comment by derekperkins** [comment]
@codex

File: go/vt/vitessdriver/convert_test.go [hunk 2]
```diff
@@ -201,3 +202,53 @@ func TestToNative(t *testing.T) {
...
+	convert := &converter{location: time.UTC}
+	for _, tcase := range testcases {
+		t.Run(tcase.name, func(t *testing.T) {
+			bv, err := convert.BuildBindVariable(tcase.in)
+			if err != nil {
+				t.Fatal(err)
+			}
+			if !reflect.DeepEqual(bv, tcase.out) {
+				t.Fatalf("BuildBindVariable(%v) = %#v, want %#v", tcase.in, bv, tcase.out)
+			}
```
Comment (mattlord) [inline go/vt/vitessdriver/convert_test.go]: Nit, but we should use require in new tests.

Comment (derekperkins) [reply go/vt/vitessdriver/convert_test.go]: changed and I added a commit migrating the rest of the vitessdriver tests to require
