### PR TITLE
Fix CheckMySQL by setting the correct wanted state

### LINKED ISSUE #11885: Tracking CheckMySQL and Query Engine history
There have been multiple failures in `CheckMySQL` code that cause it to get stuck. This issue documents the history of all the changes that have been made to this codepath to better understand the intent and the evolution of the code over time.

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description

This PR fixes the bug uncovered in https://github.com/vitessio/vitess/issues/11885#issuecomment-1339141876. 
The main issue is that when we call `CheckMySQL` we do not set the correct wanted state. This leads to new queries not being blocked while we are waiting for the requests waitgroup to be empty. 
After looking at the history of how the code evolved in https://github.com/vitessio/vitess/issues/11885, the intent of the code and the bug was clear.

This PR fixes the bug and augments an existing test to verify that we indeed do not allow new queries to come in when checkMySQL has started running.

## Related Issue(s)

- Fixes #11885 

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vttablet/tabletserver/state_manager.go [hunk 1]
```diff
@@ -330,11 +334,25 @@ func (sm *stateManager) checkMySQL() {
...
+		// unless they are part of a running transaction.
+		sm.setWantState(StateNotConnected)
 		sm.closeAll()
+
+		// Now that we reached the NotConnected state, we want to go back to the
+		// Serving state. The retry will only succeed once MySQL is reachable again
+		// Until then EnsureConnectionAndDB will error out.
+		sm.setWantState(StateServing)
 		sm.retryTransition(fmt.Sprintf("Cannot connect to MySQL, shutting down query service: %v", err))
 	}()
```
Comment (harshit-gangal) [inline go/vt/vttablet/tabletserver/state_manager.go:347]: changes are good, 

Just wanted to know why we cannot just call `SetServingType` methods which take the same actions. Also, we would have a single code path for state changes.

Comment (GuptaManan100) [reply go/vt/vttablet/tabletserver/state_manager.go:347]: We can't use that because in `mustTransition` we use `Acquire` whereas here we want to use `TryAcquire`. Also that call requires a tablet type to call to, which is something we don't want to tweek at all. So there is a trade-off between the two implementations, one. will have a single code-path but with many more if-else conditions, and this wherein there are 2 code-paths but both succinct in their implementations

**Review by harshit-gangal — APPROVED** [review]

**Review by frouioui — APPROVED** [review]
