### PR TITLE
make sure to add necessary bindvars when preparing queries

### LINKED ISSUE #7379: vtgate: query arguments missing for __vtdbname
#### Overview of the Issue
When testing `diesel migration run` with [one of Diesel's examples](https://github.com/diesel-rs/diesel/tree/master/examples/mysql/getting_started_step_1), I'm hitting the error from the title:
```
vtgate: http://78bab1349f40:33574/: query arguments missing for __vtdbname
```

The query that aggravated it was `SELECT database()` but when I execute that from the `mysql` CLI, it returns as normal.  I tried setting all the variables that Diesel sets, but it still succeeds.  I'll attach a packet capture.

#### Reproduction Steps
```bash
docker run --rm -it --entrypoint=bash gcr.io/planetscale-vitess-testing/frameworks/rust/diesel -c 'export DATABASE_URL=mysql://USERNAME:PASSWORD@HOST:PORT/DATABASE?ssl-mode=DISABLED; cd getting_started_step_1; diesel migration run'
```

#### Binary version
Using `vttestserver`, which doesn't support `-version`, but here's output from `vtcombo` in the same container:
```
$ /vt/bin/vtcombo -version
ERROR: logging before flag.Parse: E0125 18:43:12.741403     754 syslogger.go:149] can't connect to syslog
Version: acb3b4e1d (Git branch 'master') built on Mon Jan 25 16:57:11 UTC 2021 by vitess@6c41847a305c using go1.15.6 linux/amd64
```

#### Operating system and Environment details
Inside the `vttestserver` container:
```vitess@3e5d5c6a960a:/$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
vitess@3e5d5c6a960a:/$ uname -sr 
Linux 5.10.2-2-MANJARO
vitess@3e5d5c6a960a:/$ uname -m
x86_64
```

#### Log Fragments
With query logging enabled, I get this:
```
Prepare 172.17.0.4:48530        root    'userData1'     'root'  2021-01-25 22:16:12.025626      2021-01-25 22:16:12.025678      0.000052        0.000040     0.000012 0.000000        SELECT  "select :__vtdbname as `database()` from dual"  map[]   0       0       "query arguments missing for __vtdbname"        ""   ""       ""
```
but nothing else

### PR DESCRIPTION
**Pull request by systay**
Fixes #7379 

Some queries need extra bindvars injected before executing. The error here was that for the field type query during `PREPARE`, we were not setting all the required bindvars.

Signed-off-by: Andres Taylor <andres@planetscale.com>

### CODE REVIEW

File: go/vt/vtgate/executor_select_test.go [hunk 1]
```diff
@@ -2178,6 +2178,17 @@ func TestSelectBindvarswithPrepare(t *testing.T) {
...
+	executor, _, _, _ := createExecutorEnv()
+	executor.normalize = true
+	logChan := QueryLogger.Subscribe("Test")
+	defer QueryLogger.Unsubscribe(logChan)
+
+	sql := "select database()"
+	_, err := executorPrepare(executor, sql, map[string]*querypb.BindVariable{})
+	require.NoError(t, err)
+}
+
```
Comment (harshit-gangal) [inline go/vt/vtgate/executor_select_test.go:2191]: nit: could assert that the bindvars were added.

**Review by harshit-gangal — APPROVED** [review]
