### PR TITLE
Complex Expression handling for uncorrelated IN and NOT IN subqueries

### LINKED ISSUE #16433: Bug Report: Uncorrelated subquery with a aggregation is not working
### Overview of the Issue

Consider the following query - 
```sql
select count(*) from user where user.id = 2 or user.id in (select id from unsharded_a where colb = 2)
```

The query has an uncorrelated subquery in the where condition of a sharded query having an aggregation. Currently Vitess is unable to support it, and errors out with the error - `VT12001: unsupported: unmergable subquery can not be inside complex expression`

### Reproduction Steps

1. Run the given query in onecase of plan_tests.

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
-
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description

As described in https://github.com/vitessio/vitess/issues/16433, Vitess did not support complex expressions even in uncorrelated queries.
This PR adds this support. One change that we had to make was with how we add `:__sq_has_values` expression on IN and NOT IN subqueries. Previously we would add the clause after we replaced the subquery with a list argument. That worked well for cases wherein we didn't have a complex expression but doesn't work well otherwise. 

For example, for a query like `select count(*) from user where user.id = 2 or user.id in (select id from unsharded_a where colb = 2)`, after we pullout the subquery, we want the final query to look like 
```sql
select count(*) from `user` where `user`.id = 2 or (:__sq_has_values and `user`.id in ::__sq1)
```
and not like 
```sql
select count(*) from `user` where :__sq_has_values and (`user`.id = 2 or `user`.id in ::__sq1)
```

## Related Issue(s)

- Fixes #16433 

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vtgate/planbuilder/operators/subquery.go [hunk 1]
```diff
@@ -208,7 +208,7 @@ func (sq *SubQuery) GetMergePredicates() []sqlparser.Expr {
 }
 
 func (sq *SubQuery) settle(ctx *plancontext.PlanningContext, outer Operator) Operator {
-	if !sq.TopLevel {
+	if !sq.TopLevel && sq.correlated {
```
Comment (frouioui) [inline go/vt/vtgate/planbuilder/operators/subquery.go:211]: Can you explain why this is needed?

Comment (GuptaManan100) [reply go/vt/vtgate/planbuilder/operators/subquery.go:211]: We want to allow uncorrelated queries when subquery isn't the top level construct, like its underneath an Aggregator, and we can allow uncorrelated queries because they will be pulled out and run separately.

Comment (GuptaManan100) [reply go/vt/vtgate/planbuilder/operators/subquery.go:211]: I'll add a comment to the code too for ☝️

File: go/vt/vtgate/planbuilder/operators/subquery.go [hunk 2]
```diff
@@ -253,6 +253,20 @@ func (sq *SubQuery) settleFilter(ctx *plancontext.PlanningContext, outer Operato
 	}
 	post := func(cursor *sqlparser.CopyOnWriteCursor) {
 		node := cursor.Node()
+		// For IN and NOT IN type filters, we have to add a Expression that checks if we got any rows back or not
+		// for correctness. That expression should be ANDed with the expression that has the IN/NOT IN comparison.
+		if compExpr, isCompExpr := node.(*sqlparser.ComparisonExpr); sq.FilterType.NeedsListArg() && isCompExpr {
+			if listArg, isListArg := compExpr.Right.(sqlparser.ListArg); isListArg && listArg.String() == sq.ArgName {
```
Comment (frouioui) [inline go/vt/vtgate/planbuilder/operators/subquery.go:259]: Should we not check for either the right or left hand side of the outer's comparison? The query we are trying to support contains the subquery comparison on the RHS of the `OR` but what if the query was the following:
```sql
# new query
select count(*) from user where user.id in (select id from unsharded_a where colb = 2) or user.id = 2

# instead of
select count(*) from user where user.id = 2 or user.id in (select id from unsharded_a where colb = 2)
```

This comment applies to both this code and the code later in the same function where we construct the list of predicates, line `298`.

File: go/vt/vtgate/planbuilder/operators/subquery.go (hunk 1 above)
Comment (frouioui) [reply go/vt/vtgate/planbuilder/operators/subquery.go:211]: Got it, thank you

File: go/vt/vtgate/planbuilder/operators/subquery.go (hunk 2 above)
Comment (GuptaManan100) [reply go/vt/vtgate/planbuilder/operators/subquery.go:259]: The comparision operation in question is `user.id IN (subquery)`, and the right side in this is the subquery. And the subquery can't be on the left side as in `(subquery) IN user.id`.

Comment (frouioui) [reply go/vt/vtgate/planbuilder/operators/subquery.go:259]: Makes sense! Thank you.

**Review by frouioui — APPROVED** [review]

File: go/vt/vtgate/planbuilder/operators/subquery.go (hunk 1 above)
Comment (GuptaManan100) [reply go/vt/vtgate/planbuilder/operators/subquery.go:213]: Added the comment

**Review by harshit-gangal — APPROVED** [review]
