### PR TITLE
Unnest simple subqueries

### LINKED ISSUE #6827: INFORMATION_SCHEMA.TABLE_SCHEMA comparison with dynamic value no longer works
#6638 seems to have broken this query (based on our `101_initial_cluster.sh` cluster examples):

```
mysql> SELECT column_name FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = (SELECT SCHEMA()) AND TABLE_NAME = 'product' AND COLUMN_KEY = 'PRI';
ERROR 1235 (HY000): vtgate: http://localhost:15001/: comparison with `table_schema` column not supported
```

However, bare comparisons with a static value still works:

```
mysql> SELECT column_name FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = "commerce" AND TABLE_NAME = 'product' AND COLUMN_KEY = 'PRI';
+-------------+
| COLUMN_NAME |
+-------------+
| sku         |
+-------------+
```

if you revert #6638 , and run the first query, it works as expected:

```
mysql> SELECT column_name FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_SCHEMA = (SELECT SCHEMA()) AND TABLE_NAME = 'product' AND COLUMN_KEY = 'PRI';
+-------------+
| COLUMN_NAME |
+-------------+
| sku         |
+-------------+
```

This has broken Apache Sqoop, which generates queries like this, and the form of the query cannot be overridden (at least in Sqoop 1.4.7)

### PR DESCRIPTION
**Pull request by systay**
This PR adds logic to simplify subquery expressions that are simple to unnest.

If a query contains an expression looking something like:

```
SELECT * FROM user WHERE col = (SELECT 42)
```

this PR will unnest that subquery so that the query that is planned is instead:

```
SELECT * FROM user WHERE col = 42
```

Fixes #6827

### CODE REVIEW

**Review by harshit-gangal — APPROVED** [review]

**Review by GuptaManan100 — APPROVED** [review]
LGTM

File: go/vt/vtgate/executor_select_test.go [hunk 1]
```diff
@@ -509,7 +509,7 @@ func TestLastInsertIDInSubQueryExpression(t *testing.T) {
 	_, err := executorExec(executor, "select (select last_insert_id()) as x", nil)
 	require.NoError(t, err)
 	wantQueries := []*querypb.BoundQuery{{
-		Sql:           "select (select :__lastInsertId as `last_insert_id()` from dual) as x from dual",
+		Sql:           "select last_insert_id() as x from dual",
 		BindVariables: map[string]*querypb.BindVariable{"__lastInsertId": sqltypes.Uint64BindVariable(0)},
 	}}
```
Comment (harshit-gangal) [inline go/vt/vtgate/executor_select_test.go]: expected sql query looks wrong to me
this should be `select :__lastInsertId as x from dual`

**Review by harshit-gangal — CHANGES_REQUESTED** [review]
As I approved this earlier, making this as blocking so that I understand the change before merging.

File: go/vt/vtgate/executor_select_test.go [hunk 2]
```diff
@@ -508,12 +508,9 @@ func TestLastInsertIDInSubQueryExpression(t *testing.T) {
...
 	require.NoError(t, err)
-	wantQueries := []*querypb.BoundQuery{{
-		Sql:           "select (select :__lastInsertId as `last_insert_id()` from dual) as x from dual",
-		BindVariables: map[string]*querypb.BindVariable{"__lastInsertId": sqltypes.Uint64BindVariable(0)},
-	}}
 
-	assert.Equal(t, wantQueries, sbc1.Queries)
+	// the query will get rewritten into a simpler query that can be run entirely on the vtgate
+	assert.Empty(t, sbc1.Queries)
 }
```
Comment (harshit-gangal) [inline go/vt/vtgate/executor_select_test.go:514]: 1. This test does not require sbc1.SetResults as it does not go to sandbox connections.
1. Validate the query result of executed query it should match what is there in the session lastInsertId

**Review by harshit-gangal — APPROVED** [review]
I looked as old commit. Ignore my previous comment.
One comment on test expectations.
