### PR TITLE
Fix #14414:  resilient_server metrics name/prefix logic is inverted, leading to no metrics being recorded

### LINKED ISSUE #14414: Bug Report:  resilient_server metrics name/prefix logic is inverted, leading to no metrics being recorded
### Overview of the Issue

By inspection, if you look at:

https://github.com/vitessio/vitess/blob/main/go/vt/srvtopo/resilient_server.go#L87-L93

You can see that it cannot be correct.  `NewResilientServer(..)` is always called with a value for `counterPrefix`, and by the logic above, the metric will always be zeroed out.

I assume the logic is just inverted, and that is reflected in the fact that (for example) `vtgate` metrics is recorded as I would expect if you invert the logic in the `if` statement.

Without the change:
  * No `resilient_srv_topo...` metrics are recorded, for example, in `vtgate`

With the change:
  * Metrics are recorded as expected, e.g.:
```
$ curl -s http://localhost:15001/metrics | grep -i resil
# HELP vtgate_resilient_srv_topo_server_counts Resilient srvtopo server operations
# TYPE vtgate_resilient_srv_topo_server_counts counter
vtgate_resilient_srv_topo_server_counts{type="query"} 7
```

### Reproduction Steps

See overview

### Binary Version

```sh
I was testing against release-16.0;  but as noted above, the code is still the same in main.
```

### Operating System and Environment details

```sh
Linux x86_64, Fedora 38
```

### Log Fragments

```sh
See above
```

### PR DESCRIPTION
**Pull request by aquarapid**
## Description

The logic for the topo resilient server has been apparently broken since it was introduced.  I fixed a single test that was mis-named, that led to a panic with this change.  I would like to test that the name of the metric is now correct, but the stats module does not make that easy, so something like an end-to-end test would be required, and I do not think this fix justifies that level of effort. 

Unnecessary to backport, affects metrics only.

## Related Issues
  - Fixes: https://github.com/vitessio/vitess/issues/14414

## Checklist

-   [X] "Backport to:" labels have been added if this change should be back-ported
-   [X] Tests were added or are not required
-   [X] Did the new or modified tests pass consistently locally and on the CI
-   [X] Documentation was added or is not required

### CODE REVIEW

File: go/vt/srvtopo/resilient_server.go [hunk 1]
```diff
@@ -85,7 +85,7 @@ func NewResilientServer(ctx context.Context, base *topo.Server, counterPrefix st
 	}
 
 	var metric string
-	if counterPrefix == "" {
+	if counterPrefix != "" {
```
Comment (harshit-gangal) [inline go/vt/srvtopo/resilient_server.go:88]: nit: the `else` can be removed.

**Review by harshit-gangal — APPROVED** [review]
good find. A small comment for cleanup.  
Looks good.

**Comment by dbussink** [comment]
There's a test failure here, does the test also expect the incorrect case?

```
--- FAIL: TestVStreamsCreatedAndLagMetrics (0.00s)
    vstream_manager_test.go:386: 
        	Error Trace:	/home/runner/work/vitess/vitess/go/vt/vtgate/vstream_manager_test.go:386
        	Error:      	Not equal: 
        	            	expected: map[string]int64{"TestVStream.-20.PRIMARY":5, "TestVStream.20-40.PRIMARY":7}
        	            	actual  : map[string]int64{"TestVStream.-20.PRIMARY":5, "TestVStream.20-40.PRIMARY":0}
        	            	
        	            	Diff:
        	            	--- Expected
        	            	+++ Actual
        	            	@@ -2,3 +2,3 @@
        	            	  (string) (len=23) "TestVStream.-20.PRIMARY": (int64) 5,
        	            	- (string) (len=25) "TestVStream.20-40.PRIMARY": (int64) 7
        	            	+ (string) (len=25) "TestVStream.20-40.PRIMARY": (int64) 0
        	            	 }
        	Test:       	TestVStreamsCreatedAndLagMetrics
        	Messages:   	vstreamsLag matches
```

**Comment by deepthi** [comment]
Just leaving a note for any others who see this that I'm going to pick this up and fix the tests.

**Review by deepthi — APPROVED** [review]
