### PR TITLE
mysql: Ensure we set up the initial collation correctly

### LINKED ISSUE #15112: Bug Report: Broken charset response when establishing MySQL connection to Vitess 19
### Overview of the Issue

Unable to connect to Vitess 19 using PHP PDO (as used by all the major frameworks including Laravel). This issue is not present on Vitess 18.

### Reproduction Steps

Connect to a fresh copy of `vitess/vttestserver:mysql80`, for example using docker compose config:

```yaml
  db:
    image: vitess/vttestserver:mysql80
    command: "/vt/bin/vttestserver --alsologtostderr --port=33574 --mysql_bind_host=0.0.0.0 --keyspaces=test --num_shards=1"
    networks:
      - voxie
    ports:
      - "33577:33577"
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h127.0.0.1', '-P33577']
      interval: 5s
      timeout: 2s
      retries: 20
```

Connect to the server using PHP PDO. For example, using any version of PHP 8 compiled with MySQL PDO support:

```php
<?php

new PDO(
    'mysql:host=127.0.0.1;port=33577;dbname=test',
    'root',
    '',
);
```

Running the file (`php test.php`) results in the following crash:

```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000] [2054] Server sent charset (0) unknown to the client. Please, report to the developers
```

### Binary Version

vtgate is not present within the Docker image, but vtcombo is.

```sh
vtcombo version Version: 19.0.0-SNAPSHOT (Git revision 6f9c5c2ffed3be3416198b9de4c49323b946c0e5 branch 'main') built on Thu Feb  1 15:26:02 UTC 2024 by vitess@buildkitsandbox using go1.21.6 linux/amd64
```

### Operating System and Environment details

Running within Docker on MacOS. Results from within the running container:

```sh
PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

```sh
Linux 6.6.12-linuxkit
```

```
x86_64
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by dbussink**
The collation env refactor missed a bunch of setup for the MySQL listener, which resulted in a missing initial collation on the connection.

This fixes that and adds additional assertions as well.

## Related Issue(s)

Fixes #15112

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by GrahamCampbell — APPROVED** [review]
Thanks for looking at this so quickly! I've pulled this down and built it locally, and I confirm that this works, and PHP is happy to establish the connection again. 🎉

File: go/mysql/server.go [hunk 1]
```diff
@@ -315,15 +306,16 @@ func NewListenerWithConfig(cfg ListenerConfig) (*Listener, error) {
...
 		connectionID:        1,
 		connReadTimeout:     cfg.ConnReadTimeout,
 		connWriteTimeout:    cfg.ConnWriteTimeout,
 		connReadBufferSize:  cfg.ConnReadBufferSize,
 		connBufferPooling:   cfg.ConnBufferPooling,
 		connKeepAlivePeriod: cfg.ConnKeepAlivePeriod,
 		flushDelay:          cfg.FlushDelay,
-		truncateErrLen:      cfg.TruncateErrLen,
+		truncateErrLen:      cfg.Handler.Env().TruncateErrLen(),
+		charset:             cfg.Handler.Env().CollationEnv().DefaultConnectionCharset(),
```
Comment (ajm188) [inline go/mysql/server.go:318]: 👍

**Review by ajm188 — APPROVED** [review]

File: go/mysql/server.go [hunk 2]
```diff
@@ -315,15 +306,16 @@ func NewListenerWithConfig(cfg ListenerConfig) (*Listener, error) {
 		authServer:          cfg.AuthServer,
 		handler:             cfg.Handler,
 		listener:            l,
-		ServerVersion:       cfg.MySQLServerVersion,
+		ServerVersion:       cfg.Handler.Env().MySQLVersion(),
```
Comment (mattlord) [inline go/mysql/server.go:309]: Can Handler and/or Env() be nil here? IMO it's worth a safety check here that returns an error or even an explicit panic with a message if it really shouldn't happen and we can't proceed. Same for the `cfg.Handler` call chains below.

**Review by mattlord — APPROVED** [review]

File: go/mysql/server.go (hunk 2 above)
Comment (dbussink) [reply go/mysql/server.go:309]: It should never ever be nil under any circumstance. That it panics in that case is good. I  don't think we should guard this, as it means many guards all over the place then (the env is used in many other places too).
