### PR TITLE
check replication lag on state change before starting query service

### LINKED ISSUE #4426: Tablets serving stale data after backup
#### Overview of the Issue

(credit to @zmagg for the initial writeup that is ~reproduced here)

When a tablet completes creating a backup it returns to a `SERVING` state without consideration of accrued replication lag. If this value larger than you're comfortable serving in then there is a period of time between completing the backup and detecting a tablet in this unhealthy state where you're serving stale data.

The fallout is unnecessarily noisy alerts and potentially serving bad data.

#### Reproduction Steps

Roughly:

1. Begin backup that takes a non trivial period of time
2. Master receives enough writes that replication is slow
3. Observe tablet serving queries during replication while lag > an unhealthy threshold
4. Healthchecks notice unhealthy state and tablet stops serving queries

#### Log Fragments

```
15:00:54.948165 tabletserver.go:312] TabletServer state: NOT_SERVING (Not Connected) -> NOT_SERVING (Transitioning)
15:00:54.970844 engine.go:183] Time taken to load the schema: 1.053µs
15:00:54.973905 tabletserver.go:312] TabletServer state: NOT_SERVING (Transitioning) -> SERVING
15:00:54.973935 updatestreamctl.go:213] Enabling update stream, dbname: vt_byteam
15:00:54.973985 state_change.go:154] Done with post-action state refresh
15:00:54.975066 rpc_server.go:93] TabletManager.Backup(concurrency:4 )(on us_east_1-0100125104 from ): <nil>
15:00:55.977517 healthcheck.go:269] Disabling query service because of health-check failure: reported replication lag: 3049 higher than unhealthy threshold: 300
15:00:55.977543 tabletserver.go:312] TabletServer state: SERVING -> SHUTTING_DOWN (Shutting Down)
```

#### Suggested Fix

Tablets will transition into `NOT_SERVING` once completing a backup and we'll let health checks determine that it's safe to move them into a serving state when lag < healthy threshold.

### PR DESCRIPTION
**Pull request by deepthi**
Fixes #4426 
- check replication delay on replica during state_change before setting it to SERVING
- restored tablets should always start as NOT_SERVING
- SecondsBehindMaster from `SHOW SLAVE STATUS` gets set to 0 when replication is stopped and restarted. Implemented logic in backup/restore to ensure that either replication has caught up to master, or has progressed from last known position before this can be trusted to compute replication delay.

Signed-off-by: deepthi <deepthi@planetscale.com>

### CODE REVIEW

File: go/vt/vttablet/tabletmanager/state_change.go [hunk 1]
```diff
@@ -218,6 +218,18 @@ func (agent *ActionAgent) changeCallback(ctx context.Context, oldTablet, newTabl
 					disallowQueryReason = "master tablet with filtered replication on"
 				}
 			}
+			if newTablet.Type == topodatapb.TabletType_REPLICA {
+				replicationDelay, healthErr := agent.HealthReporter.Report(true, true)
```
Comment (setassociative) [inline go/vt/vttablet/tabletmanager/state_change.go]: Generally this makes a bunch of sense. I'm mostly amused as my notes on #4426 suggests I'd tried this or similar and couldn't get it working. Though possibly I went the route of `agent.runHealthCheckLocked()` which contains a `Report` instead of calling directly. Do you know if that would make a difference here?

If not, should we call it so that we get the lag data recorded as part of the history & a report sent to observers?

File: go/vt/vttablet/tabletmanager/state_change.go [hunk 2]
```diff
@@ -218,6 +218,18 @@ func (agent *ActionAgent) changeCallback(ctx context.Context, oldTablet, newTabl
 					disallowQueryReason = "master tablet with filtered replication on"
 				}
 			}
+			if newTablet.Type == topodatapb.TabletType_REPLICA {
```
Comment (setassociative) [inline go/vt/vttablet/tabletmanager/state_change.go]: is there a case where we would want something to serve if it has lag > unhealthy state? Possibly this should always if it's not a master

Comment (deepthi) [reply go/vt/vttablet/tabletmanager/state_change.go]: good point. I was thinking at a minimum to also include RDONLY but "not master" makes more sense.

File: go/vt/vttablet/tabletmanager/state_change.go [hunk 3]
```diff
@@ -218,6 +218,18 @@ func (agent *ActionAgent) changeCallback(ctx context.Context, oldTablet, newTabl
...
+				replicationDelay, healthErr := agent.HealthReporter.Report(true, true)
+				if healthErr != nil {
```
[the remark this answers is not in the document]
Comment (deepthi) [reply go/vt/vttablet/tabletmanager/state_change.go]: Yes, good point.

File: go/vt/vttablet/tabletmanager/state_change.go (hunk 1 above)
Comment (deepthi) [reply go/vt/vttablet/tabletmanager/state_change.go]: I tried this, and it had the unexpected side effect of changing a REPLICA tablet to UNKNOWN in some of the unit tests. Need to dig deeper.

Comment (deepthi) [reply go/vt/vttablet/tabletmanager/state_change.go]: I discussed this with @sougou and he's of the opinion that at this level in the code we should be calling low-level functions and not something like `runHealthCheckLocked`.

File: go/vt/vttablet/tabletmanager/healthcheck_test.go [hunk 4]
```diff
@@ -885,6 +885,128 @@ func TestOldHealthCheck(t *testing.T) {
...
+		t.Fatal(err)
+	}
+	if err := expectStateChange(agent.QueryServiceControl, true, topodatapb.TabletType_REPLICA); err != nil {
+		t.Fatal(err)
+	}
+
+	agent.HealthReporter.(*fakeHealthCheck).reportReplicationDelay = 16 * time.Second
+
+	// change to BACKUP, query service will turn off
+	fmt.Println("Change tablet type to BACKUP")
```
Comment (rafael) [inline go/vt/vttablet/tabletmanager/healthcheck_test.go]: Should we remove all this Println?

File: go/vt/vttablet/tabletmanager/healthcheck_test.go [hunk 5]
```diff
@@ -885,6 +885,128 @@ func TestOldHealthCheck(t *testing.T) {
...
+	if _, err := expectBroadcastData(agent.QueryServiceControl, true, "healthcheck not run yet", 0); err != nil {
+		t.Fatal(err)
+	}
+	if err := expectStateChange(agent.QueryServiceControl, true, topodatapb.TabletType_REPLICA); err != nil {
+		t.Fatal(err)
+	}
+
+	agent.HealthReporter.(*fakeHealthCheck).reportReplicationDelay = 16 * time.Second
+
+	// change to BACKUP, query service will turn off
```
Comment (rafael) [inline go/vt/vttablet/tabletmanager/healthcheck_test.go]: nit: Update comment to be RESTORE

File: go/vt/vttablet/tabletmanager/state_change.go (hunk 1 above)
Comment (rafael) [reply go/vt/vttablet/tabletmanager/state_change.go]: Oh nice. This is so close to what we tried. I remember running into the same issue you mention of `UNKNOWN`. I think I also tried `runHealthCheckLocked`

**Comment by rafael** [comment]
@deepthi  - This looks great. I think there are some `Println` that we need to remove from the tests.

Before we merge. Could you verify manually that this works? Run a manual integration test? The way we reproduce this is:
1) Have a script that writes tons of data and create lag. 
2) Take a backup while this script is running.
3) Have a script that reads from replica.
4) Notice the tablet UI that when it comes from backup, it does no longer serve any query.

File: go/vt/vttablet/tabletmanager/healthcheck_test.go (hunk 4 above)
Comment (deepthi) [reply go/vt/vttablet/tabletmanager/healthcheck_test.go]: yes

File: go/vt/vttablet/tabletmanager/healthcheck_test.go (hunk 5 above)
Comment (deepthi) [reply go/vt/vttablet/tabletmanager/healthcheck_test.go]: done.

**Comment by sougou** [comment]
This change looks good. @deepthi I can merge this once you've satisfied @rafael's request.

**Comment by deepthi** [comment]
> This change looks good. @deepthi I can merge this once you've satisfied @rafael's request.

In runHealthCheckLocked, when we set _replicationDelay we also set _healthy and _healthyTime. Should these fields also be set here?

**Comment by rafael** [comment]
@deepthi  - I was doing some of our internal testing I think the bug is still present in this branch. I think I was able to create instructions that should help you reproduce in any environment.

Using vtbench:
1) Create a credential files with this format: 
```
# vtbench_mysql_creds.json
{
   "vtgate_user":[
      "vt_pass"
  ]
}
```

2) Create a table with the following schema: 

```
CREATE TABLE `test_table` (
  `i` int(11) DEFAULT NULL,
  `c` char(10) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4
```

3) Use vtbench to insert data into the table:

```
vtbench -host localhost -protocol mysql -port 15306 -user vtgate_user -db-credentials-file ./vtbench_mysql_creds.json -db @master --count 300000 --threads 25 -sql "INSERT INTO test_table (i,c)  VALUES(1,'record one') /* vt_bench:thread */"```
```

4) This should create lag pretty quickly in the replicas.

5) Once replicas are lagging run the following:

```
while true; do vtbench -host localhost -protocol mysql -port 15306 -user vtgate_user -db-credentials-file ./vtbench_mysql_creds.json -db @replica --count 30000 --threads 25 -sql 'select count(*) from test_table'; done
```

6) If lag is beyond the serving threshold, this loop will be failing for the most part.

7) Trigger a backup to one of the replicas.

8) You will notice that when the replica comes back from backup, some queries slip in and get served: 

Screen Shot 2019-08-13 at 5 32 37 PM

**Comment by deepthi** [comment]
The latest changes do ensure that replica does not go into serving if it is lagged more than unhealthyThreshold after completing a backup.
Scenarios tested:
* tablet is healthy before backup, comes back to serving after backup
* tablet is degraded before backup, still degraded after backup, comes back to serving
* tablet is degraded before backup, unhealthy after backup, goes to non_serving
* tablet is unhealthy before backup, stays non_serving after backup

There are a few oddities to be noted:
* when trying to change tablet type and state after completing a backup, if the tablet is lagged, it stays in BACKUP type until it is caught up and only then transitions into REPLICA type. This seems to be an artifact of how state_change has been implemented in the code.
* in my testing, I stop writing to the master after a while a wait for the replica to catch up (post-backup). the lag will keep growing even as the gap between Executed_Gtid_Set and Retrieved_Gtid_Set narrows. I suspect this is because there are no new transactions on the master (which would trigger a proper re-eval of SecondsBehindMaster). Only when the Executed_Gtid_Set catches up to master, the SecondsBehindMaster goes to 0. So instead of gradually dropping, it suddenly goes to 0. This is probably not going to happen in a real system where there is continuous traffic to master.

Restore testing TBD.

File: go/vt/mysqlctl/builtinbackupengine.go [hunk 6]
```diff
@@ -236,7 +239,22 @@ func findFilesToBackup(cnf *Mycnf) ([]FileEntry, error) {
 
 // ExecuteBackup returns a boolean that indicates if the backup is usable,
 // and an overall error.
-func (be *BuiltinBackupEngine) ExecuteBackup(ctx context.Context, cnf *Mycnf, mysqld MysqlDaemon, logger logutil.Logger, bh backupstorage.BackupHandle, backupConcurrency int, hookExtraEnv map[string]string) (bool, error) {
+func (be *BuiltinBackupEngine) ExecuteBackup(ctx context.Context, params BackupParams) (bool, error) {
+
+	// extract all params from BackupParams
```
[the remark this answers is not in the document]
Comment (deepthi) [reply go/vt/mysqlctl/builtinbackupengine.go]: that params struct is used to pass the params down two levels of calls. Not all params are used at both levels so it is a union of the two sets of params. Do you still feel like we should not extract the params into vars?

File: go/vt/mysqlctl/backup.go [hunk 7]
```diff
@@ -217,15 +219,16 @@ func removeExistingFiles(cnf *Mycnf) error {
...
-	cnf *Mycnf,
-	mysqld MysqlDaemon,
-	dir string,
-	restoreConcurrency int,
-	hookExtraEnv map[string]string,
-	localMetadata map[string]string,
-	logger logutil.Logger,
-	deleteBeforeRestore bool,
-	dbName string) (mysql.Position, error) {
+	params RestoreParams) (mysql.Position, error) {
```
[the remark this answers is not in the document]
Comment (deepthi) [reply go/vt/mysqlctl/backup.go]: fixed with the latest push

File: go/vt/mysqlctl/builtinbackupengine.go [hunk 8]
```diff
@@ -328,12 +352,35 @@ func (be *BuiltinBackupEngine) ExecuteBackup(ctx context.Context, cnf *Mycnf, my
 		if err := WaitForSlaveStart(mysqld, slaveStartDeadline); err != nil {
 			return usable, vterrors.Wrap(err, "slave is not restarting")
 		}
-	}
 
-	// And set read-only mode
-	logger.Infof("resetting mysqld read-only to %v", readOnly)
-	if err := mysqld.SetReadOnly(readOnly); err != nil {
-		return usable, err
+		// wait for reliable seconds behind master
```
Comment (setassociative) [inline go/vt/mysqlctl/builtinbackupengine.go]: doc nit: "Wait for a reliable 'seconds behind master' value" or something. My initial read of this was that it was going to wait for a number of seconds that we considered reliable to have us get a new seconds behind master reading.

File: go/vt/mysqlctl/builtinbackupengine.go [hunk 9]
```diff
@@ -328,12 +348,34 @@ func (be *BuiltinBackupEngine) ExecuteBackup(ctx context.Context, cnf *Mycnf, my
...
+		// have happened to master, so we are up-to-date
+		// otherwise, wait for replica's Position to change from
+		// the saved replicationPosition before proceeding
+		tmc := tmclient.NewTabletManagerClient()
+		remoteCtx, remoteCancel := context.WithTimeout(ctx, *topo.RemoteOperationTimeout)
+		defer remoteCancel()
+
+		masterPos, err := getMasterPosition(remoteCtx, tmc, topoServer, keyspace, shard)
+		// if we are unable to get master position, return error
+		if err != nil {
```
[the remark this answers is not in the document]
Comment (setassociative) [reply go/vt/mysqlctl/builtinbackupengine.go]: Agreed. Also the same type of tablet/mysql loss is something that needs to be handled already by an operator as vttablet/mysqld could go down and fall behind the ability to catch up for several reasons already, e.g., network partition. This failure mode should be well covered by normal tooling.

The thing I'm more interested in actually is going to be
> when trying to change tablet type and state after completing a backup, if the tablet is lagged, it stays in BACKUP type until it is caught up and only then transitions into REPLICA type. This seems to be an artifact of how state_change has been implemented in the code.

**Comment by deepthi** [comment]
@setassociative is this a concern? Can you articulate what you see as potential problems with it?

> when trying to change tablet type and state after completing a backup, if the tablet is lagged, it stays in BACKUP type until it is caught up and only then transitions into REPLICA type. This seems to be an artifact of how state_change has been implemented in the code.

File: go/vt/mysqlctl/backupengine.go [hunk 10]
```diff
@@ -39,13 +40,40 @@ var (
...
+	ExecuteBackup(ctx context.Context, params BackupParams) (bool, error)
 	ShouldDrainForBackup() bool
 }
 
+// BackupParams is the struct that holds all params passed to ExecuteBackup
+type BackupParams struct {
+	Cnf          *Mycnf
+	Mysqld       MysqlDaemon
+	Logger       logutil.Logger
+	BackupHandle backupstorage.BackupHandle
```
[the remark this answers is not in the document]
Comment (deepthi) [reply go/vt/mysqlctl/backupengine.go]: good point. I'll change this.

File: go/vt/mysqlctl/backupengine.go [hunk 11]
```diff
@@ -39,13 +40,40 @@ var (
...
+	Concurrency  int
+	HookExtraEnv map[string]string
+	TopoServer   *topo.Server
+	Keyspace     string
+	Shard        string
+}
+
+// RestoreParams is the struct that holds all params passed to ExecuteRestore
+type RestoreParams struct {
```
[the remark this answers is not in the document]
Comment (deepthi) [reply go/vt/mysqlctl/backupengine.go]: will do

File: go/vt/mysqlctl/builtinbackupengine.go (hunk 8 above)
Comment (deepthi) [reply go/vt/mysqlctl/builtinbackupengine.go]: I'll fix the comment

**Comment by setassociative** [comment]
@deepthi With respect to the BACKUP mode thing: sorry, I don't have concerns and should have been more clear. I was calling it out simply because that felt the more "new" change and thus a little more interesting.
