### PR TITLE
Fix for "text type with an unknown/unsupported collation cannot be hashed" error

### LINKED ISSUE #13764: Bug Report: unexpected error `text type with an unknown/unsupported collation cannot be hashed`
### Overview of the Issue

I found out that the newest image version of `vitess/vttestserver:mysql80` (same for mysql57) started to fail some tests in https://github.com/prisma/prisma/pull/20608

From what I understand, this is what comes out from the main branch, labeled as v18.0 (dev)

This is unexpected because only the docker image version changed, and the tests started to fail with
```
text type with an unknown/unsupported collation cannot be hashed
```

It looks like it might be related to the use of `BINARY` in the SQL (see reproduction repo below)

[Originally posted on a #shared-planetscale Slack Channel](https://prisma-company.slack.com/archives/C01CUJDJ7UN/p1691584127937129)

### Reproduction Steps

See minimal reproduction repository 
https://github.com/Jolg42/repro-prisma-vitess-error

### Binary Version

```sh
See docker image
`mysql` says `Server version: 8.0.21-vitess Version: 18.0.0-SNAPSHOT (Git revision ee7b9e7fbaef309d5cb39991252d88418092ccd9 branch 'main') built on Tue Aug  8 17:13:58 UTC 2023 by vitess@buildkitsandbox using go1.20.5 linux/amd64`
```

### Operating System and Environment details

```sh
See docker image.
Could be reproduced locally on macOS and remotely on Linux/Ubuntu with GitHub Actions
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by systay**
## Description
The vtgate planner and runtime was tripping up itself, trying to hash a weightstring value but getting the typing wrong, which lead to this error being produced. 

As of the merging of #13450, we started using the hashing distinct a lot more than before, and these errors have started popping up.

I recommend we backport this fix - we used this hashing distinct in earlier releases, just not as much as today, so this bug is probably there in earlier releases as well. That combined with it being a pretty small and safe fix makes me say backport.

## Related Issue(s)
Fixes #13764

## Checklist
-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

**Review by vmg — APPROVED** [review]
Rather elegant as far as hacks go. :ok_hand:

File: go/vt/vtgate/semantics/semantic_state.go [hunk 1]
```diff
@@ -291,6 +291,14 @@ func (st *SemTable) AddExprs(tbl *sqlparser.AliasedTableExpr, cols sqlparser.Sel
...
+	// which means that they don't have any type information. We can safely assume that they
+	// are VarBinary, since that's the only type that WeightString() can return.
+	_, isWS := e.(*sqlparser.WeightStringFuncExpr)
+	if isWS {
+		return sqltypes.VarBinary, collations.CollationBinaryID, true
+	}
+
 	if typ, found := st.ExprTypes[e]; found {
 		return typ.Type, typ.Collation, true
 	}
```
Comment (harshit-gangal) [inline go/vt/vtgate/semantics/semantic_state.go:304]: should we rearrange this check and do this first 
```
if typ, found := st.ExprTypes[e]; found {
    return typ.Type, typ.Collation, true
}
```
if not found then check the expression for the weight_string function

**Review by harshit-gangal — APPROVED** [review]
one comment. rest looks good.

**Review by GuptaManan100 — APPROVED** [review]
