### PR TITLE
planner: allow pushdown of window functions partitioned by unique vindex

### LINKED ISSUE #18070: Bug Report: Window function breaks in v21, works in v19
### Overview of the Issue

We're using window functions of the type SELECT DISTINCT FIRST_VALUE(id) OVER ( PARTITION BY... 
This has been working for us in Vitess 19.0.8, but breaks in 21.0.3 with 'ERROR 1235 (42000): VT12001: unsupported: OVER CLAUSE with sharded keyspace'

### Reproduction Steps

[README.md](https://github.com/user-attachments/files/19512566/README.md)

### Binary Version

```sh
Server version: 8.0.29-21 Version: 21.0.3 (Git revision 94fdc736eae8928a8fdde44e9ec9c3bee1868d6f branch 'HEAD') built on Wed Feb 12 16:56:27 UTC 2025 by runner@fv-az1705-503 using go1.23.5 linux/amd64
```

### Operating System and Environment details

```sh
cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.10 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.10"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.10 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8"
BUG_REPORT_URL="https://issues.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.10
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.10"

uname -sr
Linux 4.18.0-553.34.1.el8_10.x86_64

uname -m
x86_64
```

### Log Fragments

```sh

```

### PR DESCRIPTION
**Pull request by c-r-dev**
## Description

This PR introduces an optimization that allows window functions to be pushed down to individual shards when they are partitioned by a column that matches the unique vindex. Previously, all window function queries required single-shard routing, which limited their applicability on sharded tables.

Let's consider the following example on a sharded table `user` where `Id` is a unique vindex:

```sql
SELECT 
  Id, 
  col,
  ROW_NUMBER() OVER (PARTITION BY Id ORDER BY col DESC) as rnk
FROM user
```

### Before
The query would fail because window functions were restricted to single-shard routes:
```
VT12001: unsupported: OVER CLAUSE with sharded keyspace
```

### After
The planner detects that `PARTITION BY Id` matches a unique vindex, allowing safe pushdown.

**Plan:**
```
Route (Scatter on user)
└── Window (PARTITION BY Id ORDER BY col DESC)
    └── Table (user)
```

**SQL Executed on Shards:**
```sql
SELECT Id, col, ROW_NUMBER() OVER (PARTITION BY Id ORDER BY col DESC) as rnk FROM user
```

The optimized plan executes the window function on each shard independently, then gathers results at the vtgate level.

## Related Issue(s)

Fixes #18070 

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added
-   [x] Did the new or modified tests pass consistently locally and on CI? 
-   [x] Documentation was added or is not required

### AI Disclosure

I used Claude Sonnet 4 to understand the code structure, test cases and code formatting to be consistent with rest of code base.

### CODE REVIEW

**Comment by mattlord** [comment]
@c-r-dev it looks like the test is failing. We should start there. 

Can you also please help me understand why you feel this is a good way to do this? It seems like this will add cost to every query for every vitess user, no? We should benchmark that (I will try to get the vitess benchmark site back up this week after migrating it across IaaS providers).

File: go/vt/vtgate/planbuilder/operators/window_planning.go [hunk 1]
```diff
@@ -0,0 +1,260 @@
...
+	shardedRouting, ok := route.Routing.(*ShardedRouting)
+	if !ok || len(shardedRouting.VindexPreds) == 0 {
+		return ""
+	}
+
+	vpp := shardedRouting.VindexPreds[0]
+	if vpp.ColVindex != nil && len(vpp.ColVindex.Columns) > 0 {
+		return vpp.ColVindex.Columns[0].String()
+	}
+	return ""
```
Comment (arthurschreiber) [inline go/vt/vtgate/planbuilder/operators/window_planning.go]: Will this work right with multi column primary vindexes? Would it be better to return the vindex directly, and have the caller handle the columns directly?

**Comment by c-r-dev** [comment]
> @c-r-dev it looks like the test is failing. We should start there.
> 
> Can you also please help me understand why you feel this is a good way to do this? It seems like this will add cost to every query for every vitess user, no? We should benchmark that (I will try to get the vitess benchmark site back up this week after migrating it across IaaS providers).

thanks @mattlord for helping to check . I have tried tracing the current code path , and putting in a plug for supporting window functions which may go across shards but use shardingkey (and partition key also includes sharing key).
I have tried to keep this logic specific to queries with window function only, and not impact every query from vitess user.
It will be great to benchmark this , need your help with pointers on running the benchmark tests and measure performance.

File: go/vt/vtgate/planbuilder/operators/window_planning.go (hunk 1 above)
Comment (c-r-dev) [reply go/vt/vtgate/planbuilder/operators/window_planning.go]: thanks @arthurschreiber for checking , totally agree - will make the changes in next round and update the PR.

**Comment by c-r-dev** [comment]
> > @c-r-dev it looks like the test is failing. We should start there.
> > Can you also please help me understand why you feel this is a good way to do this? It seems like this will add cost to every query for every vitess user, no? We should benchmark that (I will try to get the vitess benchmark site back up this week after migrating it across IaaS providers).
> 
> thanks @mattlord for helping to check . I have tried tracing the current code path , and putting in a plug for supporting window functions which may go across shards but use shardingkey (and partition key also includes sharing key). I have tried to keep this logic specific to queries with window function only, and not impact every query from vitess user. It will be great to benchmark this , need your help with pointers on running the benchmark tests and measure performance.

@mattlord all CI checks are passing now (except the label one), please help to review and share feedback if the approach looks fine. Also for benchmark tests will follow your pointer.

File: go/vt/vtgate/planbuilder/operators/window_planning.go (hunk 1 above)
Comment (c-r-dev) [reply go/vt/vtgate/planbuilder/operators/window_planning.go]: @arthurschreiber , I have tried refactoring the code to check for primary vindex and get the shardingColumns in the latest revision. Please help to review when you get chance, let me know if this approach is good or needs to be changed.

**Comment by arthurschreiber** [comment]
@c-r-dev I spent some time today with @systay reviewing this changeset.

After careful consideration, I don't think we'll be able to merge these changes in their current form. Logically, the changes are correct - queries against sharded keyspaces utilizing window functions can be pushed down if the partition clause guarantees that there is no additional processing that needs to be done on the `vtgate` layer.

Unfortunately, the way this PR is implemented attacks the problem from the wrong "side". Currently, the query planner is missing support for window functions, and this PR then checks for errors and fixes up the planning by special casing `UNION` statements and analyzing the `OVER` clause.

The better approach would be to support window functions better at an earlier stage of planning, similar to how aggregate functions are planned. Basically, what we want is the ability to push down window operations "under" the route operations, if the window has the correct partitioning. Then the planners route merging logic can automatically do things like merging union queries together, and the special casing you added here wouldn't need to be done.

And if we end up with a window function at the top level of the operations tree after planning, that means we couldn't push down the window function and the query won't be supported (for the time being).

For your needs, these changes will work fine (i.e. being able to run these queries), but if we want to have this fixed in Vitess properly, this will need to follow the approach I described above.

**Comment by c-r-dev** [comment]
> @c-r-dev I spent some time today with @systay reviewing this changeset.
> 
> After careful consideration, I don't think we'll be able to merge these changes in their current form. Logically, the changes are correct - queries against sharded keyspaces utilizing window functions can be pushed down if the partition clause guarantees that there is no additional processing that needs to be done on the `vtgate` layer.
> 
> Unfortunately, the way this PR is implemented attacks the problem from the wrong "side". Currently, the query planner is missing support for window functions, and this PR then checks for errors and fixes up the planning by special casing `UNION` statements and analyzing the `OVER` clause.
> 
> The better approach would be to support window functions better at an earlier stage of planning, similar to how aggregate functions are planned. Basically, what we want is the ability to push down window operations "under" the route operations, if the window has the correct partitioning. Then the planners route merging logic can automatically do things like merging union queries together, and the special casing you added here wouldn't need to be done.
> 
> And if we end up with a window function at the top level of the operations tree after planning, that means we couldn't push down the window function and the query won't be supported (for the time being).
> 
> For your needs, these changes will work fine (i.e. being able to run these queries), but if we want to have this fixed in Vitess properly, this will need to follow the approach I described above.

thanks @arthurschreiber for helping to go over this , and sharing the best approach to tackle this. I will go over aggregate functions , and follow similar approach for window functions. I will spend some time and make code changes.

Will update the PR once i have the changes ready for review.

**Comment by c-r-dev** [comment]
I am restructuring the implementation based on feedback,  resetting the branch to apply the new approach cleanly. The previous commits are backed up into  https://github.com/c-r-dev/vitess/tree/window_functions_backup

**Comment by c-r-dev** [comment]
@arthurschreiber, thanks for pointing me to how aggregate functions are planned. 
I followed that pattern and implemented window function support.

_Changes Overview_

This PR spans 33 files organized into logical commits by package:

1. **sqlparser** - window function AST nodes and parsing
2. **opcode** - window function opcodes and execution logic  
3. **semantics** - Analyze window functions in query context
4. **planbuilder** - Route window functions to appropriate executors
   - Multi-source primitive detection (JOIN, UNION, etc.)
   - Added comprehensive test cases covering sharded/unsharded scenarios

_CI Compatibility_

For the upgrade/downgrade test `vtgate=N, vttablet=N-1, vtctld=N-1`, the window function error 
message changed. The test now accepts both old and new messages to handle version 
transitions gracefully (commit: ececd57). Need your help to suggest whats the best way to handle this.

Looking forward to your feedback !

**Comment by arthurschreiber** [comment]
> For the upgrade/downgrade test `vtgate=N, vttablet=N-1, vtctld=N-1`, the window function error
> message changed. The test now accepts both old and new messages to handle version
> transitions gracefully (commit: [ececd57](https://github.com/vitessio/vitess/commit/ececd575bc4946917f04c0ac9c5e0d67d24943d4)). Need your help to suggest whats the best way to handle this.

You can check what version of vtgate is running in the test and then use the appropriate assertion - e.g. verify the old message is used for v23 and earlier, and verify the new message is used for newer versions.

File: go/vt/vtgate/planbuilder/window.go [hunk 2]
```diff
@@ -0,0 +1,192 @@
...
+		}, expr.Col)
+	}
+
+	if len(windowFuncs) == 0 {
+		return true
+	}
+
+	// Validate each window function partitions by sharding key
+	for _, wf := range windowFuncs {
+		if !isPartitionedByShardingKey(wf, tables) {
```
Comment (arthurschreiber) [inline go/vt/vtgate/planbuilder/window.go]: I don't really like that we're talking about "sharding key" here - both in the function name as well as in tests and comments. I think we should try to stick to referring to vindexes here.

Maybe `isPartitionedByUniqueVindex` would be better (and would match prior art like `exprHasUniqueVindex` from `aggregation_pushing.go`).

It also seems like there could be some re-use of logic between the `GROUP BY` and `PARTITION BY` checks that are made, but this can be explored in a follow up PR.

File: go/vt/vtgate/planbuilder/window.go [hunk 3]
```diff
@@ -0,0 +1,192 @@
...
+				alias = sqlparser.NewIdentifierCS(t.QTable.Table.Name.String())
+			}
+			tables = append(tables, windowTableInfo{vTable: t.VTable, alias: alias})
+		}
+		return nil
+	})
+
+	if len(tables) == 0 {
+		return false
+	}
```
Comment (arthurschreiber) [inline go/vt/vtgate/planbuilder/window.go]: Can you give an example of a query that would have `len(tables) == 0`?

Comment (c-r-dev) [reply go/vt/vtgate/planbuilder/window.go]: Thanks, I included that as a defensive check, but realistically, by the time we reach this point in the planner, we shouldn't be seeing an empty table list. I've removed it since it's redundant.

File: go/vt/vtgate/planbuilder/window.go (hunk 2 above)
Comment (c-r-dev) [reply go/vt/vtgate/planbuilder/window.go]: thanks , I've renamed the function to `isPartitionedByUniqueVindex` and updated all comments and test cases to use "vindex" terminology instead of "sharding key".

File: go/vt/vtgate/planbuilder/window.go (hunk 3 above)
Comment (c-r-dev) [reply go/vt/vtgate/planbuilder/window.go]: @arthurschreiber , I have incorporated latest feedback and refactored the code,

Please note for error message change ,  for upgrade/downgrade tests - i have made change in git workflow file https://github.com/vitessio/vitess/pull/18903/commits/9986f10d9fcb3f7c3c68d3891a746de0acbcc4c2

The error message test case are now passing , noticed transient CI failures.

File: go/vt/vtgate/planbuilder/window.go [hunk 4]
```diff
@@ -0,0 +1,188 @@
+/*
+Copyright 2021 The Vitess Authors.
```
Comment (mattlord) [inline go/vt/vtgate/planbuilder/window.go]: Any new copyright clause should have the current year. Can you please double check all of them?

File: go/vt/sqlparser/parse_test.go [hunk 5]
```diff
@@ -3122,6 +3122,74 @@ var (
 	}, {
 		input:  "SELECT JSON_PRETTY(@j)",
 		output: "select json_pretty(@j) from dual",
+	}, {
+		// Window Functions
+		input:  "select row_number() over () from t",
+		output: "select row_number() over () from t",
+	}, {
+		input:  "select rank() over w from t window w as (partition by a order by b)",
+		output: "select rank() over w from t window w AS ( partition by a order by b asc)",
```
Comment (mattlord) [inline go/vt/sqlparser/parse_test.go]: Nit, but can we remove the space here after the leading `(`? It's a wasted byte and doesn't match the input when it really should.

File: go/vt/vtgate/engine/opcode/constants.go [hunk 6]
```diff
@@ -203,3 +203,101 @@ func (code AggregateOpcode) IsDistinct() bool {
...
+	case WindowUnassigned:
+		return sqltypes.Null
+	case WindowFirstValue, WindowLastValue, WindowNthValue, WindowLead, WindowLag:
+		return typ
+	case WindowRowNumber, WindowRank, WindowDenseRank, WindowNtile:
+		return sqltypes.Int64
+	case WindowPercentRank, WindowCumeDist:
+		return sqltypes.Float64
+	default:
+		panic(code.String()) // we have a unit test checking we never reach here
```
Comment (mattlord) [inline go/vt/vtgate/engine/opcode/constants.go]:
```suggestion
		panic("invalid window function found") // we have a unit test checking we never reach here
```

**Comment by mattlord** [comment]
@c-r-dev docs PR that you can review and edit: https://github.com/vitessio/website/pull/2033 ❤️ Please let me know if you need any help getting set up on the docs repo.

**Comment by mattlord** [comment]
@Promptless please add a review suggestion for changes to the changelog/24.0/24.0.0/summary.md file for this PR

File: go/vt/vtgate/engine/opcode/constants.go (hunk 6 above)
Comment (c-r-dev) [reply go/vt/vtgate/engine/opcode/constants.go]: thanks , incorporated with 15454bce587ab4d8d0b2130d64e93a2fe9d17969

File: go/vt/sqlparser/parse_test.go (hunk 5 above)
Comment (c-r-dev) [reply go/vt/sqlparser/parse_test.go]: thanks , incorporated with https://github.com/vitessio/vitess/commit/15454bce587ab4d8d0b2130d64e93a2fe9d17969

**Comment by c-r-dev** [comment]
> This is looking great, @c-r-dev ! ❤️ I just had some minor comments/suggestions/questions. Please let me know what you think.
> 
> I also added labels for website docs and the v24 release notes. I'm happy to help with these things.

thanks , the docs update PR looks good and comprehensive. https://github.com/vitessio/website/pull/2033

**Comment by mattlord** [comment]
In progress benchmark comparison with main: https://benchmark.vitess.io/compare?old=main&new=15454bce587ab4d8d0b2130d64e93a2fe9d17969

**Comment by mattlord** [comment]
@Promptless please push a commit which adds a summary of the changes here for the v24 release in the `changelog/24.0/24.0.0/summary.md` file to this PR. If you cannot do that, then please suggest changes to the file in a comment.

**Comment by c-r-dev** [comment]
@mattlord ,  i have updated summary.md (release note) https://github.com/vitessio/vitess/pull/18903/commits/2fba3a510a93616be29da0f43e7fc2f54c288d1f  , pls help to review when you get a chance.
