### PR TITLE
json: Fix quoting JSON keys

### LINKED ISSUE #14065: Bug Report: JSON SQL marshaling does not escape keys properly
### Overview of the Issue

Marshalling the following JSON document to SQL doesn't escape the key properly:

```json
{"key with ' in it": []}
```

Leads to:

```sql
JSON_OBJECT(_utf8mb4'key with ' in it', JSON_ARRAY())
```

instead of:

```sql
JSON_OBJECT(_utf8mb4'key with \' in it', JSON_ARRAY())
```

### Reproduction Steps

-

### Binary Version

```sh
-
```

### Operating System and Environment details

```sh
-
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by dbussink**
We didn't properly quote JSON keys when marshalling to SQL.

## Related Issue(s)

Fixes #14065

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/mysql/json/marshal_test.go [hunk 1]
```diff
@@ -0,0 +1,41 @@
+package json
```
Comment (systay) [inline go/mysql/json/marshal_test.go:1]: license missing

**Review by systay — APPROVED** [review]

**Review by rohit-nayak-ps — APPROVED** [review]

File: go/mysql/json/marshal_test.go (hunk 1 above)
Comment (mattlord) [reply go/mysql/json/marshal_test.go:1]: Good catch! I totally missed that.

Comment (dbussink) [reply go/mysql/json/marshal_test.go:17]: Fixed!
