### PR TITLE
Fix Panic in PRS due to a missing nil check

### LINKED ISSUE #14655: Bug Report: Panic in calling PRS from vtctld
### Overview of the Issue

It was noticed in the CI that sometimes calling PRS from vtctld causes a panic. The panic was coming from the line https://github.com/vitessio/vitess/blob/cd9693c40a7965e7aebaf8c749e9742c6dca0729/go/vt/vtctl/grpcvtctldserver/server.go#L2755

Investigating the code uncovers the problem. As the course of PRS, if we fail in getting the durability policy or if the tablets are unreachable we return with an error. But even in these cases ev is not nil, but ev.NewPrimary is nil, this causes the panic.

### Reproduction Steps

Run PRS from vtctld, such that at least one tablet is unreachable

### Binary Version

```sh
release-16.0 onwards
```

### Operating System and Environment details

```sh
-
```

### Log Fragments

```sh
-
```

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description

This PR fixes the bug described in https://github.com/vitessio/vitess/issues/14655. We were just missing a nil check and that has been added. This PR also adds a test to verify we don't see the panic anymore.

## Related Issue(s)

- Fixes #14655

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vtctl/grpcvtctldserver/server_test.go [hunk 1]
```diff
@@ -7580,7 +7579,71 @@ func TestPlannedReparentShard(t *testing.T) {
 					Nanos:   1,
 				},
 			},
-			shouldErr: true,
+			expectedErr: "duration: seconds:-1 nanos:1 is out of range for time.Duration",
```
Comment (ajm188) [inline go/vt/vtctl/grpcvtctldserver/server_test.go:7582]: this might be a bit unstable, how about `expectedError error` and then asserting `errors.Is(err, test.expectedErr)`?

**Review by ajm188 — APPROVED** [review]

File: go/vt/vtctl/grpcvtctldserver/server_test.go (hunk 1 above)
Comment (GuptaManan100) [reply go/vt/vtctl/grpcvtctldserver/server_test.go:7582]: Why do you think this would be unstable? `require.EqualError` takes in a string as a second argument. I thought it was meant to be used this way?

**Review by frouioui — APPROVED** [review]

File: go/vt/vtctl/grpcvtctldserver/server_test.go (hunk 1 above)
Comment (ajm188) [reply go/vt/vtctl/grpcvtctldserver/server_test.go:7582]: right, but we ever change the exact wording of the error message, this test will break. versus if we just assert on the _type_ of error being returned, it is more stable

Comment (GuptaManan100) [reply go/vt/vtctl/grpcvtctldserver/server_test.go:7582]: Oh I understand now! We want to assert on the type of error. I explored this possibility today, but unfortunately that won't work for this case. Because we are returning the error as `fmt.Errorf("duration: %v is out of range for time.Duration", dpb)` it doesn't have a specific type that we can assert on. Plus I want to ensure we error out with the correct message and not with a different message that doesn't make sense. 
I think for now this is fine and if we change the error message, then we should also change the expectations of the test.
