### PR TITLE
[vtctldserver] Migrate routing rules RPCs, and also `RebuildVSchemaGraph`

### LINKED ISSUE #7958: `vtctlclient ApplyRoutingRules` advertises a `-dry-run` option that does not exist
E.g.:

```
$ vtctlclient -server 127.0.0.1:15999 ApplyRoutingRules -rules="$(cat /tmp/foo.json)" -dry-run
flag provided but not defined: -dry-run
Usage: ApplyRoutingRules {-rules=<rules> || -rules_file=<rules_file>} [-cells=c1,c2,...] [-skip_rebuild] [-dry-run]

Applies the VSchema routing rules.

  -cells value
        If specified, limits the rebuild to the cells, after upload. Ignored if skipRebuild is set.
  -rules string
        Specify rules as a string
  -rules_file string
        Specify rules in a file
  -skip_rebuild
        If set, do no rebuild the SrvSchema objects.
ApplyRoutingRules Error: rpc error: code = Unknown desc = flag provided but not defined: -dry-run
```

From the usage, it can be seen that a `-dry-run` option is advertised;  but it does not actually exist, as a glance at the Vitess source will also show.

The documentation also refers to this in various places, e.g. https://vitess.io/docs/reference/features/schema-routing-rules/#applyroutingrules

### LINKED ISSUE #8196: Migrate `{Apply,Get}RoutingRules` to vtctldserver
#### Feature Description

As part of this work we should also take care of #7958.

#### Use Case(s)

Adding more functionality to the new VtctldServer to push that migration forward.

### PR DESCRIPTION
**Pull request by ajm188**
## Description

This PR migrates the following RPCs to the `VtctldServer` implementation, and reimplements the corresponding vtctl commands to use the new implementation under the hood:
* `ApplyRoutingRules`
* `GetRoutingRules`
* `RebuildVSchemaGraph`

I also took this opportunity to add a `-dry-run` flag to the vtctl command `ApplyRoutingRules` to tackle #7958 as part of this change.

### In Action

<details>
<summary>new client functionality</summary>
```
❯ vtctldclient --server "localhost:15999" GetRoutingRules
{
  "rules": []
}
❯ vtctldclient --server "localhost:15999" RebuildVSchemaGraph
RebuildVSchemaGraph: ok
❯ vtctldclient --server "localhost:15999" ApplyRoutingRules -r '{"rules": [{"from_table": "t1", "to_tables": ["t2", "t3"]}]}'
New RoutingRules object:
{
  "rules": [
    {
      "from_table": "t1",
      "to_tables": [
        "t2",
        "t3"
      ]
    }
  ]
}
If this is not what you expected, check the input data (as JSON parsing will skip unexpected fields).
❯ vtctldclient --server "localhost:15999" GetRoutingRules
{
  "rules": [
    {
      "from_table": "t1",
      "to_tables": [
        "t2",
        "t3"
      ]
    }
  ]
}
❯ vtctldclient --server "localhost:15999" ApplyRoutingRules -r '{"rules": [{"from_table": "t1", "to_tables": ["t2", "t3", "t4]}]}' --skip-rebuild
E0527 06:22:11.987119   73190 main.go:42] line: 1, position 65: unexpected end of JSON input
❯ vtctldclient --server "localhost:15999" ApplyRoutingRules -r '{"rules": [{"from_table": "t1", "to_tables": ["t2", "t3", "t4"]}]}' --skip-rebuild
New RoutingRules object:
{
  "rules": [
    {
      "from_table": "t1",
      "to_tables": [
        "t2",
        "t3",
        "t4"
      ]
    }
  ]
}
If this is not what you expected, check the input data (as JSON parsing will skip unexpected fields).
Skipping rebuild of VSchema graph, will need to run RebuildVSchemaGraph for changes to take effect.
```

</details>

<details>
<summary>File-based rules in new client</summary>
```
❯ vtctldclient --server "localhost:15999" GetRoutingRules > routing_rules.json
❯ vim routing_rules.json
❯ cat routing_rules.json
{
  "rules": [
    {
      "from_table": "t1",
      "to_tables": [
        "t2"
      ]
    }
  ]
}
❯ vtctldclient --server "localhost:15999" ApplyRoutingRules -f routing_rules.json
New RoutingRules object:
{
  "rules": [
    {
      "from_table": "t1",
      "to_tables": [
        "t2"
      ]
    }
  ]
}
If this is not what you expected, check the input data (as JSON parsing will skip unexpected fields).
❯ vtctldclient --server "localhost:15999" GetRoutingRules
{
  "rules": [
    {
      "from_table": "t1",
      "to_tables": [
        "t2"
      ]
    }
  ]
}
```

</details>

<details>
<summary>Old client</summary>
```
❯ vtctlclient -server "localhost:15999" GetRoutingRules
{}
❯ vtctlclient -server "localhost:15999" ApplyRoutingRules -rules '{"rules": [{"from_table": "t1", "to_tables": ["t2", "t3", "t4"]}]}'
New RoutingRules object:
{
  "rules": [
    {
      "fromTable": "t1",
      "toTables": [
        "t2",
        "t3",
        "t4"
      ]
    }
  ]
}
If this is not what you expected, check the input data (as JSON parsing will skip unexpected fields).
❯ vtctlclient -server "localhost:15999" GetRoutingRules
{
  "rules": [
    {
      "fromTable": "t1",
      "toTables": [
        "t2",
        "t3",
        "t4"
      ]
    }
  ]
}
```

</details>

<details>
<summary>Old client with dry-run</summary>
```
❯ vtctlclient -server "localhost:15999" ApplyRoutingRules -rules '{"rules": [{"from_table": "t1", "to_tables": ["t2", "t3", "t4"]}]}' -dry-run
=== DRY RUN ===
New RoutingRules object:
{
  "rules": [
    {
      "fromTable": "t1",
      "toTables": [
        "t2",
        "t3",
        "t4"
      ]
    }
  ]
}
If this is not what you expected, check the input data (as JSON parsing will skip unexpected fields).
=== (END) DRY RUN ===
❯ vtctlclient -server "localhost:15999" ApplyRoutingRules -rules '{"rules": [{"from_table": "t1", "to_tables": ["t2", "t3", "t4"]}]}' -dry-run -skip_rebuild
=== DRY RUN ===
New RoutingRules object:
{
  "rules": [
    {
      "fromTable": "t1",
      "toTables": [
        "t2",
        "t3",
        "t4"
      ]
    }
  ]
}
If this is not what you expected, check the input data (as JSON parsing will skip unexpected fields).
=== (END) DRY RUN ===
W0527 08:28:28.695105   85989 main.go:67] W0527 12:28:28.694526 vtctl.go:3323] DRY RUN: Skipping rebuild of SrvVSchema, will need to run RebuildVSchemaGraph for changes to take effect
❯ vtctlclient -server "localhost:15999" GetRoutingRules
{}
```

</details>

## Related Issue(s)

Closes #8196 
Fixes #7958 

## Checklist
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

### CODE REVIEW

File: go/cmd/vtctldclient/internal/command/routing_rules.go [hunk 1]
```diff
@@ -0,0 +1,157 @@
...
+		fmt.Printf("[DRY RUN] Would have saved new RoutingRules object:\n%s\n", data)
+
+		if applyRoutingRulesOptions.SkipRebuild {
+			fmt.Println("[DRY RUN] Would not have rebuilt VSchema graph, would have required operator to run RebuildVSchemaGraph for changes to take effect")
+		} else {
+			fmt.Print("[DRY RUN] Would have rebuilt the VSchema graph")
+			if len(applyRoutingRulesOptions.Cells) == 0 {
+				fmt.Print(" in all cells\n")
+			} else {
+				fmt.Printf(" in the following cells: %s.\n", strings.Join(applyRoutingRulesOptions.Cells, ", "))
```
Comment (doeg) [inline go/cmd/vtctldclient/internal/command/routing_rules.go:105]: The details ✨

**Review by doeg — APPROVED** [review]
