### PR TITLE
Fix cascading Delete failure while using Prepared statements

### LINKED ISSUE #14047: Bug Report: Cascading Delete fails while using Prepared statements
### Overview of the Issue

This bug was found by the fuzzer that is added in https://github.com/vitessio/vitess/pull/13980.

We are running a `DELETE` query via prepared statements on table `fk_t11` and it causes the data in `fk_t12` to mismatch -
```go
--- FAIL: TestFkFuzzTest/Unsharded_-_Single_Thread_-_Balanced_Inserts_and_Deletes_Prepared_-_true (60.23s)
E0920 13:24:55.391476   15896 fk_fuzz_test.go:505] Failing query - [prepare stmt_del from 'delete from fk_t11 where id = ?' SET @id = 8 execute stmt_del using @id]
mysql.go:223: Query (SELECT * FROM fk_t12 ORDER BY id) results mismatched.
        Vitess Results:
        [INT64(2) VARCHAR("1")]
        [INT64(7) VARCHAR("1")]
        Vitess RowsAffected: 0
        MySQL Results:
        [INT64(2) VARCHAR("1")]
        [INT64(7) VARCHAR("1")]
        [INT64(9) VARCHAR("3")]
        MySQL RowsAffected: 0
```

The schema we are using looks like - 
```
/*
 *                fk_t10
 *                   │
 * On Delete Cascade │
 * On Update Cascade │
 *                   │
 *                   ▼
 *                fk_t11──────────────────┐
 *                   │                    │
 *                   │                    │ On Delete Restrict
 * On Delete Cascade │                    │ On Update Restrict
 * On Update Cascade │                    │
 *                   │                    │
 *                   ▼                    ▼
 *                fk_t12               fk_t13
 */
```

Initially the state of the database looks like - 
```
E0920 13:23:55.596002   15896 fk_fuzz_test.go:224] MySQL data for fk_t10 -
[[INT64(9) VARCHAR("3")] [INT64(10) VARCHAR("1")]]
E0920 13:23:55.596005   15896 fk_fuzz_test.go:224] MySQL data for fk_t11 -
[[INT64(3) VARCHAR("1")] [INT64(6) NULL] [INT64(8) VARCHAR("3")] [INT64(10) VARCHAR("3")]]
E0920 13:23:55.596009   15896 fk_fuzz_test.go:224] MySQL data for fk_t12 -
[[INT64(2) VARCHAR("1")] [INT64(7) VARCHAR("1")] [INT64(9) VARCHAR("3")]]
E0920 13:23:55.596013   15896 fk_fuzz_test.go:224] MySQL data for fk_t13 -
[[INT64(6) VARCHAR("3")] [INT64(8) VARCHAR("3")] [INT64(9) VARCHAR("3")]]
```

On executing the query, we expect the query to fail because deleting the row in `fk_t11` with `id` 8 shouldn't succeed as `fk_t13` has rows which prevent its deletion.

We do see that Vitess reports the correct error. But somehow it ends up deleting some rows from `fk_t12` when it shouldn't. Post running the query - 

```
E0920 13:24:55.391619   15896 fk_fuzz_test.go:507] MySQL data for fk_t12 -
[[INT64(2) VARCHAR("1")] [INT64(7) VARCHAR("1")] [INT64(9) VARCHAR("3")]]
E0920 13:24:55.391629   15896 fk_fuzz_test.go:508] Vitess data for fk_t12 -
[[INT64(2) VARCHAR("1")] [INT64(7) VARCHAR("1")]]
```

### Reproduction Steps

Create the tables with the given schema and insert the rows as stated.
Then, try running the delete query as listed above.

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
main
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description

This PR fixes the bug reported in https://github.com/vitessio/vitess/issues/14047.

While debugging it was noticed that the reason Vitess is ending up cascading the deletes, but fails to rollback the changes when the delete on the parent fails, is because the `ExecStmt` Primitive would always run without a transaction.

This led to Vitess running the cascade operations outside a transaction. So, once the delete on the child table succeeded, we weren't able to roll it back even when the delete on the parent failed. This also explains why the problem was peculiar to prepared statements.

In this PR, I have added testing for the planning of a execute query such that it does cause a delete cascade. I have also fixed the problem described above by making the `ExecStmt` Primitive consult its input before deciding it can run without a transaction.

I have also verified that with these changes, the test in the fuzzer (https://github.com/vitessio/vitess/pull/13980) passes.

## Related Issue(s)

- Fixes #14047 

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vtgate/engine/exec_prepared_statement.go [hunk 1]
```diff
@@ -31,8 +31,10 @@ var _ Primitive = (*ExecStmt)(nil)
 type ExecStmt struct {
 	Params []*sqlparser.Variable
 	Input  Primitive
+}
 
-	noTxNeeded
+func (e *ExecStmt) NeedsTransaction() bool {
+	return e.Input.NeedsTransaction()
```
Comment (GuptaManan100) [inline go/vt/vtgate/engine/exec_prepared_statement.go:37]: This is basically the bug fix, rest it all testing 😆

**Review by shlomi-noach — APPROVED** [review]
Yet another great find!

**Review by harshit-gangal — APPROVED** [review]
