### PR TITLE
Fix `DROP CONSTRAINT` to work the same way as MySQL

### LINKED ISSUE #19217: Bug Report: ALTER TABLE ... DROP CONSTRAINT does not work for foreign key constraints
## Overview of the Issue

MySQL supports the standard SQL syntax `ALTER TABLE ... DROP CONSTRAINT <name>` to drop constraints of any type, including foreign key constraints. Per the [MySQL 8.4 documentation](https://dev.mysql.com/doc/refman/8.4/en/alter-table.html#alter-table-foreign-key):

> ALTER TABLE permits more general (and SQL standard) syntax for dropping and altering existing constraints of any type, where the constraint type is determined from the constraint name.

However, Vitess currently translates `DROP CONSTRAINT` to `DROP CHECK`, which fails when the constraint is actually a foreign key. Users see an error like:

```
Check constraint 'constraint_name' is not found in the table. (errno 3821)
```

This causes compatibility issues with ORMs like Drizzle that generate `DROP CONSTRAINT` syntax.

## Reproduction Steps

1. Create the following tables:
```sql
CREATE TABLE `Parent` (
    `id` varchar(191) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE InnoDB;

CREATE TABLE `Child` (
    `id` varchar(191) NOT NULL,
    `parentId` varchar(191) NOT NULL,
    PRIMARY KEY (`id`),
    CONSTRAINT `Child_parentId_fkey` FOREIGN KEY (`parentId`) REFERENCES `Parent` (`id`)
) ENGINE InnoDB;
```

2. Attempt to drop the foreign key constraint using standard SQL syntax:
```sql
ALTER TABLE `Child` DROP CONSTRAINT `Child_parentId_fkey`;
```

3. Observe the error: `Check constraint 'Child_parentId_fkey' is not found in the table. (errno 3821)`

4. Note that the MySQL-specific syntax works correctly:
```sql
ALTER TABLE `Child` DROP FOREIGN KEY `Child_parentId_fkey`;
```

## Binary Version

All current versions

## Operating System and Environment details

All platforms

## Log Fragments

N/A

### PR DESCRIPTION
**Pull request by nickvanw**
## Summary

MySQL supports `ALTER TABLE ... DROP CONSTRAINT <name>` as a general syntax for dropping any constraint type (foreign key, check, etc.). Vitess was incorrectly translating `DROP CONSTRAINT` to `DROP CHECK`, causing failures when the constraint was actually a foreign key.

This PR fixes schemadiff to look up the actual constraint type and generate the correct MySQL-specific syntax (`DROP FOREIGN KEY` or `DROP CHECK`).

Backporting this as it is divergent behavior to actual MySQL. 

## Related Issue(s)

Fixes #19217

## Checklist

- [x] "Backport to:" labels have been added if this change should be back-ported to release branches
- [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
- [x] Tests were added or are not required
- [x] Did the new or modified tests pass consistently locally and on CI?
- [x] Documentation was added or is not required

## Deployment Notes

None.

### AI Disclosure

This PR was written by Claude Code (Opus 4.5) and humans, working together as one.

### CODE REVIEW

File: go/vt/schemadiff/schema.go [hunk 1]
```diff
@@ -133,6 +133,21 @@ func getForeignKeyParentTableNames(createTable *sqlparser.CreateTable) (names []
...
 }
 
+func findForeignKeyDefinition(createTable *sqlparser.CreateTable, constraintName string) *sqlparser.ForeignKeyDefinition {
+	if createTable == nil || createTable.TableSpec == nil {
+		return nil
+	}
+	for _, cs := range createTable.TableSpec.Constraints {
+		if strings.EqualFold(cs.Name.String(), constraintName) {
+			if check, ok := cs.Details.(*sqlparser.ForeignKeyDefinition); ok {
+				return check
```
Comment (mattlord) [inline go/vt/schemadiff/schema.go]: Nit, but `check` seems like an odd variable name since this is NOT a check constraint.

File: go/vt/schemadiff/schema.go [hunk 2]
```diff
@@ -1020,21 +1035,21 @@ func (s *Schema) SchemaDiff(other *Schema, hints *DiffHints) (*SchemaDiff, error
 					}
 					return checkChildForeignKeyDefinition(fk, diff)
 				case *sqlparser.DropKey:
-					if node.Type != sqlparser.ForeignKeyType {
+					switch node.Type {
+					case sqlparser.ForeignKeyType, sqlparser.ConstraintType:
+						// Dropping a foreign key; we need to understand which table this foreign key used to reference.
```
Comment (mattlord) [inline go/vt/schemadiff/schema.go]: Nit, but now we *might* be dropping a FK. In the second case we don't know what type of constraint this is until we do the find call.
