### PR TITLE
VDiff tablet selection: pick non-serving tablets in Reshard workflows

### LINKED ISSUE #14400: VDiffs on reverse Reshard workflows never start
### Overview of the Issue

VDiffs that are created for reverse workflows do not start because they cannot find any tablets to stream from on the original source:
* In https://github.com/vitessio/vitess/pull/13582 we changed the tablet picker to only pick tablets which were Serving. 
* New shards are created with `IsPrimaryServing=true`. So VDiffs for forward workflows work since the picker does pick tablets from the new shards.
* However when we switch primary traffic we set `IsPrimaryServing=false` for the shards we are switching away from. This means that the picker for reverse workflows does not find any tablets so source the target streams from. 

Note that the reverse workflow itself is still running properly.

Found while debugging failed vdiffs for the reverse workflows in https://github.com/vitessio/vitess/pull/14327

### Reproduction Steps

* Run local example upto and including `./305_switch_writes.sh`. 
* Start a vdiff for the reverse workflow with 
`vtctlclient VDiff -- --tablet_types=replica customer.cust2cust_reverse create`
* Check that it doesn't progress using `vtctlclient VDiff customer.cust2cust show last`

### Binary Version

```sh
vttablet version Version: 19.0.0-SNAPSHOT (Git revision eddb7da44636994d1064906ca20d06543e6044a0 branch 'main') built on Tue Oct 31 11:48:06 CET 2023 by rohit@RSs-Laptop.home using go1.21.0 darwin/arm64
```

### Operating System and Environment details

```sh
Main: eddb7da44636994d1064906ca20d06543e6044a0
```

### Log Fragments

```sh
The logs for the picked tablet in reverse workflow show unhealthy tablets:

rI1031 11:45:34.844917   98871 tablet_picker.go:441] Connecting to tablet for tablet picker: alias:{cell:"zone1" uid:201} hostname:"rss-laptop.home" port_map:{key:"grpc" value:16201} port_map:{key:"vt" value:15201} keyspace:"customer" shard:"0" type:REPLICA mysql_hostname:"rss-laptop.home" mysql_port:17201 default_conn_collation:255
I1031 11:45:34.845345   98871 tablet_picker.go:446] Checking tablet health for tablet picker: alias:{cell:"zone1" uid:201} hostname:"rss-laptop.home" port_map:{key:"grpc" value:16201} port_map:{key:"vt" value:15201} keyspace:"customer" shard:"0" type:REPLICA mysql_hostname:"rss-laptop.home" mysql_port:17201 default_conn_collation:255
I1031 11:45:34.860529   98871 tablet_picker.go:448] Got health response for tablet picker: alias:{cell:"zone1" uid:201} hostname:"rss-laptop.home" port_map:{key:"grpc" value:16201} port_map:{key:"vt" value:15201} keyspace:"customer" shard:"0" type:REPLICA mysql_hostname:"rss-laptop.home" mysql_port:17201 default_conn_collation:255, shr target:{keyspace:"customer" shard:"0" tablet_type:REPLICA} realtime_stats:{replication_lag_seconds:138} tablet_alias:{cell:"zone1" uid:201}
I1031 11:45:34.860686   98871 tablet_picker.go:453] Tablet picker found unhealthy tablet: alias:{cell:"zone1" uid:201} hostname:"rss-laptop.home" port_map:{key:"grpc" value:16201} port_map:{key:"vt" value:15201} keyspace:"customer" shard:"0" type:REPLICA mysql_hostname:"rss-laptop.home" mysql_port:17201 default_conn_collation:255

However for forward workflows we get a healthy tablet:
I1031 11:51:41.024681   12776 tablet_picker.go:441] Connecting to tablet for tablet picker: alias:{cell:"zone1" uid:302} hostname:"rss-laptop.home" port_map:{key:"grpc" value:16302} port_map:{key:"vt" value:15302} keyspace:"customer" shard:"-80" key_range:{end:"\x80"} type:RDONLY mysql_hostname:"rss-laptop.home" mysql_port:17302 default_conn_collation:255
I1031 11:51:41.024734   12776 tablet_picker.go:446] Checking tablet health for tablet picker: alias:{cell:"zone1" uid:302} hostname:"rss-laptop.home" port_map:{key:"grpc" value:16302} port_map:{key:"vt" value:15302} keyspace:"customer" shard:"-80" key_range:{end:"\x80"} type:RDONLY mysql_hostname:"rss-laptop.home" mysql_port:17302 default_conn_collation:255
I1031 11:51:41.029337   12776 tablet_picker.go:448] Got health response for tablet picker: alias:{cell:"zone1" uid:302} hostname:"rss-laptop.home" port_map:{key:"grpc" value:16302} port_map:{key:"vt" value:15302} keyspace:"customer" shard:"-80" key_range:{end:"\x80"} type:RDONLY mysql_hostname:"rss-laptop.home" mysql_port:17302 default_conn_collation:255, shr target:{keyspace:"customer" shard:"-80" tablet_type:RDONLY} serving:true realtime_stats:{replication_lag_seconds:80} tablet_alias:{cell:"zone1" uid:302}
I1031 11:51:41.029352   12776 tablet_picker.go:450] Tablet picker found healthy tablet: alias:{cell:"zone1" uid:302} hostname:"rss-laptop.home" port_map:{key:"grpc" value:16302} port_map:{key:"vt" value:15302} keyspace:"customer" shard:"-80" key_range:{end:"\x80"} type:RDONLY mysql_hostname:"rss-laptop.home" mysql_port:17302 default_conn_collation:255
I1031 11:51:41.029379   12776 tablet_picker.go:352] Tablet picker found a healthy serving tablet for streaming: alias:{cell:"zone1" uid:302} hostname:"rss-laptop.home" port_map:{key:"grpc" value:16302} port_map:{key:"vt" value:15302} keyspace:"customer" shard:"-80" key_range:{end:"\x80"} type:RDONLY mysql_hostname:"rss-laptop.home" mysql_port:17302 default_conn_collation:255
```

### PR DESCRIPTION
**Pull request by rohit-nayak-ps**
## Description

This PR adds an option to the tablet picker to allow non-serving tablets to be selected. We use this option while picking tablets to stream data for target shards in VDiff runs.

See https://github.com/vitessio/vitess/issues/14400 for more details.

## Related Issue(s)

Fixes #14400

This issue was identified while working on https://github.com/vitessio/vitess/pull/14327 and I confirmed that the changes in this PR fix it.

## Checklist

-   [X] "Backport to:" labels have been added if this change should be back-ported
-   [X] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [ ] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vttablet/tabletmanager/vreplication/controller.go [hunk 1]
```diff
@@ -268,11 +268,11 @@ func (ct *controller) runBlp(ctx context.Context) (err error) {
 			isUnrecoverableError(err) ||
 			!ct.lastWorkflowError.ShouldRetry() {
 
-			log.Errorf("vreplication stream %d going into error state due to %+v", ct.id, err)
 			if errSetState := vr.setState(binlogdatapb.VReplicationWorkflowState_Error, err.Error()); errSetState != nil {
 				log.Errorf("INTERNAL: unable to setState() in controller. Attempting to set error text: [%v]; setState() error is: %v", err, errSetState)
```
Comment (mattlord) [inline go/vt/vttablet/tabletmanager/vreplication/controller.go:272]:
```suggestion
				log.Errorf("INTERNAL: unable to setState() in controller: %v. Could not set set error text: %v", errSetState, err)
```

Comment (rohit-nayak-ps) [reply go/vt/vttablet/tabletmanager/vreplication/controller.go]: done

File: go/vt/vttablet/tabletmanager/vreplication/controller.go [hunk 2]
```diff
@@ -268,11 +268,11 @@ func (ct *controller) runBlp(ctx context.Context) (err error) {
 			isUnrecoverableError(err) ||
 			!ct.lastWorkflowError.ShouldRetry() {
 
-			log.Errorf("vreplication stream %d going into error state due to %+v", ct.id, err)
 			if errSetState := vr.setState(binlogdatapb.VReplicationWorkflowState_Error, err.Error()); errSetState != nil {
-				log.Errorf("INTERNAL: unable to setState() in controller. Attempting to set error text: [%v]; setState() error is: %v", err, errSetState)
+				log.Errorf("INTERNAL: unable to setState() in controller: %v, Could not set error text to: %v.", errSetState, err)
```
Comment (mattlord) [inline go/vt/vttablet/tabletmanager/vreplication/controller.go:272]: Nit, but the `Could` in the middle of the log message should be lowercase `could` or we should end the previous sentence: `... controller: %v.` It's obviously minor / nit picky and either one is fine.

File: go/vt/discovery/tablet_picker_test.go [hunk 3]
```diff
@@ -591,6 +591,72 @@ func TestPickFallbackType(t *testing.T) {
 	assert.True(t, proto.Equal(primaryTablet, tablet), "Pick: %v, want %v", tablet, primaryTablet)
 }
 
+// TestPickNonServingTablets validates that  non serving tablets are included when the
```
Comment (mattlord) [inline go/vt/discovery/tablet_picker_test.go:594]: Extra whitespace here: `that  non`

File: go/vt/discovery/tablet_picker_test.go [hunk 4]
```diff
@@ -591,6 +591,72 @@ func TestPickFallbackType(t *testing.T) {
...
+	// Tablet should not be selected as it is unhealthy.
+	replicaTablet := addTablet(ctx, te, 200, topodatapb.TabletType_REPLICA, localCell, false, false)
+	defer deleteTablet(t, te, replicaTablet)
+
+	// Tablet should be selected because the IncludeNonServingTablets option is set and it is healthy.
+	replicaTablet2 := addTablet(ctx, te, 300, topodatapb.TabletType_REPLICA, localCell, false, true)
+	defer deleteTablet(t, te, replicaTablet2)
+
+	var cancel context.CancelFunc
+	ctx, cancel = context.WithTimeout(ctx, 200*time.Millisecond)
```
Comment (mattlord) [inline go/vt/discovery/tablet_picker_test.go:618]: We should increase this, I think, in order to prevent CI flakiness when there are machine pauses.

File: go/vt/discovery/tablet_picker_test.go [hunk 5]
```diff
@@ -591,6 +591,72 @@ func TestPickFallbackType(t *testing.T) {
...
+	defer cancel()
+	_, err := te.topoServ.UpdateShardFields(ctx, te.keyspace, te.shard, func(si *topo.ShardInfo) error {
+		si.PrimaryAlias = primaryTablet.Alias
```
Comment (mattlord) [inline go/vt/discovery/tablet_picker_test.go:621]: Not a bad idea to set `PrimaryIsServing` to true as well.

File: go/vt/discovery/tablet_picker_test.go [hunk 6]
```diff
@@ -591,6 +591,72 @@ func TestPickFallbackType(t *testing.T) {
...
+	assert.True(t, proto.Equal(primaryTablet, tablet), "Pick: %v, want %v", tablet, primaryTablet)
+
+	options.IncludeNonServingTablets = true
+	tp, err = NewTabletPicker(ctx, te.topoServ, cells, localCell, te.keyspace, te.shard, tabletTypes, options)
+	require.NoError(t, err)
+	ctx3, cancel3 := context.WithTimeout(ctx, 1*time.Second)
+	defer cancel3()
+	var picked1, picked2, picked3 bool
+	// IncludeNonServingTablets is true: both the healthy tablets should be picked even though one is not serving.
+	for i := 0; i < 30; i++ {
```
Comment (mattlord) [inline go/vt/discovery/tablet_picker_test.go:642]: Worth doing it more, I'd say 50 times, to give us a more sure chance to select the replica (since I think it's technically random). That or we could use TableSelectionPreference of IN_ORDER to test them independently.

**Review by mattlord — APPROVED** [review]
LGTM! I only had some minor questions/nits that you can address as you feel is best.

**Review by shlomi-noach — APPROVED** [review]

File: go/vt/discovery/tablet_picker_test.go (hunk 5 above)
Comment (rohit-nayak-ps) [reply go/vt/discovery/tablet_picker_test.go:626]: This is done in `CreateShard()`
