### PR TITLE
Gen4: add bind variables support for join

### LINKED ISSUE #8552: Incorrect Gen4 Plan
#### Overview of the Issue

Found an error in the rails tests now, coming from Gen4
Executed query :-
```sql
SELECT `assemblies`.* FROM `assemblies` INNER JOIN `assemblies_parts` ON `assemblies`.`id` = `assemblies_parts`.`assembly_id` WHERE `assemblies_parts`.`part_id` = 2
```
Error -
```
Code: INVALID_ARGUMENT missing bind var assemblies_parts_assembly_id
```

Outputs for v3 and Gen4 on the query - 

```json
"SELECT `user`.`id` FROM `user` INNER JOIN `user_extra` ON `user`.`id` = `user_extra`.`assembly_id` WHERE `user_extra`.`user_id` = 2"
{
  "QueryType": "SELECT",
  "Original": "SELECT `user`.`id` FROM `user` INNER JOIN `user_extra` ON `user`.`id` = `user_extra`.`assembly_id` WHERE `user_extra`.`user_id` = 2",
  "Instructions": {
    "OperatorType": "Join",
    "Variant": "Join",
    "JoinColumnIndexes": "-1",
    "TableName": "`user`_user_extra",
    "Inputs": [
      {
        "OperatorType": "Route",
        "Variant": "SelectScatter",
        "Keyspace": {
          "Name": "user",
          "Sharded": true
        },
        "FieldQuery": "select `user`.id from `user` where 1 != 1",
        "Query": "select `user`.id from `user`",
        "Table": "`user`"
      },
      {
        "OperatorType": "Route",
        "Variant": "SelectEqualUnique",
        "Keyspace": {
          "Name": "user",
          "Sharded": true
        },
        "FieldQuery": "select 1 from user_extra where 1 != 1",
        "Query": "select 1 from user_extra where user_extra.assembly_id = :user_id and user_extra.user_id = 2",
        "Table": "user_extra",
        "Values": [
          2
        ],
        "Vindex": "user_index"
      }
    ]
  }
}
{
  "QueryType": "SELECT",
  "Original": "SELECT `user`.`id` FROM `user` INNER JOIN `user_extra` ON `user`.`id` = `user_extra`.`assembly_id` WHERE `user_extra`.`user_id` = 2",
  "Instructions": {
    "OperatorType": "Join",
    "Variant": "Join",
    "JoinColumnIndexes": "1",
    "TableName": "user_extra_`user`",
    "Inputs": [
      {
        "OperatorType": "Route",
        "Variant": "SelectEqualUnique",
        "Keyspace": {
          "Name": "user",
          "Sharded": true
        },
        "FieldQuery": "select user_extra.assembly_id from user_extra where 1 != 1",
        "Query": "select user_extra.assembly_id from user_extra where user_extra.user_id = 2",
        "Table": "user_extra",
        "Values": [
          2
        ],
        "Vindex": "user_index"
      },
      {
        "OperatorType": "Route",
        "Variant": "SelectEqualUnique",
        "Keyspace": {
          "Name": "user",
          "Sharded": true
        },
        "FieldQuery": "select `user`.id from `user` where 1 != 1",
        "Query": "select `user`.id from `user` where `user`.id = :user_extra_assembly_id",
        "Table": "`user`",
        "Values": [
          ":user_extra_assembly_id"
        ],
        "Vindex": "user_index"
      }
    ]
  }
}
```

#### Binary version
main

### PR DESCRIPTION
**Pull request by frouioui**
## Description

This pull request adds support for bind variables in joins. Join plan/primitive/tree are now aware of the bind variable's index.

## Related Issue(s)

Fixes #8552 

#7280 

## Checklist
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vtgate/engine/join.go [hunk 1]
```diff
@@ -261,6 +261,7 @@ func (jn *Join) description() PrimitiveDescription {
 	other := map[string]interface{}{
 		"TableName":         jn.GetTableName(),
 		"JoinColumnIndexes": strings.Trim(strings.Join(strings.Fields(fmt.Sprint(jn.Cols)), ","), "[]"),
+		"JoinVars":          jn.Vars,
```
Comment (systay) [inline go/vt/vtgate/engine/join.go:264]: wdyt about only doing this when `jn.Vars` is not empty?

**Review by systay — APPROVED** [review]

**Review by harshit-gangal — APPROVED** [review]
