### PR TITLE
Fix error around breaking of multistatements

### LINKED ISSUE #6747: Errors in multi-statement queries not fatal to statement sequence
The MySQL protocol supports sending multiple statements in a single query (see https://dev.mysql.com/doc/internals/en/multi-statement.html).  Vitess supports this, but the behavior of vtgate seems to be different from MySQL server itself.

MySQL behavior:
  * For a multi-statement sequence, when an error is seen, the server will return the result of the statements successfully executed, plus the error, and then **stop the sequence execution at that point**

Vitess behavior:
  * For a multi-statement sequence, when an error is seen, the server will return the error, but then **continue execution of the multi statement sequence**, returning those results as well.

Unfortunately, this behavior is not explicitly documented anywhere, but the MySQL client C API documents seem to infer that the client should stop after an error is seen;  so it makes sense for the server to stop executing the multi-statement sequence upon error.  This seems the way that many clients were written, and it seems that some (like the C# connector) will react badly and emit an error like:

```
MySqlConnector.MySqlProtocolException : Packet received out-of-order. Expected 1; got 2
```

Other connectors, like the Python MySQL connector from Oracle, seems not to care;  and do not raise an error other than the error produced.  This connector will not, however, return any of the results seen from the server after the error.

Here is a simple repro, using the MySQL Python connector and the Vitess local examples (`101_initial_cluster.sh`):

  * Connecting directly to the MySQL instance, allow login from localhost port 17100 and activate the general log for this instance:
```
$ mysql -S ~/go/vtdataroot/vt_0000000100/mysql.sock -u root -A
Welcome to the MySQL monitor.  Commands end with ; or \g.
.
.
mysql> create user root@'127.0.0.1' identified by 'root';
Query OK, 0 rows affected (0.00 sec)
mysql> grant all privileges on *.* to root@'127.0.0.1';
Query OK, 0 rows affected (0.00 sec)
mysql> flush privileges;
Query OK, 0 rows affected (0.00 sec)
mysql> set global general_log=1;
Query OK, 0 rows affected (0.00 sec)
```

  * Now, run the following test program against Vitess, while tailing the MySQL instance general log:

```
$ cat test_vitess.py 
import mysql.connector

cnx = mysql.connector.Connect(host='localhost', port=15306,
      database='commerce', user='root', password="root",
      get_warnings=True, autocommit=True)
cursor = cnx.cursor()

stmt = '''SELECT * from foo; SELECT * from product;'''
iterator = cursor.execute(stmt, multi=True)
try:
  for i in iterator:
    print(i.fetchall())
except Exception:
  print("Encountered error")
  pass

cnx.close()

$ python test_vitess.py 
Encountered error

The general log shows:

2020-09-18T21:01:42.935530Z      1098 Query     select * from foo where 1 != 1
2020-09-18T21:01:42.938324Z      1142 Query     select * from product limit 10001
```

  * Note this shows that both queries were executed, even though the first query is in error (table `foo` does not exist)

  * Now, run the same program, modified to run directly against the MySQL on port 17100:

```
$ cat test_mysql.py 
import mysql.connector

cnx = mysql.connector.Connect(host='localhost', port=17100,
      database='vt_commerce', user='root', password="root",
      get_warnings=True, autocommit=True)
cursor = cnx.cursor()

stmt = '''SELECT * from foo; SELECT * from product;'''
iterator = cursor.execute(stmt, multi=True)
try:
  for i in iterator:
    print(i.fetchall())
except Exception:
  print("Encountered error")
  pass

cnx.close()

$ python test_mysql.py 
Encountered error

The general log shows:

2020-09-18T21:03:55.250390Z      1562 Query     SELECT * from foo;
2020-09-18T21:03:55.251502Z      1562 Quit
```

 * Note this proves that after the error, the server does not execute the 2nd statement in the multi-statement query.

### PR DESCRIPTION
**Pull request by systay**
When a multi-statement query is received, any errors should abort the execution of the remaining queries.

The `execQuery` and `handleNextCommand` were returning an error, but not actually using the error value - just checking if it was nil or not.

We need to be able to know on the outside of `execQuery` if an error occured and if it was an error we need to close the connection for or if it was a simple execution error.

Fixes #6747

### CODE REVIEW

**Comment by systay** [comment]
I extracted the actual bug fixing into it's own PR. I'm thinking we might want to back-port it.

File: go/mysql/conn.go [hunk 1]
```diff
@@ -1122,14 +1113,22 @@ func (c *Conn) handleNextCommand(handler Handler) error {
...
+			return false
 		}
 	}
 
-	return nil
+	return true
 }
 
-func (c *Conn) execQuery(query string, handler Handler, more bool) error {
+type execResult byte
```
Comment (demmer) [inline go/mysql/conn.go:1123]: Style nit -- I'd move this type declaration up to the top of the file since `execSuccess` and `connErr` are referred to above.

File: go/mysql/conn.go [hunk 2]
```diff
@@ -758,86 +758,80 @@ func (c *Conn) writeEOFPacket(flags uint16, warnings uint16) error {
...
+		} else {
+			queries = []string{query}
+		}
+		for index, sql := range queries {
+			more := false
+			if index != len(queries)-1 {
+				more = true
+			}
+			res := c.execQuery(sql, handler, more)
+			if res != execSuccess {
```
Comment (demmer) [inline go/mysql/conn.go:813]: Maybe I'm confused (or it's still too early in the morning) but based on my understanding of the bug shouldn't you continue this loop and process all the rest of the queries unless the result is `connErr`?

Comment (demmer) [reply go/mysql/conn.go:813]: Sorry ignore that comment -- I now understand the bug better.

**Review by deepthi — COMMENTED** [review]
The fix looks fine. Do you plan to resolve the TODOs before this is merged?

**Comment by deepthi** [comment]
unit test failed again (on retry). You might want to fix mysql/server_test to reset the stats/counts to resolve the failure.
```
2020-10-02T00:49:00.3064679Z ##[error]    server_test.go:638: Expected Timing count delta All should be >= 2, got 1
2020-10-02T00:49:00.3065971Z ##[error]    server_test.go:638: Expected Timing count delta Query should be >= 1, got 0
```

**Comment by systay** [comment]
> The fix looks fine. Do you plan to resolve the TODOs before this is merged?

Done ✔️

**Review by deepthi — APPROVED** [review]
LGTM

**Comment by deepthi** [comment]
All the failing tests on the last commit are known to be flaky. Opened #6812 to disable the failing TER test.
