### PR TITLE
builtinbackup: log during restore as restore, not as backup

### LINKED ISSUE #16482: Bug Report: incorrect logging from restoring a backup
### Overview of the Issue

When restoring from a backup using the builtin engine, the restore process logs progress for large files. However, the log messages all say "Backup" instead of "Restore".

### Reproduction Steps

Restore vttablet from a non-trivial sized backup. It needs to take at least 5 seconds for a data file to be downloaded/decompressed/copied for us to log the progress.

### Binary Version

```sh
main
```

### Operating System and Environment details

```sh
any
```

### Log Fragments

```sh
2024-07-24 06:38:34.596	
I0724 06:38:34.596780       1 builtinbackupengine.go:911] Restore: copying 181 files
2024-07-24 06:38:34.596	
2024-07-24 06:38:34.597	
I0724 06:38:34.596959       1 builtinbackupengine.go:1044] Copying file 41: _vt/redo_state.ibd
2024-07-24 06:38:34.731	
I0724 06:38:34.731475       1 compression.go:168] Decompressing using external command: "nice -n 19 zstd -c -d"
2024-07-24 06:38:34.738	
I0724 06:38:34.738136       1 builtinbackupengine.go:1137] closing decompressor
2024-07-24 06:38:34.738	
I0724 06:38:34.738176       1 builtinbackupengine.go:770] Done taking Backup "41"
...
2024-07-24 06:39:07.950	
I0724 06:39:07.950819       1 builtinbackupengine.go:1044] Copying file 61: redacted.ibd
2024-07-24 06:39:08.150	
I0724 06:39:08.150312       1 compression.go:168] Decompressing using external command: "nice -n 19 zstd -c -d"
2024-07-24 06:39:10.013	
I0724 06:39:13.152385       1 builtinbackupengine.go:775] Backup "61": 126976.00kb
2024-07-24 06:39:15.014	
I0724 06:39:18.150973       1 builtinbackupengine.go:775] Backup "61": 266240.00kb
2024-07-24 06:39:20.013	
I0724 06:39:23.150549       1 builtinbackupengine.go:775] Backup "61": 394080.00kb
2024-07-24 06:39:25.013	
I0724 06:39:28.151452       1 builtinbackupengine.go:775] Backup "61": 512000.00kb
2024-07-24 06:39:30.013	
I0724 06:39:33.153175       1 builtinbackupengine.go:775] Backup "61": 643072.00kb
2024-07-24 06:39:33.300	
I0724 06:39:33.300279       1 builtinbackupengine.go:1137] closing decompressor
2024-07-24 06:39:33.300	
I0724 06:39:33.300426       1 builtinbackupengine.go:770] Done taking Backup "61"
```

### PR DESCRIPTION
**Pull request by deepthi**
## Description
Parameterize the `ReportProgress` function which is being used by both backup and restore so that we log properly.

## Related Issue(s)
Fixes #16482

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/mysqlctl/builtinbackupengine.go [hunk 1]
```diff
@@ -766,21 +766,25 @@ func (bp *backupPipe) HashString() string {
 	return hex.EncodeToString(bp.crc32.Sum(nil))
 }
 
-func (bp *backupPipe) ReportProgress(period time.Duration, logger logutil.Logger) {
+func (bp *backupPipe) ReportProgress(period time.Duration, logger logutil.Logger, restore bool) {
+	messageStr := "restoring "
```
Comment (mattlord) [inline go/vt/mysqlctl/builtinbackupengine.go:770]: Nit, but log messages most often use sentence capitalization (and punctuation if multiple sentences) — including the ones we're replacing. So I'd prefer capitalizing the first letter of the first word here too. Obviously very minor though.

File: go/vt/mysqlctl/builtinbackupengine.go [hunk 2]
```diff
@@ -813,7 +817,7 @@ func (be *BuiltinBackupEngine) backupFile(ctx context.Context, params BackupPara
 	}
 
 	br := newBackupReader(fe.Name, fi.Size(), timedSource)
-	go br.ReportProgress(builtinBackupProgress, params.Logger)
+	go br.ReportProgress(builtinBackupProgress, params.Logger /*restore*/, false)
```
Comment (mattlord) [inline go/vt/mysqlctl/builtinbackupengine.go:820]: The comment should be with the boolean rather than the logger. This is how I've seen it before in the code base:
```
go br.ReportProgress(builtinBackupProgress, params.Logger, false /* restore */)
```

File: go/vt/mysqlctl/builtinbackupengine.go [hunk 3]
```diff
@@ -1078,7 +1082,7 @@ func (be *BuiltinBackupEngine) restoreFile(ctx context.Context, params RestorePa
 	}()
 
 	br := newBackupReader(name, 0, timedSource)
-	go br.ReportProgress(builtinBackupProgress, params.Logger)
+	go br.ReportProgress(builtinBackupProgress, params.Logger /*restore*/, true)
```
Comment (mattlord) [inline go/vt/mysqlctl/builtinbackupengine.go:1085]: Same note here about the comment.

**Review by mattlord — APPROVED** [review]
LGTM! I only had a couple of nits that you can resolve as you feel best.

File: go/vt/mysqlctl/builtinbackupengine.go (hunk 2 above)
Comment (deepthi) [reply go/vt/mysqlctl/builtinbackupengine.go:820]: Oops :)

File: go/vt/mysqlctl/builtinbackupengine.go (hunk 1 above)
Comment (deepthi) [reply go/vt/mysqlctl/builtinbackupengine.go:770]: That would have been my preference too. However, we are using the same string once in the middle and once at the beginning. If you look at the logs pasted in the issue, we have something like "Done taking Backup", which is arguably worse than "done taking backup".
I didn't want to create two strings, one capitalized and one not, and it didn't seem worth fiddling with functions in the experimental text/cases package, so I chose what felt like the lesser evil.

Comment (deepthi) [reply go/vt/mysqlctl/builtinbackupengine.go:770]: I did change `completed` to `Completed`.

**Review by rohit-nayak-ps — APPROVED** [review]

**Review by GuptaManan100 — APPROVED** [review]

**Review by frouioui — APPROVED** [review]
