### PR TITLE
[release-17.0] Upgrade-Downgrade Fix: Schema-initialization stuck on semi-sync ACKs while upgrading

### LINKED ISSUE #13426: Bug Report: upgrade to v16 from v15 blocks on semi-sync
### Overview of the Issue

We upgraded a large database to v16 recently. During the rollout, errors were served to the app for ~30 seconds.
The root cause seems to be that the upgrade of _vt schema during PlannedReparent was blocked by semi-sync.

### Reproduction Steps

Upgrade a 3+ tablet cluster with semi-sync enabled from v15 to v16.

### Binary Version

```sh
16.0.0+
```

### Operating System and Environment details

```sh
Any
```

### Log Fragments

```sh
2023-06-26 20:33:46.339	
I0626 20:33:46.338969       1 replication.go:586] Setting semi-sync mode: primary=true, replica=true
2023-06-26 20:33:46.339	
I0626 20:33:46.339255       1 query.go:81] exec SET GLOBAL rpl_semi_sync_master_enabled = 1, GLOBAL rpl_semi_sync_slave_enabled = 1
2023-06-26 20:33:46.339	
I0626 20:33:46.339689       1 tm_state.go:186] Changing Tablet Type: PRIMARY for cell:"redacted" uid:redacted
2023-06-26 20:33:46.358	
I0626 20:33:46.357886       1 syslogger.go:129] <redacted> [tablet] updated
2023-06-26 20:33:46.371	
I0626 20:33:46.371122       1 sidecardb.go:408] Applying DDL for table views:
2023-06-26 20:33:46.371	
CREATE TABLE IF NOT EXISTS `_vt`.`views` (
2023-06-26 20:33:46.371	
	`TABLE_SCHEMA` varchar(64) NOT NULL,
2023-06-26 20:33:46.371	
	`TABLE_NAME` varchar(64) NOT NULL,
2023-06-26 20:33:46.371	
	`CREATE_STATEMENT` longtext NOT NULL,
2023-06-26 20:33:46.371	
	`UPDATED_AT` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp(),
2023-06-26 20:33:46.371	
	PRIMARY KEY (`TABLE_SCHEMA`, `TABLE_NAME`)
2023-06-26 20:33:46.371	
) ENGINE InnoDB
2023-06-26 20:33:48.215	
I0626 20:33:48.215033       1 state_manager.go:682] Going unhealthy due to replication error: no replication status (errno 100) (sqlstate HY000)
2023-06-26 20:34:16.356	
I0626 20:34:16.356183       1 sidecardb.go:357] createSidecarDB: _vt
```

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description

When we introduced the schema-init-db code, we failed to realize that it would start doing writes as part of the code to change the tablet type. As part of the PRS process, we used to call `PromoteReplica` first, followed by calls to `SetReplicationSource`. 

When a user upgrades from v16 (/v15) to v17 (/v16), as part of `PromoteReplica` call, the schema-init realizes that there are schema diffs to apply and ends up writing to the database. The problem is that if semi-sync is enabled, all of these writes get blocked indefinitely. Eventually, `PromoteReplica` fails and this fails the entire `PRS` call.

In this PR we fix this issue, by altering the PRS flow slightly, where we call `SetReplicationSource` on all the replicas and `PromoteReplica` on the new primary in parallel. This allows `PromoteReplica` to be unblocked just as any semi-sync capable replica reparents to it.

As part of this PR, the upgrade-downgrade tests for manual backups has been augmented as well to start using semi-sync and to follow the correct steps to upgrade the cluser instead of just shutting down all the tablets and restarting all the tablets. Also, we call `PlannedReparentShard` now in the test instead of `InitShardPrimary` which has been long deprecated.

## Related Issue(s)
- Fixes #13426 

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vtctl/reparentutil/planned_reparenter.go [hunk 1]
```diff
@@ -688,6 +672,20 @@ func (pr *PlannedReparenter) reparentTablets(
 		}(alias, tabletInfo.Tablet)
 	}
 
+	// If `PromoteReplica` call is requried, we should call it and use the position that it returns.
+	if promoteReplicaRequired {
```
Comment (ajm188) [inline go/vt/vtctl/reparentutil/planned_reparenter.go:676]: it would be kinda neat if `PromoteReplica` was a no-op if the tablet was already type:PRIMARY since it would simplify the logic here a bit (however, that would make the actual server-side implementation more involved, and possibly too much, so 🤷 )

**Review by ajm188 — COMMENTED** [review]
this makes sense to me! i don't think i have any questions right now; great stuff!!

File: go/vt/vtctl/reparentutil/planned_reparenter.go (hunk 1 above)
Comment (GuptaManan100) [reply go/vt/vtctl/reparentutil/planned_reparenter.go]: `PromoteReplica` is already idempotent. We can call it over and over and it won't be wrong per se, but we still only want to call it when required.

Also, I wanted to reduce the change to the `PRS` flow as much as possible and only make the small change of running `PromoteReplica` in parallel instead of sequentially.

**Comment by GuptaManan100** [comment]
Once this PR is merged, we'll have to port the changes to `main` as well.

**Review by deepthi — APPROVED** [review]
Nice work!
