### PR TITLE
VReplication: VStreamer

### LINKED ISSUE #4011: binlogplayer failed if source replica restarted after migrate replica
#### Overview of the Issue

in a resharding process, after migrate replica, the source shard replica is in NonServing state, if the  source shard replica restarted, replica is NonServing now, it will not load scheme infomation, the binlog player will failed,binlog player need the schema information

#### Reproduction Steps

start a resharding workflow, after migrate rdonly and replica, before migrate master, restart the source shard replica, the binlog player will failed

#### Binary version
my version is 2.1,other version should the same issue

### PR DESCRIPTION
**Pull request by sougou**
## VStreamer

This is the first part of VReplication. CFP is #4375.

The new VStreamer differs from the older binlog_streamer design in the following ways:
* Only supports RBR. This is because we can't support smart filtering with SBR.
* Deprecates Update Stream. We'll build a more powerful version on top of the new VStreamer.
* Handles a unified `Filter` request that is more flexible than the previous table or keyrange based format. It allows for table, keyrange, custom expressions and filters that can be expressed as `select` statements.
* Response is a stream of events instead of transactions. This addresses the max packet size problem.
* Response also contains row image changes (rather than statements). Statement generation will be handled by the VReplication player on the other end. This gives better flexibility because the player can perform intelligent merge operations based on existing data, which cannot be done from the server side.
* Can update itself to VSchema changes. This is necessary if new tables get introduced during VReplication.
* Can react to DDL changes. Only create table and add column for now.
* Buffering based on a recommended packet size.

The above differences make this different enough that the old binlog_streamer was not reusable.

### New desing

The new design follows the new 'TabletServer' service pattern:
* vstreamer is a separate package under the `tabletserver/` directory.
* It has an `Engine` with InitDBConfig, Open and Close functions. Open and Close are idempotent.
* Close does not return until all streams have been stopped.

In terms of life-cycle, VStreamer does not depend on serving state. It's started as soon as VTTablet can connect to MySQL. It's stopped only on full shutdown. This is because VStreamer has to serve during migration of served types where the sources might have stopped serving.

VStreamer depends on the schema engine, and opens it on startup (if closed). This serendipitously fixes #4011.

VStreamer uses a cancelable context to track closure, and a waitgroup to ensure all ongoing streams are ended before Close can return.

The Stream function is strucutally similar to the binlog_streamer's Stream, but has been reworked to accommodate the changes: sending individual events, row images, and buffering.

There is a separate planbuilder module to analyze the filter rules and build plans for each table that matches a rule.

The service is additionally exported by TabletServer. This will eventually become part of the QueryService API, because it will end up replacing the UpdateStream call.

The new VStreamer has extensive tests. In particular, all tests run with a real MySQL instance underneath, and test out actual events coming from the underlying MySQL.

### CODE REVIEW

File: go/vt/vttablet/tabletserver/tabletserver.go [hunk 1]
```diff
@@ -1263,6 +1274,40 @@ func (tsv *TabletServer) execDML(ctx context.Context, target *querypb.Target, qu
 	return int64(qr.RowsAffected), nil
 }
 
+// VStream streams VReplication events.
+func (tsv *TabletServer) VStream(ctx context.Context, target *querypb.Target, startPos mysql.Position, filter *binlogdatapb.Filter, send func([]*binlogdatapb.VEvent) error) error {
+	// This code is partially duplicated from execRequest. This is because
```
Comment (rafael) [inline go/vt/vttablet/tabletserver/tabletserver.go]: could you add more context here? I was trying where is the copy coming from in `func (tsv *TabletServer) execRequest(`, but it was not obvious.  Did you mean startRequest?

File: go/vt/vttablet/tabletserver/tabletserver.go [hunk 2]
```diff
@@ -1263,6 +1274,40 @@ func (tsv *TabletServer) execDML(ctx context.Context, target *querypb.Target, qu
...
+				return vterrors.Errorf(vtrpcpb.Code_INVALID_ARGUMENT, "invalid shard %v", target.Shard)
+			case target.TabletType != tsv.target.TabletType:
+				for _, otherType := range tsv.alsoAllow {
+					if target.TabletType == otherType {
+						return nil
+					}
+				}
+				return vterrors.Errorf(vtrpcpb.Code_FAILED_PRECONDITION, "invalid tablet type: %v, want: %v or %v", target.TabletType, tsv.target.TabletType, tsv.alsoAllow)
+			}
+		} else if !tabletenv.IsLocalContext(ctx) {
```
Comment (rafael) [inline go/vt/vttablet/tabletserver/tabletserver.go]: In the context of `VStream` does make sense to allow `Stream` request with nil targets? Would that be a table streaming to itself?

File: go/vt/vttablet/tabletserver/vstreamer/engine.go [hunk 3]
```diff
@@ -0,0 +1,235 @@
...
+func (vse *Engine) vschema() *vindexes.KeyspaceSchema {
+	vse.mu.Lock()
+	defer vse.mu.Unlock()
+	return vse.kschema
+}
+
+// Stream starts a new stream.
+func (vse *Engine) Stream(ctx context.Context, startPos mysql.Position, filter *binlogdatapb.Filter, send func([]*binlogdatapb.VEvent) error) error {
+	// Ensure kschema is initialized and the watcher is started.
+	vse.watcherOnce.Do(vse.setWatch)
```
Comment (rafael) [inline go/vt/vttablet/tabletserver/vstreamer/engine.go]: Instead of doing a `watcherOnce` here, I would initialize this as part of the `Open` or even when creating the engine. That would be consistent on how we do it in vschema_manager.

File: go/vt/vttablet/tabletserver/vstreamer/planbuilder.go [hunk 4]
```diff
@@ -0,0 +1,361 @@
...
+	*mysql.TableMap
+	Columns []schema.TableColumn
+}
+
+func (plan *Plan) filter(values []sqltypes.Value) (bool, []sqltypes.Value, error) {
+	result := make([]sqltypes.Value, len(plan.ColExprs))
+	for i, colExpr := range plan.ColExprs {
+		switch colExpr.Operation {
+		case OpMonth:
+			v, _ := sqltypes.ToInt64(values[colExpr.ColNum])
```
Comment (rafael) [inline go/vt/vttablet/tabletserver/vstreamer/planbuilder.go]: Per discussion in Slack, I think it will be good to add a comment on why this processing is happening in this side and not defer to the player.

File: go/vt/vttablet/tabletserver/tabletserver.go (hunk 1 above)
Comment (sougou) [reply go/vt/vttablet/tabletserver/tabletserver.go]: Yeah. It's startRequest.

File: go/vt/vttablet/tabletserver/tabletserver.go (hunk 2 above)
Comment (sougou) [reply go/vt/vttablet/tabletserver/tabletserver.go]: It has to wait till first use. I've added an explanation.

**Comment by rafael** [comment]
LGTM +1
