### PR TITLE
enhancement: handle advisory locks 

### LINKED ISSUE #10130: Bug Report: Unexpected transaction rollback on client session that previously executed GET_LOCK
### Overview of the Issue

We have been observing an unexpected ROLLBACK that is injected by vttablet into the client transaction. The simplified client transaction would look like (for the failure case):
```
BEGIN
INSERT INTO Test(i) VALUES(1)    - succeeds
ROLLBACK                                     - unexpected, injected by vttablet
<some other queries>
SELECT FROM Test where i=1       - returns no data (expected)
<some other quries>
COMMIT
```
When application detects an error (no data), we can see that SELECT returned no rows for the data inserted in the same transaction. When looking into vttablet query logs we found that vttablet executed ROLLBACK right after INSERT statement. Application was not aware that the transaction was affected and continued with SELECT which returned with no error but with no data.

We found that "unexpected ROLLBACK" was triggered when vtgate failed to execute lock heartbeat related to the same client connection.
```
scatter_conn.go:280] Locking heartbeat failed, held locks might be released: held locks released: vttablet: rpc error: code = Aborted desc = transaction 1650647255709171310: ended at 2022-04-22 21:21:27.249 UTC (exceeded timeout: 30s) (CallerID: userData1)
```

Error message `transaction ... ended at 2022-04-22 21:21:27.249 UTC` told us that something happened earlier on this client session which now affects our transaction. vttablet log shows that "some" other transaction had been killed on this connection before.
```
tx_pool.go:126] killing transaction (exceeded timeout: 30s): 1650647255709171310
```
We found that transaction 1650647255709171310 is related GET_LOCK/RELEASE_LOCK that was executed on the same client connection few minutes before our transaction.

**UNEXPECTED BEHAVIOUR:**

It seems that vttablet does not correctly clean up reserved connection (from GET_LOCK) after RELEASE_LOCK. 30 seconds later (queryserver-config-transaction-timeout) when client transaction is executed it will be unexpectedly rolled back by Vitess.

### Reproduction Steps

1. Deploy the following vschema in a sharded keyspace.
```
{
    "sharded": true,
    "vindexes": {
        "hash_vdx": {
            "type": "hash"
        }
    },
    "tables": {
        "Test": { "column_vindexes": [ { "column": "i", "name": "hash_vdx" } ] }
    }
}
```
2. Create table.
```
CREATE TABLE Test(i int);
```
3. Open mysql client session
4.
```
SELECT GET_LOCK('my-lock', 5);
<wait 1s>
SELECT RELEASE_LOCK('my-lock');

<wait 35s>

BEGIN;
INSERT INTO Test(i) VALUES (1);
SELECT * FROM Test WHERE i=1;
COMMIT;
```

Unexpected behaviour:
```
mysql> SELECT * FROM Test WHERE i=1;
Empty set (0.01 sec)
```

Expected behaviour:
```
mysql> SELECT * FROM Test WHERE i=1;
+------+
| i    |
+------+
|    1 |
+------+
1 row in set (0.01 sec)
```

### Binary Version

```sh
$ /vt/bin/vtgate --version
Version: 13.0.0 (Git revision bc4a9606e1 branch 'heads/v13.0.0') built on Tue Feb 22 14:23:16 UTC 2022 by vitess@buildkitsandbox using go1.17.6 linux/amd64

Default vttablet/mysqld configuration (timeouts not changed).
```

### Operating System and Environment details

```sh
Kubernetes deployment, MySQL Percona version 5.7.36-39
```

### Log Fragments

```sh
Logs from the above reproduction steps:

GET_LOCK/RELEASE_LOCK (vttablet query log):

Reserve	172.18.0.5:52250:/queryservice.Query/ReserveExecute(gRPC)	gRPC	'userData1'	'root'	2022-04-22 21:20:50.672964	2022-04-22 21:20:50.674007	0.001044		""	map[#maxLimit:type:INT64 value:"10001" vtg1:type:VARCHAR value:"my-lock" vtg2:type:INT64 value:"5"]	0	""	none	0.000000	0.000000	0	0	0	""	
Execute	172.18.0.5:52250:/queryservice.Query/ReserveExecute(gRPC)	gRPC	'userData1'	'root'	2022-04-22 21:20:50.674048	2022-04-22 21:20:50.674729	0.000683	Select	"select GET_LOCK(:vtg1, :vtg2) from dual"	map[#maxLimit:type:INT64 value:"10001" vtg1:type:VARCHAR value:"my-lock" vtg2:type:INT64 value:"5"]	1	"select GET_LOCK('my-lock', 5) from dual limit 10001"	mysql	0.000591	0.000000	0	1650647255709171310	1	""	
Execute	172.18.0.5:52250:/queryservice.Query/Execute(gRPC)	gRPC	'userData1'	'root'	2022-04-22 21:20:56.729215	2022-04-22 21:20:56.729856	0.000641	Select	"select RELEASE_LOCK(:vtg1) from dual"	map[#maxLimit:type:INT64 value:"10001" vtg1:type:VARCHAR value:"my-lock"]	1	"select RELEASE_LOCK('my-lock') from dual limit 10001"	mysql	0.000471	0.000000	0	0	1	""	
```

vtgate failed to execute lock heartbeat (vtgate error log):
```
W0422 21:21:45.931273    5651 scatter_conn.go:280] Locking heartbeat failed, held locks might be released: held locks released: vttablet: rpc error: code = Aborted desc = transaction 1650647255709171310: ended at 2022-04-22 21:21:27.249 UTC (exceeded timeout: 30s) (CallerID: userData1)
```
lock heartbeat failed on vttablet with:
```
W0422 21:21:45.930192    2515 tabletserver.go:1391] Code: ABORTED
transaction 1650647255709171310: ended at 2022-04-22 21:21:27.249 UTC (exceeded timeout: 30s) (CallerID: userData1)
: Sql: "select 1", BindVars: {}
```
likely because lock transaction (reserved connection on shard #1) was already killed (vttablet error log):
```
W0422 21:21:27.249041    2515 tx_pool.go:126] killing transaction (exceeded timeout: 30s): 1650647255709171310	
```

Client transaction - note ROLLBACK after INSERT (vttablet query log):
```
Begin	172.18.0.5:52250:/queryservice.Query/BeginExecute(gRPC)	gRPC	'userData1'	'root'	2022-04-22 21:21:45.929774	2022-04-22 21:21:45.930670	0.000896		"begin"	map[]	0	""	none	0.000000	0.000000	01650647255709171311	0	""	
Execute	172.18.0.5:52250:/queryservice.Query/BeginExecute(gRPC)	gRPC	'userData1'	'root'	2022-04-22 21:21:45.930691	2022-04-22 21:21:45.931636	0.000945	Insert	"insert into Test(i) values (:_i_0)"	map[_i_0:type:INT64 value:"1" vtg1:type:INT64 value:"1"]	1	"insert into Test(i) values (1)"	mysql	0.000858	0.000000	1	1650647255709171311	0	""	
Rollback	172.18.0.5:52250:/queryservice.Query/Rollback(gRPC)	gRPC	'userData1'	'root'	2022-04-22 21:21:45.933583	2022-04-22 21:21:45.952414	0.018831		"rollback"	map[]	0	""	none	0.000000	0.000000	0	1650647255709171311	0	""	
Execute	172.18.0.5:52250:/queryservice.Query/Execute(gRPC)	gRPC	'userData1'	'root'	2022-04-22 21:21:45.960452	2022-04-22 21:21:45.961422	0.000970	Select	"select * from Test where i = :vtg1"	map[#maxLimit:type:INT64 value:"10001" vtg1:type:INT64 value:"1"]	1	"select * from Test where i = 1 limit 10001"	mysql	0.000747	0.000017	0	0	0	""
```
```

### PR DESCRIPTION
**Pull request by harshit-gangal**
## Description

Existing:
The initial implementation of the advisory lock function based on https://github.com/vitessio/vitess/issues/6367 does not keep track of the locking function executed on MySQL. The functionality uses the reserved connection to keep holding the lock and uses a lock heartbeat to keep the connection alive.

Issue:
Once the session is done using the advisory lock the reserve connection was never released and if the connection is lost for any reason the next query on the session can see an unexpected result.

Change:
This implementation keeps track of the advisory locks executed on the MySQL and based on the release lock or release unlock calls, it will also release the reserved connection held once no lock is held on the MySQL.

## Related Issue(s)

 - Closes #10130 

## Checklist

-   [X] Tests were added or are not required
-   [X] Documentation was added or is not required

### CODE REVIEW

File: go/test/endtoend/vtgate/reservedconn/get_lock_test.go [hunk 1]
```diff
@@ -255,3 +255,19 @@ func TestLocksResetLockOnTimeout(t *testing.T) {
 	utils.AssertContainsError(t, conn, `select is_free_lock('lock')`, "held locks released")
 	utils.AssertMatches(t, conn, `select is_free_lock('lock')`, `[[INT64(1)]]`)
 }
+
+func TestLockWaitOnConnTimeoutWithTxNext(t *testing.T) {
```
Comment (systay) [inline go/test/endtoend/vtgate/reservedconn/get_lock_test.go:259]: all the `time.Sleep`s make me nervous that we are introducing flakiness, but I have not alternative to offer

File: go/vt/vttablet/tabletserver/planbuilder/plan.go [hunk 2]
```diff
@@ -218,13 +211,22 @@ func Build(statement sqlparser.Statement, tables map[string]*schema.Table, isRes
 		}, nil
 	case *sqlparser.Select:
 		plan, err = analyzeSelect(stmt, tables)
```
Comment (systay) [inline go/vt/vttablet/tabletserver/planbuilder/plan.go:213]: shouldn't we check the err here before moving on?

File: go/vt/vtgate/scatter_conn.go [hunk 3]
```diff
@@ -676,15 +681,15 @@ func (stc *ScatterConn) ExecuteLock(
 
 	switch info.actionNeeded {
 	case nothing:
-		if reservedID == 0 {
-			return nil, vterrors.Errorf(vtrpcpb.Code_INTERNAL, "[BUG] reserved id zero not expected %v", reservedID)
-		}
 		qr, err = qs.Execute(ctx, rs.Target, query.Sql, query.BindVariables, 0 /* transactionID */, reservedID, opts)
 		if err != nil && wasConnectionClosed(err) {
+			// TODO: try to acquire lock again.
```
Comment (systay) [inline go/vt/vtgate/scatter_conn.go:686]: did you leave this here intentionally?

File: go/vt/vttablet/tabletserver/planbuilder/plan_test.go [hunk 4]
```diff
@@ -268,6 +268,41 @@ func TestMessageStreamingPlan(t *testing.T) {
...
+				plan, err = Build(statement, testSchema, false, "dbName")
+			}
+
+			var out string
+			if err != nil {
+				out = err.Error()
+			} else {
+				bout, err := json.Marshal(plan)
+				if err != nil {
+					t.Fatalf("Error marshalling %v: %v", plan, err)
```
Comment (systay) [inline go/vt/vttablet/tabletserver/planbuilder/plan_test.go:288]: nit: If you are working on these tests, might as well update them to follow how we write tests these days - with `utils.Diff` and `require.NoError`

File: go/test/endtoend/vtgate/reservedconn/get_lock_test.go (hunk 1 above)
Comment (harshit-gangal) [reply go/test/endtoend/vtgate/reservedconn/get_lock_test.go:259]: this is to ensure that timeouts happen

File: go/vt/vttablet/tabletserver/planbuilder/plan.go (hunk 2 above)
Comment (harshit-gangal) [reply go/vt/vttablet/tabletserver/planbuilder/plan.go:213]: this is based on assumption that only one of them will be non-nil and not both.
I can do the check if you think otherwise.

File: go/vt/vtgate/scatter_conn.go (hunk 3 above)
Comment (harshit-gangal) [reply go/vt/vtgate/scatter_conn.go:686]: yes, I believe we can try acquiring a lock here again, but not sure if this seems a good approach.

File: go/vt/vttablet/tabletserver/planbuilder/plan.go (hunk 2 above)
Comment (systay) [reply go/vt/vttablet/tabletserver/planbuilder/plan.go:213]: looks like an error to me like this

**Comment by deepthi** [comment]
Should only be merged after release-14.0 branch is created (as specified in linked issue).

**Comment by harshit-gangal** [comment]
> Should only be merged after release-14.0 branch is created (as specified in linked issue).

This PR should be merged before 14.0 as the changes are backward compatible, the next change will be after 14.0 cutover.

**Comment by harshit-gangal** [comment]
> Should only be merged after release-14.0 branch is created (as specified in linked issue).

I have updated the issue description, I guess it was confusing.

**Review by systay — APPROVED** [review]
Nice change
