### PR TITLE
fix: Infinite logs in case of non-existent stream logs

### LINKED ISSUE #16195: vtctld: infinite loop on "Found stream log for nonexistent stream"
### Overview of the Issue

I've been running various workflow commands for our materialize streams. There's something happening that triggers an infinite loop in vtctld spitting out logs, maxing out available CPU, and rendering the cluster nearly unusable. Loading vtadmin seems to be an immediately reliable trigger to put it into that state, and restarting vtctld resolves the problem. I have some broken workflows, but nothing immediately stands out as being an issue.

### Reproduction Steps

?

### Binary Version

```sh
v20.0.0-rc1
```

### Operating System and Environment details

```sh
GKE v1.29
```

### Log Fragments

```sh
W0615 00:23:28.969774       1 server.go:855] Found stream log for nonexistent stream: id:11623 stream_id:44 type:"Stream Created" state:"Stopped" created_at:{seconds:1714397383} updated_at:{seconds:1714397383} message:"{\"cell\":\"\",\"component_throttled\":\"\",\"db_name\":\"keywords\",\"defer_secondary_keys\":\"0\",\"id\":\"44\",\"max_replication_lag\":\"9223372036854775807\",\"max_tps\":\"9223372036854775807\",\"pos\":\"\",\"rows_copied\":\"0\",\"source\":\"keyspace:\\\"workspaces\\\" shard:\\\"0\\\" filter:{rules:{match:\\\"keywords__workspaces__copy\\\" filter:\\\"SELECT workspace_id, version_id, name, slug, is_test, created_at, updated_at, deleted_at FROM workspaces\\\"}} on_ddl:EXEC\",\"state\":\"Stopped\",\"tablet_types\":\"REPLICA,PRIMARY\",\"tags\":\"\",\"time_heartbeat\":\"0\",\"time_throttled\":\"0\",\"time_updated\":\"1714397383\",\"transaction_timestamp\":\"0\",\"workflow\":\"keywords__workspaces__copy\",\"workflow_sub_type\":\"0\",\"workflow_type\":\"0\"}" count:1
W0615 00:23:28.969789       1 server.go:855] Found stream log for nonexistent stream: id:11623 stream_id:44 type:"Stream Created" state:"Stopped" created_at:{seconds:1714397383} updated_at:{seconds:1714397383} message:"{\"cell\":\"\",\"component_throttled\":\"\",\"db_name\":\"keywords\",\"defer_secondary_keys\":\"0\",\"id\":\"44\",\"max_replication_lag\":\"9223372036854775807\",\"max_tps\":\"9223372036854775807\",\"pos\":\"\",\"rows_copied\":\"0\",\"source\":\"keyspace:\\\"workspaces\\\" shard:\\\"0\\\" filter:{rules:{match:\\\"keywords__workspaces__copy\\\" filter:\\\"SELECT workspace_id, version_id, name, slug, is_test, created_at, updated_at, deleted_at FROM workspaces\\\"}} on_ddl:EXEC\",\"state\":\"Stopped\",\"tablet_types\":\"REPLICA,PRIMARY\",\"tags\":\"\",\"time_heartbeat\":\"0\",\"time_throttled\":\"0\",\"time_updated\":\"1714397383\",\"transaction_timestamp\":\"0\",\"workflow\":\"keywords__workspaces__copy\",\"workflow_sub_type\":\"0\",\"workflow_type\":\"0\"}" count:1
W0615 00:23:28.969805       1 server.go:855] Found stream log for nonexistent stream: id:11623 stream_id:44 type:"Stream Created" state:"Stopped" created_at:{seconds:1714397383} updated_at:{seconds:1714397383} message:"{\"cell\":\"\",\"component_throttled\":\"\",\"db_name\":\"keywords\",\"defer_secondary_keys\":\"0\",\"id\":\"44\",\"max_replication_lag\":\"9223372036854775807\",\"max_tps\":\"9223372036854775807\",\"pos\":\"\",\"rows_copied\":\"0\",\"source\":\"keyspace:\\\"workspaces\\\" shard:\\\"0\\\" filter:{rules:{match:\\\"keywords__workspaces__copy\\\" filter:\\\"SELECT workspace_id, version_id, name, slug, is_test, created_at, updated_at, deleted_at FROM workspaces\\\"}} on_ddl:EXEC\",\"state\":\"Stopped\",\"tablet_types\":\"REPLICA,PRIMARY\",\"tags\":\"\",\"time_heartbeat\":\"0\",\"time_throttled\":\"0\",\"time_updated\":\"1714397383\",\"transaction_timestamp\":\"0\",\"workflow\":\"keywords__workspaces__copy\",\"workflow_sub_type\":\"0\",\"workflow_type\":\"0\"}" count:1
W0615 00:23:28.969822       1 server.go:855] Found stream log for nonexistent stream: id:11623 stream_id:44 type:"Stream Created" state:"Stopped" created_at:{seconds:1714397383} updated_at:{seconds:1714397383} message:"{\"cell\":\"\",\"component_throttled\":\"\",\"db_name\":\"keywords\",\"defer_secondary_keys\":\"0\",\"id\":\"44\",\"max_replication_lag\":\"9223372036854775807\",\"max_tps\":\"9223372036854775807\",\"pos\":\"\",\"rows_copied\":\"0\",\"source\":\"keyspace:\\\"workspaces\\\" shard:\\\"0\\\" filter:{rules:{match:\\\"keywords__workspaces__copy\\\" filter:\\\"SELECT workspace_id, version_id, name, slug, is_test, created_at, updated_at, deleted_at FROM workspaces\\\"}} on_ddl:EXEC\",\"state\":\"Stopped\",\"tablet_types\":\"REPLICA,PRIMARY\",\"tags\":\"\",\"time_heartbeat\":\"0\",\"time_throttled\":\"0\",\"time_updated\":\"1714397383\",\"transaction_timestamp\":\"0\",\"workflow\":\"keywords__workspaces__copy\",\"workflow_sub_type\":\"0\",\"workflow_type\":\"0\"}" count:1
W0615 00:23:28.969839       1 server.go:855] Found stream log for nonexistent stream: id:11623 stream_id:44 type:"Stream Created" state:"Stopped" created_at:{seconds:1714397383} updated_at:{seconds:1714397383} message:"{\"cell\":\"\",\"component_throttled\":\"\",\"db_name\":\"keywords\",\"defer_secondary_keys\":\"0\",\"id\":\"44\",\"max_replication_lag\":\"9223372036854775807\",\"max_tps\":\"9223372036854775807\",\"pos\":\"\",\"rows_copied\":\"0\",\"source\":\"keyspace:\\\"workspaces\\\" shard:\\\"0\\\" filter:{rules:{match:\\\"keywords__workspaces__copy\\\" filter:\\\"SELECT workspace_id, version_id, name, slug, is_test, created_at, updated_at, deleted_at FROM workspaces\\\"}} on_ddl:EXEC\",\"state\":\"Stopped\",\"tablet_types\":\"REPLICA,PRIMARY\",\"tags\":\"\",\"time_heartbeat\":\"0\",\"time_throttled\":\"0\",\"time_updated\":\"1714397383\",\"transaction_timestamp\":\"0\",\"workflow\":\"keywords__workspaces__copy\",\"workflow_sub_type\":\"0\",\"workflow_type\":\"0\"}" count:1
W0615 00:23:28.969702       1 server.go:855] Found stream log for nonexistent stream: id:1566 stream_id:46 type:"Stream Created" state:"Stopped" created_at:{seconds:1714397466} updated_at:{seconds:1714397466} message:"{\"cell\":\"\",\"component_throttled\":\"\",\"db_name\":\"keywords\",\"defer_secondary_keys\":\"0\",\"id\":\"46\",\"max_replication_lag\":\"9223372036854775807\",\"max_tps\":\"9223372036854775807\",\"pos\":\"\",\"rows_copied\":\"0\",\"source\":\"keyspace:\\\"workspaces\\\" shard:\\\"0\\\" filter:{rules:{match:\\\"keywords__teams__copy\\\" filter:\\\"SELECT team_id, version_id, workspace_id, name, slug, description, image, created_at, updated_at, deleted_at FROM teams\\\"}} on_ddl:EXEC\",\"state\":\"Stopped\",\"tablet_types\":\"REPLICA,PRIMARY\",\"tags\":\"\",\"time_heartbeat\":\"0\",\"time_throttled\":\"0\",\"time_updated\":\"1714397466\",\"transaction_timestamp\":\"0\",\"workflow\":\"keywords__teams__copy\",\"workflow_sub_type\":\"0\",\"workflow_type\":\"0\"}" count:1
W0615 00:23:28.969855       1 server.go:855] Found stream log for nonexistent stream: id:11623 stream_id:44 type:"Stream Created" state:"Stopped" created_at:{seconds:1714397383} updated_at:{seconds:1714397383} message:"{\"cell\":\"\",\"component_throttled\":\"\",\"db_name\":\"keywords\",\"defer_secondary_keys\":\"0\",\"id\":\"44\",\"max_replication_lag\":\"9223372036854775807\",\"max_tps\":\"9223372036854775807\",\"pos\":\"\",\"rows_copied\":\"0\",\"source\":\"keyspace:\\\"workspaces\\\" shard:\\\"0\\\" filter:{rules:{match:\\\"keywords__workspaces__copy\\\" filter:\\\"SELECT workspace_id, version_id, name, slug, is_test, created_at, updated_at, deleted_at FROM workspaces\\\"}} on_ddl:EXEC\",\"state\":\"Stopped\",\"tablet_types\":\"REPLICA,PRIMARY\",\"tags\":\"\",\"time_heartbeat\":\"0\",\"time_throttled\":\"0\",\"time_updated\":\"1714397383\",\"transaction_timestamp\":\"0\",\"workflow\":\"keywords__workspaces__copy\",\"workflow_sub_type\":\"0\",\"workflow_type\":\"0\"}" count:1
W0615 00:23:28.969900       1 server.go:855] Found stream log for nonexistent stream: id:1566 stream_id:46 type:"Stream Created" state:"Stopped" created_at:{seconds:1714397466} updated_at:{seconds:1714397466} message:"{\"cell\":\"\",\"component_throttled\":\"\",\"db_name\":\"keywords\",\"defer_secondary_keys\":\"0\",\"id\":\"46\",\"max_replication_lag\":\"9223372036854775807\",\"max_tps\":\"9223372036854775807\",\"pos\":\"\",\"rows_copied\":\"0\",\"source\":\"keyspace:\\\"workspaces\\\" shard:\\\"0\\\" filter:{rules:{match:\\\"keywords__teams__copy\\\" filter:\\\"SELECT team_id, version_id, workspace_id, name, slug, description, image, created_at, updated_at, deleted_at FROM teams\\\"}} on_ddl:EXEC\",\"state\":\"Stopped\",\"tablet_types\":\"REPLICA,PRIMARY\",\"tags\":\"\",\"time_heartbeat\":\"0\",\"time_throttled\":\"0\",\"time_updated\":\"1714397466\",\"transaction_timestamp\":\"0\",\"workflow\":\"keywords__teams__copy\",\"workflow_sub_type\":\"0\",\"workflow_type\":\"0\"}" count:1
W0615 00:23:28.963148       1 server.go:855] Found stream log for nonexistent stream: id:10955 stream_id:45 type:"Stream Created" state:"Stopped" created_at:{seconds:1714397466} updated_at:{seconds:1714397466} message:"{\"cell\":\"\",\"component_throttled\":\"\",\"db_name\":\"keywords\",\"defer_secondary_keys\":\"0\",\"id\":\"45\",\"max_replication_lag\":\"9223372036854775807\",\"max_tps\":\"9223372036854775807\",\"pos\":\"\",\"rows_copied\":\"0\",\"source\":\"keyspace:\\\"workspaces\\\" shard:\\\"0\\\" filter:{rules:{match:\\\"keywords__teams__copy\\\" filter:\\\"SELECT team_id, version_id, workspace_id, name, slug, description, image, created_at, updated_at, deleted_at FROM teams\\\"}} on_ddl:EXEC\",\"state\":\"Stopped\",\"tablet_types\":\"REPLICA,PRIMARY\",\"tags\":\"\",\"time_heartbeat\":\"0\",\"time_throttled\":\"0\",\"time_updated\":\"1714397466\",\"transaction_timestamp\":\"0\",\"workflow\":\"keywords__teams__copy\",\"workflow_sub_type\":\"0\",\"workflow_type\":\"0\"}" count:1
W0615 00:23:28.969921       1 server.go:855] Found stream log for nonexistent stream: id:1566 stream_id:46 type:"Stream Created" state:"Stopped" created_at:{seconds:1714397466} updated_at:{seconds:1714397466} message:"{\"cell\":\"\",\"component_throttled\":\"\",\"db_name\":\"keywords\",\"defer_secondary_keys\":\"0\",\"id\":\"46\",\"max_replication_lag\":\"9223372036854775807\",\"max_tps\":\"9223372036854775807\",\"pos\":\"\",\"rows_copied\":\"0\",\"source\":\"keyspace:\\\"workspaces\\\" shard:\\\"0\\\" filter:{rules:{match:\\\"keywords__teams__copy\\\" filter:\\\"SELECT team_id, version_id, workspace_id, name, slug, description, image, created_at, updated_at, deleted_at FROM teams\\\"}} on_ddl:EXEC\",\"state\":\"Stopped\",\"tablet_types\":\"REPLICA,PRIMARY\",\"tags\":\"\",\"time_heartbeat\":\"0\",\"time_throttled\":\"0\",\"time_updated\":\"1714397466\",\"transaction_timestamp\":\"0\",\"workflow\":\"keywords__teams__copy\",\"workflow_sub_type\":\"0\",\"workflow_type\":\"0\"}" count:1
W0615 00:23:28.969925       1 server.go:855] Found stream log for nonexistent stream: id:10955 stream_id:45 type:"Stream Created" state:"Stopped" created_at:{seconds:1714397466} updated_at:{seconds:1714397466} message:"{\"cell\":\"\",\"component_throttled\":\"\",\"db_name\":\"keywords\",\"defer_secondary_keys\":\"0\",\"id\":\"45\",\"max_replication_lag\":\"9223372036854775807\",\"max_tps\":\"9223372036854775807\",\"pos\":\"\",\"rows_copied\":\"0\",\"source\":\"keyspace:\\\"workspaces\\\" shard:\\\"0\\\" filter:{rules:{match:\\\"keywords__teams__copy\\\" filter:\\\"SELECT team_id, version_id, workspace_id, name, slug, description, image, created_at, updated_at, deleted_at FROM teams\\\"}} on_ddl:EXEC\",\"state\":\"Stopped\",\"tablet_types\":\"REPLICA,PRIMARY\",\"tags\":\"\",\"time_heartbeat\":\"0\",\"time_throttled\":\"0\",\"time_updated\":\"1714397466\",\"transaction_timestamp\":\"0\",\"workflow\":\"keywords__teams__copy\",\"workflow_sub_type\":\"0\",\"workflow_type\":\"0\"}" count:1
W0615 00:23:28.969938       1 server.go:855] Found stream log for nonexistent stream: id:10955 stream_id:45 type:"Stream Created" state:"Stopped" created_at:{seconds:1714397466} updated_at:{seconds:1714397466} message:"{\"cell\":\"\",\"component_throttled\":\"\",\"db_name\":\"keywords\",\"defer_secondary_keys\":\"0\",\"id\":\"45\",\"max_replication_lag\":\"9223372036854775807\",\"max_tps\":\"9223372036854775807\",\"pos\":\"\",\"rows_copied\":\"0\",\"source\":\"keyspace:\\\"workspaces\\\" shard:\\\"0\\\" filter:{rules:{match:\\\"keywords__teams__copy\\\" filter:\\\"SELECT team_id, version_id, workspace_id, name, slug, description, image, created_at, updated_at, deleted_at FROM teams\\\"}} on_ddl:EXEC\",\"state\":\"Stopped\",\"tablet_types\":\"REPLICA,PRIMARY\",\"tags\":\"\",\"time_heartbeat\":\"0\",\"time_throttled\":\"0\",\"time_updated\":\"1714397466\",\"transaction_timestamp\":\"0\",\"workflow\":\"keywords__teams__copy\",\"workflow_sub_type\":\"0\",\"workflow_type\":\"0\"}" count:1
W0615 00:23:28.969692       1 server.go:855] Found stream log for nonexistent stream: id:6978 stream_id:6 type:"Message" state:"Running" created_at:{seconds:1708787706} updated_at:{seconds:1711690256} message:"vstream ended" count:5
W0615 00:23:28.969972       1 server.go:855] Found stream log for nonexistent stream: id:6978 stream_id:6 type:"Message" state:"Running" created_at:{seconds:1708787706} updated_at:{seconds:1711690256} message:"vstream ended" count:5
W0615 00:23:28.969985       1 server.go:855] Found stream log for nonexistent stream: id:6978 stream_id:6 type:"Message" state:"Running" created_at:{seconds:1708787706} updated_at:{seconds:1711690256} message:"vstream ended" count:5
W0615 00:23:28.969956       1 server.go:855] Found stream log for nonexistent stream: id:10955 stream_id:45 type:"Stream Created" state:"Stopped" created_at:{seconds:1714397466} updated_at:{seconds:1714397466} message:"{\"cell\":\"\",\"component_throttled\":\"\",\"db_name\":\"keywords\",\"defer_secondary_keys\":\"0\",\"id\":\"45\",\"max_replication_lag\":\"9223372036854775807\",\"max_tps\":\"9223372036854775807\",\"pos\":\"\",\"rows_copied\":\"0\",\"source\":\"keyspace:\\\"workspaces\\\" shard:\\\"0\\\" filter:{rules:{match:\\\"keywords__teams__copy\\\" filter:\\\"SELECT team_id, version_id, workspace_id, name, slug, description, image, created_at, updated_at, deleted_at FROM teams\\\"}} on_ddl:EXEC\",\"state\":\"Stopped\",\"tablet_types\":\"REPLICA,PRIMARY\",\"tags\":\"\",\"time_heartbeat\":\"0\",\"time_throttled\":\"0\",\"time_updated\":\"1714397466\",\"transaction_timestamp\":\"0\",\"workflow\":\"keywords__teams__copy\",\"workflow_sub_type\":\"0\",\"workflow_type\":\"0\"}" count:1
W0615 00:23:28.969996       1 server.go:855] Found stream log for nonexistent stream: id:6978 stream_id:6 type:"Message" state:"Running" created_at:{seconds:1708787706} updated_at:{seconds:1711690256} message:"vstream ended" count:5
W0615 00:23:28.969999       1 server.go:855] Found stream log for nonexistent stream: id:10955 stream_id:45 type:"Stream Created" state:"Stopped" created_at:{seconds:1714397466} updated_at:{seconds:1714397466} message:"{\"cell\":\"\",\"component_throttled\":\"\",\"db_name\":\"keywords\",\"defer_secondary_keys\":\"0\",\"id\":\"45\",\"max_replication_lag\":\"9223372036854775807\",\"max_tps\":\"9223372036854775807\",\"pos\":\"\",\"rows_copied\":\"0\",\"source\":\"keyspace:\\\"workspaces\\\" shard:\\\"0\\\" filter:{rules:{match:\\\"keywords__teams__copy\\\" filter:\\\"SELECT team_id, version_id, workspace_id, name, slug, description, image, created_at, updated_at, deleted_at FROM teams\\\"}} on_ddl:EXEC\",\"state\":\"Stopped\",\"tablet_types\":\"REPLICA,PRIMARY\",\"tags\":\"\",\"time_heartbeat\":\"0\",\"time_throttled\":\"0\",\"time_updated\":\"1714397466\",\"transaction_timestamp\":\"0\",\"workflow\":\"keywords__teams__copy\",\"workflow_sub_type\":\"0\",\"workflow_type\":\"0\"}" count:1
W0
```

### PR DESCRIPTION
**Pull request by beingnoble03**
## Description
In `GetWorkflows()` we use the following algo while collecting logs for a workflow.
We first sort all the streams of each shard by `streamID` in ASC order. Now, we call `fetchStreamLogs` for each workflow. Inside `fetchStreamLogs`, we fetch the streamLogs from each tablet. Now, we run a `for` loop across all the tablets we got from `results` (from query for fetching logs and results sorted by `streamID` in ASC order). Now, as we have already sorted the `shardStreams` by `streamID` and logs are also ordered by `streamID`, so we use a variable `streamIdx` which starts from 0. Now, we run a `for` loop across stream log results from that particular tablet (we got from the outer loop). In this loop, we update `streamIdx` in this code block:
```go
for streamIdx < len(streams) {
	stream := streams[streamIdx]
	if stream.Id < streamLog.StreamId {
		streamIdx++
		continue
	}

	if stream.Id > streamLog.StreamId {
		s.Logger().Warningf("Found stream log for nonexistent stream: %+v", streamLog)
		// This can happen on manual/failed workflow cleanup so keep going.
		continue
	}

	// stream.Id == streamLog.StreamId
	stream.Logs = append(stream.Logs, streamLog)
	break
}
```
So, basically if we increase the `streamIdx` (i.e. `streamIdx++` ) , the next `streamID` will be greater than the last one because we already sorted the streams of each shard. We can consider that `continue` in this loop means that we are finding the stream that matches the particular `streamLog.StreamID`, and break means jumping to next log. But, in the following condition:
```go
if stream.Id > streamLog.StreamId {
      s.Logger().Warningf("Found stream log for nonexistent stream: %+v", streamLog)
      // This can happen on manual/failed workflow cleanup so keep going.
      continue
}
```
Instead of jumping to the next log, we are continuing the search for matching `stream.Id` even when we know it's not possible to find it, because even if we increase the `streamIdx`, `stream.Id` will increase as the results are already sorted. This results in an infinite loop. Instead we should break the for loop and jump to the next log.

Failing Case: If the streamIDs are: 1, 2, 4, 6 and logs have streamIDs in this order: 1, 1, 1, 3, 3, 3, 4. Now, inside the loop when we are at log with streamID 3, right now we will be stuck. And, if we increase the `streamIdx` it won't be right, as we would already be at `stream.Id = 4` and  this will skip the logs for stream 4 and stream 6. But, if we break, we'll be accessing the next log, which would be the correct approach.

## Related Issue(s)
- Fixes #16195

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on CI?
-   [ ] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vtctl/workflow/server_test.go [hunk 1]
```diff
@@ -1811,3 +1811,60 @@ func createReadVReplicationWorkflowFunc(t *testing.T, workflowType binlogdatapb.
 		}, nil
 	}
 }
+
```
Comment (mattlord) [inline go/vt/vtctl/workflow/server_test.go:1814]: We should add a brief comment about what this is testing as it's not obvious from the name.

**Review by mattlord — APPROVED** [review]
Excellent work (as usual), @beingnoble03 ! Thank you. ❤️ I only had the very minor note about adding a comment for the new unit test. 

I confirmed that it tests what we want. When running it against main:
```
❯ go test -timeout 10s -run ^TestGetWorkflowsSingleStream$ vitess.io/vitess/go/vt/vtctl/workflow
... MANY of these
W1018 16:36:43.159766   58815 server.go:865] Found stream log for nonexistent stream: id:1 type:"State Change" state:"Running" created_at:{seconds:1136214245} updated_at:{seconds:1136214245} message:"test message for non-existent 1" count:1
W1018 16:36:43.159768   58815 server.go:865] Found stream log for nonexistent stream: id:1 type:"State Change" state:"Running" created_at:{seconds:1136214245} updated_at:{seconds:1136214245} message:"test message for non-existent 1" count:1
W1018 16:36:43.159771   58815 server.go:865] Found stream log for nonexistent stream: id:1 type:"State Change" state:"Running" created_at:{seconds:1136214245} updated_at:{seconds:1136214245} message:"test message for non-existent 1" count:1
W1018 16:36:43.159774   58815 server.go:865] Found stream log for nonexistent stream: id:1 type:"State Change" state:"Running" created_at:{seconds:1136214245} updated_at:{seconds:1136214245} message:"test message for non-existent 1" count:1
W1018 16:36:43.159776   58815 server.go:865] Found stream log for nonexistent stream: id:1 type:"State Change" state:"Running" created_at:{seconds:1136214245} updated_at:{seconds:1136214245} message:"test message for non-existent 1" count:1
panic: test timed out after 10s
	running tests:
		TestGetWorkflowsSingleStream (10s)
```

It demonstrates perfectly what had been seen — spinning in a tight loop spewing that warning forever — and that it works as expected/desired in the PR branch.

File: go/vt/vtctl/workflow/server_test.go (hunk 1 above)
Comment (beingnoble03) [reply go/vt/vtctl/workflow/server_test.go:1814]: Thanks for pointing out that @mattlord! I've changed the test func name and added the comment.

**Review by rohit-nayak-ps — APPROVED** [review]
