### PR TITLE
Trigger the loadTablets function when no primary is assigned to the shard

### LINKED ISSUE #12624: Bug Report: TabletExternallyReparented during vttablets rolling-update may cause a service interruption
### Overview of the Issue

We've encountered a problem with `TabletExternallyReparented`: our vtgates continued to connect to the previous `PRIMARY` tablet even after reparenting.

The vtgate does not recognize the newly restarted tablet pod (with a new IP address) until the `TopologyWatcher` calls the [loadTablets function](https://github.com/vitessio/vitess/blob/c4292b7c560766275e22be8105cf95d9d5afe7b8/go/vt/discovery/topology_watcher.go#L150) to get the latest tablets.
As a result, the second `TabletExternallyReparented` call within [tablet_refresh_interval (default: 1 minute)](https://github.com/vitessio/vitess/blob/c4292b7c560766275e22be8105cf95d9d5afe7b8/go/vt/discovery/healthcheck.go#L166) after the `SPARE` pod restart may cause a service interruption

Discussion is https://vitess.slack.com/archives/C0PQY0PTK/p1678243354071319.

### Reproduction Steps

1. Set up a minikube cluster:

```sh
# Make sure to set the CNI plugin to kindnet so that the pod's IP address changes every time it restarts, similar to the behavior in the GKE environment. 
# This is because the pod in the default minikube single node cluster does not change its IP address during vttablet rolling updates.
$ minikube start --cni=kindnet --kubernetes-version=v1.19.16 --cpus=4 --memory=8000 --disk-size=40g -p parallel-test

# Make sure that the vitess-operator's image is planetscale/vitess-operator:v2.8.1
$ minikube -p parallel-test kubectl -- apply -f operator.yaml
```

2. Deploy the following yaml:

- Note: The default value of `tablet_refresh_interval` makes it difficult to reproduce this issue with just a few attempts. Increasing the tablet_refresh_interval duration makes it easier to reproduce the issue.

```yaml
apiVersion: planetscale.com/v2
kind: VitessCluster
metadata:
  name: example
spec:
  images:
    vtctld: vitess/lite:v15.0.1
    vtadmin: vitess/vtadmin:latest
    vtgate: vitess/lite:v15.0.1
    vttablet: vitess/lite:v15.0.1
    vtbackup: vitess/lite:v15.0.1
    mysqld:
      mysql56Compatible: vitess/lite:v15.0.1
    mysqldExporter: prom/mysqld-exporter:v0.11.0
  cells:
  - name: zone1
    gateway:
      authentication:
        static:
          secret:
            name: example-cluster-config
            key: users.json
      # extraFlags:
       #  tablet_refresh_interval: "5m"
      replicas: 1
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 256Mi
  vitessDashboard:
    cells:
    - zone1
    extraFlags:
      security_policy: read-only
    replicas: 1
    resources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
  vtadmin:
    rbac:
      name: example-cluster-config
      key: rbac.yaml
    cells:
      - zone1
    apiAddresses:
      - http://localhost:14001
    replicas: 1
    readOnly: false
    apiResources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi
    webResources:
      limits:
        memory: 128Mi
      requests:
        cpu: 100m
        memory: 128Mi

  keyspaces:
  - name: main
    durabilityPolicy: none
    turndownPolicy: Immediate
    partitionings:
    - equal:
        parts: 1
        shardTemplate:
          databaseInitScriptSecret:
            name: example-cluster-config
            key: init_db.sql
          replication:
            enforceSemiSync: false
          tabletPools:
          - cell: zone1
            type: externalmaster
            replicas: 2
            vttablet:
              extraFlags:
                db_charset: utf8mb4_unicode_ci
                log_queries_to_file: vt/vtdataroot/queries.log
                queryserver-config-pool-size: "10"
              resources:
                limits:
                  memory: 256Mi
                requests:
                  cpu: 100m
                  memory: 256Mi
            externalDatastore:
              user: root
              host: mysql
              port: 3306
              database: main
              credentialsSecret:
                name: example-cluster-config
                key: ext_db_credentials_secret.json
  updateStrategy:
    type: Immediate
---
apiVersion: v1
kind: Secret
metadata:
  name: example-cluster-config
type: Opaque
stringData:
  users.json: |
    {
      "user": [{
        "UserData": "user",
        "Password": ""
      }]
    }
  init_db.sql: |
    # This file is executed immediately after mysql_install_db,
    # to initialize a fresh data directory.

    ###############################################################################
    # Equivalent of mysql_secure_installation
    ###############################################################################

    # Changes during the init db should not make it to the binlog.
    # They could potentially create errant transactions on replicas.
    SET sql_log_bin = 0;
    # Remove anonymous users.
    DELETE FROM mysql.user WHERE User = '';

    # Disable remote root access (only allow UNIX socket).
    DELETE FROM mysql.user WHERE User = 'root' AND Host != 'localhost';

    # Remove test database.
    DROP DATABASE IF EXISTS test;

    ###############################################################################
    # Vitess defaults
    ###############################################################################

    # Vitess-internal database.
    CREATE DATABASE IF NOT EXISTS _vt;
    # Note that definitions of local_metadata and shard_metadata should be the same
    # as in production which is defined in go/vt/mysqlctl/metadata_tables.go.
    CREATE TABLE IF NOT EXISTS _vt.local_metadata (
      name VARCHAR(255) NOT NULL,
      value VARCHAR(255) NOT NULL,
      db_name VARBINARY(255) NOT NULL,
      PRIMARY KEY (db_name, name)
      ) ENGINE=InnoDB;
    CREATE TABLE IF NOT EXISTS _vt.shard_metadata (
      name VARCHAR(255) NOT NULL,
      value MEDIUMBLOB NOT NULL,
      db_name VARBINARY(255) NOT NULL,
      PRIMARY KEY (db_name, name)
      ) ENGINE=InnoDB;

    # Admin user with all privileges.
    CREATE USER 'vt_dba'@'localhost';
    GRANT ALL ON *.* TO 'vt_dba'@'localhost';
    GRANT GRANT OPTION ON *.* TO 'vt_dba'@'localhost';

    # User for app traffic, with global read-write access.
    CREATE USER 'vt_app'@'localhost';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, FILE,
      REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES,
      LOCK TABLES, EXECUTE, REPLICATION CLIENT, CREATE VIEW,
      SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER
      ON *.* TO 'vt_app'@'localhost';

    # User for app debug traffic, with global read access.
    CREATE USER 'vt_appdebug'@'localhost';
    GRANT SELECT, SHOW DATABASES, PROCESS ON *.* TO 'vt_appdebug'@'localhost';

    # User for administrative operations that need to be executed as non-SUPER.
    # Same permissions as vt_app here.
    CREATE USER 'vt_allprivs'@'localhost';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, FILE,
      REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES,
      LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW,
      SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER
      ON *.* TO 'vt_allprivs'@'localhost';

    # User for slave replication connections.
    # TODO: Should we set a password on this since it allows remote connections?
    CREATE USER 'vt_repl'@'%';
    GRANT REPLICATION SLAVE ON *.* TO 'vt_repl'@'%';

    # User for Vitess filtered replication (binlog player).
    # Same permissions as vt_app.
    CREATE USER 'vt_filtered'@'localhost';
    GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, RELOAD, PROCESS, FILE,
      REFERENCES, INDEX, ALTER, SHOW DATABASES, CREATE TEMPORARY TABLES,
      LOCK TABLES, EXECUTE, REPLICATION SLAVE, REPLICATION CLIENT, CREATE VIEW,
      SHOW VIEW, CREATE ROUTINE, ALTER ROUTINE, CREATE USER, EVENT, TRIGGER
      ON *.* TO 'vt_filtered'@'localhost';

    # User for Orchestrator (https://github.com/openark/orchestrator).
    # TODO: Reenable when the password is randomly generated.
    CREATE USER 'orc_client_user'@'%' IDENTIFIED BY 'orc_client_user_password';
    GRANT SUPER, PROCESS, REPLICATION SLAVE, RELOAD
      ON *.* TO 'orc_client_user'@'%';
    GRANT SELECT
      ON _vt.* TO 'orc_client_user'@'%';

    FLUSH PRIVILEGES;

    RESET SLAVE ALL;
    RESET MASTER;
  rbac.yaml: |
    rules:
    - resource: "*"
      actions:
        - "get"
        - "create"
        - "put"
        - "ping"
      subjects: ["*"]
      clusters: ["*"]
    - resource: "Shard"
      actions:
        - "emergency_reparent_shard"
        - "planned_reparent_shard"
      subjects: ["*"]
      clusters:
        - "local"
  orc_config.json: |
    {
      "Debug": true,
      "MySQLTopologyUser": "orc_client_user",
      "MySQLTopologyPassword": "orc_client_user_password",
      "MySQLReplicaUser": "vt_repl",
      "MySQLReplicaPassword": "",
      "RecoveryPeriodBlockSeconds": 5
    }
  ext_db_credentials_secret.json: |
    {
      "root": ["password"]
    }
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  ports:
    - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:5.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim
```

3. Create a table:

```SQL
create table customer(
  customer_id bigint not null auto_increment,
  email varbinary(128),
  primary key(customer_id)
) ENGINE=InnoDB;
```

4. Apply the following diff:

```diff
$ minikube -p parallel-test kubectl -- diff -f parallel_cluster_vttablet-update.yaml; date;
...
@@ -225,7 +225,7 @@
               extraFlags:
                 db_charset: utf8mb4_unicode_ci
                 log_queries_to_file: vt/vtdataroot/queries.log
                 # My Comment: This change itself doesn't mean anything. Just any change to trigger the rolling update.
-                queryserver-config-pool-size: "10"
+                queryserver-config-pool-size: "15"
               resources:
                 limits:
                   memory: 256Mi
Mon Mar 13 15:58:07 JST 2023
```

```sh
$ minikube -p parallel-test kubectl -- apply -f parallel_cluster_vttablet-update.yaml; date;
vitesscluster.planetscale.com/example configured
secret/example-cluster-config configured
persistentvolumeclaim/mysql-pv-claim unchanged
service/mysql unchanged
deployment.apps/mysql unchanged
Mon Mar 13 15:58:08 JST 2023
```

5. View error

```sh
$ minikube -p parallel-test kubectl -- port-forward --address localhost service/example-zone1-vtgate-bc6cde92 15306:3306
```

```sh
# Issue the query in whichever way you prefer
# ex. mysql -h 127.0.0.1 -P 15306 -u user --table --execute="select * from customer;"

2023-03-13 15:59:07.25799 +0900
#<Mysql2::Error::TimeoutError: [mysql_127.0.0.1:15306] Timeout waiting for a response from the last query. (waited 3 seconds)>

2023-03-13 15:59:11.282234 +0900
#<Mysql2::Error::TimeoutError: [mysql_127.0.0.1:15306] Timeout waiting for a response from the last query. (waited 3 seconds)>

2023-03-13 15:59:15.304278 +0900
#<Mysql2::Error: target: main.-.primary: vttablet: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.244.0.37:15999: connect: connection refused">

2023-03-13 15:59:18.287796 +0900
#<Mysql2::Error: target: main.-.primary: vttablet: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial tcp 10.244.0.37:15999: connect: connection refused">

2023-03-13 15:59:19.316975 +0900
#<Mysql2::Error: target: main.-.primary: vttablet: Connection Closed>
...
2023-03-13 15:59:35.7701 +0900
#<Mysql2::Error: target: main.-.primary: vttablet: Connection Closed>
```

```sh
$ watch -n 1 'mysql -h 127.0.0.1 -P 15306 -u user --table --execute="show vitess_tablets" | tee -a /tmp/vitess_tablets.txt; echo `date` | tee -a /tmp/vitess_tablets.txt'
...
+-------+----------+-------+------------+-------------+------------------+-------------+----------------------+
| Cell  | Keyspace | Shard | TabletType | State       | Alias            | Hostname    | PrimaryTermStartTime |
+-------+----------+-------+------------+-------------+------------------+-------------+----------------------+
| zone1 | main     | -     | PRIMARY    | SERVING     | zone1-4073072872 | 10.244.0.37 | 2023-03-13T06:58:09Z |
| zone1 | main     | -     | SPARE      | NOT_SERVING | zone1-1951951717 | 10.244.0.36 |                      |
+-------+----------+-------+------------+-------------+------------------+-------------+----------------------+
Mon Mar 13 15:59:07 JST 2023

# Start the errors
+-------+----------+-------+------------+-------------+------------------+-------------+----------------------+
| Cell  | Keyspace | Shard | TabletType | State       | Alias            | Hostname    | PrimaryTermStartTime |
+-------+----------+-------+------------+-------------+------------------+-------------+----------------------+
| zone1 | main     | -     | SPARE      | NOT_SERVING | zone1-1951951717 | 10.244.0.36 |                      |
| zone1 | main     | -     | SPARE      | NOT_SERVING | zone1-4073072872 | 10.244.0.37 |                      |
+-------+----------+-------+------------+-------------+------------------+-------------+----------------------+
Mon Mar 13 15:59:17 JST 2023
...
+-------+----------+-------+------------+-------------+------------------+-------------+----------------------+
| Cell  | Keyspace | Shard | TabletType | State       | Alias            | Hostname    | PrimaryTermStartTime |
+-------+----------+-------+------------+-------------+------------------+-------------+----------------------+
| zone1 | main     | -     | SPARE      | NOT_SERVING | zone1-1951951717 | 10.244.0.36 |                      |
| zone1 | main     | -     | SPARE      | NOT_SERVING | zone1-4073072872 | 10.244.0.37 |                      |
+-------+----------+-------+------------+-------------+------------------+-------------+----------------------+
Mon Mar 13 15:59:35 JST 2023

# Finish the errors
+-------+----------+-------+------------+-------------+------------------+-------------+----------------------+
| Cell  | Keyspace | Shard | TabletType | State       | Alias            | Hostname    | PrimaryTermStartTime |
+-------+----------+-------+------------+-------------+------------------+-------------+----------------------+
| zone1 | main     | -     | PRIMARY    | SERVING     | zone1-1951951717 | 10.244.0.38 | 2023-03-13T06:59:07Z |
| zone1 | main     | -     | SPARE      | NOT_SERVING | zone1-1951951717 | 10.244.0.36 |                      |
| zone1 | main     | -     | SPARE      | NOT_SERVING | zone1-4073072872 | 10.244.0.39 |                      |
+-------+----------+-------+------------+-------------+------------------+-------------+----------------------+
Mon Mar 13 15:59:36 JST 2023
```

### Binary Version

This issue can be reproduced in either version v15.0.1 or v16.0.0.

```sh
$ mysql -h 127.0.0.1 -P 15306 -u user --table 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 1
Server version: 5.7.9-vitess-15.0.1 Version: 15.0.1 (Git revision 13ee9c817638d59bebd6bc598f9d673a893c41cd branch 'heads/v15.0.1') built on Tue Nov 29 21:08:39 UTC 2022 by vitess@buildkitsandbox using go1.18.7 linux/amd64
```

OR

```sh
$ mysql -h 127.0.0.1 -P 15306 -u user --table 
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 244
Server version: 8.0.30-Vitess Version: 16.0.0 (Git revision bb768df0008fc09f7e6868a4fa571c32cc1cb526 branch 'heads/v16.0.0') built on Tue Feb 28 15:38:00 UTC 2023 by vitess@buildkitsandbox using go1.20.1 linux/amd64
```

### Operating System and Environment details

This issue can be reproduced in either version v15.0.1 (with planetscale/vitess-operator:v2.8.1) or v16.0.0 (with planetscale/vitess-operator:v2.9.0).

```sh
$ kubectl describe pods/example-zone1-vtgate-bc6cde92-5f479548d-7rzb4 | grep Image
    Image:         vitess/lite:v15.0.1
    Image ID:      docker-pullable://vitess/lite@sha256:9cf89b7948fa288ef43239ff57a74174bd0d981e760dd44316352daea8692dd4

$ kubectl describe pods/vitess-operator-557f797f86-sj9z8 | grep Image
    Image:         planetscale/vitess-operator:v2.8.1
    Image ID:      docker-pullable://planetscale/vitess-operator@sha256:5937ea75815332b1d8545bb49ee9c860f9006b8b1df358aa9be2b9fa3704d335
```

OR

```sh
$ kubectl describe pods/example-zone1-vtgate-bc6cde92-c76674cf8-phz7w | grep Image
    Image:         vitess/lite:v16.0.0
    Image ID:      docker-pullable://vitess/lite@sha256:ac0254e2f1c741536e3fb039a0c2ccb32db2ba82b1313c2c43503add3a7ada1d

$ kubectl describe pods/vitess-operator-84dbfdcd46-vm895 | grep Image
    Image:         planetscale/vitess-operator:v2.9.0
    Image ID:      docker-pullable://planetscale/vitess-operator@sha256:c8002219fe961f2d95e8c56c1af185b14a29b87847c86cfbdb8884dae73c7eaa
```

### Log Fragments

- https://gist.github.com/yoheimuta/c678cb7e5ea3453abe6ede3475e31e56

Here is a diagram that illustrates the sequence of events and their flow, as described in the above log.

BugReport_vttablet (2)

### PR DESCRIPTION
**Pull request by yoheimuta**
## Description

This PR ensures that the vtgate will route traffic to the new primary tablet without waiting for the `tabletRefreshInterval`.

This is to prevent situations where a new primary tablet for a shard has just been created and the `tableRefreshInterval` has not yet passed, causing an interruption where no primary is assigned to the shard.

## Related Issue(s)

- Fixes #12624

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go [hunk 1]
```diff
@@ -0,0 +1,243 @@
...
+
+	// update the new primary tablet to be read-write
+	err = clusterInstance.VtctlclientProcess.ExecuteCommand("SetReadWrite", tablet.Alias)
+	require.NoError(t, err)
+
+	// wait for the vtgate to finish updating the new primary tablet
+	time.Sleep(1 * time.Second)
+
+	// verify that the vtgate will recognize the new primary tablet
+	qr, _ := vtgateConn.ExecuteFetch("show vitess_tablets", 100, true)
```
Comment (yoheimuta) [inline go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:160]: If you run the test code with the slight modifications against the current main, the following output will be generated:

```
...
I0414 16:43:31.320373   87256 vtctlclient_process.go:210] Executing vtctlclient with command: vtctlclient --server localhost:6708 TabletExternallyReparented healthcheck_test_cell-0000009999 (attempt 1 of 10)
I0414 16:43:31.472102   87256 vtctlclient_process.go:210] Executing vtctlclient with command: vtctlclient --server localhost:6708 SetReadWrite healthcheck_test_cell-0000009999 (attempt 1 of 10)
    reparent_test.go:161: qr=[[VARCHAR("healthcheck_test_cell") VARCHAR("healthcheck_test_ks") VARCHAR("-80") VARCHAR("REPLICA") VARCHAR("NOT_SERVING") VARCHAR("healthcheck_test_cell-0000001336") VARCHAR("localhost") VARCHAR("")] [VARCHAR("healthcheck_test_cell") VARCHAR("healthcheck_test_ks") VARCHAR("80-") VARCHAR("PRIMARY") VARCHAR("SERVING") VARCHAR("healthcheck_test_cell-0000001337") VARCHAR("localhost") VARCHAR("2023-04-14T07:41:48Z")]]
    reparent_test.go:162:
                Error Trace:    /Users/yoheimuta/.go/vitess/go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:162
                Error:          Not equal:
                                expected: 3
                                actual  : 2
                Test:           TestHealthCheckExternallyReparentNewTablet
                Messages:       wrong number of tablet records in healthcheck, expected 3 but had 2
    reparent_test.go:164:
                Error Trace:    /Users/yoheimuta/.go/vitess/go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:164
                Error:          Not equal:
                                expected: "PRIMARY"
                                actual  : "REPLICA"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -PRIMARY
                                +REPLICA
                Test:           TestHealthCheckExternallyReparentNewTablet
    reparent_test.go:165:
                Error Trace:    /Users/yoheimuta/.go/vitess/go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:165
                Error:          Not equal:
                                expected: "SERVING"
                                actual  : "NOT_SERVING"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -SERVING
                                +NOT_SERVING
                Test:           TestHealthCheckExternallyReparentNewTablet
    reparent_test.go:166:
                Error Trace:    /Users/yoheimuta/.go/vitess/go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:166
                Error:          Not equal:
                                expected: "healthcheck_test_cell-0000009999"
                                actual  : "healthcheck_test_cell-0000001336"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -healthcheck_test_cell-0000009999
                                +healthcheck_test_cell-0000001336
                Test:           TestHealthCheckExternallyReparentNewTablet
I0414 16:43:42.524622   87256 mysqlctl_process.go:156] Shutting down MySQL: 1336

I0414 16:43:54.685033   87256 mysqlctl_process.go:175] MySQL shutdown complete: 1336
I0414 16:43:54.764293   87256 vtctlclient_process.go:210] Executing vtctlclient with command: vtctlclient --server localhost:6708 DeleteTablet healthcheck_test_cell-0000001336 (attempt 1 of 10)
    reparent_test.go:243: Deleted tablet: healthcheck_test_cell-0000001336
    reparent_test.go:175:
                Error Trace:    /Users/yoheimuta/.go/vitess/go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:175
                Error:          Received unexpected error:
                                target: healthcheck_test_ks.-80.primary: current keyspace is being resharded (errno 1105) (sqlstate HY000) during query: insert into customer(customer_id, email) values(2, 'dummy1')
                Test:           TestHealthCheckExternallyReparentNewTablet
--- FAIL: TestHealthCheckExternallyReparentNewTablet (93.68s)
```

Comment (yoheimuta) [reply go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:160]: When you run the same test code against the current branch:

```
...
reparent_test.go:225: Added tablet: healthcheck_test_cell-0000009999
I0414 17:05:59.561821   92542 vtctlclient_process.go:210] Executing vtctlclient with command: vtctlclient --server localhost:6708 TabletExternallyReparented healthcheck_test_cell-0000009999 (attempt 1 of 10)
I0414 17:05:59.755164   92542 vtctlclient_process.go:210] Executing vtctlclient with command: vtctlclient --server localhost:6708 SetReadWrite healthcheck_test_cell-0000009999 (attempt 1 of 10)
    reparent_test.go:161: qr=[ # NOTE: Inserted new lines manually
[VARCHAR("healthcheck_test_cell") VARCHAR("healthcheck_test_ks") VARCHAR("-80") VARCHAR("PRIMARY") VARCHAR("SERVING") VARCHAR("healthcheck_test_cell-0000009999") VARCHAR("localhost") VARCHAR("2023-04-14T08:05:59Z")] 
[VARCHAR("healthcheck_test_cell") VARCHAR("healthcheck_test_ks") VARCHAR("-80") VARCHAR("REPLICA") VARCHAR("NOT_SERVING") VARCHAR("healthcheck_test_cell-0000006955") VARCHAR("localhost") VARCHAR("")] 
[VARCHAR("healthcheck_test_cell") VARCHAR("healthcheck_test_ks") VARCHAR("80-") VARCHAR("PRIMARY") VARCHAR("SERVING") VARCHAR("healthcheck_test_cell-0000006956") VARCHAR("localhost") VARCHAR("2023-04-14T08:04:46Z")]
]
...
```

```
...
I0414 17:05:59.811311   93642 tablet_health_check.go:110] HealthCheckUpdate(Serving State): tablet: healthcheck_test_cell-6955 (localhost) serving true => false for healthcheck_test_ks/-80 (PRIMARY) reason: healthCheck update
I0414 17:05:59.814976   93642 healthcheck.go:509] We will have no health data for the next new primary tablet after demoting the tablet: healthcheck_test_cell-6955 (localhost), so start loading tablets now
I0414 17:05:59.835891   93642 healthcheck.go:382] Adding tablet to healthcheck: alias:{cell:"healthcheck_test_cell" uid:9999} hostname:"localhost" port_map:{key:"grpc" value:6722} port_map:{key:"vt" value:6721} keyspace:"healthcheck_test_ks" shard:"-80" key_range:{end:"\x80"} type:PRIMARY mysql_hostname:"localhost" mysql_port:6723 primary_term_start_time:{seconds:1681459559 nanoseconds:687021000} db_server_version:"5.7.39" default_conn_collation:255
I0414 17:05:59.837507   93642 tablet_health_check.go:110] HealthCheckUpdate(Serving State): tablet: healthcheck_test_cell-9999 (localhost) serving false => true for healthcheck_test_ks/-80 (PRIMARY) reason: healthCheck update
...
```

File: go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go [hunk 2]
```diff
@@ -0,0 +1,243 @@
...
+}
+
+// TestHealthCheckExternallyReparentNewTablet ensures that calling TabletExternallyReparented on a new tablet will switch the primary tablet
+// without having to wait for the tabletRefreshInterval.
+func TestHealthCheckExternallyReparentNewTablet(t *testing.T) {
+	ctx := context.Background()
+
+	// verify output of `show vitess_tablets` and `INSERT` statement
+	vtgateConn, err := mysql.Connect(ctx, &vtParams)
+	require.Nil(t, err)
```
Comment (mattlord) [inline go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:140]: Nit, but `require.NoError(t, err)` is more widely used and more explicit.

File: go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go [hunk 3]
```diff
@@ -0,0 +1,243 @@
...
+			Port: clusterInstance.VtgateMySQLPort,
+		}
+		return m.Run()
+	}()
+	os.Exit(exitCode)
+}
+
+// TestHealthCheckExternallyReparentNewTablet ensures that calling TabletExternallyReparented on a new tablet will switch the primary tablet
+// without having to wait for the tabletRefreshInterval.
+func TestHealthCheckExternallyReparentNewTablet(t *testing.T) {
```
Comment (mattlord) [inline go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:135]: Have you executed all of the new tests locally, at least 20 times in a row, to be sure it's not flaky?

File: go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go [hunk 4]
```diff
@@ -0,0 +1,243 @@
...
+	qr, err = vtgateConn.ExecuteFetch("insert into customer(customer_id, email) values(2, 'dummy1')", 100, true) // -80
+	require.EqualValues(t, 1, qr.RowsAffected)
+	require.NoError(t, err)
+}
+
+func tabletAlias(tabletUID int) string {
+	return fmt.Sprintf("%s-%010d", cell, tabletUID)
+}
+
+func addTablet(t *testing.T, tabletUID int, tabletType string) *cluster.Vttablet {
```
Comment (mattlord) [inline go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:181]: Is there anything unique about this function? I feel like we have other utilities we could use here instead.

File: go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go [hunk 5]
```diff
@@ -0,0 +1,243 @@
...
+		tablet.Type,
+		clusterInstance.TopoProcess.Port,
+		clusterInstance.Hostname,
+		clusterInstance.TmpDirectory,
+		clusterInstance.VtTabletExtraArgs,
+		clusterInstance.DefaultCharset)
+
+	// wait for mysqld to be ready
+	err = proc.Wait()
+	require.Nil(t, err)
```
Comment (mattlord) [inline go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:215]: Same note here and below about using NoError.

File: go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go [hunk 6]
```diff
@@ -0,0 +1,243 @@
...
+
+	tablet.VttabletProcess.ServingStatus = ""
+	err = tablet.VttabletProcess.Setup()
+	require.Nil(t, err)
+
+	serving := tablet.VttabletProcess.WaitForStatus("SERVING", time.Duration(60*time.Second))
+	assert.Equal(t, serving, true, "Tablet did not become ready within a reasonable time")
```
Comment (mattlord) [inline go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:222]: Any reason we're using assert here rather than require?

File: go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go [hunk 7]
```diff
@@ -0,0 +1,243 @@
...
+
+	t.Logf("Added tablet: %s", tablet.Alias)
+	return tablet
+}
+
+func deleteTablet(t *testing.T, tablet *cluster.Vttablet) {
```
Comment (mattlord) [inline go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:228]: This also feels like something used throughout the tests and maybe we can avoid adding another copy.

File: go/vt/discovery/healthcheck.go [hunk 8]
```diff
@@ -228,6 +229,9 @@ type HealthCheck interface {
 
 	// Unsubscribe removes a listener.
 	Unsubscribe(c chan *TabletHealth)
+
+	// LoadTabletsTrigger returns a channel that is used to inform when to load tablets.
+	LoadTabletsTrigger() chan struct{}
```
Comment (mattlord) [inline go/vt/discovery/healthcheck.go:234]: IMO, `GetLoadTabletsTrigger` is a better name.

**Review by mattlord — APPROVED** [review]
It makes sense to me. We should have @GuptaManan100 review though.

I had some minor comments that we can discuss, but will approve now since we need to wait for Manan anyway.

File: go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go (hunk 2 above)
Comment (yoheimuta) [reply go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go]: Fixed by [f2c1c7d](https://github.com/vitessio/vitess/pull/12893/commits/f2c1c7d716ad1de724ad4d676c26213a8cf1a3ed).

File: go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go (hunk 5 above)
Comment (yoheimuta) [reply go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go]: Fixed by [f2c1c7d](https://github.com/vitessio/vitess/pull/12893/commits/f2c1c7d716ad1de724ad4d676c26213a8cf1a3ed).

File: go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go (hunk 6 above)
Comment (yoheimuta) [reply go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go]: Fixed by [3b5799d](https://github.com/vitessio/vitess/pull/12893/commits/3b5799d390923c581653d87a0ae1b619707b281f).
I'm not particular about it. The reason is that I just referred to [the existing test](https://github.com/vitessio/vitess/blob/8c3e37c28bec8f76e818402127e8d37addf77867/go/test/endtoend/vtgate/tablet_healthcheck_cache/correctness_test.go#L217).

File: go/vt/discovery/healthcheck.go (hunk 8 above)
Comment (yoheimuta) [reply go/vt/discovery/healthcheck.go]: It makes perfectly sense.
Changed by [a710157](https://github.com/vitessio/vitess/pull/12893/commits/a7101571a76869bb0fb0f248553ed1b4a9235630).

File: go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go (hunk 4 above)
Comment (yoheimuta) [reply go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:180]: Can you tell me where I can find the common addTablet utility function? And, if it's not available, do you think it's a good idea to create a new utility function since I've referenced [the adjacent test file](https://github.com/vitessio/vitess/blob/8c3e37c28bec8f76e818402127e8d37addf77867/go/test/endtoend/vtgate/tablet_healthcheck_cache/correctness_test.go#L176) in the first place?

File: go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go (hunk 7 above)
Comment (yoheimuta) [reply go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:227]: I have the same question here: https://github.com/vitessio/vitess/pull/12893#discussion_r1179908022.

File: go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go (hunk 3 above)
Comment (yoheimuta) [reply go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:134]: I never experienced a test failure during development, but I hadn't executed it 20 times in a row until now. So I ran two trials (`./test_script.sh`), which failed on the ninth attempt each time. I assume it's due to the machine load.

Fixed by [db90a74](https://github.com/vitessio/vitess/pull/12893/commits/db90a743fed4fc3fd73646eb7136bd678a003f97). I confirmed that the code passed locally 20 times in a row. 
You can find the log: https://gist.github.com/yoheimuta/840f49dabdf4373fe8a91144e06590be.

<details>
<summary>test_script.sh</summary>

```bash
#!/bin/bash

# Set the log file name
logfile="test_results.log"

# Clean up the log file
rm -f "$logfile"

# Execute the test and clean-up commands 20 times
for i in {1..20}; do
  echo "Running test iteration $i" | tee -a "$logfile"

  # Test
  go test -v -count=1 -run "^TestHealthCheckExternallyReparentNewTablet$" vitess.io/vitess/go/test/endtoend/vtgate/tablet_healthcheck --alsologtostderr >> "$logfile" 2>&1
  exit_code=$?

  # Check the exit code and exit the loop if the test failed
  if [ $exit_code -ne 0 ]; then
    echo "Test failed on iteration $i, stopping the script" | tee -a "$logfile"
    break
  fi

  # Clean-up
  rm -f /var/folders/yj/0nkt3j750nz3x582dpf84r3w0000gn/T/endtoend.port
  rm -rf /Users/yoheimuta/.go/vitess/vtdataroot/vtroot_6701
  killall mysqld vtgate vttablet etcd2

  echo "Finished test iteration $i" | tee -a "$logfile"
  echo "-------------------------------------------------" | tee -a "$logfile"
done

echo "All test iterations completed" | tee -a "$logfile"
```
</details>

**Comment by yoheimuta** [comment]
@mattlord Thanks for the review! I've just finished responding to your comments.

**Review by GuptaManan100 — COMMENTED** [review]
The changes look good to me! It is probably a good idea to get another member from @vitessio/query-serving to take a look.

I had one more question. Does this problem arise only with `TabletExternallyReparented` or also with `PlannedReparentShard`?

**Comment by yoheimuta** [comment]
@GuptaManan100 Thanks for taking the time to review! 

> Does this problem arise only with TabletExternallyReparented or also with PlannedReparentShard?

That seems to be true, although I haven't seen it in production because our MySQL is managed externally.

When I ran the test case in this PR with slight modifications against the current main, I was able to reproduce the same problem with PlannedReparentShard. Here's the output that was generated:

```diff
diff --git a/go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go b/go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go
index dbc46bdda7..a9b8a173b3 100644
--- a/go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go
+++ b/go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go
@@ -141,16 +142,17 @@ func TestHealthCheckExternallyReparentNewTablet(t *testing.T) {

        // add a new tablet
        reparentTabletUID := 9999
-       reparentTabletType := "rdonly"
+       reparentTabletType := "replica"
        tablet := addTablet(t, reparentTabletUID, reparentTabletType)

        // promote the new tablet to the primary
-       err = clusterInstance.VtctlclientProcess.ExecuteCommand("TabletExternallyReparented", tablet.Alias)
+       err = clusterInstance.VtctlclientProcess.ExecuteCommand("PlannedReparentShard", "--", "--keyspace_shard", keyspaceName+"/"+shards[0], "--new_primary", tablet.Alias)
        require.NoError(t, err)

-        // update the new primary tablet to be read-write
-       err = clusterInstance.VtctlclientProcess.ExecuteCommand("SetReadWrite", tablet.Alias)
-       require.NoError(t, err)
```

```sh
# My Comment: FAILED
reparent_test.go:226: Added tablet: healthcheck_test_cell-0000009999
I0502 18:35:50.019849    2609 vtctlclient_process.go:210] Executing vtctlclient with command: vtctlclient --server localhost:6708 PlannedReparentShard -- --keyspace_shard healthcheck_test_ks/-80 --new_primary healthcheck_test_cell-0000009999 (attempt 1 of 10)
    reparent_test.go:163:
                Error Trace:    /Users/yoheimuta/.go/vitess/go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:163
                Error:          Not equal:
                                expected: 3
                                actual  : 2
                Test:           TestHealthCheckExternallyReparentNewTablet
                Messages:       wrong number of tablet records in healthcheck, expected 3 but had 2. Got result=&{[name:"Cell" type:VARCHAR charset:33 flags:1 name:"Keyspace" type:VARCHAR charset:33 flags:1 name:"Shard" type:VARCHAR charset:33 flags:1 name:"TabletType" type:VARCHAR charset:33 flags:1 name:"State" type:VARCHAR charset:33 flags:1 name:"Alias" type:VARCHAR charset:33 flags:1 name:"Hostname" type:VARCHAR charset:33 flags:1 name:"PrimaryTermStartTime" type:VARCHAR charset:33 flags:1] 0 0 
# My Comment: Inserted new lines manually
# My Comment: The vtgate has recognized the previous primary demotion but not the latest primary promotion, resulting in the -80 shard being without a primary tablet.
[
   [VARCHAR("healthcheck_test_cell") VARCHAR("healthcheck_test_ks") VARCHAR("-80") VARCHAR("REPLICA") VARCHAR("SERVING") VARCHAR("healthcheck_test_cell-0000007558") VARCHAR("localhost") VARCHAR("")]
   [VARCHAR("healthcheck_test_cell") VARCHAR("healthcheck_test_ks") VARCHAR("80-") VARCHAR("PRIMARY") VARCHAR("SERVING") VARCHAR("healthcheck_test_cell-0000007559") VARCHAR("localhost") VARCHAR("2023-05-02T09:34:39Z")]
]  2 }
    reparent_test.go:165:
                Error Trace:    /Users/yoheimuta/.go/vitess/go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:165
                Error:          Not equal:
                                expected: "PRIMARY"
                                actual  : "REPLICA"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -PRIMARY
                                +REPLICA
                Test:           TestHealthCheckExternallyReparentNewTablet
    reparent_test.go:167:
                Error Trace:    /Users/yoheimuta/.go/vitess/go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:167
                Error:          Not equal:
                                expected: "healthcheck_test_cell-0000009999"
                                actual  : "healthcheck_test_cell-0000007558"

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -healthcheck_test_cell-0000009999
                                +healthcheck_test_cell-0000007558
                Test:           TestHealthCheckExternallyReparentNewTablet
I0502 18:36:04.772983    2609 mysqlctl_process.go:157] Shutting down MySQL: 7558
I0502 18:36:16.037105    2609 mysqlctl_process.go:176] MySQL shutdown complete: 7558
I0502 18:36:16.108869    2609 vtctlclient_process.go:210] Executing vtctlclient with command: vtctlclient --server localhost:6708 DeleteTablet healthcheck_test_cell-0000007558 (attempt 1 of 10)
    reparent_test.go:244: Deleted tablet: healthcheck_test_cell-0000007558

# My Comment: vtgate failed to route the `INSERT` statement to the new primary tablet
    reparent_test.go:176:
                Error Trace:    /Users/yoheimuta/.go/vitess/go/test/endtoend/vtgate/tablet_healthcheck/reparent_test.go:176
                Error:          Received unexpected error:
                                target: healthcheck_test_ks.-80.primary: current keyspace is being resharded (errno 1105) (sqlstate HY000) during query: insert into customer(customer_id, email) values(2, 'dummy1')
                Test:           TestHealthCheckExternallyReparentNewTablet
--- FAIL: TestHealthCheckExternallyReparentNewTablet (95.31s)
FAIL
E0502 18:36:16.963298    2609 cluster_process.go:1032] Error in mysqlctl teardown wait: exit status 1
FAIL    vitess.io/vitess/go/test/endtoend/vtgate/tablet_healthcheck     125.399s
FAIL
```

When I ran this modified test code against the current branch:

```sh
# My Comment: PASSED
...
reparent_test.go:225: Added tablet: healthcheck_test_cell-0000009999
I0502 18:19:11.714629   95212 vtctlclient_process.go:210] Executing vtctlclient with command: vtctlclient --server localhost:6708 PlannedReparentShard -- --keyspace_shard healthcheck_test_ks/-80 --new_primary healthcheck_test_cell-0000009999 (attempt 1 of 10)
I0502 18:19:29.157709   95212 mysqlctl_process.go:157] Shutting down MySQL: 8431
I0502 18:19:41.530447   95212 mysqlctl_process.go:176] MySQL shutdown complete: 8431
I0502 18:19:41.635834   95212 vtctlclient_process.go:210] Executing vtctlclient with command: vtctlclient --server localhost:6708 DeleteTablet healthcheck_test_cell-0000008431 (attempt 1 of 10)
    reparent_test.go:243: Deleted tablet: healthcheck_test_cell-0000008431
--- PASS: TestHealthCheckExternallyReparentNewTablet (99.66s)
PASS
E0502 18:19:43.225517   95212 cluster_process.go:1032] Error in mysqlctl teardown wait: exit status 1
ok      vitess.io/vitess/go/test/endtoend/vtgate/tablet_healthcheck     130.870s
```

**Comment by harshit-gangal** [comment]
The changes look good. 
But, have you tried enabling vtgate buffering in production and see if that helps your use case?

**Comment by yoheimuta** [comment]
@harshit-gangal Thank you for the review!

> But, have you tried enabling vtgate buffering in production 

Nice point. Yes, we let the vitess-operator set the default parameters for [vtgate buffering](https://vitess.io/docs/14.0/reference/features/vtgate-buffering/#vtgate-flags-to-enable-buffering) as follows:

```sh
$ kubectl describe pods/cocalero-api-asianortheast1a-vtgate-6085c9ff-676897cd9c-84ppl | grep buffer
      --buffer_max_failover_duration=10s
      --buffer_min_time_between_failovers=20s
      --buffer_size=1000
      --enable_buffer=true
```

> and see if that helps your use case?

Partially. The feature can be helpful if the disruption is brief and ceases quickly. However, in our previous incident, the disruption lasted for 15 seconds, so the feature ended up draining all the buffered requests after 10 seconds had elapsed. Therefore, the feature doesn't help in such cases.

You can find the logs generated during the reproducible step, where the `tablet_refresh_interval` remains the default 1 minute, here: https://gist.github.com/yoheimuta/c678cb7e5ea3453abe6ede3475e31e56#file-vtgate-log-txt-L31.

**Review by harshit-gangal — APPROVED** [review]
