### PR TITLE
BugFix: Errant GTID detection for a single replica

### LINKED ISSUE #12023: Bug Report: ERS flags a single replica as having errant GTIDs
### Overview of the Issue

If ERS is called with a single replica being up, it is sometimes flagged as having errant GTIDs. This causes recovery to fail.

Consider this situation - 
1. There is a shard with 2 tablets. One is a primary and the other is a replica. The durability policy is none.
2. The replica tablet has been a primary at some point of time.
3. If the primary tablet crashes at this point of time, VTOrc will initiate a ERS. But the ERS will fail complaining the replica has errant GTIDs.

### Reproduction Steps

1. Run a cluster with 2 tablets of replica type, durability policy being none.
2. Reparent to the second tablet.
3. Shutdown the first one.
4. Watch VTOrc unable to repair the failure

### Binary Version

```sh
main and older releases
```

### Operating System and Environment details

```sh
all
```

### Log Fragments

```sh
I1229 13:02:53.210381   96905 topology_recovery.go:275] Analysis: DeadPrimary, deadprimary localhost:7112
I1229 13:02:53.210688   96905 topology_recovery.go:212] topology_recovery: will initiate emergency reparent shard in keyspace - ks, shard - 0
I1229 13:02:53.211391   96905 topology_recovery.go:212] topology_recovery: Getting a new durability policy for none
I1229 13:02:53.214101   96905 topology_recovery.go:212] topology_recovery: getting replication position from zone1-0000000100
I1229 13:02:53.214137   96905 topology_recovery.go:212] topology_recovery: getting replication position from zone1-0000000101
W1229 13:02:53.215014   96905 component.go:41] [core] grpc: addrConn.createTransport failed to connect to {localhost:7111 localhost:7111 <nil> <nil> 0 <nil>}. Err: connection error: desc = "transport: Error while dialing dial tcp [::1]:7111: connect: connection refused"
W1229 13:02:53.215553   96905 topology_recovery.go:289] ERS - failed to get replication status from zone1-0000000101: rpc error: code = Canceled desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp [::1]:7111: connect: connection refused"
I1229 13:02:53.215576   96905 topology_recovery.go:212] topology_recovery: failed to get replication status from zone1-0000000101: rpc error: code = Canceled desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp [::1]:7111: connect: connection refused"
E1229 13:02:53.215913   96905 replication.go:126] skipping zone1-0000000100 because we detected errant GTIDs - ba18ad8c-874a-11ed-b8b9-e7f414845b3c:1-46
```

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description

This PR fixes the issue raised in #12023. The errant GTID detection code has been fixed to not mark a single replica as errant.

## Related Issue(s)

- Fixes #12023 

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Documentation was added or is not required

### CODE REVIEW

**Comment by GuptaManan100** [comment]
After these changes, the unit test works, but the end to end test is still failing with 
```
=== RUN   TestSingleReplicaERS
    reparent_test.go:91: 
        	Error Trace:	/Users/manangupta/vitess/go/test/endtoend/reparent/newfeaturetest/reparent_test.go:91
        	Error:      	Received unexpected error:
        	            	exit status 1
        	Test:       	TestSingleReplicaERS
        	Messages:   	error in Emergency Reparent Shard output - W1229 15:11:58.375233    7733 main.go:96] W1229 09:41:58.375155 replication.go:270] failed to get replication status from zone1-0000000102: rpc error: code = Canceled desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: can't assign requested address"
        	            	EmergencyReparentShard Error: rpc error: code = Unknown desc = 1 replica(s) failed: tablet zone1-0000000102 SetReplicationSource failed: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: can't assign requested address": rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: can't assign requested address": tablet zone1-0000000102 SetReplicationSource failed: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: can't assign requested address": rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: can't assign requested address"
        	            	E1229 15:12:13.415378    7733 main.go:105] remote error: rpc error: code = Unknown desc = 1 replica(s) failed: tablet zone1-0000000102 SetReplicationSource failed: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: can't assign requested address": rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: can't assign requested address": tablet zone1-0000000102 SetReplicationSource failed: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: can't assign requested address": rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: can't assign requested address"
--- FAIL: TestSingleReplicaERS (70.66s)
```

The reason for this failure is that ERS only succeeds when one replica succeeds. But in this case, there is going to be no other replica. There is going to be just one tablet which is promoted to primary.

File: go/mysql/replication_status.go [hunk 1]
```diff
@@ -179,6 +179,11 @@ func ProtoToReplicationStatus(s *replicationdatapb.Status) ReplicationStatus {
 // provided as a list of ReplicationStatus's. This method only works if the flavor for all retrieved ReplicationStatus's is MySQL.
 // The result is returned as a Mysql56GTIDSet, each of whose elements is a found errant GTID.
 func (s *ReplicationStatus) FindErrantGTIDs(otherReplicaStatuses []*ReplicationStatus) (Mysql56GTIDSet, error) {
+	if len(otherReplicaStatuses) == 0 {
+		// If there is nothing to compare this replica against, then we must assume that its GTID set is the correct one.
+		return nil, nil
+	}
```
Comment (mattlord) [inline go/mysql/replication_status.go:185]: I think that we should note/comment that this function:
  - Is best effort (in this new case we can't know)
  - Can return false positives: not all replicas' IO threads will be in sync and `s` may simply be further ahead and have a larger `Retrieved_Gtid_Set`
      - This is true even with semi-sync as we only require 1 ACKer by default AFAIK 
  - Thus should only be used when the old primary is no longer available (ERS) as comparing the replica with the old primary is the only sure way to check for errant GTIDs

Make sense, or am I missing something(s)?

File: go/test/endtoend/reparent/newfeaturetest/reparent_test.go [hunk 2]
```diff
@@ -55,3 +55,43 @@ func TestRecoverWithMultipleVttabletFailures(t *testing.T) {
...
+// replica is one such that it was a primary itself before. This way its executed gtid set
+// will have atleast 2 tablets in it. We want to make sure this tablet is not marked as errant
+// and ERS succeeds.
+func TestSingleReplicaERS(t *testing.T) {
+	// Set up a cluster with none durability policy
+	defer cluster.PanicHandler(t)
+	clusterInstance := utils.SetupReparentCluster(t, "none")
+	defer utils.TeardownCluster(clusterInstance)
+	tablets := clusterInstance.Keyspaces[0].Shards[0].Vttablets
+	// Confirm that the replication is setup correctly in the beginning
```
Comment (mattlord) [inline go/test/endtoend/reparent/newfeaturetest/reparent_test.go:70]: Probably worth a comment that tablets[0] is the PRIMARY at this point, although the code shows it.

Comment (mattlord) [reply go/test/endtoend/reparent/newfeaturetest/reparent_test.go:70]: Also a note that the reparent endtoend tests — and endtoend tests in general — will become problematic at some point if they are always growing. Would be great, IMO, if we could find way to rely more on unit tests.  Is the unit test not enough in this case?

**Review by mattlord — APPROVED** [review]
LGTM. I had a few comments/requests, but nothing blocking.

File: go/mysql/replication_status.go (hunk 1 above)
Comment (rsajwani) [reply go/mysql/replication_status.go:185]: yeah same comment, this can result in data loss .. are we ok with that..

**Review by rsajwani — APPROVED** [review]

**Comment by mattlord** [comment]
> After these changes, the unit test works, but the end to end test is still failing with
> 
> ```
> === RUN   TestSingleReplicaERS
>     reparent_test.go:91: 
>         	Error Trace:	/Users/manangupta/vitess/go/test/endtoend/reparent/newfeaturetest/reparent_test.go:91
>         	Error:      	Received unexpected error:
>         	            	exit status 1
>         	Test:       	TestSingleReplicaERS
>         	Messages:   	error in Emergency Reparent Shard output - W1229 15:11:58.375233    7733 main.go:96] W1229 09:41:58.375155 replication.go:270] failed to get replication status from zone1-0000000102: rpc error: code = Canceled desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: can't assign requested address"
>         	            	EmergencyReparentShard Error: rpc error: code = Unknown desc = 1 replica(s) failed: tablet zone1-0000000102 SetReplicationSource failed: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: can't assign requested address": rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: can't assign requested address": tablet zone1-0000000102 SetReplicationSource failed: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: can't assign requested address": rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: can't assign requested address"
>         	            	E1229 15:12:13.415378    7733 main.go:105] remote error: rpc error: code = Unknown desc = 1 replica(s) failed: tablet zone1-0000000102 SetReplicationSource failed: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: can't assign requested address": rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: can't assign requested address": tablet zone1-0000000102 SetReplicationSource failed: rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: can't assign requested address": rpc error: code = DeadlineExceeded desc = latest balancer error: connection error: desc = "transport: Error while dialing dial tcp :0: connect: can't assign requested address"
> --- FAIL: TestSingleReplicaERS (70.66s)
> ```
> 
> The reason for this failure is that ERS only succeeds when one replica succeeds. But in this case, there is going to be no other replica. There is going to be just one tablet which is promoted to primary.

Just noting that we discussed this on a call and believe the right thing to do here is account for the case where there's only 1 replica and support this ERS scenario — since 1 primary and 1 replica is not uncommon or unsupported. Then the new endtoend test should pass and we can merge.

@GuptaManan100 let me know if you want a re-review and I'll quickly take a look. Thanks!

File: go/test/endtoend/reparent/newfeaturetest/reparent_test.go (hunk 2 above)
Comment (GuptaManan100) [reply go/test/endtoend/reparent/newfeaturetest/reparent_test.go:70]: The unit test passes and the end to end test fails, so I'll say no. Maybe I can add a couple more unit tests. In general, I merge some of these tests after 1 release. i.e. we already have tests that test reparenting, I can do this as part of a different test, in the ers package, the only reason I don't is because those tests also run in upgrade-downgrade and this one would fail there.

File: go/mysql/replication_status.go (hunk 1 above)
Comment (GuptaManan100) [reply go/mysql/replication_status.go:185]: I'll add a comment but there won't be false positives or rather there shouldn't be. The function doesn't mark the GTIDs as errant if they come from the current primary. It can miss some GTIDs which are errant, but not the other way around.

Comment (GuptaManan100) [reply go/mysql/replication_status.go:186]: Added a comment.

**Comment by GuptaManan100** [comment]
@mattlord As discussed, I have patched ERS to allow for this specific case where there are a total of 2 replicas. The end-to-end test now works. 🙇

File: go/vt/vtctl/reparentutil/emergency_reparenter.go [hunk 3]
```diff
@@ -609,6 +609,12 @@ func (erp *EmergencyReparenter) reparentReplicas(
 			// we're going to be explicit that this is doubly unexpected.
 			return nil, vterrors.Wrapf(rec.Error(), "received more errors (= %d) than replicas (= %d), which should be impossible: %v", errCount, numReplicas, rec.Error())
 		case errCount == numReplicas:
+			if len(tabletMap) <= 2 {
+				// If there are atmost 2 tablets in the tablet map, we shouldn't be failing the promotion if the replica fails to SetReplicationSource.
```
Comment (mattlord) [inline go/vt/vtctl/reparentutil/emergency_reparenter.go:613]: Two minor typos:
```
// If there are at most 2 tablets in the tablet map, we shouldn't be failing the promotion if the replica fails to SetReplicationSource.
// The failing replica is probably the old primary that is down, so it is okay if it fails. We still log a warning message in the logs.
```

I'll leave it up to you if it's worth another CI run 🙂

File: go/vt/vtctl/reparentutil/emergency_reparenter.go [hunk 4]
```diff
@@ -609,6 +609,12 @@ func (erp *EmergencyReparenter) reparentReplicas(
...
+				// The failing replica is probably the old primary that is down, so it is okay if if fails. We still log a warning message in the logs.
+				erp.logger.Warningf("The only replica failed to set replication source: %v", rec.Error())
```
Comment (mattlord) [inline go/vt/vtctl/reparentutil/emergency_reparenter.go:615]: As a user, I don't think I'd understand the issue here. I'd recommend something like this:
```
erp.logger.Warningf("Failed to set the MySQL replication source during ERS but because there is only one other tablet we assume it is the one that had failed and will progress with the reparent. Error: %v", rec.Error())
```

**Review by mattlord — APPROVED** [review]
Thanks! ❤️ I had a couple of minor comments, but will leave those up to you to decide on.

File: go/vt/vtctl/reparentutil/emergency_reparenter.go (hunk 3 above)
Comment (GuptaManan100) [reply go/vt/vtctl/reparentutil/emergency_reparenter.go]: Fixed.

File: go/vt/vtctl/reparentutil/emergency_reparenter.go (hunk 4 above)
Comment (GuptaManan100) [reply go/vt/vtctl/reparentutil/emergency_reparenter.go]: Fixed

**Review by deepthi — APPROVED** [review]

**Review by rsajwani — APPROVED** [review]
