### PR TITLE
Fix TestSelectScatterPartialOLAP data race

### LINKED ISSUE #18996: Bug Report: `TestSelectScatterPartialOLAP` data race
### Overview of the Issue

When I run `make unit_test_race` after `source dev.env`, I see a data race warning from `TestSelectScatterPartialOLAP`

### Reproduction Steps

```sh
$ source dev.env
$ make unit_test_race
```

### Binary Version

```sh
$ git log --oneline
562b8b6a02 (HEAD -> main, origin/main, origin/HEAD) planner: allow pushdown of window functions partitioned by unique vindex (#18903)
ea7f6b1195 Remove old GC table name format (#18981)
1f492101ab vdiff: do not sort by table name in summary, it is not necessary (#18972)
```

### Operating System and Environment details

```sh
$ cat /etc/os-release
PRETTY_NAME="Ubuntu 24.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="24.04"
VERSION="24.04.3 LTS (Noble Numbat)"
VERSION_CODENAME=noble
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=noble
LOGO=ubuntu-logo

$ uname -sr
Linux 6.8.0-87-generic

$ uname -m
x86_64
```

### Log Fragments

```go
==================
WARNING: DATA RACE
Write at 0x00c000a58068 by goroutine 1668:
  vitess.io/vitess/go/vt/vtgate/executorcontext.(*SafeSession).ResetTx()
      /home/zq2/vitess/go/vt/vtgate/executorcontext/safe_session.go:170 +0x585
  vitess.io/vitess/go/vt/vtgate.(*TxConn).Rollback.deferwrap1()
      /home/zq2/vitess/go/vt/vtgate/tx_conn.go:415 +0x33
  runtime.deferreturn()
      /usr/local/go/src/runtime/panic.go:589 +0x5d
  vitess.io/vitess/go/vt/vtgate.(*ScatterConn).multiGoTransaction()
      /home/zq2/vitess/go/vt/vtgate/scatter_conn.go:745 +0x5ee
  vitess.io/vitess/go/vt/vtgate.(*ScatterConn).StreamExecuteMulti()
      /home/zq2/vitess/go/vt/vtgate/scatter_conn.go:405 +0x584
  vitess.io/vitess/go/vt/vtgate.(*Executor).StreamExecuteMulti()
      /home/zq2/vitess/go/vt/vtgate/executor.go:1661 +0x156
  vitess.io/vitess/go/vt/vtgate/executorcontext.(*VCursorImpl).StreamExecuteMulti()
      /home/zq2/vitess/go/vt/vtgate/executorcontext/vcursor_impl.go:886 +0x57c
  vitess.io/vitess/go/vt/vtgate/engine.(*shardRoute).StreamExecute()
      /home/zq2/vitess/go/vt/vtgate/engine/shard_route.go:42 +0x243
  vitess.io/vitess/go/vt/vtgate/engine.runOneStream.func1()
      /home/zq2/vitess/go/vt/vtgate/engine/merge_sort.go:232 +0x2a5

Previous read at 0x00c000a58068 by goroutine 1671:
  vitess.io/vitess/go/vt/vtgate.(*TxConn).Rollback()
      /home/zq2/vitess/go/vt/vtgate/tx_conn.go:417 +0x108
  vitess.io/vitess/go/vt/vtgate.(*ScatterConn).multiGoTransaction()
      /home/zq2/vitess/go/vt/vtgate/scatter_conn.go:745 +0x5ee
  vitess.io/vitess/go/vt/vtgate.(*ScatterConn).StreamExecuteMulti()
      /home/zq2/vitess/go/vt/vtgate/scatter_conn.go:405 +0x584
  vitess.io/vitess/go/vt/vtgate.(*Executor).StreamExecuteMulti()
      /home/zq2/vitess/go/vt/vtgate/executor.go:1661 +0x156
  vitess.io/vitess/go/vt/vtgate/executorcontext.(*VCursorImpl).StreamExecuteMulti()
      /home/zq2/vitess/go/vt/vtgate/executorcontext/vcursor_impl.go:886 +0x57c
  vitess.io/vitess/go/vt/vtgate/engine.(*shardRoute).StreamExecute()
      /home/zq2/vitess/go/vt/vtgate/engine/shard_route.go:42 +0x243
  vitess.io/vitess/go/vt/vtgate/engine.runOneStream.func1()
      /home/zq2/vitess/go/vt/vtgate/engine/merge_sort.go:232 +0x2a5

Goroutine 1668 (running) created at:
  vitess.io/vitess/go/vt/vtgate/engine.runOneStream()
      /home/zq2/vitess/go/vt/vtgate/engine/merge_sort.go:228 +0x2cc
  vitess.io/vitess/go/vt/vtgate/engine.(*MergeSort).TryStreamExecute()
      /home/zq2/vitess/go/vt/vtgate/engine/merge_sort.go:78 +0x2e4
  vitess.io/vitess/go/vt/vtgate/executorcontext.(*VCursorImpl).StreamExecutePrimitive()
      /home/zq2/vitess/go/vt/vtgate/executorcontext/vcursor_impl.go:789 +0x2d8
  vitess.io/vitess/go/vt/vtgate/engine.(*Route).mergeSort()
      /home/zq2/vitess/go/vt/vtgate/engine/route.go:315 +0x536
  vitess.io/vitess/go/vt/vtgate/engine.(*Route).streamExecuteShards()
      /home/zq2/vitess/go/vt/vtgate/engine/route.go:277 +0x547
  vitess.io/vitess/go/vt/vtgate/engine.(*Route).TryStreamExecute()
      /home/zq2/vitess/go/vt/vtgate/engine/route.go:220 +0x21c
  vitess.io/vitess/go/vt/vtgate/executorcontext.(*VCursorImpl).StreamExecutePrimitive()
      /home/zq2/vitess/go/vt/vtgate/executorcontext/vcursor_impl.go:789 +0x2d8
  vitess.io/vitess/go/vt/vtgate.(*Executor).StreamExecute.func1()
      /home/zq2/vitess/go/vt/vtgate/executor.go:365 +0x519
  vitess.io/vitess/go/vt/vtgate.(*Executor).newExecute()
      /home/zq2/vitess/go/vt/vtgate/plan_execute.go:176 +0xbfd
  vitess.io/vitess/go/vt/vtgate.(*Executor).StreamExecute()
      /home/zq2/vitess/go/vt/vtgate/executor.go:402 +0x76e
  vitess.io/vitess/go/vt/vtgate.executorStream()
      /home/zq2/vitess/go/vt/vtgate/executor_framework_test.go:338 +0x24f
  vitess.io/vitess/go/vt/vtgate.TestSelectScatterPartialOLAP()
      /home/zq2/vitess/go/vt/vtgate/executor_select_test.go:1804 +0xf18
  vitess.io/vitess/go/vt/vtgate.TestSelectScatterPartialOLAP()
      /home/zq2/vitess/go/vt/vtgate/executor_select_test.go:1772 +0x6c4
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1934 +0x21c
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1997 +0x44

Goroutine 1671 (running) created at:
  vitess.io/vitess/go/vt/vtgate/engine.runOneStream()
      /home/zq2/vitess/go/vt/vtgate/engine/merge_sort.go:228 +0x2cc
  vitess.io/vitess/go/vt/vtgate/engine.(*MergeSort).TryStreamExecute()
      /home/zq2/vitess/go/vt/vtgate/engine/merge_sort.go:78 +0x2e4
  vitess.io/vitess/go/vt/vtgate/executorcontext.(*VCursorImpl).StreamExecutePrimitive()
      /home/zq2/vitess/go/vt/vtgate/executorcontext/vcursor_impl.go:789 +0x2d8
  vitess.io/vitess/go/vt/vtgate/engine.(*Route).mergeSort()
      /home/zq2/vitess/go/vt/vtgate/engine/route.go:315 +0x536
  vitess.io/vitess/go/vt/vtgate/engine.(*Route).streamExecuteShards()
      /home/zq2/vitess/go/vt/vtgate/engine/route.go:277 +0x547
  vitess.io/vitess/go/vt/vtgate/engine.(*Route).TryStreamExecute()
      /home/zq2/vitess/go/vt/vtgate/engine/route.go:220 +0x21c
  vitess.io/vitess/go/vt/vtgate/executorcontext.(*VCursorImpl).StreamExecutePrimitive()
      /home/zq2/vitess/go/vt/vtgate/executorcontext/vcursor_impl.go:789 +0x2d8
  vitess.io/vitess/go/vt/vtgate.(*Executor).StreamExecute.func1()
      /home/zq2/vitess/go/vt/vtgate/executor.go:365 +0x519
  vitess.io/vitess/go/vt/vtgate.(*Executor).newExecute()
      /home/zq2/vitess/go/vt/vtgate/plan_execute.go:176 +0xbfd
  vitess.io/vitess/go/vt/vtgate.(*Executor).StreamExecute()
      /home/zq2/vitess/go/vt/vtgate/executor.go:402 +0x76e
  vitess.io/vitess/go/vt/vtgate.executorStream()
      /home/zq2/vitess/go/vt/vtgate/executor_framework_test.go:338 +0x24f
  vitess.io/vitess/go/vt/vtgate.TestSelectScatterPartialOLAP()
      /home/zq2/vitess/go/vt/vtgate/executor_select_test.go:1804 +0xf18
  vitess.io/vitess/go/vt/vtgate.TestSelectScatterPartialOLAP()
      /home/zq2/vitess/go/vt/vtgate/executor_select_test.go:1772 +0x6c4
  testing.tRunner()
      /usr/local/go/src/testing/testing.go:1934 +0x21c
  testing.(*T).Run.gowrap1()
      /usr/local/go/src/testing/testing.go:1997 +0x44
```

### PR DESCRIPTION
**Pull request by Devanshusharma2005**
## Description

This PR fixes a potential race condition in vtgate where multiple goroutines may access or mutate `PreSessions`, `ShardSessions`, and `PostSessions` concurrently during `Rollback`, `Release`, or `ReleaseAll`.  

Previously, these flows directly iterated over session slice fields without taking a stable snapshot. If another goroutine modified those slices at the same time, it could lead to a data race.  

This change introduces safe snapshot helpers on `SafeSession` and updates the relevant call sites to use them, ensuring that Rollback, Release, and ReleaseAll work on a stable copy of the session slices.  

The race was detected in the unit test `TestSelectScatterPartialOLAP`, which would occasionally fail with `-race` enabled.

## Related Issue(s)

Fixes #18996

## BEFORE

image

## AFTER 

Screenshot 2026-02-15 at 4 00 11 PM

### Reproduction Steps

To reproduce the race condition in `TestSelectScatterPartialOLAP`, run the test multiple times with the race detector enabled:

```bash
source dev.env
go clean -testcache
cnt=0
while [[ $cnt -lt 200 ]]; do
  echo "Run $cnt"
  go test -count=1 -race -timeout 30s \
    -run ^TestSelectScatterPartialOLAP$ \
    vitess.io/vitess/go/vt/vtgate || break
  cnt=$((cnt+1))
done
```

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on CI?
-   [ ] Documentation was added or is not required

### AI Disclosure

Used grep command to trace the function calls and map out the flow, then manually patched the logic (kept it simple since it's a small change.)

### CODE REVIEW

File: go/vt/vtgate/executorcontext/safe_session.go [hunk 1]
```diff
@@ -419,6 +419,44 @@ func (session *SafeSession) InTransaction() bool {
...
+
+func (session *SafeSession) GetShardSessionsForCleanup() []*vtgatepb.Session_ShardSession {
+	session.mu.Lock()
+	defer session.mu.Unlock()
+	totalSize := len(session.PreSessions) + len(session.ShardSessions) + len(session.PostSessions)
+	shardSessions := make([]*vtgatepb.Session_ShardSession, 0, totalSize)
+	shardSessions = append(shardSessions, session.PreSessions...)
+	shardSessions = append(shardSessions, session.ShardSessions...)
+	shardSessions = append(shardSessions, session.PostSessions...)
+	return shardSessions
```
Comment (arthurschreiber) [inline go/vt/vtgate/executorcontext/safe_session.go]: What do you think about `slices.Concat`?


```suggestion

	return slices.Concat(session.PreSessions, session.ShardSessions, session.PostSession)
```

File: go/vt/vtgate/executorcontext/safe_session.go [hunk 2]
```diff
@@ -419,6 +419,44 @@ func (session *SafeSession) InTransaction() bool {
...
+		totalSize = baseSize + 1
+	}
+	allShardSessions := make([]*vtgatepb.Session_ShardSession, 0, totalSize)
+	allShardSessions = append(allShardSessions, session.PreSessions...)
+	allShardSessions = append(allShardSessions, session.ShardSessions...)
+	allShardSessions = append(allShardSessions, session.PostSessions...)
+	if session.LockSession != nil {
+		allShardSessions = append(allShardSessions, session.LockSession)
+	}
+	return allShardSessions
```
Comment (arthurschreiber) [inline go/vt/vtgate/executorcontext/safe_session.go]: Here as well:


```suggestion

	var lockSessions []*vtgatepb.Session_ShardSession
	if session.LockSession != nil {
		lockSessions = []*vtgatepb.Session_ShardSession{session.LockSession}
	}
	return slices.Concat(session.PreSessions, session.ShardSessions, session.PostSessions, lockSessions)
```

File: go/vt/vtgate/executorcontext/safe_session.go (hunk 1 above)
Comment (Devanshusharma2005) [reply go/vt/vtgate/executorcontext/safe_session.go]: Ah yes. Basically append is good for when we have to add few elements in a slice
and concat for combining the slices. Tho concat does slightly more allocations (but ig this is the tradeoff we can do here against the messy code of append).
Improving it.

File: go/vt/vtgate/executorcontext/safe_session.go [hunk 3]
```diff
@@ -419,6 +420,32 @@ func (session *SafeSession) InTransaction() bool {
...
+	session.mu.Lock()
+	defer session.mu.Unlock()
+
+	allSessions := slices.Concat(session.PreSessions, session.ShardSessions, session.PostSessions)
+	if session.LockSession != nil {
+		return append(allSessions, session.LockSession)
+	}
+	return allSessions
+}
+
```
Comment (Devanshusharma2005) [inline go/vt/vtgate/executorcontext/safe_session.go:444]: Applied your first suggestion here now.

**Comment by arthurschreiber** [comment]
> Tho concat does slightly more allocations (but ig this is the tradeoff we can do here against the messy code of append).

@Devanshusharma2005 I don't think that's right. You can see how concat is implemented here: https://cs.opensource.google/go/go/+/refs/tags/go1.26.0:src/slices/slices.go;l=489-505

Essentially, it gets the full length required for the final slice, then allocates that slice and appends into it. Basically exactly what you did before. So it doesn't perform any additional allocations.

File: go/vt/vtgate/executorcontext/safe_session.go [hunk 4]
```diff
@@ -419,6 +420,32 @@ func (session *SafeSession) InTransaction() bool {
...
+func (session *SafeSession) GetShardSessionsForReleaseAll() []*vtgatepb.Session_ShardSession {
+	session.mu.Lock()
+	defer session.mu.Unlock()
+
+	allSessions := slices.Concat(session.PreSessions, session.ShardSessions, session.PostSessions)
+	if session.LockSession != nil {
+		return append(allSessions, session.LockSession)
+	}
+	return allSessions
```
Comment (arthurschreiber) [inline go/vt/vtgate/executorcontext/safe_session.go]: Depending on the sizes of the sessions being concatenated, the `append` call might end up allocating a new slice.

It's better if you do this:


```suggestion
    lockSessions := make([]*vtgatepb.Session_ShardSession, 0, 1)
	if session.LockSession != nil {
		lockSessions = append(lockSessions, session.LockSession)
	}
	return slices.Concat(session.PreSessions, session.ShardSessions, session.PostSessions, lockSessions)
```

As we specify the capacity of `lockSessions`, the `append` call on it won't cause any allocations. And `lockSessions` will not be allocated on the heap, but on the stack (so it will be extremely cheap).

The whole operation will thus only allocate one slice on the heap - the one that ends up being returned.

**Comment by arthurschreiber** [comment]
@Devanshusharma2005 👋 Hey, I left a few more comments. I'm not sure the code here warrants being so performance focused, but I think it's a good learning opportunity to better understand how to make changes with a performance focus in mind.

**Comment by Devanshusharma2005** [comment]
> @Devanshusharma2005 👋 Hey, I left a few more comments. I'm not sure the code here warrants being so performance focused, but I think it's a good learning opportunity to better understand how to make changes with a performance focus in mind.

Hi arthur. Thank you so much for these reviews.
They are helping me to focus more on such details. 
I'll commit the fix soon.

File: go/vt/vtgate/executorcontext/safe_session.go (hunk 4 above)
Comment (Devanshusharma2005) [reply go/vt/vtgate/executorcontext/safe_session.go]: okay i got it. Basically that append can cause the reallocation.

**Comment by Devanshusharma2005** [comment]
@arthurschreiber I’ve implemented your first `slices.Concat` recommendation for `GetShardSessionsForReleaseAll`. This helped me better understand how `slices.Concat` guarantees a single allocation and avoids the potential reallocation that could happen when appending after an exact capacity slice. 
If there are any further improvements or refinements you’d suggest, I’d be happy to incorporate them.

File: go/vt/vtgate/executorcontext/safe_session.go [hunk 5]
```diff
@@ -419,6 +420,32 @@ func (session *SafeSession) InTransaction() bool {
 	return session.Session.InTransaction
 }
 
+// We take and return a snapshot of PreSessions, ShardSessions, and PostSessions
+// because multiple goroutines might access or mutate these slices at the same time,
+// which can lead to a race condition. This snapshot is used by Rollback/Release
+// so they can safely work on a stable copy without holding the lock.
+
+func (session *SafeSession) GetShardSessionsForCleanup() []*vtgatepb.Session_ShardSession {
```
Comment (mhamza15) [inline go/vt/vtgate/executorcontext/safe_session.go]: Let's try to follow Go doc guidelines: https://go.dev/doc/comment. Applies to other parts below as well.

Comment (mhamza15) [reply go/vt/vtgate/executorcontext/safe_session.go]: Also, smaller nit, feel free to ignore: https://go.dev/doc/effective_go#Getters

**Comment by Devanshusharma2005** [comment]
@arthurschreiber lets get this across the finish line ^^
