### PR TITLE
`EmergencyReparentShard`: small observability and correctness fixes

### LINKED ISSUE #19850: Bug Report: EmergencyReparentShard: observability gaps and sort contract violation
### Overview of the Issue

3 x minor quality issues found in the ERS code:

#### 1. Silent candidate filtering in `findErrantGTIDs()`

In [`emergency_reparenter.go` line 909](https://github.com/vitessio/vitess/blob/main/go/vt/vtctl/reparentutil/emergency_reparenter.go#L909), candidates with nil or zero `*RelayLogPositions` are silently skipped during errant GTID detection with no log message. Operators have no visibility into why a candidate was excluded

```go
if candidatePositions == nil || candidatePositions.IsZero() {
    continue // no log — candidate silently dropped
}
```

#### 2. `fmt.Errorf` instead of `vterrors.Wrapf` in cleanup error

In [`emergency_reparenter.go` line 194](https://github.com/vitessio/vitess/blob/main/go/vt/vtctl/reparentutil/emergency_reparenter.go#L194), the restart replication cleanup failure uses `fmt.Errorf` instead of `vterrors.Wrapf`, which loses the structured error code that the rest of the ERS code path uses

```go
err = fmt.Errorf("%w, and restart replication cleanup failed: %v", err, cleanupErr)
```

#### 3. `reparentSorter.Less()` violates `sort.Sort` contract

In [`reparent_sorter.go` line 102](https://github.com/vitessio/vitess/blob/main/go/vt/vtctl/reparentutil/reparent_sorter.go#L102), when all tiebreakers are exhausted _(same GTIDs, same promotion rules, same InnoDB buffer pool)_, the final fallback is:

```go
return !jPromotionRule.BetterThan(iPromotionRule)
```

Since `BetterThan` uses strict `<`, equal promotion rules return `false`, making this `!false` = `true`. This means `Less(i, j)` AND `Less(j, i)` both return `true` — violating the strict weak ordering contract required by `sort.Sort`. This makes ERS candidate selection non-deterministic for equal candidates

### Reproduction Steps

1. Code review of the affected lines
2. For the sort issue: sort 3 x replicas with identical GTIDs, promotion rules, and no InnoDB buffer pool data — observe non-deterministic ordering across runs

### Binary Version

`main` branch

### Operating System and Environment details

All platforms

### Log Fragments

N/A — these are code-level issues found during review

### PR DESCRIPTION
**Pull request by timvaillancourt**
## Description

3 x small fixes for ERS observability and correctness:

1. **Silent candidate filtering** — `findErrantGTIDs()` silently skipped candidates with nil/zero positions during errant GTID detection. Added a `log.Warn` so operators can see why a candidate was excluded

2. **`fmt.Errorf` → `vterrors.Wrapf`** — The restart replication cleanup error in `reparentShardLocked()` was using `fmt.Errorf`, which loses the structured error code that the rest of the ERS code path uses

3. **Sort contract violation** — `reparentSorter.Less()` violated `sort.Sort`'s strict weak ordering contract when all tiebreakers were exhausted _(same GTIDs, same promotion rules, same buffer pool)_. Both `Less(i, j)` and `Less(j, i)` returned `true`, making candidate selection non-deterministic. Added tablet UID as a stable final tiebreaker

## Related Issue(s)

Fixes #19850

## Checklist

- [x] "Backport to:" labels have been added if this change should be back-ported to release branches
- [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
- [x] Tests were added or are not required
- [x] Did the new or modified tests pass consistently locally and on CI?
- [x] Documentation was added or is not required

## Deployment Notes

N/A

### AI Disclosure

Claude Code assisted with development. Claude prepared this PR summary

### CODE REVIEW

File: go/vt/vtctl/reparentutil/reparent_sorter.go [hunk 1]
```diff
@@ -99,7 +99,13 @@ func (rs *reparentSorter) Less(i, j int) bool {
 		}
 	}
 
-	return !jPromotionRule.BetterThan(iPromotionRule)
+	if jPromotionRule != iPromotionRule {
+		return !jPromotionRule.BetterThan(iPromotionRule)
+	}
+
+	// All else equal, use tablet UID as a stable tiebreaker so that sort
+	// order is deterministic across runs.
```
[the remark this answers is not in the document]
Comment (nickvanw) [reply go/vt/vtctl/reparentutil/reparent_sorter.go]: One follow-up request here: comparing only `Alias.Uid` still leaves `cell1-0000000100` and `cell2-0000000100` equivalent, and ERS builds the candidate slice from map iteration before sorting. That means candidate selection can still vary across runs when otherwise-equal tablets share a UID across cells. Please compare the full alias (`Cell`, then `Uid`, or `topoproto.TabletAliasString`) so the final ordering is deterministic across cells too.

**Review by nickvanw — APPROVED** [review]
Approved overall. The `vterrors.Wrapf` change is correct, and the sorter update fixes the comparator contract issue. I left one inline follow-up on the final tie-breaker still not being fully deterministic across cells.

File: go/vt/vtctl/reparentutil/emergency_reparenter.go [hunk 2]
```diff
@@ -907,6 +908,7 @@ func (erp *EmergencyReparenter) findErrantGTIDs(
 	for _, candidate := range maxLenCandidates {
 		candidatePositions := validCandidates[candidate]
 		if candidatePositions == nil || candidatePositions.IsZero() {
+			log.Warn("skipping candidate during errant GTID detection: nil or zero positions", slog.String("candidate", candidate))
```
Comment (arthurschreiber) [inline go/vt/vtctl/reparentutil/emergency_reparenter.go]: This is the first use of the package level logger in this file, and I'm not sure this is intended. `erp.logger` ensures that the log lines end up on the caller side of `EmergencyReparentShard`, while `log.Warn` will only show up in the `vtctld` stderr.

You might have wanted to use `erp.logger.Warningf("skipping candidate %s during errant GTID detection: nil or zero positions", candidate)` instead?

**Review by arthurschreiber — COMMENTED** [review]
LGTM, just one nit around the use of the logger.

File: go/vt/vtctl/reparentutil/emergency_reparenter.go (hunk 2 above)
Comment (timvaillancourt) [reply go/vt/vtctl/reparentutil/emergency_reparenter.go]: @arthurschreiber good point! Updated in https://github.com/vitessio/vitess/pull/19851/commits/512a7896d4e82f419baea9a67a1a293a9053ce93 🙇

**Comment by timvaillancourt** [comment]
@arthurschreiber / @nickvanw I believe the concerns on this PR are addressed

@nickvanw for some reason your approval is broken: it's clear you approved but GitHub orphaned some of the state. A re-approval is appreciated 🙇

**Comment by timvaillancourt** [comment]
> @nickvanw for some reason your approval is broken: it's clear you approved but GitHub orphaned some of the state. A re-approval is appreciated 🙇

Ha! Removing @nickvanw's review somehow made GitHub fix the review state 😬

**Review by nickvanw — APPROVED** [review]
> @nickvanw for some reason your approval is broken: it's clear you approved but GitHub orphaned some of the state. A re-approval is appreciated 🙇

Thanks GitHub.

**Review by dbussink — APPROVED** [review]
