### PR TITLE
Fixing a panic in vtgate with OLAP mode

### LINKED ISSUE #8694: Panic in vtgate with OLAP mode
~Could be related to #8687 , but logging separately since this has a clean repro:~

  * Recent main (`Version: 12.0.0-SNAPSHOT (Git revision 4358c6a85e branch 'main')`
  * Unsharded keyspace called `keyspace` with primary and 2 replicas (no vschema):
  ```
$ vtctlclient -server localhost:15999 ListAllTablets
zone1-0000000100 keyspace1 0 primary 192.168.0.134:15100 192.168.0.134:17100 [] 2021-08-26T18:21:22Z
zone1-0000000101 keyspace1 0 replica 192.168.0.134:15101 192.168.0.134:17101 [] <null>
zone1-0000000102 keyspace1 0 replica 192.168.0.134:15102 192.168.0.134:17102 [] <null>
  ```
  * Create a table, insert some data, and verify:
  ```
$ mysql -u user  -h 127.0.0.1 -P 15306 -p  keyspace1
.
.
mysql> create table t1 (c1 bigint not null, c2 bigint not null, c3 bigint, primary key(c1));                      
Query OK, 0 rows affected (0.07 sec)

mysql> insert into t1 (c1,c2) values (20,21);                                                                
Query OK, 1 row affected (0.01 sec)

mysql> select * from t1;
+----+----+------+
| c1 | c2 | c3   |
+----+----+------+
| 20 | 21 | NULL |
+----+----+------+
1 row in set (0.01 sec)
  ```
  * Connect to database again (NOTE:  not using a dbname), issue a `USE` for our keyspace, switch to OLAP and do `show tables`:
  ```
$ mysql -u user  -h 127.0.0.1 -P 15306 -p  
.
.
.
mysql> use keyspace1;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> set workload=olap;
Query OK, 0 rows affected (0.00 sec)

mysql> show tables;
ERROR 2013 (HY000): Lost connection to MySQL server during query
  ```

  * Panic from vtgate log:
  ```
I0826 11:21:23.745757   30998 tablet_health_check.go:111] HealthCheckUpdate(Serving State): tablet: zone1-102 (192.168.0.134) serving false => true for keyspace1/0 (REPLICA) reason: healthCheck update
E0826 11:26:02.754808   30998 server.go:303] mysql_server caught panic:
runtime error: index out of range [0] with length 0
runtime/panic.go:88 (0x435324)
vitess.io/vitess/go/vt/vtgate/engine/rename_fields.go:78 (0xeb89c8)
vitess.io/vitess/go/vt/vtgate/engine/rename_fields.go:87 (0xed121c)
vitess.io/vitess/go/vt/vtgate/scatter_conn.go:330 (0xfaf6aa)
vitess.io/vitess/go/vt/vtgate/scatter_conn.go:376 (0xfcf8ee)
vitess.io/vitess/go/vt/vttablet/queryservice/wrapped.go:198 (0xdee1d8)
vitess.io/vitess/go/vt/vttablet/grpctabletconn/conn.go:195 (0x121cd24)
vitess.io/vitess/go/vt/vttablet/queryservice/wrapped.go:196 (0xdee349)
vitess.io/vitess/go/vt/vtgate/tabletgateway.go:270 (0xfb3d8f)
vitess.io/vitess/go/vt/vttablet/queryservice/wrapped.go:194 (0xdebee1)
vitess.io/vitess/go/vt/vtgate/scatter_conn.go:375 (0xfcfaa7)
vitess.io/vitess/go/vt/vtgate/scatter_conn.go:516 (0xfd0328)
vitess.io/vitess/go/vt/vtgate/scatter_conn.go:521 (0xfb0628)
vitess.io/vitess/go/vt/vtgate/scatter_conn.go:374 (0xfafb64)
vitess.io/vitess/go/vt/vtgate/executor.go:1483 (0xfa1064)
vitess.io/vitess/go/vt/vtgate/vcursor_impl.go:447 (0xfba564)
vitess.io/vitess/go/vt/vtgate/engine/send.go:158 (0xec1b1e)
vitess.io/vitess/go/vt/vtgate/engine/rename_fields.go:91 (0xeb8a4c)
vitess.io/vitess/go/vt/vtgate/executor.go:1113 (0xf9d999)
vitess.io/vitess/go/vt/vtgate/vtgate.go:429 (0xfc69ec)
vitess.io/vitess/go/vt/vtgate/plugin_mysql_server.go:219 (0xfa5d29)
vitess.io/vitess/go/mysql/conn.go:1255 (0xcf0b13)
vitess.io/vitess/go/mysql/conn.go:1240 (0xcf06f5)
vitess.io/vitess/go/mysql/conn.go:877 (0xced41e)
vitess.io/vitess/go/mysql/server.go:474 (0xd14391)
vitess.io/vitess/go/mysql/server.go:286 (0xd1afa4)
runtime/asm_amd64.s:1371 (0x472740)
  ```

EDIT: Updated description to reflect that this may have nothing to do with health check, it just happens to occur right after vtgate logs a health check message.

### PR DESCRIPTION
**Pull request by frouioui**
## Description

This pull request fixes a panic in vtgate that happens when a `show tables` or a `use <database>` query is sent to Vitess after entering `olap` mode.

## Related Issue(s)
Fixes #8694 

## Checklist
- [x] Should this PR be backported?
- [x] Tests were added or are not required
- [x] Documentation was added or is not required

### CODE REVIEW

**Comment by deepthi** [comment]
Let's backport to 11.0 branch (and others if they are affected).

File: go/vt/vtgate/engine/rename_fields.go [hunk 1]
```diff
@@ -73,6 +73,9 @@ func (r *RenameFields) Execute(vcursor VCursor, bindVars map[string]*querypb.Bin
 }
 
 func (r *RenameFields) renameFields(qr *sqltypes.Result) {
+	if len(r.Indices) != len(qr.Fields) {
+		return
+	}
```
Comment (harshit-gangal) [inline go/vt/vtgate/engine/rename_fields.go:78]: the fix will avoid renaming the result fields.

Instead, we should check two things here.
1. if qr.Fields is nil then return.
2. while ranging over the r.Indices, index value should be < than qr.Fields length.

Comment (frouioui) [reply go/vt/vtgate/engine/rename_fields.go:78]: @harshit-gangal, thank you for the feedback. My thoughts were that having two different lengths for `r.Indices` and `qr.Fields` meant that one of the two slices has incomplete data, we cannot ensure that the first `n` indexes of `qr.Fields` map both `r.Indices` & `r.Cols[ind]` `n` indexes. Since I wanted to avoid any scenario where we end up with partial or deteriorated data, I initially decided to not continue if the lengths are different.

File: go/vt/vtgate/engine/rename_fields.go [hunk 2]
```diff
@@ -73,9 +73,12 @@ func (r *RenameFields) Execute(vcursor VCursor, bindVars map[string]*querypb.Bin
...
-	for i := 0; i < len(r.Indices) && i < len(qr.Fields); i++ {
-		colName := r.Cols[r.Indices[i]]
-		qr.Fields[i].Name = colName
+	for ind, index := range r.Indices {
+		if ind == len(qr.Fields) {
+			break
+		}
+		colName := r.Cols[ind]
+		qr.Fields[index].Name = colName
 	}
```
Comment (harshit-gangal) [inline go/vt/vtgate/engine/rename_fields.go]: this will panic for case 
when qr.Fields has 5 columns
and the r.Indices want to replace 2 and 6 index fields.

Comment (frouioui) [reply go/vt/vtgate/engine/rename_fields.go]: my bad, pushed the fix

**Review by harshit-gangal — APPROVED** [review]
