### PR TITLE
Fix restore from backup execution path to use context from caller

### LINKED ISSUE #12830: executeRestoreFullBackup should use context from caller to pass down to 'restoreFiles'
### Description
Currently [executeRestoreFullBackup](https://github.com/vitessio/vitess/blob/main/go/vt/mysqlctl/builtinbackupengine.go#L806) calls to `restoreFiles` using context.Background(), this implies that it can run forever. Since `executeRestoreFullBackup` ignores the ctx passed to it by the caller, there is no way for restore to be cancelled once it is initiated. 

This can return sucessfull restore even if there was any failure down the stack during `restoreFiles`.

### Expectation
Context cancelled or timed-out at caller level should be respcted by `restoreFiles` to make sure restore returns failure incase of context cancelled or timed-out.

### PR DESCRIPTION
**Pull request by rsajwani**
## Description

Mainly this PR is fixing a bug I identified during [PR12703](https://github.com/vitessio/vitess/pull/12703). VtctldClient calls 'RestoreFromBackup' with context. The context timeout value is set using `action_timeout` flag. But During `executeRestoreFullBackup` and `executeRestoreIncrementalBackup`, instead of passing the original context, we pass `context.Background()` to these methods. This results in restore to run in background even if client context get `Canceled` or `Timed-out`. To fix this issue we pass on that same context object.

Reference file: https://github.com/vitessio/vitess/blob/main/go/vt/mysqlctl/builtinbackupengine.go

There are few more fixes in this PR

1- Fixed typo in spelling `Canceled`
2- During restore,  if the context get canceled, we report bug to backupHandler instead of `rec` structure. This can result in restore not throwing any error to its caller. 
3- Reporting errors back to client incase of failure during backup or restore.
 
 ## NOTE
 During restore if context get timed-out or canceled, the tablet type remains 'RESTORE' and does not revert back to its original state. The reason is before we start restore, all the existing files first get deleted. Now if restore get aborted in the middle, the MySQL instance won't able to restart with incomplete set of restore files. This result in ChangeTabletType to fail. 

 

## Related Issue(s)

closes #12830. 

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/mysqlctl/builtinbackupengine.go [hunk 1]
```diff
@@ -914,7 +914,7 @@ func (be *BuiltinBackupEngine) restoreFiles(ctx context.Context, params RestoreP
 			select {
 			case <-ctx.Done():
 				log.Errorf("Context cancelled during %q backup", fe.Name)
-				bh.RecordError(vterrors.Errorf(vtrpc.Code_CANCELED, "context canceled"))
+				rec.RecordError(vterrors.Errorf(vtrpc.Code_CANCELED, "context canceled"))
```
Comment (rsajwani) [inline go/vt/mysqlctl/builtinbackupengine.go:917]: bug left in https://github.com/vitessio/vitess/pull/12703

Comment (rsajwani) [reply go/vt/mysqlctl/builtinbackupengine.go:917]: We didn't have restore test so we weren't able to catch it .. now that I wrote restore test but it will not catch this until we fix https://github.com/vitessio/vitess/issues/12830

**Comment by rsajwani** [comment]
spoke offline with @mattlord. He is suggesting to fix https://github.com/vitessio/vitess/issues/12830 in this same PR... I will update the PR with additional changes once I research on #12830

**Comment by rsajwani** [comment]
> spoke offline with @mattlord. He is suggesting to fix #12830 in this same PR... I will update the PR with additional changes once I research on #12830

done

File: go/vt/mysqlctl/builtinbackupengine_test.go [hunk 2]
```diff
@@ -260,6 +246,134 @@ func TestExecuteBackupWithCancelledContext(t *testing.T) {
...
+	assert.NoError(t, err)
+	assert.NotNil(t, bm)
+
+	// Restore using timed-out context
+	mysqld = mysqlctl.NewFakeMysqlDaemon(fakesqldb.New(t))
+	mysqld.ExpectedExecuteSuperQueryList = []string{"STOP SLAVE", "START SLAVE"}
+	restoreParams.Mysqld = mysqld
+	timedOutCtx, cancel := context.WithTimeout(ctx, 1*time.Second)
+	defer cancel()
+	// Let the context timed out.
```
Comment (deepthi) [inline go/vt/mysqlctl/builtinbackupengine_test.go:365]:
```suggestion
	// Let the context time out.
```

Comment (rsajwani) [reply go/vt/mysqlctl/builtinbackupengine_test.go:365]: done

File: go/vt/mysqlctl/builtinbackupengine_test.go [hunk 3]
```diff
@@ -260,6 +246,134 @@ func TestExecuteBackupWithCancelledContext(t *testing.T) {
...
+	time.Sleep(1 * time.Second)
+	bm, err = be.ExecuteRestore(timedOutCtx, restoreParams, bh)
+	// ExecuteRestore should fail.
+	assert.Error(t, err)
+	assert.Nil(t, bm)
+	// error message can contain any combination of "context deadline exceeded" or "context canceled"
+	if !strings.Contains(err.Error(), "context canceled") && !strings.Contains(err.Error(), "context deadline exceeded") {
+		assert.Fail(t, "Test should failed with either `context canceled` or `context deadline exceeded`")
```
[the remark this answers is not in the document]
Comment (rsajwani) [reply go/vt/mysqlctl/builtinbackupengine_test.go:373]: done

File: changelog/17.0/17.0.0/summary.md [hunk 4]
```diff
@@ -74,6 +75,14 @@ Prior to v17, it was possible to create a shard name with invalid characters, wh
 
 Shard names may no longer contain the forward slash ("/") character, and TopoServer's `CreateShard` method returns an error if given such a name.
 
+#### <a id="VtctldClient-RestoreFromBackup"> VtctldClient call to RestoreFromBackup using correct context
+
+The VtctldClient calls for RestoreFromBackup initiate an asynchronous process to restore data from either the latest backup or the closest one before the specified backup-timestamp.
```
Comment (deepthi) [inline changelog/17.0/17.0.0/summary.md:80]:
```suggestion
The VtctldClient command RestoreFromBackup initiates an asynchronous process on the specified tablet to restore data from either the latest backup or the closest one before the specified backup-timestamp.
```

File: changelog/17.0/17.0.0/summary.md [hunk 5]
```diff
@@ -74,6 +75,14 @@ Prior to v17, it was possible to create a shard name with invalid characters, wh
...
+Prior to v17, this asynchronous process could run indefinitely in the background since it was called using an empty background. In v17 [PR#12830](https://github.com/vitessio/vitess/issues/12830),
+this behavior was changed to use the same context with which the client called the RestoreFromBackup command, which uses action_timeout to wait for any command to finish.
```
Comment (deepthi) [inline changelog/17.0/17.0.0/summary.md:82]:
```suggestion
this behavior was changed to use a context with a timeout of `action_timeout`.
```

File: changelog/17.0/17.0.0/summary.md [hunk 6]
```diff
@@ -74,6 +75,14 @@ Prior to v17, it was possible to create a shard name with invalid characters, wh
...
+If you are using VtctldClient to initiate a restore, make sure you provide an appropriate value for action_timeout to give enough time for the restore process to complete.
+Otherwise, the restore will throw an error if the context expires before it completes.
```
Comment (deepthi) [inline changelog/17.0/17.0.0/summary.md:84]: What happens to the tablet state? does it go back to its previous tablet_type?

File: changelog/17.0/17.0.0/summary.md [hunk 7]
```diff
@@ -8,6 +8,7 @@
     - [VTAdmin web migrated from create-react-app to vite](#migrated-vtadmin)
     - [Keyspace name validation in TopoServer](#keyspace-name-validation)
     - [Shard name validation in TopoServer](#shard-name-validation)
+    - [VtctldClient call to RestoreFromBackup using correct context](#VtctldClient-RestoreFromBackup)
```
[the remark this answers is not in the document]
Comment (rsajwani) [reply changelog/17.0/17.0.0/summary.md:11]: fixed

File: changelog/17.0/17.0.0/summary.md [hunk 8]
```diff
@@ -74,6 +75,14 @@ Prior to v17, it was possible to create a shard name with invalid characters, wh
 
 Shard names may no longer contain the forward slash ("/") character, and TopoServer's `CreateShard` method returns an error if given such a name.
 
+#### <a id="VtctldClient-RestoreFromBackup"> VtctldClient call to RestoreFromBackup using correct context
+
+The VtctldClient calls for RestoreFromBackup initiate an asynchronous process to restore data from either the latest backup or the closest one before the specified backup-timestamp.
+Prior to v17, this asynchronous process could run indefinitely in the background since it was called using an empty background. In v17 [PR#12830](https://github.com/vitessio/vitess/issues/12830),
```
[the remark this answers is not in the document]
Comment (rsajwani) [reply changelog/17.0/17.0.0/summary.md:81]: done

File: changelog/17.0/17.0.0/summary.md (hunk 5 above)
Comment (rsajwani) [reply changelog/17.0/17.0.0/summary.md:82]: done

File: changelog/17.0/17.0.0/summary.md (hunk 6 above)
Comment (rsajwani) [reply changelog/17.0/17.0.0/summary.md]: Restore is tricky. It does not go back to original state and it keeps sentinel file which is indication that last restore failed. Since we cancel in the middle of copy , depends upon where we left it give error during the restore while calling ChangeTabletType()->updateLocked->ts.canServe

Comment (rsajwani) [reply changelog/17.0/17.0.0/summary.md]: part of it is due to fact that during restore we first delete all the files. 
	logger.Infof("Restore: deleting existing files")
	if err := removeExistingFiles(cnf); err != nil {
		return err
	}
This prevent us from being coming back to original state.

File: go/vt/mysqlctl/builtinbackupengine.go [hunk 9]
```diff
@@ -816,7 +817,7 @@ func (be *BuiltinBackupEngine) executeRestoreFullBackup(ctx context.Context, par
 // The underlying mysql database is expected to be up and running.
 func (be *BuiltinBackupEngine) executeRestoreIncrementalBackup(ctx context.Context, params RestoreParams, bh backupstorage.BackupHandle, bm builtinBackupManifest) error {
 	params.Logger.Infof("Restoring incremental backup to position: %v", bm.Position)
-	createdDir, err := be.restoreFiles(context.Background(), params, bh, bm)
+	createdDir, err := be.restoreFiles(ctx, params, bh, bm)
```
Comment (rsajwani) [inline go/vt/mysqlctl/builtinbackupengine.go:820]: this is the bug fix.

File: go/vt/mysqlctl/backup.go [hunk 10]
```diff
@@ -404,6 +401,13 @@ func Restore(ctx context.Context, params RestoreParams) (*BackupManifest, error)
 		return nil, err
 	}
 
+	// if we got restore error then after restarting MYSQL we should return back with error
```
Comment (deepthi) [inline go/vt/mysqlctl/backup.go:404]: Does the test case validate that mysqld is indeed up after a timed-out restore?

File: changelog/17.0/17.0.0/summary.md (hunk 6 above)
Comment (rsajwani) [reply changelog/17.0/17.0.0/summary.md]: So I verified this again .. in topo we go back to 'REPLICA' state but in VTAdmin (which calls `show vitess_tablets`) will show `RESTORE`. Reason being as stated above mysql will be down due to incomplete set of files.

File: go/vt/vttablet/tabletmanager/restore.go [hunk 11]
```diff
@@ -283,8 +283,9 @@ func (tm *TabletManager) restoreDataLocked(ctx context.Context, logger logutil.L
 		// Do nothing here, let the rest of code run
 		params.Logger.Infof("Dry run. No changes made")
 	default:
+		bgCtx := context.Background()
 		// If anything failed, we should reset the original tablet type
-		if err := tm.tmState.ChangeTabletType(ctx, originalType, DBActionNone); err != nil {
+		if err := tm.tmState.ChangeTabletType(bgCtx, originalType, DBActionNone); err != nil {
```
Comment (shlomi-noach) [inline go/vt/vttablet/tabletmanager/restore.go:288]: I don't understand this change here. It looks like the opposite of the bugfix. Why would we not reuse `ctx`?

**Review by shlomi-noach — APPROVED** [review]
Looks good, nice catch! There's one change I don't understand, please see inline comment.

File: go/vt/vttablet/tabletmanager/restore.go (hunk 11 above)
Comment (rsajwani) [reply go/vt/vttablet/tabletmanager/restore.go:288]: We need to set status back to 'REPLICA' (or whatever prior to backup/restore) in all cases. If we use 'ctx' then incase of it being canceled or timed out we won't able to set the status back to original value (https://github.com/vitessio/vitess/issues/12701)

File: changelog/17.0/17.0.0/summary.md (hunk 6 above)
Comment (deepthi) [reply changelog/17.0/17.0.0/summary.md]: If this is really the behavior then it's a healthcheck issue. When the tablet goes back to REPLICA, it should be sending a healthcheck update to vtgate which updates its cache, which is what is used by `show vitess_tablets`. Can you file a separate issue for this? It's so far from this PR's issue that we should not try to fix it in this PR.

**Review by deepthi — APPROVED** [review]

**Comment by deepthi** [comment]
I'm going to merge this now, but looks like we may need another follow up PR for the tablet type change.

File: changelog/17.0/17.0.0/summary.md (hunk 6 above)
Comment (rsajwani) [reply changelog/17.0/17.0.0/summary.md]: for number 2, since restore fail and we stop the MySql , therefore it lost .sock file so we weren't able to connect and do any change to db.. the topo is refresh to replica value (therefore vtctlclient give you 'replica') and as I mentioned show vitess_tablet continue to show restore.

Comment (rsajwani) [reply changelog/17.0/17.0.0/summary.md]: bug filed
https://github.com/vitessio/vitess/issues/12945
