### PR TITLE
Fix view tracking on sharded keyspace

### LINKED ISSUE #15456: ALTER VIEW does not pick up column changes
## Context
On a sharded keyspace, when altering a table by adding or removing a column, and then using a view with a `select *` in it, Vitess will accept the DDLs, but the column list on the view does not reflect the changes on the table.

## Reproduction steps
Set-up, create a table and a view:
```sql
create table t (id int, primary key (id));
insert into t (id) values (9000);
create view v as select * from t;
```

Add a column to the table and update the view:
```sql
alter table t add column test int;
alter view v as select * from t;
```

Query the view. See the new column is missing:
```sql
select * from v;
+------+
| id   |
+------+
| 9000 |
+------+

show create view v;
+------+---------------------------------------------------------------------------------------------------------------------------+----------------------+----------------------+
| View | Create View                                                                                                               | character_set_client | collation_connection |
+------+---------------------------------------------------------------------------------------------------------------------------+----------------------+----------------------+
| v    | CREATE ALGORITHM=UNDEFINED DEFINER=`vt_app`@`localhost` SQL SECURITY DEFINER VIEW `v` AS select `t`.`id` AS `id` from `t` | utf8mb4              | utf8mb4_0900_ai_ci   |
+------+---------------------------------------------------------------------------------------------------------------------------+----------------------+----------------------+
```

Try updating the view again later in the same session or a new one. The new column is picked up:

```sql
alter view v as select * from t;
show create view v;
+------+------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+----------------------+
| View | Create View                                                                                                                                    | character_set_client | collation_connection |
+------+------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+----------------------+
| v    | CREATE ALGORITHM=UNDEFINED DEFINER=`vt_app`@`localhost` SQL SECURITY DEFINER VIEW `v` AS select `t`.`id` AS `id`,`t`.`test` AS `test` from `t` | utf8mb4              | utf8mb4_0900_ai_ci   |
+------+------------------------------------------------------------------------------------------------------------------------------------------------+----------------------+----------------------+
> select * from v;
+------+------+
| id   | test |
+------+------+
| 9000 | NULL |
+------+------+
```

### PR DESCRIPTION
**Pull request by harshit-gangal**
## Description
When `vtgate` receives `SELECT *` queries and possesses authoritative column information for the tables in the query, it expands `*` into the actual column list, simplifying subsequent planning.

This column information is sourced from the schema tracker, which experiences a slight delay in reflecting schema changes in `vtgate`. Previously, following an `ALTER TABLE` that modified the column list, an immediate `ALTER VIEW` incorporating a `SELECT *` led `vtgate` to expand the columns using outdated information from the schema tracker, causing the resultant view to misrepresent the updated schema.

The remedy involves refraining from expanding columns in `CREATE/ALTER VIEW` statements, allowing MySQL to handle column expansion. The schema tracker then forwards the view definition to `vtgate`, ensuring consistency.

However, a temporal lag may persist; if a view is queried immediately post-alteration, it might display the previous definition until `vtgate` receives the updated information. Unlike before, where the view would permanently display an incorrect definition, this issue is now transient.

## Related Issue(s)
Fixes #15456

## Checklist
-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vttablet/onlineddl/executor.go [hunk 1]
```diff
@@ -3069,6 +3069,7 @@ func (e *Executor) executeAlterViewOnline(ctx context.Context, onlineDDL *schema
 		// it actually easier for us to issue a CREATE OR REPLACE, because it
 		// actually creates a view...
 		stmt = &sqlparser.CreateView{
+
```
Comment (dbussink) [inline go/vt/vttablet/onlineddl/executor.go:3072]: Stray newline here?

File: go/vt/vtgate/planbuilder/ddl.go [hunk 2]
```diff
@@ -192,64 +192,63 @@ func findTableDestinationAndKeyspace(vschema plancontext.VSchema, ddlStatement s
...
-	})
-	return destination, keyspace, nil
+func buildCreateView(
+	ctx context.Context,
+	vschema plancontext.VSchema,
+	ddl *sqlparser.CreateView,
+	reservedVars *sqlparser.ReservedVars,
+	enableOnlineDDL, enableDirectDDL bool,
+) (key.Destination, *vindexes.Keyspace, error) {
+	return buildCreateViewCommon(ctx, vschema, reservedVars, enableOnlineDDL, enableDirectDDL, ddl.Select, ddl)
```
Comment (GuptaManan100) [inline go/vt/vtgate/planbuilder/ddl.go:212]: These two functions look identical now. Can't we rename one and use it for both?

**Review by GuptaManan100 — APPROVED** [review]
rest lgtm

**Review by systay — APPROVED** [review]
