### PR TITLE
Fix for empty results when no shards can be found to route to

### LINKED ISSUE #10144: Bug Report: exists may returns random result on a sharded table
### Overview of the Issue

We found an issue with exists : I can't provide the exact query we use, but for the query like 
```
select exists(select * from foo where some_field=some_value)
```
here foo is in a sharded keyspace, it seems if the inner query has result in one shard but have no result in another shard, then the outer query will return a random 0 or 1.  Not sure if it is related, but for our particular query, the table is sharded on the field 'some_field', so if Vitess is smart enough, it doesn't need to send the query to all the shard. 
We tried using gen4 planner, got the same result.

### Reproduction Steps

See description.

### Binary Version

```sh
v13.0.0
```

### Operating System and Environment details

```sh
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by GuptaManan100**
## Description
Queries that follow the following pattern - 
```mysql
select exists(select * from foo where some_field=some_value)
```

The table `foo` would has a lookup vindex on `some_field` and there are no matching rows for `some_value`. What Vitess would do when no shards could be found to route to is to return an empty result. This is correct for most cases, but not always. The query above would return an empty result instead of a `0`.

## Related Issue(s)
- Fixes #10144 

## Checklist
-   [x] "Backport me!" label has been added if this change should be backported YES
-   [x] Tests were added or are not required
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vtgate/planbuilder/gen4_planner.go [hunk 1]
```diff
@@ -93,7 +93,13 @@ func gen4SelectStmtPlanner(
 			return primitive, nil
 		}
 	}
-	return plan.Primitive(), nil
+
+	primitive := plan.Primitive()
+	if rb, ok := primitive.(*engine.Route); ok {
```
Comment (GuptaManan100) [inline go/vt/vtgate/planbuilder/gen4_planner.go:98]: I think a comment here as to why the previous behaviour is desirable for JOINs and others would be good.

**Review by GuptaManan100 — COMMENTED** [review]
Everything else LGTM!
