### PR TITLE
fixing issue with xtrabackup and long gtids

### LINKED ISSUE #16303: Bug Report: long GTIDs cause xtrabackup backups to fail
### Overview of the Issue

We reported an issue to Percona where if GTIDs get too long (beacuse we have replaced server enough times in a shard), we get to a point where Xtrabackup starts to truncate the output of its loglines, which means we end up with an invalid/incorrect GTID. This seems to happen the the size of `@@gtid_executed` gets close to 8KB. Upstream ticket for more details: https://perconadev.atlassian.net/browse/PXB-3302

### Reproduction Steps

1. have a MySQL server with long enough GTIDs. See the [Percona ticket](https://perconadev.atlassian.net/browse/PXB-3302) for a reproduction of this scenario.
2. Try to start a backup using the `xtrabackupengine`.
3. Backup will fail with:
```
E0701 04:32:40.512452 3937211 main.go:96] E0701 11:32:40.511911 backup.go:107] E0701 11:32:40.509443 backup.go:127] backup is not usable, aborting it: [Code: INTERNAL
invalid MySQL 5.6 SID "f7e534c2-0f61-2024-07-01T04"
```
note the `T04` is the beginning of the next line of output from xtrabackup.

### Binary Version

```sh
tested on v14, but this should happen on any version because it is an issue with Xtrabackup and how Vitess obtains the replication position of its backup
```

### Operating System and Environment details

```sh
Ubuntu 22.04
```

### Log Fragments

```sh
I0701 04:32:40.499083 2078479 xtrabackupengine.go:334] xtrabackup stderr: 2024-07-01T04:32:40.498984-07:00 0 [Note] [MY-011825] [Xtrabackup] completed OK!
I0701 04:32:40.508453 2078479 xtrabackupengine.go:667] Found position: *REDACTED*,f61b69f5-24ae-11ee-864f-126f112aba75:1,f65e62ed-d3b9-11ed-b553-125b93f33a1b:1-2281198,f7e534c2-0f61-2024-07-01T04:32:39.275652-07:000[Note][MY-011825][Xtrabackup]MySQLslavebinlogposition:masterhost
I0701 04:32:40.509243 2078479 xtrabackupengine.go:124] Closing backup file backup.xbstream.gz
E0701 04:32:40.509403 2078479 backup.go:127] backup is not usable, aborting it: [Code: INTERNAL
invalid MySQL 5.6 SID "f7e534c2-0f61-2024-07-01T04"
```

### PR DESCRIPTION
**Pull request by rvrangel**
## Description

Instead of reading the GTIDs from the `xtrabackup` output, this will make use of the `--extra-lsndir` flag to output a copy of the `xtrabackup_info` file which has the full GTID information, instead of reading it from the `STDERR` where it eventually gets truncated after the line size gets close to ~8KB

## Related Issue(s)

Fixes #16303
## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [ ] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on CI?
-   [ ] Documentation was added or is not required

### CODE REVIEW

File: go/vt/mysqlctl/xtrabackupengine.go [hunk 1]
```diff
@@ -300,6 +312,7 @@ func (be *XtrabackupEngine) backupFiles(
 		"--slave-info",
 		"--user=" + xtrabackupUser,
 		"--target-dir=" + params.Cnf.TmpDir,
+		"--extra-lsndir=" + tempDir,
```
Comment (timvaillancourt) [inline go/vt/mysqlctl/xtrabackupengine.go:315]: @rvrangel will this flag exist in "most" recent versions of `xtrabackup`?

Comment (rvrangel) [reply go/vt/mysqlctl/xtrabackupengine.go:315]: good question, [it is present since the 2.4 EOL version](https://docs.percona.com/percona-xtrabackup/2.4/xtrabackup_bin/xbk_option_reference.html#extra-lsndirdirectory), so any recent version should have it I imagine.

Comment (deepthi) [reply go/vt/mysqlctl/xtrabackupengine.go:315]: Where will the temporary directory be created by default? Are we sure to have the necessary permissions?
I'm wondering why not use `params.Cnf.TmpDir` and just write the file there.

**Review by deepthi — COMMENTED** [review]
This will be a good change. The original implementation was definitely somewhat naive :)

File: go/vt/mysqlctl/xtrabackupengine.go (hunk 1 above)
Comment (rvrangel) [reply go/vt/mysqlctl/xtrabackupengine.go:315]: it will default to the system's `$TMPDIR` (usually `/tmp`) which we should almost always have permissions, the idea was that we could just remove it once we are done. but if we want to create it under `params.Cnf.TmpDir`, seems like the `--target-dir` is mostly unused because we stream the backup to `STDOUT`.

we could also use that path directly and instead of creating the temporary subdirectory and we either delete the files separately (it is just `xtrabackup_info` and `xtrabackup_checkpoints`) or we could just leave them there as the result of the last `xtrabackup` taken. @deepthi do you have a preference?

Comment (deepthi) [reply go/vt/mysqlctl/xtrabackupengine.go:315]: What are the pros and cons of leaving the files behind versus deleting them? The next backup would overwrite them anyway, right?
Beyond this one decisions, almost any of the options would work. It's probably a bit simpler to not create a new temporary directory and just use one of the existing ones.

Comment (rvrangel) [reply go/vt/mysqlctl/xtrabackupengine.go:315]: leaving them is mostly for investigation (if needed), I guess we can just not remove them so there is a copy in the temp folder of the files from the last backup attempt in case an operator wants to look at it, otherwise it will just get overwritten the next time a backup is taken. I will update the PR tomorrow

**Review by deepthi — APPROVED** [review]
The DCO check needs to be fixed before we can merge this.
The actual changes look good.

**Review by frouioui — APPROVED** [review]
