### PR TITLE
Fix scalar aggregation with literals in empty result sets

### LINKED ISSUE #18468: Bug Report: Sub-select + Limit Scatter Bug
### Overview of the Issue

Incorrect query result when running a sub-select with a limit where we need to scatter.

### Reproduction Steps

1. vschema

```json
{
  "sharded": true,
  "tables": {
    "contacts": {
      "column_vindexes": [
        {
          "column": "id",
          "name": "hash"
        }
      ]
    }
  },
  "vindexes": {
    "hash": {
      "type": "xxhash"
    }
  }
}
```

2. schema

```sql
CREATE TABLE `contacts` (
  `id` bigint unsigned NOT NULL,
  `team_id` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `contacts_team_id_index` (`team_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

3. Run a query where no rows in the contacts table have team_id 1:

```sql
SELECT 1 AS `id`, COUNT(*)
FROM (
  SELECT `id` FROM `contacts`
  WHERE `team_id` = 1
  LIMIT 100
) `t`;
```

The returned data is `(NULL, 0)`. This is incorrect. The correct row to return is `(1, 0)`. If I remove the LIMIT from the inner query, the correct result is produced.

Vexplain:

```json
{
	"OperatorType": "Aggregate",
	"Variant": "Scalar",
	"Aggregates": "any_value(0) AS id, count_star(1) AS count(*)",
	"Inputs": [
		{
			"OperatorType": "Projection",
			"Expressions": [
				":team_id as :team_id /* INT64 */",
				"1 as 1"
			],
			"Inputs": [
				{
					"OperatorType": "Limit",
					"Count": ":vtg1",
					"Inputs": [
						{
							"OperatorType": "Route",
							"Variant": "Scatter",
							"Keyspace": {
								"Name": "voxie",
								"Sharded": true
							},
							"FieldQuery": "select 1 from (select id from contacts where 1 != 1) as t where 1 != 1",
							"Query": "select 1 from (select id from contacts where team_id = :team_id /* INT64 */) as t limit :vtg1 /* INT64 */",
							"Table": "contacts"
						}
					]
				}
			]
		}
	]
}
```

### Binary Version

```sh
Vitess 21.0.5 / PlanetScale V21 are both reproducers.
```

### Operating System and Environment details

```sh
vttestserver image or PlanetScale are both reproducers.
```

### Log Fragments

```sh

```

### PR DESCRIPTION
**Pull request by systay**
## Description

Fixes an issue where scalar aggregations with literal values incorrectly returned NULL when the input result set was empty, instead of evaluating the literal expression.

### Problem

When executing queries like:
```sql
SELECT 1 AS `id`, COUNT(*) FROM (SELECT `id` FROM table WHERE condition LIMIT 100) `t`
```

If the subquery returns no rows due to the WHERE condition, Vitess incorrectly returned:
```
(NULL, 0)
```

Instead of the expected MySQL-compatible result:
```
(1, 0)  
```

The issue occurred because the aggregation engine primitives depended on incoming rows to provide values. When no rows were present, literal expressions (like `1`) were treated the same as column references and returned NULL.

### Solution

Allow the engine primitives to handle evaluating evalengine expressions to handle literals and parameters given empty inputs.

## Related Issue(s)
Fixes #18468

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/sqlparser/analyzer.go [hunk 1]
```diff
@@ -379,6 +379,20 @@ func IsColName(node Expr) bool {
 	return ok
 }
 
+var errNotStatic = fmt.Errorf("not static")
```
Comment (dbussink) [inline go/vt/sqlparser/analyzer.go]: `errors.New` should be fine here since there's no actual formatting.

File: go/vt/vtgate/engine/aggregations.go [hunk 2]
```diff
@@ -232,28 +258,51 @@ func (a *aggregatorSum) reset() {
...
+	return eval(env, a.expr)
+}
+
+func eval(env *evalengine.ExpressionEnv, eexpr evalengine.Expr) (sqltypes.Value, error) {
+	v, err := env.Evaluate(eexpr)
+	if err != nil {
+		return sqltypes.Value{}, err
+	}
+
+	return v.Value(collations.Unknown), nil
```
Comment (dbussink) [inline go/vt/vtgate/engine/aggregations.go]: Is this correct? I think this should be the default collation from the expression env?

File: go/vt/vtgate/engine/ordered_aggregate.go [hunk 3]
```diff
@@ -290,8 +308,8 @@ func (oa *OrderedAggregate) GetFields(ctx context.Context, vcursor VCursor, bind
 	if err != nil {
 		return nil, err
 	}
-
-	_, fields, err := newAggregation(qr.Fields, oa.Aggregates)
+	env := evalengine.NewExpressionEnv(ctx, bindVars, vcursor)
+	_, fields, err := newAggregation(qr.Fields, oa.Aggregates, env)
```
Comment (dbussink) [inline go/vt/vtgate/engine/ordered_aggregate.go]: If we also create this here and also in other spots, should we create it once inside the `OrderedAggregate`?

File: go/vt/wrangler/vdiff.go [hunk 4]
```diff
@@ -1418,6 +1421,18 @@ func (vc *contextVCursor) StreamExecutePrimitive(ctx context.Context, primitive
...
+func (vc *contextVCursor) TimeZone() *time.Location {
+	return time.Local
+}
+
+func (vc *contextVCursor) SQLMode() string {
+	return config.DefaultSQLMode
+}
+
+func (vc *contextVCursor) Environment() *vtenv.Environment {
+	return vtenv.NewTestEnv()
```
Comment (dbussink) [inline go/vt/wrangler/vdiff.go]: Same here, should we create it once inside the `contextVCursor`?

File: go/vt/vtgate/engine/ordered_aggregate.go (hunk 3 above)
Comment (systay) [reply go/vt/vtgate/engine/ordered_aggregate.go]: I don't think we can store this in the primitive. they are shared across users, and could have different bindvars and session state

Comment (dbussink) [reply go/vt/vtgate/engine/ordered_aggregate.go]: Ah ok, that makes sense. I guess we don't really have an execution context here we can keep it in to avoid having to allocate it each time?

Comment (systay) [reply go/vt/vtgate/engine/ordered_aggregate.go]: sad but true

File: go/vt/vtgate/engine/ordered_aggregate.go [hunk 5]
```diff
@@ -290,8 +308,8 @@ func (oa *OrderedAggregate) GetFields(ctx context.Context, vcursor VCursor, bind
 	if err != nil {
 		return nil, err
 	}
-
-	_, fields, err := newAggregation(qr.Fields, oa.Aggregates)
+	env := evalengine.NewExpressionEnv(ctx, bindVars, vcursor)
+	_, fields, err := newAggregation(qr.Fields, oa.Aggregates, env, 0)
```
Comment (dbussink) [inline go/vt/vtgate/engine/ordered_aggregate.go]: We shouldn't use `0` for any collation value since that's `unknown` and would not be correct. If this always a guaranteed numeric value in an aggregation here, we can use `collations.CollationBinaryID`. 

In other aggregate spots, we also have this code:

```
collation := collations.CollationForType(sqltype, env.DefaultConnectionCharset())
```

If we use something like that, can't we then avoid having to pass in the collation id explicitly? And rely on similar logic?

Comment (systay) [reply go/vt/vtgate/engine/ordered_aggregate.go]: I think my IDE did this, without asking me about it. Fixed!

**Review by dbussink — APPROVED** [review]

File: go/vt/vtgate/engine/aggregations.go [hunk 6]
```diff
@@ -53,15 +58,26 @@ type AggregateParams struct {
...
+// NewAggregateParam creates a new aggregate param
+func NewAggregateParam(
+	oc opcode.AggregateOpcode,
+	col int,
+	expr evalengine.Expr,
+	alias string,
+	collationEnv *collations.Environment,
+) *AggregateParams {
+	if expr != nil && oc != opcode.AggregateConstant {
+		panic(vterrors.VT13001("expr should be nil"))
```
Comment (harshit-gangal) [inline go/vt/vtgate/engine/aggregations.go:70]: nit: can have better error message, defining why.

Comment (systay) [reply go/vt/vtgate/engine/aggregations.go:70]: this is just defensive coding. If this ever happens, we messed up somewhere else. `VT13001` means *bug* - i.e. not expected. not sure which why to write here

File: go/vt/vtgate/engine/aggregations.go [hunk 7]
```diff
@@ -98,7 +124,7 @@ func (ap *AggregateParams) typ(inputType querypb.Type) querypb.Type {
 
 type aggregator interface {
 	add(row []sqltypes.Value) error
-	finish() sqltypes.Value
+	finish(env *evalengine.ExpressionEnv, coll collations.ID) (sqltypes.Value, error)
```
Comment (harshit-gangal) [inline go/vt/vtgate/engine/aggregations.go:127]: There new params are used by only aggregateConstant. Can it be made part of the struct than interface?

File: go/vt/vtgate/engine/aggregations.go [hunk 8]
```diff
@@ -35,7 +35,12 @@ import (
 // It contains the opcode and input column number.
 type AggregateParams struct {
 	Opcode opcode.AggregateOpcode
-	Col    int
+
+	// Input source specification - exactly one of these should be set:
+	// Col: Column index for simple column references (e.g., SUM(column_name))
+	// EExpr: Evaluated expression for literals, parameters
+	Col   int
+	EExpr evalengine.Expr
```
Comment (arthurschreiber) [inline go/vt/vtgate/engine/aggregations.go:43]: I guess if `EExpr` is set, the value in `Col` is ignored? I'm asking because it says "exactly one should be set", but `0` (the default / empty value fro `Col`) is a valid value and I was confused for a moment what this means then.
