### PR TITLE
v3: fix a panic and refactor for future primitives

### LINKED ISSUE #4851: vtgate query planner panic for count of (join + order by)
Failing test case for go/vt/vtgate/planbuilder/testdata/aggr_cases.txt:

`"select count(*) from (select col, user_extra.extra from user join user_extra on user.id = user_extra.user_id order by user_extra.extra) a"`

Output:

```
$  go test vitess.io/vitess/go/vt/vtgate/planbuilder -run "^(TestPlan)$"
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 59 [running]:
testing.tRunner.func1(0xc00031f000)
	/home/dweitzman/bin/go1.11/src/testing/testing.go:792 +0x387
panic(0x934900, 0xfa5260)
	/home/dweitzman/bin/go1.11/src/runtime/panic.go:513 +0x1b9
vitess.io/vitess/go/vt/vtgate/planbuilder.(*route).Wireup(0xc000338480, 0xa77160, 0xc00033ca20, 0xc00032dea0, 0x0, 0x0)
	/home/dweitzman/code/vitess/go/vt/vtgate/planbuilder/route.go:377 +0xcd3
vitess.io/vitess/go/vt/vtgate/planbuilder.(*orderedAggregate).Wireup(0xc00033ca20, 0xa77160, 0xc00033ca20, 0xc00032dea0, 0x0, 0x40e148)
	/home/dweitzman/code/vitess/go/vt/vtgate/planbuilder/ordered_aggregate.go:469 +0xfc
vitess.io/vitess/go/vt/vtgate/planbuilder.buildSelectPlan(0xc000329520, 0xa73b60, 0xc000126640, 0xe0829d, 0x31, 0x8, 0x8)
	/home/dweitzman/code/vitess/go/vt/vtgate/planbuilder/select.go:33 +0x128
vitess.io/vitess/go/vt/vtgate/planbuilder.BuildFromStmt(0xc0001fa480, 0x89, 0xa72420, 0xc000329520, 0xa73b60, 0xc000126640, 0x94d2e0, 0x1, 0xc000126640)
	/home/dweitzman/code/vitess/go/vt/vtgate/planbuilder/builder.go:138 +0x425
vitess.io/vitess/go/vt/vtgate/planbuilder.Build(0xc0001fa480, 0x89, 0xa73b60, 0xc000126640, 0xe0829d, 0x31, 0x2f7)
	/home/dweitzman/code/vitess/go/vt/vtgate/planbuilder/builder.go:124 +0x97
vitess.io/vitess/go/vt/vtgate/planbuilder.testFile.func1(0xc00031f000)
	/home/dweitzman/code/vitess/go/vt/vtgate/planbuilder/plan_test.go:225 +0xb5
testing.tRunner(0xc00031f000, 0xc00033c4b0)
	/home/dweitzman/bin/go1.11/src/testing/testing.go:827 +0xbf
created by testing.(*T).Run
	/home/dweitzman/bin/go1.11/src/testing/testing.go:878 +0x353
FAIL	vitess.io/vitess/go/vt/vtgate/planbuilder	0.013s
```

### PR DESCRIPTION
**Pull request by sougou**
Previously group by and order by constructs were treated as special case. The new change extends the builder interface and requires all primitives to implement the corresponding push functions.

This approach allows for primitives to be composed more easily because of the fact that we don't special case these constructs any more.

This also fixes #4851. The above changes make it easy to introduce a new mergeSort pseudo primitive that differentiates regular routes from those that perform a merge-sort. This prevents push-down of some constructs that were previously (incorrectly) allowed.

### CODE REVIEW

File: go/vt/vtgate/planbuilder/merge_sort.go [hunk 1]
```diff
@@ -0,0 +1,123 @@
...
+	"errors"
+
+	"vitess.io/vitess/go/vt/sqlparser"
+	"vitess.io/vitess/go/vt/vtgate/engine"
+)
+
+var _ builder = (*mergeSort)(nil)
+
+// mergeSort is a pseudo-primitive. It amends the
+// the underlying Route to performa a merge sort.
```
Comment (deepthi) [inline go/vt/vtgate/planbuilder/merge_sort.go]:
```suggestion
// the underlying Route to perform a merge sort.
```

File: go/vt/vtgate/planbuilder/merge_sort.go [hunk 2]
```diff
@@ -0,0 +1,123 @@
...
+func (ms *mergeSort) MakeDistinct() error {
+	return ms.input.MakeDistinct()
+}
+
+// PushGroupBy satisfies the builder interface.
+func (ms *mergeSort) PushGroupBy(groupBy sqlparser.GroupBy) error {
+	return ms.input.PushGroupBy(groupBy)
+}
+
+// PushGroupBy satisfies the builder interface.
```
Comment (deepthi) [inline go/vt/vtgate/planbuilder/merge_sort.go]:
```suggestion
// PushOrderBy satisfies the builder interface.
```

File: go/vt/vtgate/planbuilder/merge_sort.go [hunk 3]
```diff
@@ -0,0 +1,123 @@
...
+// A merge sort is created due to the push of an ORDER BY clause.
+// So, the function should never get called.
```
Comment (deepthi) [inline go/vt/vtgate/planbuilder/merge_sort.go]:
```suggestion
// So, this function should never get called.
```

File: go/vt/vtgate/planbuilder/route.go [hunk 4]
```diff
@@ -149,72 +149,81 @@ func (rb *route) PushAnonymous(expr sqlparser.SelectExpr) *resultColumn {
...
-	// multi-sharded options would have already been removed. So, this
-	// call is only for checking if the route has single shard options.
+// PushOrderBy satisfies the builder interface.
+func (rb *route) PushOrderBy(orderBy sqlparser.OrderBy) (builder, error) {
+	switch len(orderBy) {
+	case 0:
+		return rb, nil
+	case 1:
+		isSpecial := false
+		if _, ok := orderBy[0].Expr.(*sqlparser.NullVal); ok {
```
Comment (deepthi) [inline go/vt/vtgate/planbuilder/route.go]: Nice way of handling null and rand. +1

File: go/vt/vtgate/planbuilder/subquery.go [hunk 5]
```diff
@@ -120,12 +119,22 @@ func (sq *subquery) PushSelect(expr *sqlparser.AliasedExpr, _ builder) (rc *resu
...
+// MakeDistinct satisfies the builder interface.
+func (sq *subquery) MakeDistinct() error {
+	return errors.New("unsupported: distinct on cross-shard subquery")
 }
 
-// PushOrderByRand satisfies the builder interface.
-func (sq *subquery) PushOrderByRand() {
+// PushGroupBy satisfies the builder interface.
+func (sq *subquery) PushGroupBy(_ sqlparser.GroupBy) error {
+	return errors.New("unupported: group by on cross-shard subquery")
```
Comment (deepthi) [inline go/vt/vtgate/planbuilder/subquery.go]:
```suggestion
	return errors.New("unsupported: group by on cross-shard subquery")
```

Comment (deepthi) [reply go/vt/vtgate/planbuilder/subquery.go]: Why didn't this fail a unit test?

File: go/vt/vtgate/planbuilder/testdata/vindex_func_cases.txt [hunk 6]
```diff
@@ -329,30 +329,5 @@
   }
 }
 
-# limit and order by null clauses
```
Comment (deepthi) [inline go/vt/vtgate/planbuilder/testdata/vindex_func_cases.txt]: my understanding is that we still support `order by null`, so why has this testcase been deleted?

File: go/vt/vtgate/planbuilder/subquery.go (hunk 5 above)
Comment (sougou) [reply go/vt/vtgate/planbuilder/subquery.go]: This code is unreachable because there are higher level checks that catch this case. But it can get called in the future as things evolve.

It's something one has to keep in mind while making changes: review code coverage of tests and make sure reachable code is reached.

File: go/vt/vtgate/planbuilder/testdata/vindex_func_cases.txt (hunk 6 above)
Comment (sougou) [reply go/vt/vtgate/planbuilder/testdata/vindex_func_cases.txt]: It previously ignored order by null (and rand), which was kind of incorrect, especially for rand. So, I decided to instead go with the simplified rule that you shouldn't order by anything for vindex functions.
