### PR TITLE
Make connection killing resilient to MySQL hangs

### LINKED ISSUE #11884: Bug Report: VTTablet & VTGate routing traffic to hung MySQL server
### Overview of the Issue

We had an issue today where:

1. MySQL (5.7) crashed due to a corrupt memory error on the machine
2. This triggered a core dump, which due to the large amount of memory that needed to be dumped took around 19 minutes
3. During that time VTGate continued to route traffic to the VTTablet, and those queries hung indefinitely.
4. Every minute the VTGate would report that it was transitioning the VTTablet from `serving true => false` but then it would immediately transition it back from `false => true`
5. As soon as the core-dump was complete (19 minutes later), and MySQL restarted, the VTTablet spotted that replication lag was now high and took the host offline until it caught up.
6. Once replication lag caught up, the host was moved back to serving, and things were all :+1:

### Cause

I believe @dm-2 and I have tracked this down to being caused by a few things:

1. The code that checks the replication status of the MySQL server passes a `context.TODO()` to `getPoolReconnect`: https://github.com/vitessio/vitess/blob/a36de2c036e9ec9055ec11220ffabe6b1ed13e5d/go/vt/mysqlctl/replication.go#L326 and https://github.com/vitessio/vitess/blob/a36de2c036e9ec9055ec11220ffabe6b1ed13e5d/go/vt/mysqlctl/query.go#L34-L40. 
    - As far as I can tell there are no cancellations or timeouts on this code. I believe that means the `conn.ExecuteFetch` will then block indefinitely if the MySQL host is in a bad state after the crash while it's doing a core-dump
    - The fact that this code blocks, then prevents [repltracker.Status()](https://github.com/vitessio/vitess/blob/7fafc94671d746d4827a4b98e37f65036fd9bb29/go/vt/vttablet/tabletserver/repltracker/repltracker.go#L143) from completing, which prevents the health state of the vttablet updating: [lag, err := sm.rt.Status()](https://github.com/vitessio/vitess/blob/7fafc94671d746d4827a4b98e37f65036fd9bb29/go/vt/vttablet/tabletserver/state_manager.go#L637-L642), and prevents the updates state being broadcast back to the vtgate streamHealth.
2. On its own, this bug _shouldn't_ be a huge deal, as the vtgate `tablet_health_check` code will detect that it's not seen an updated serving status come in from the [vttablet for it's timeout](https://github.com/vitessio/vitess/blob/7fafc94671d746d4827a4b98e37f65036fd9bb29/go/vt/discovery/tablet_health_check.go#L264-L267) (in our case 1 minute) and so will transition the vtgate's own state to `serving false`.
    - This does indeed happen, and we see in the logs that we called `closeConnection` to transition the tablet to `serving false` here: https://github.com/vitessio/vitess/blob/7fafc94671d746d4827a4b98e37f65036fd9bb29/go/vt/discovery/tablet_health_check.go#L334-L336
    - However, after a short delay we will retry, and we will create a new StreamHealth connection to the vttablet to try again. When the initial connection is made, vttablet immediately sends back the "current" health state of the vttablet: https://github.com/vitessio/vitess/blob/a36de2c036e9ec9055ec11220ffabe6b1ed13e5d/go/vt/vttablet/tabletserver/health_streamer.go#L211-L212. This state will still say that the tablet is healthy, as what we learned from (1) is that we are blocked on setting the state to unhealthy due to the unresponsive mysql server.
    - The vtgate then sees this "healthy" response, and transitions it's view of the vttablet back to `serving true` and starts routing traffic to it again.
3. Another side-effect of this we spotted is that the `Replication()` call from (1) holds the `sm.mu.Lock()` the whole time, which causes other code to be blocked indefinitely that relies on taking the lock, like `/vars/debug` which cannot get the current `IsServing` state because of the lock: https://github.com/vitessio/vitess/blob/7fafc94671d746d4827a4b98e37f65036fd9bb29/go/vt/vttablet/tabletserver/state_manager.go#L678-L683

### Possible fixes:

It seems like the connection setup, and query execution to mysql in `getPoolReconnect` needs a timeout to prevent it blocking indefinitely, and to set the vttablet's state to not serving if it cannot fetch replication state from mysql. I think that would resolve all the issues here?

### Reproduction Steps

I don't know how to reliably reproduce this with clear steps. I'm guessing the problem would be visible if we crashed mysql in a non-graceful way such that it didn't fully terminate connections (or whatever happens while it's doing a core dump).

I think the analysis above covers it though.

### Binary Version

```sh
Server version: 5.7.32-vitess Version: 14.0.1 (Git revision 631084ae79181ba816ba2d98bee07c16d8b2f7b4 branch 'master') built on Mon Nov 21 16:30:24 UTC 2022 by root@bcaa51ae028b using go1.18.4 linux/amd64
```

### Operating System and Environment details

```sh
I don't know this off-hand but I don't know how pertinent it is given the details above?
```

### Log Fragments

```sh
W1205 10:17:52.962960       1 tablet_health_check.go:335] tablet alias:{cell:"ash1" uid:171471394} hostname:"<crashed host>" port_map:{key:"grpc" value:15991} port_map:{key:"vt" value:15101} keyspace:"x_ks" shard:"c0-" key_range:{start:"\xc0"} type:REPLICA db_name_override:"x" mysql_hostname:"<crashed host>" mysql_port:3306 db_server_version:"0.0.0" default_conn_collation:45 healthcheck stream error: Code: CANCELED
```

```
I1205 10:17:52.963050       1 tablet_health_check.go:111] HealthCheckUpdate(Serving State): tablet: ash1-171471394 (<crashed host>) serving true => false for x_ks/c0- (REPLICA) reason: vttablet: rpc error: code = Canceled desc = context canceled
```

```
I1205 10:17:53.051535       1 tablet_health_check.go:111] HealthCheckUpdate(Serving State): tablet: ash1-171471394 (<crashed host>) serving false => true for x_ks/c0- (REPLICA) reason: healthCheck update
```

we then see the exact same pattern repeated one minute later, and every minute, until the core-dump completes and the host restarts.
```

### PR DESCRIPTION
**Pull request by arthurschreiber**
## Description

This fixes some issues around `*Conn.Kill` that can be encountered when MySQL "hangs" (e.g. either by sending it a `SIGSTOP` signal or when MySQL is writing a core dump file after a crash).

`Kill` has no context / timeout support at all. This means that when MySQL hangs, and some other code tries to send the `KILL <id>` statement to MySQL (e.g. due to `setDeadline` or because the code tries to call `Kill` directly), the `Kill` function is just going to hang as well.

I added a new function `KillWithContext` that allows passing in a `Context` object and correctly honors cancellation. I replaced `setDeadline` with direct calls to `KillWithContext`, with a 5 second timeout. I don't think a 5 second timeout actually makes any sense - but `setDeadline` intended to use a timeout of `2*elapsed + 5*time.Second` (which never actually worked). Because `KILL <id>` on MySQL is supposed to return instantly, I think a much lower timeout would be sufficient.

In case the context passed to `KillWithContext` is canceled / timed out, there's nothing we can do - the client side connection on which we want to kill the executing statement was already closed anyway, and sending the `KILL <id>` statement is more or less best effort. So we just close the kill connection and return.

### TODO

* I want to go through all callers of `Kill` and either switch them over to pass a `Context` to higher level methods like `Exec`, or switch them to use `KillWithContext` instead.
* This also requires more tests. Existing tests are all passing, but they didn't cover the "broken" cases.

## Related Issue(s)

- Fixes #11884 

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [ ] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [ ] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vttablet/tabletserver/connpool/dbconn.go [hunk 1]
```diff
@@ -163,17 +163,38 @@ func (dbc *Conn) execOnce(ctx context.Context, query string, maxrows int, wantfi
...
 
-	done, wg := dbc.setDeadline(ctx)
-	qr, err := dbc.conn.ExecuteFetch(query, maxrows, wantfields)
+	resultChan := make(chan *sqltypes.Result, 1)
+	errChan := make(chan error, 1)
 
-	if done != nil {
-		close(done)
-		wg.Wait()
+	startTime := time.Now()
```
Comment (harshit-gangal) [inline go/vt/vttablet/tabletserver/connpool/dbconn.go:169]: making channel on runtime for every call seems expensive to me.
I have added `Benchmark me` label to it as well.

Comment (vmg) [reply go/vt/vttablet/tabletserver/connpool/dbconn.go:169]: This is no worse than the current code, which already creates a channel _and_ a waitgroup. The current code, however, is very wasteful. So I think we can improve this to make this even less costly! Let me try...

**Comment by vmg** [comment]
@arthurnn: can you apply https://github.com/vitessio/vitess/commit/996e652f421c290ea5a546603190e3a49ed74beb to this PR? It significantly reduces all allocations we perform and should make us faster than the previous code, while still being correct

**Comment by arthurschreiber** [comment]
@vmg Thanks! I'm on it. 🙇‍♂️

**Comment by arthurschreiber** [comment]
@vmg Just for my understanding, the improvements come from not copying the current query string, and by creating one channel instead of two?

**Comment by vmg** [comment]
Yeah, the current string is obviously unrelated to your PR, I just noticed that we were using `atomic.Value` which is a very rough (type unsafe) API that has been superseded by `atomic.Pointer`.

The changes in the actual connection path boil down to always creating a single channel instead of two. I also noticed we were fetching the current time twice (one for the metrics and one for the potential `Kill` call) so I unified that. Overall I think this is a huge improvement. The previous `setDeadline` was expensive and definitely showing up in profiles, and with this new code we're gonna see half as many allocations, because we only have a channel per request now and previously we had a channel and a `WaitGroup`.

There are ways to make this zero allocation but I don't think we should attempt that for now.

**Review by harshit-gangal — APPROVED** [review]

**Comment by arthurschreiber** [comment]
I reopened this because we'll pick up working on this again. 👍

File: go/mysql/fakesqldb/server.go [hunk 2]
```diff
@@ -419,12 +423,9 @@ func (db *DB) HandleQuery(c *mysql.Conn, query string, callback func(*sqltypes.R
 	for _, pat := range db.patternData {
 		if pat.expr.MatchString(query) {
 			userCallback, ok := db.queryPatternUserCallback[pat.expr]
+			db.mu.Unlock()
 			if ok {
-				// Since the user call back can be indefinitely stuck, we shouldn't hold the lock indefinitely.
-				// This is only test code, so no actual cause for concern.
-				db.mu.Unlock()
 				userCallback(query)
-				db.mu.Lock()
```
Comment (arthurschreiber) [inline go/mysql/fakesqldb/server.go:427]: We had to refactor this a bit - there's other places in this code that can end up blocking (e.g. the `BeforeFunc` call further above) and where we need to release the lock beforehand.

Instead of unlocking and relocking here, we changed the unlock calls to not be `defer`ed. We're not happy about that, but it seemed like the simplest way forward.

I think it would be nice to refactor the fake db server to clean some of this up in the future.

**Review by vmg — APPROVED** [review]
Looks great. Thanks for adding the tests!

**Comment by vmg** [comment]
I think the error in CI is related to the changes here, but looking at the test, it may just not be properly written/testing the right thing. Can you give it a look @arthurschreiber?

**Comment by arthurschreiber** [comment]
@vmg I kicked the tests off again. I could not see any relationship between the failures and the changes in this PR - did I miss something? 🤔

**Comment by arthurschreiber** [comment]
Oh, there is a different set of CI statuses on the commit and on the PR? Weird. I'm taking a look.

**Comment by arthurschreiber** [comment]
Ok, so from what I understand the failures in the `mysql57` unit test build are all coming from the same test case?(`TestSerializeTransactionsSameRow_ConcurrentTransactions`). Digging into what's going on there.

**Review by harshit-gangal — APPROVED** [review]

**Comment by arthurschreiber** [comment]
I think I figured it out. The test case had an implicit dependency on the "incorrect" behaviour of `fakesqldb.DB` where only a single connection could be executing a query (and all other connections would have to wait implicitly for the callbacks of that first query to have finished executing). With that behaviour removed, the test case was failing.

I fixed it by making all 3 queries / transaction wait explicitly for the `allQueriesPending` channel.

**Comment by vmg** [comment]
Looks great! I figured the test was making wrong assumptions. Thanks again @arthurschreiber

**Comment by GrahamCampbell** [comment]
To be backported to v19?

**Comment by deepthi** [comment]
> To be backported to v19?

Sorry we missed this. The release is going out today. In future the way to get an apto-backport is to add a backport label before the PR is merged. I realize you don't have the permissions to do that, but @arthurschreiber does.

**Comment by GrahamCampbell** [comment]
We can probs just add the label to my 2nd PR, if it's wanted in 18.0 or 17.0. I don't personally care to see this backported earlier than 19.0. ;)

**Comment by arthurschreiber** [comment]
Mh. I hoped adding backport labels will open backport PRs, but it doesn't look like that's working. :/ I'll open the backport PRs manually then.

**Comment by GrahamCampbell** [comment]
I don't think this was ever backported to v19 either?

**Comment by GrahamCampbell** [comment]
So I'm sure sure the vitess team will accept a v17 or v18 backport. My v19 backport was rejected: https://github.com/vitessio/vitess/pull/15411.
