### PR TITLE
Fix the race condition during vttablet startup

### LINKED ISSUE #15730: Bug Report: vttablet DBA pool can be poisoned with broken connection during startup
### Overview of the Issue

Similar to #15537 and #14562, there's another race possible during `vttablet` startup that can result in a broken connection in the pool due to a specific ordering at startup.

The `vttablet` process starts up and tries to retrieve the MySQL port which is needed for example for replication set up. This is done early on in the tablet manager initialization process:

https://github.com/vitessio/vitess/blob/4519c8fa929350dc506bb40cbbe19a6e47fe580d/go/vt/vttablet/tabletmanager/tm_init.go#L705-L731

Specifically `GetMysqlPort()` here is called which is implemented using the DBA connection pool:

https://github.com/vitessio/vitess/blob/4519c8fa929350dc506bb40cbbe19a6e47fe580d/go/vt/mysqlctl/replication.go#L176-L190

`mysqld.FetchSuperQuery` here specifically is what does that. 

The problem though is that this is called in parallel with the grants that could still be initializing. So that means that we could here use a connection that succeeds in getting the port (as no special permissions are needed), but then that connection is poisoned for future use as it had the wrong grants. We then later on start failing, even once the grants have finished initializing. 

### Reproduction Steps

-

### Binary Version

```sh
-
```

### Operating System and Environment details

```sh
-
```

### Log Fragments

```sh
-
```

### PR DESCRIPTION
**Pull request by dbussink**
This avoids the problem where the connection pool is poisoned when we check for the MySQL port, by avoiding to use the pool in the first place. We only ever run this once at startup, so we can create a new connection here and then dispose of it once we've retrieved the port.

That way we know the connection pool is still clean and doesn't have any problems.

## Related Issue(s)

Fixes #15730

## Checklist

-   [x] "Backport to:" labels have been added if this change should be back-ported to release branches
-   [x] If this change is to be back-ported to previous releases, a justification is included in the PR description
-   [x] Tests were added or are not required
-   [x] Did the new or modified tests pass consistently locally and on CI?
-   [x] Documentation was added or is not required

### CODE REVIEW

File: go/vt/mysqlctl/mysqld.go [hunk 1]
```diff
@@ -521,11 +521,15 @@ func (mysqld *Mysqld) WaitForDBAGrants(ctx context.Context, waitTime time.Durati
...
+	params, err := mysqld.dbcfgs.DbaConnector().MysqlParams()
+	if err != nil {
+		return err
+	}
 	timer := time.NewTimer(waitTime)
 	ctx, cancel := context.WithTimeout(ctx, waitTime)
 	defer cancel()
 	for {
-		conn, connErr := dbconnpool.NewDBConnection(ctx, mysqld.dbcfgs.DbaConnector())
+		conn, connErr := mysql.Connect(ctx, params)
```
Comment (dbussink) [inline go/vt/mysqlctl/mysqld.go:532]: Opted to also refactor this case slightly to avoid using the pool entirely so for any future readers it's also more obvious no pooling is actually used.

File: go/vt/mysqlctl/replication.go [hunk 2]
```diff
@@ -174,8 +175,21 @@ func (mysqld *Mysqld) RestartReplication(hookExtraEnv map[string]string) error {
...
 
 // GetMysqlPort returns mysql port
-func (mysqld *Mysqld) GetMysqlPort() (int32, error) {
-	qr, err := mysqld.FetchSuperQuery(context.TODO(), "SHOW VARIABLES LIKE 'port'")
+func (mysqld *Mysqld) GetMysqlPort(ctx context.Context) (int32, error) {
+	// We can not use the connection pool here. This check runs very early
+	// during MySQL startup when we still might be loading things like grants.
+	// This means we need to use an isolated connection to avoid poisoning the
+	// DBA connection pool for further queries.
+	params, err := mysqld.dbcfgs.DbaConnector().MysqlParams()
```
Comment (dbussink) [inline go/vt/mysqlctl/replication.go:183]: Changing it here to use a connection without pooling which avoids the poisoning. I also fixed the `context.TODO()` while being in here, making sure it's explicitly passed in.

**Comment by dbussink** [comment]
> Can this be backported to v19?

@GrahamCampbell Are you affected by this bug? We haven't backported previous fixes either mentioned in the linked issue. It only happens when you first initialize a Vitess cluster, often when using k8s where things spin up in a fairly random order.

File: go/vt/mysqlctl/mysqld.go (hunk 1 above)
Comment (deepthi) [reply go/vt/mysqlctl/mysqld.go:532]: This is good. When I was looking at this yesterday, I had to navigate through the code to see that `NewDBConnection` returns a non-pooled connection.

File: go/vt/vttablet/tabletmanager/tm_init.go [hunk 3]
```diff
@@ -730,10 +730,18 @@ func (tm *TabletManager) checkMysql() error {
 	return nil
 }
 
+const portCheckTimeout = 5 * time.Second
+
+func (tm *TabletManager) getMysqlPort() (int32, error) {
```
Comment (deepthi) [inline go/vt/vttablet/tabletmanager/tm_init.go:735]: It seems overkill to define a function that is used exactly once. Why can't all this be folded into findMysqlPort? It will grow from 10 lines to 15 lines.

Comment (dbussink) [reply go/vt/vttablet/tabletmanager/tm_init.go:735]: @deepthi Because it's setting up a context and you can't defer that properly in a `for` loop. So hence the separate function so it's not needed to manually cancel that which is more error prone.

**Review by deepthi — APPROVED** [review]

File: go/vt/mysqlctl/replication.go [hunk 4]
```diff
@@ -174,8 +175,21 @@ func (mysqld *Mysqld) RestartReplication(hookExtraEnv map[string]string) error {
...
+	if err != nil {
+		return 0, err
+	}
+	conn, err := mysql.Connect(ctx, params)
+	if err != nil {
+		return 0, err
+	}
+	defer conn.Close()
+	qr, err := conn.ExecuteFetch("SHOW VARIABLES LIKE 'port'", 1, false)
```
Comment (arthurschreiber) [inline go/vt/mysqlctl/replication.go:192]: I know this is not super important here, but should the context be passed down to the actual query? We've seen various cases where MySQL ends up being "stuck" for whatever reason not replying to incoming queries, and this would cause the `GetMysqlPort` function to hang indefinitely (instead of returning an error once `ctx` expires).

**Review by arthurschreiber — APPROVED** [review]

File: go/vt/mysqlctl/replication.go (hunk 4 above)
Comment (dbussink) [reply go/vt/mysqlctl/replication.go:192]: @arthurschreiber Do you mean as a general feature / refactor? It's not possible to pass in a context at the moment in the MySQL connection handling that Vitess does.

That might be useful as a separate feature / change, but I think that's independent of what we're doing here?

**Review by GuptaManan100 — APPROVED** [review]
LGTM!
