### PR TITLE
topology_watcher: Allow tablets to reuse old tablet addresses.

### LINKED ISSUE #5229: vtgate intermittently loses a tablet
We've had this lingering issue for a long time where vtgates "loose" a tablet. We've made some discoveries lately and think we have a hunch of where the issue is.

Screen Shot 2019-09-26 at 3 15 38 PM

There should be a tablet `uswest2-0000011101` in this shard but it's missing. No matter how long we wait it will never return. If we restart the tablet it does return.

If we look in the log when there is this issue we find the following log entry in the vtgate:
```
adding duplicate tablet uswest2-0000011101 for uswest2: alias:<cell:"uswest2" uid:11101 > hostname:"10.136.93.210" port_map:<key:"grpc" value:16002 > port_map:<key:"vt" value:15002 > keyspace:"arnhem_customer" shard:"-20" key_range:<end:" " > type:SPARE db_name_override:"vt_arnhem_customer_lo_20" mysql_hostname:"REDACTED" mysql_port:3306
```

Tracing that down to the following code go/vt/discovery/healthcheck.go:736:
```
	if _, ok := hc.addrToHealth[key]; ok {
		hc.mu.Unlock()
		log.Warningf("adding duplicate tablet %v for %v: %+v", name, tablet.Alias.Cell, tablet)
		return
	}
```

Another piece of the puzzle is that this usually happens when there's been a restart. Either due to a restart of the cluster (for a redeploy) or because of a node crash or something similar.

I think the issue here is that when the tablets restart the tablet pod is allocated by Kubernetes to a node that previously ran a different tablet. That is, the node:port combo (which constitutes the `key` above) is re-used for different tablets!

I think the solution is just not to do this check. The new tablet simply overwrites the old but I'm not sure what the implications would be. Maybe the solution is just to crash and have Kubernetes restart the vtgate pod and then it will not have seen the old tablet on that node and all will be good?

It doesn't seem like we should be the only ones encountering this issue with running Vitess on Kubernetes...

### PR DESCRIPTION
**Pull request by enisoc**
Fixes #5229.

The unit test failed before I added the check in RemoveTablet that we're deleting the tablet we think we are.

I also removed the goroutines from `RemoveTablet` and `ReplaceTablet` because it's ludicrous that there was no guarantee whatsoever of what state you'll be in at the end of `loadTablets()`. Let me know if there was some reason we had tried to make those asynchronous.

Signed-off-by: Anthony Yeh <enisoc@planetscale.com>

### CODE REVIEW

File: go/vt/discovery/healthcheck.go [hunk 1]
```diff
@@ -752,15 +771,13 @@ func (hc *HealthCheckImpl) AddTablet(tablet *topodatapb.Tablet, name string) {
...
 }
 
 // ReplaceTablet removes the old tablet and adds the new tablet.
 func (hc *HealthCheckImpl) ReplaceTablet(old, new *topodatapb.Tablet, name string) {
-	go func() {
-		hc.deleteConn(old)
-		hc.AddTablet(new, name)
-	}()
+	hc.deleteConn(old)
+	hc.AddTablet(new, name)
```
Comment (tirsen) [inline go/vt/discovery/healthcheck.go]: Nice yeah this should hopefully eliminate a huge source of threading issues

**Comment by tirsen** [comment]
I'll patch this in and will test it in our environment. It was very easy to reproduce the issue there.

**Comment by tirsen** [comment]
I can confirm this solves the issue in our environment but I'll let someone else more familiar with the code do a deeper review.

**Comment by enisoc** [comment]
@demmer explained that the reason `RemoveTablet` and `ReplaceTablet` were in goroutines was likely because they had seen that sometimes the attempt to close the connection inside `deleteConn()` would hang forever, which deadlocked the healthchecker because it held the mutex forever.

However, it seems that now we don't close connections synchronously anyway. We just cancel the Context and move on. So I believe it should be safe to run `RemoveTablet` synchronously now.

File: go/vt/discovery/healthcheck.go [hunk 2]
```diff
@@ -733,10 +744,18 @@ func (hc *HealthCheckImpl) AddTablet(tablet *topodatapb.Tablet, name string) {
...
-	if _, ok := hc.addrToHealth[key]; ok {
-		hc.mu.Unlock()
-		log.Warningf("adding duplicate tablet %v for %v: %+v", name, tablet.Alias.Cell, tablet)
-		return
+	if th, ok := hc.addrToHealth[key]; ok {
+		// Something already exists at this key.
+		// If it's the same tablet, something is wrong.
+		if topoproto.TabletAliasEqual(th.latestTabletStats.Tablet.Alias, tablet.Alias) {
+			hc.mu.Unlock()
+			log.Warningf("refusing to add duplicate tablet %v for %v: %+v", name, tablet.Alias.Cell, tablet)
```
Comment (sougou) [inline go/vt/discovery/healthcheck.go]: This should eventually become an acceptable state, which will allow us to "update if needed" kind of calls. But let the warning remain for now. It will allow us to find out if this really happens in the wild.

The other future improvement on this will be to add a timestamp that tracks when a tablet acquired the address to declare the true winner. Similar to how we're solving the mastership story.
