### PR TITLE
Use the emulated MySQL version for special comments

### LINKED ISSUE #7482: Create database if not exists fails for mysqldump
From mysqldump:

```
-- CREATE DATABASE /*!32312 IF NOT EXISTS*/ `mysql` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

```

Fails on Vitess. Ideally it should just ignore it.

```
ERROR 1235 (HY000) at line 32: vtgate: http://harshit-X1:15001/: create database not allowed
```

### PR DESCRIPTION
**Pull request by GuptaManan100**
Added MySQL Version that the parser would emulate for special comments

Fixes #7482

### CODE REVIEW

File: go/vt/sqlparser/parser.go [hunk 1]
```diff
@@ -35,6 +35,9 @@ var parserPool = sync.Pool{}
 // zeroParser is a zero-initialized parser to help reinitialize the parser for pooling.
 var zeroParser = *(yyNewParser().(*yyParserImpl))
 
+// MySQLVersion is the version of MySQL that the parser would emulate
+var MySQLVersion string = "5.7.9"
+
```
Comment (harshit-gangal) [inline go/vt/sqlparser/parser.go:40]: Should we not keep the vtgate mysql server in sync with parser version?

File: go/vt/sqlparser/token.go [hunk 2]
```diff
@@ -1027,11 +1031,98 @@ func (tkn *Tokenizer) scanMySQLSpecificComment() (int, []byte) {
...
+				break
+			}
+		} else {
+			break
+		}
+	}
+	if val != "" {
+		v, err := strconv.Atoi(val)
+		if err != nil {
+			return nil, err
```
Comment (harshit-gangal) [inline go/vt/sqlparser/token.go:1091]: converting mysql_version to comment version will be easier to convert and compare. This complex logic can be avoided.

File: go/vt/sqlparser/token.go [hunk 3]
```diff
@@ -1027,11 +1031,98 @@ func (tkn *Tokenizer) scanMySQLSpecificComment() (int, []byte) {
...
+		}
+		res[1], err = strconv.Atoi(string(version[1:3]))
+		if err != nil {
+			return nil, err
+		}
+		res[2], err = strconv.Atoi(string(version[3:]))
+		if err != nil {
+			return nil, err
+		}
```
Comment (harshit-gangal) [inline go/vt/sqlparser/token.go:1121]: we can avoid this by converting mysql version to comment version.

File: go/vt/sqlparser/token.go (hunk 2 above)
Comment (systay) [reply go/vt/sqlparser/token.go:1091]: I'm not seeing how converting mysql_version to comment version is much easier. Could you expand on your thinking?

File: go/vt/sqlparser/token.go [hunk 4]
```diff
@@ -1027,11 +1031,59 @@ func (tkn *Tokenizer) scanMySQLSpecificComment() (int, []byte) {
...
+		v, err := strconv.Atoi(val)
+		if err != nil {
+			return "", err
+		}
+		res[idx] = v
+		idx++
+	}
+	if idx == 0 {
+		return "", vterrors.Errorf(vtrpc.Code_INVALID_ARGUMENT, "MySQL version not correctly setup - %s.", version)
+	}
```
[the remark this answers is not in the document]
Comment (harshit-gangal) [reply go/vt/sqlparser/token.go:1082]: Revert is revered so this comment does not make sense now. Kindly ignore.

File: go/vt/sqlparser/parser.go (hunk 1 above)
Comment (harshit-gangal) [inline go/vt/sqlparser/parser.go:40]: VtGate mysql version is used, I think this is redundant and can be removed.

File: go/vt/sqlparser/token.go [hunk 5]
```diff
@@ -1027,11 +1031,59 @@ func (tkn *Tokenizer) scanMySQLSpecificComment() (int, []byte) {
...
-	_, sql := ExtractMysqlComment(buffer.String())
-	tkn.specialComment = NewStringTokenizer(sql)
+
+	commentVersion, sql := ExtractMysqlComment(buffer.String())
+
+	mysqlVersion, err := convertMySQLVersionToCommentVersion(MySQLVersion)
+	if err != nil {
+		tkn.Error(err.Error())
+		return tkn.Scan()
+	}
```
Comment (harshit-gangal) [inline go/vt/sqlparser/token.go:1041]: We can do this once at the start of VTGate as this value currently cannot change after VTGate startup.

**Review by harshit-gangal — APPROVED** [review]

File: go/vt/sqlparser/parser.go (hunk 1 above)
Comment (GuptaManan100) [reply go/vt/sqlparser/parser.go:40]: We cannot use Vtgate mysql version directly since it creates an import cycle. So we set this variable in the parser from the vtgate.

File: go/vt/sqlparser/token.go (hunk 5 above)
Comment (GuptaManan100) [reply go/vt/sqlparser/token.go]: done

File: go/vt/servenv/buildinfo.go [hunk 6]
```diff
@@ -106,7 +106,10 @@ func init() {
 		goArch:             runtime.GOARCH,
 		version:            versionName,
 	}
-	sqlparser.MySQLVersion = AppVersion.MySQLVersion()
+	sqlparser.MySQLVersion, err = sqlparser.ConvertMySQLVersionToCommentVersion(AppVersion.MySQLVersion())
+	if err != nil {
+		panic(fmt.Sprintf("%s", err))
```
Comment (systay) [inline go/vt/servenv/buildinfo.go:111]: Eeek... Do we have to panic? What about logging and moving on?

Comment (GuptaManan100) [reply go/vt/servenv/buildinfo.go:111]: Alright I'll do that

Comment (deepthi) [reply go/vt/servenv/buildinfo.go]: General guideline is that vtgate should never panic.

File: go/vt/sqlparser/token.go [hunk 7]
```diff
@@ -1027,11 +1031,55 @@ func (tkn *Tokenizer) scanMySQLSpecificComment() (int, []byte) {
...
+				break
+			}
+		} else {
+			break
+		}
+	}
+	if val != "" {
+		v, err := strconv.Atoi(val)
+		if err != nil {
+			return "", err
```
Comment (harshit-gangal) [inline go/vt/sqlparser/token.go:1071]: nit: method should be placed where it is used.

File: go/vt/sqlparser/token_test.go [hunk 8]
```diff
@@ -146,10 +148,12 @@ func TestString(t *testing.T) {
...
 	for _, tcase := range testcases {
-		id, got := NewStringTokenizer(tcase.in).Scan()
-		if tcase.id != id || string(got) != tcase.want {
-			t.Errorf("Scan(%q) = (%s, %q), want (%s, %q)", tcase.in, tokenName(id), got, tokenName(tcase.id), tcase.want)
-		}
+		t.Run(tcase.in, func(t *testing.T) {
+			id, got := NewStringTokenizer(tcase.in).Scan()
+			if tcase.id != id || string(got) != tcase.want {
+				t.Errorf("Scan(%q) = (%s, %q), want (%s, %q)", tcase.in, tokenName(id), got, tokenName(tcase.id), tcase.want)
+			}
```
Comment (harshit-gangal) [inline go/vt/sqlparser/token_test.go:155]: these can be changed to assert calls

**Review by harshit-gangal — APPROVED** [review]

File: go/vt/sqlparser/token.go (hunk 7 above)
Comment (GuptaManan100) [reply go/vt/sqlparser/token.go]: Done

File: go/vt/sqlparser/token_test.go (hunk 8 above)
Comment (GuptaManan100) [reply go/vt/sqlparser/token_test.go]: Done

**Review by systay — APPROVED** [review]
