### PR TITLE
Fix owned vindex query to keep alias in table expression

### LINKED ISSUE #4257: OwnedVindexQuery keeps alias in where clause but drops alias in table expression
This test case in dml_cases.txt will pass, but you can see that it's generating an invalid `OwnedVindexQuery` query that references aliases without setting them:

```
# update by primary keyspace id, changing one vindex column, with alias
"update user_metadata as um set um.email = 'juan@vitess.io' where um.user_id = 1"
{
  "Original": "update user_metadata as um set um.email = 'juan@vitess.io' where um.user_id = 1",
  "Instructions": {
    "Opcode": "UpdateEqual",
    "Keyspace": {
      "Name": "user",
      "Sharded": true
    },
    "Query": "update user_metadata as um set um.email = 'juan@vitess.io' where um.user_id = 1",
    "Vindex": "user_index",
    "Values": [1],
    "ChangedVindexValues": {
      "email_user_map": ["juan@vitess.io"]
    },
    "Table": "user_metadata",
    "OwnedVindexQuery": "select email, address from user_metadata where um.user_id = 1 for update"
  }
}
```

### PR DESCRIPTION
**Pull request by harshit-gangal**
## Description

This PR fixes the table expression to keep table alias. Also, add table alias support in delete statement parsing.

## Related Issue(s)

- Fixes #4257

## Checklist
- [X] Tests were added or are not required
- [X] Documentation was added or is not required

### CODE REVIEW

File: go/vt/vtgate/planbuilder/dml.go [hunk 1]
```diff
@@ -179,15 +179,15 @@ func buildDMLPlan(vschema ContextVSchema, dmlType string, stmt sqlparser.Stateme
 	return edml, ksidVindex, ksidCol, nil
 }
 
-func generateDMLSubquery(where *sqlparser.Where, orderBy sqlparser.OrderBy, limit *sqlparser.Limit, table *vindexes.Table, ksidCol string) string {
+func generateDMLSubquery(tblExpr sqlparser.TableExpr, where *sqlparser.Where, orderBy sqlparser.OrderBy, limit *sqlparser.Limit, table *vindexes.Table, ksidCol string) string {
```
Comment (GuptaManan100) [inline go/vt/vtgate/planbuilder/dml.go:182]: `table` is an unused argument now, isn't it?

**Review by GuptaManan100 — APPROVED** [review]

File: go/vt/vtgate/planbuilder/dml.go (hunk 1 above)
Comment (harshit-gangal) [reply go/vt/vtgate/planbuilder/dml.go:182]: it is used to get vindex columns for projection columns
