### PR TITLE
flags: deprecate vtctld_addr and delete related code

### LINKED ISSUE #12559: Task: cleanup remnants of vtctld UI
### Overview of the Issue

- `vtctld_addr` flag needs to be deprecated and deleted. It was used to link from vttablet and vtgate `/debug/status` pages to the old UI
- Broken links on `/debug/status` pages need to be deleted

vttablet:
vttablet-debug-status

vtgate:
Screenshot 2023-03-06 at 10 40 45 AM

For the vtgate link, we should simply remove the hyperlink.

### Reproduction Steps

N/A

### Binary Version

```sh
16.0.0
```

### Operating System and Environment details

```sh
Any
```

### Log Fragments

_No response_

### PR DESCRIPTION
**Pull request by deepthi**
## Description
- Deprecated `vtctld_addr` flag
- Removed references in vtgate and vttablet status pages to vtctld APIs

- Removed link to `Address` from vtgate's `Gateway Status`. Looking at `git blame`, this addr field has always been passed as "" (empty string), and it has never linked to anything useful.
Screenshot 2023-03-08 at 3 30 36 PM

- Changed links on vttablet status page that were calling out to vtctld http API to be plain text
Screenshot 2023-03-08 at 3 31 01 PM
- Removed SrvKeyspace and Replication Graph from vttablet status page. They don't belong there.

Compare to screenshots in linked issue to see the changes. 

## Related Issue(s)
Fixes #12559 

## Checklist

-   [ ] "Backport to:" labels have been added if this change should be back-ported
-   [x] Tests were added or are not required
-   [ ] Did the new or modified tests pass consistently locally and on the CI
-   [x] Documentation was added or is not required https://github.com/vitessio/website/pull/1404

### CODE REVIEW

File: go/vt/vtgate/vtgate.go [hunk 1]
```diff
@@ -76,8 +76,6 @@ var (
 	noScatter          bool
 	enableShardRouting bool
 
-	// TODO(deepthi): change these two vars to unexported and move to healthcheck.go when LegacyHealthcheck is removed
```
Comment (deepthi) [inline go/vt/vtgate/vtgate.go:79]: This comment was obsolete, hence deleted.

File: go/vt/vtctl/vtctl.go [hunk 2]
```diff
@@ -387,7 +387,7 @@ var commands = []commandGroup{
 			{
 				name:   "CreateKeyspace",
 				method: commandCreateKeyspace,
-				params: "[--sharding_column_name=name] [--sharding_column_type=type] [--served_from=tablettype1:ks1,tablettype2:ks2,...] [--force] [--keyspace_type=type] [--base_keyspace=base_keyspace] [--snapshot_time=time] [--durability-policy=policy_name] <keyspace name>",
+				params: "[--served_from=tablettype1:ks1,tablettype2:ks2,...] [--force] [--keyspace_type=type] [--base_keyspace=base_keyspace] [--snapshot_time=time] [--durability-policy=policy_name] <keyspace name>",
```
Comment (deepthi) [inline go/vt/vtctl/vtctl.go:390]: Unrelated to the issue, we discovered that these flags which no longer exist were still lingering in the help text.

File: go/vt/vtgate/vtgate.go [hunk 3]
```diff
@@ -565,7 +563,7 @@ func (vtg *VTGate) VStream(ctx context.Context, tabletType topodatapb.TabletType
 
 // GetGatewayCacheStatus returns a displayable version of the Gateway cache.
 func (vtg *VTGate) GetGatewayCacheStatus() TabletCacheStatusList {
-	return vtg.resolver.GetGatewayCacheStatus()
+	return vtg.gw.CacheStatus()
```
Comment (deepthi) [inline go/vt/vtgate/vtgate.go:566]: The indirection was necessary when we had both DiscoveryGateway and TabletGateway. Now that we have only one Gateway, we can go to that directly instead of going through resolver.

**Review by dbussink — COMMENTED** [review]
Does this need an item in the release notes?

Also the test failure needs to be fixed as well, it needs some cleanup here I think: https://github.com/planetscale/vitess/blob/ds-fix-12559/go/test/endtoend/clustertest/vtctld_test.go#L118-L128

**Review by ajm188 — APPROVED** [review]
LGTM

**Comment by deepthi** [comment]
> Does this need an item in the release notes?
> 
vtctld UI has already been deleted, so the links we removed were actually producing `404`s.
However, it is worth adding a note for the flag deprecation. I will do that and fix the failing test as well.
Thanks for catching this.

**Review by dbussink — APPROVED** [review]
